### ISSUE TITLE
Favicon is broken in Safari 12 on macOS Mojave

### ISSUE THREAD

**Issue by jsynowiec** [octobox/octobox#1010]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
Safari 12 (finally) supports displaying favicons on the tabs but the Octobox icon is broken - it displays just as a black circle.

![image](https://user-images.githubusercontent.com/1029142/46002277-f78eb480-c0ad-11e8-87b1-ba57da96a947.png)

Not sure if this is a problem with favicon or with Safari.

🎯 **Goal**
Favicon displays properly, as in Chrome or Firefox.

**Comment by andrew** [comment]
I've not updated to Mojave yet, will likely upgrade at the weekend and then I can tackle this if no-one else gets there before me.

Interestingly they appear to be working in safari on iOS 12:

![img_2899](https://user-images.githubusercontent.com/1060/46015394-1b5ff380-c0ca-11e8-99ec-9c66740d9742.jpg)

**Comment by rufo** [comment]
I haven't looked into exactly what logic Safari 12 uses, but I've noticed this with my pinned tab as well using Safari 12 on High Sierra 😕 

From what's going on, it looks like Safari on Mac is trying to use [the pinned tab SVG](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html) for the favicon preferentially. According to [the `<link>` tag in the `favicons` partial](https://github.com/octobox/octobox/blob/11173e998763f2774c99d7f87e9661c1ec48858e/app/views/layouts/_favicons.html.erb#L15), it's supposed to use [the `infinitacle-round.svg` image](https://github.com/octobox/octobox/blob/master/app/assets/images/infinitacle-round.svg), but it's not rendering the tentacle at the smaller size for some reason... it renders correctly when viewed in the content area, so it's not like Safari can't render it.

Odd SVG rendering aside, maybe what makes more sense is to switch to using [the standard `infinitacle.svg`](https://github.com/octobox/octobox/blob/master/app/assets/images/infinitacle.svg) image? That way it would bring Safari 12 more in-line with the favicon on other platforms anyway. I'll try and make that change a bit later today to see if it renders correctly, and post a screenshot to compare 🙂

**Comment by rufo** [comment]
I updated it locally, and it seems to render fine:

![screen shot 2018-09-26 at 11 06 04 am](https://user-images.githubusercontent.com/2745/46093384-d1841580-c17c-11e8-9208-5e7941492f7a.png)
![screen shot 2018-09-26 at 11 06 14 am](https://user-images.githubusercontent.com/2745/46093385-d1841580-c17c-11e8-9967-98df6beff19c.png)

I've opened a PR at #1021 for further discussion - totally cool with going a different route if that works out better, just figured I'd throw the quick fix up there 🙂

**Comment by andrew** [comment]
Deploying this now, thanks for investigating @rufo 👍
