### ISSUE TITLE
Synchronize UI/UX with Github's design scheme

### ISSUE THREAD

**Issue by pradyunsg** [octobox/octobox#1012]
🎯 **Goal**

Use the same colours and design scheme as GitHub.

📋  **Why**

 * The use of Octobox is closely associated with GitHub
 * Less of a visual change when switching between the two plaforms
 * Using the same UI/UX would make Octobox feel like natural extension of GitHub (which is a good thing IMO)

This is mostly a thought that came to mind while doing https://github.com/octobox/octobox/issues/793#issuecomment-424299086.

**Comment by andrew** [comment]
If you have particular UX changes in mind it would be good to hear but we don't want to copy GitHub too closely otherwise we might run into trademark/branding related problems with them whilst we get Octobox listed on the GitHub marketplace.

**Comment by pradyunsg** [comment]
Two that come to mind immediately:

- Top bar containing direct access to Settings and Admin like GitHub provides Pull Requests/Issues/Trending/Explore
- Using similar/same colours + borders for UI elements as GitHub (like the icons in the table header)

**Comment by andrew** [comment]
We won't be switching to primer, it's nowhere near as complete as Bootstrap, we're already using https://octicons.github.com/ for all the icons. I'd like Octobox to have some of it's own identity rather than try to pretend it's part of GitHub.

**Comment by andrew** [comment]
> Top bar containing direct access to Settings and Admin like GitHub provides Pull Requests/Issues/Trending/Explore

Octobox really only has the one view, the notifications list, the other pages are settings which mirrors the GitHub header in that they are tucked away in the user menu because they are rarely used.

If we end up having other functional sections that would be frequently switched between it would make sense to put them in the header.

**Comment by pradyunsg** [comment]
> I'd like Octobox to have some of it's own identity rather than try to pretend it's part of GitHub.

Fair enough. :)
