### ISSUE TITLE
Improving single notification displays

### ISSUE THREAD

**Issue by pradyunsg** [octobox/octobox#1013]
From #793.

![draft 1](https://user-images.githubusercontent.com/3275593/46010983-13ac4900-c0e2-11e8-9646-6d34bdf47c81.png)

Notes:

- Title/Sub-Text wraps when the content is too long (as currently).
- As shown, action icons We can space the icons carefully and accomodate an extra icon when we're in that context.
- On-hover icons added in #823 can replace the reason badge, bringing all possible actions on the notification closer.
- The "reason" boxes should be less brightly colored to capture less attention.

**Comment by andrew** [comment]
Related issue on mobile: https://github.com/octobox/octobox/issues/925 cc @BenJam

**Comment by BenJam** [comment]
Side by side: 

<img width="822" alt="screen shot 2018-10-01 at 11 24 48" src="https://user-images.githubusercontent.com/158833/46283835-92373980-c56d-11e8-9fa9-c08d04ae1927.png">

![image](https://user-images.githubusercontent.com/158833/46283843-982d1a80-c56d-11e8-9062-358513e3e677.png)

**Comment by andrew** [comment]
I prefer the current because for the majority of notifications, everything fits on a single row so you can see more notifications per page.

The column based arrangement makes the UI predictable for scanning down any single column.

I wonder if the reason icons could be grouped together with the labels as they are very similar (categorization/filters).

One other thing I think the gmail interface does well is truncating subject lines with a fade. Seems to me we should be more aggressive with really long strings rather than designing the UI around them.

**Comment by pradyunsg** [comment]
I obviously have a preference for the layout I proposed. ;)

> I prefer the current because for the majority of notifications, everything fits on a single row so you can see more notifications per page.

This I agree with. I do feel that this is a trade-off and I am biased towards having a less tabular approach.

> The column based arrangement makes the UI predictable for scanning down any single column.

Part of the reason I put the repository name first in the list is that that's what I've noticed myself using most often. I usually don't care about who filed the issue and I guess when I do, clicking the username/doing a `user:andrew` search are low-enough effort paths to suggest those as alternatives.

> One other thing I think the gmail interface does well is truncating subject lines with a fade. Seems to me we should be more aggressive with really long strings rather than designing the UI around them.

Taking cues from GMail's UI is a good idea in general, given how polished it is. GMail's intends to present a summary of the content, with minimal labeling (I'd speculate most users have 0 or 1 label on their emails). Octobox currently tries to present as much information as it can, which I feel is the right approach for the notifications.

**Comment by pradyunsg** [comment]
@andrew @BenJam Hi again! I've been AWOL due to real life! :)

Any suggestions on how we can move forward here? Maybe we need to direct some Octobox users to provide feedback here; I'm thinking maybe a tweet would help get some attention here. :P

**Comment by ringods** [comment]
> The column based arrangement makes the UI predictable for scanning down any single column.

I also favour the current layout for the reason above.

**Comment by BenJam** [comment]
hey @pradyunsg thanks for getting back into this. It sounds like most people prefer the 'one row per notification view' as mentioned by a few above. I think the jetbrains tracker is a bit of a mess at scale:

<img width="1163" alt="screenshot 2019-01-02 at 11 40 20" src="https://user-images.githubusercontent.com/158833/50590583-86685580-0e83-11e9-9c4f-2c6c3a086639.png">

i.e. I dont find those rows scannable, it takes more energy to get though the list. 

BUT DON'T FET.

Maybe there's something to be done in this vein on the responsive views (currently clipping in at < bootstraps 'large' devices. Currently looking like this: 

<img width="906" alt="screenshot 2019-01-02 at 11 46 07" src="https://user-images.githubusercontent.com/158833/50590740-0f7f8c80-0e84-11e9-9c3c-0300155e304e.png">

I think maybe some of these ideas might find a better home there.

**Comment by pradyunsg** [comment]
> I think the jetbrains tracker is a bit of a mess at scale:

I agree -- I don't think that Octobox would/should present that much information though. I do think that the initially proposed layout combined with deterministic positions for repo / author / date info, would make things better.

**Comment by pradyunsg** [comment]
Essentially, now I'm suggesting moving the title to its own line and keeping other metadata presented in a column-style layout under that.
