### ISSUE TITLE
Cannot unarchive issues

### ISSUE THREAD

**Issue by RX14** [octobox/octobox#1016]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

attempting to unarchive any issue in any way fails

**Comment by andrew** [comment]
I noticed that this evening as well, as will investigate first thing tomorrow

**Comment by RX14** [comment]
This is still broken when unarchiving multiple items like this:

![](http://owo.sh/73b8b7.png)

**Comment by prashuchaudhary** [comment]
@andrew I checked the code and `Archive button` and `UnArchive Button` should be mutually exclusive. How can I get the above screen ??

And I checked for the case when Archiving Multiple Notifications on `octobox.io`, its working as expected.

@RX14 can you further clarify ??

**Comment by andrew** [comment]
@prashuchaudhary the only place that both buttons show up is on search results pages which contain both archived and unarchived results

**Comment by prashuchaudhary** [comment]
@andrew fixed the JS code in #1023

**Comment by andrew** [comment]
@prashuchaudhary thanks, just deploying that now 👍

**Comment by prashuchaudhary** [comment]
Excellent 🎉
