### ISSUE TITLE
Reloading doesn't work

### ISSUE THREAD

**Issue by RX14** [octobox/octobox#1017]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
I press `r` or click the refresh button and the refresh icon does not spin, the page is not refreshed and new issues do not appear. After refreshing the whole page, new issues appear.

**Comment by andrew** [comment]
I suspect I’ve broken some JavaScript somewhere, will investigate first time in the morning as well, thanks for reporting 👍

**Comment by bodinsamuel** [comment]
I was going to report it, it's been a couple days since it's stopped working. Thanks for the quick fix 👍 🙏

**Comment by RX14** [comment]
Thanks for the quick fix, works for me!
