### ISSUE TITLE
y to archive broke

### ISSUE THREAD

**Issue by RX14** [octobox/octobox#1026]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

I press `y`, the currently selected issue isn't archived.

**Comment by andrew** [comment]
Definitely need to get working on https://github.com/octobox/octobox/issues/268 🙈

**Comment by andrew** [comment]
Pretty sure this bug came from https://github.com/octobox/octobox/pull/1023/files

**Comment by andrew** [comment]
PR for a fix here: https://github.com/octobox/octobox/pull/1029

**Comment by andrew** [comment]
Deploying now, thanks for reporting

**Comment by RX14** [comment]
thanks, fixed
