### ISSUE TITLE
incorrect link for releases

### ISSUE THREAD

**Issue by carlwgeorge** [octobox/octobox#103]
I'm using the [hosted version](https://octobox.io) and I noticed that the link given for GitHub releases is incorrect and results in a 404 error.

Examples:
My notification for https://github.com/iuscommunity-pkg/python35u-mod_wsgi/releases/4.5.10-1.ius links to https://github.com/iuscommunity-pkg/python35u-mod_wsgi/releases/4921688.
My notification for https://github.com/iuscommunity-pkg/mariadb101u/releases/10.1.20-1.ius links to https://github.com/iuscommunity-pkg/mariadb101u/releases/4936375.

**Comment by andrew** [comment]
I figured my [hack](https://github.com/andrew/octobox/blob/master/app/models/notification.rb#L73-L77) would break eventually, #4 will fix this properly

**Comment by andrew** [comment]
@carlwgeorge just pushed a partial fix for this as #4 isn't going to happen any time soon, for now new release notification links will go to the main Releases page for the repo, i.e.  https://github.com/iuscommunity-pkg/python35u-mod_wsgi/releases/

**Comment by carlwgeorge** [comment]
Thanks!  That certainly helps.

You spurred my curiosity, so I dug into this deeper (despite not know ruby at all).  I think in order to get the desired link, you have to make an additional http request to the actual `subject.url` from the notification and get the `html_url` property from that response.

**Comment by andrew** [comment]
Going to close this for now, will be improved by #4 eventually

**Comment by andrew** [comment]
Reopening this as now that #411 has been merged this is now fixable.
