### ISSUE TITLE
Unable to Unarchive

### ISSUE THREAD

**Issue by StanleyGoldman** [octobox/octobox#1031]
I'm unable to unarchive issues
Attempting via the checkboxes and button or the intline button towards the right.
Page reloads, nothing happens.

Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

**Comment by andrew** [comment]
Are you seeing any JavaScript errors in the console?

Are you running on the latest version from master, there were a number of JavaScript fixes merged in the past couple days

**Comment by andrew** [comment]
Cc @tarebyte as it looks like it might be the GitHub instance

**Comment by tarebyte** [comment]
@StanleyGoldman I just pushed up the latest version to our instance, mind taking another look to see if you have the issue?

**Comment by StanleyGoldman** [comment]
@tarebyte the issue is resolved

**Comment by StanleyGoldman** [comment]
Thanks @andrew
