### ISSUE TITLE
Error: bad_verification_code

### ISSUE THREAD

**Issue by frenck** [octobox/octobox#1032]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [X] My instance

Running release b145970.

🐞 **Problem**

Since this morning, I've lost authentication with GitHub on my instance.

```
E, [2018-09-30T10:10:00.728117 #24644] ERROR -- omniauth: (github) Authentication failure! invalid_credentials: OAuth2::Error, bad_verification_code: The code passed is incorrect or expired.
error=bad_verification_code&error_description=The+code+passed+is+incorrect+or+expired.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-oauth-app-access-token-request-errors%2F%23bad-verification-code
```

![image](https://user-images.githubusercontent.com/195327/46255223-c42b9b80-c49a-11e8-8d38-b51faa58bbb0.png)

I've tried the following:
- Revoking authentication, trying to re-auth. (As suggested by the GitHub developer docs)
- Refreshing the GitHub client secret to ensure that is not part of the issue.

Notification syncing also causes errors:

```
rake aborted!
OpenSSL::Cipher::CipherError: 
/opt/app/models/user.rb:117:in `effective_access_token'
/opt/app/workers/sync_notifications_worker.rb:15:in `perform'
/opt/config/initializers/custom_sidekiq_worker.rb:9:in `perform_async_if_configured'
/opt/app/models/user.rb:74:in `sync_notifications'
/opt/lib/tasks/tasks.rake:6:in `block (3 levels) in <top (required)>'
/opt/lib/tasks/tasks.rake:4:in `block (2 levels) in <top (required)>'
Tasks: TOP => tasks:sync_notifications
(See full trace by running task with --trace)
```

I've logged in with a different GitHub account, and that just works!
So it seems to be related to existing GitHub accounts already in the system (or my personal account, but that seems weird, especially since I've done the re-auth).

I'm kinda lost here. I've been using this instance for over 3 months now, without issues. And suddenly this happened.

🎯 **Goal**

Use Octobox, since this tool became mandatory for my workflow.

💡 **Possible solutions**

I haven't found any possible solutions.

📋  **Steps to solve the problem**

Still looking for steps to resolve my issue.

**Workaround**

Deleting the database and restart from scratch (that sucks).

**Comment by prashuchaudhary** [comment]
@frenck I can only suggest a temp solution. You can hardcode your `Github Access Token` in `subject_token` method in `user.rb`. 

`
  def subject_token
    "<YOUR_ACCESS_TOKEN>" || effective_access_token
  end
`

**Comment by andrew** [comment]
Looks like this might be due to this upgrade that encrypted the access tokens: https://github.com/octobox/octobox/pull/619

@frenck have you upgraded recently? That PR was merged August 9th, if you were running octobox before then and then upgraded that would likely pinpoint the issue.

Can you access the rails console? If so, here's some code to see if your encrpyted access token is missing:

```ruby
User.find_by_github_login('frenck').encrypted_access_token.nil?
```

**Comment by frenck** [comment]
@andrew That point me in the right direction and I might actually know what is going on!
Thank you...

Nevertheless, change of encryption key, should be recoverable or at least be pointed out in the logs correctly (e.g., failed to decrypt?)

**Comment by andrew** [comment]
Agreed, it should be recoverable, we just need to work out what state it's in so we can detect and handle it correctly. If `encrypted_access_token` is blank that's a different case to if `OCTOBOX_ATTRIBUTE_ENCRYPTION_KEY` has changed.

**Comment by prashuchaudhary** [comment]
@andrew I face the same problem. I have somehow don't have `app_token` for my user. 

So I have to change this method 
```
def subject_token
    effective_access_token || app_token
end
```

**Comment by prashuchaudhary** [comment]
Also I tried getting my `decrypted app_token` or `decrypted access_token` but did not succeed

**Comment by frenck** [comment]
@andrew in my case the Rails secret changed since I have not anticipated on the newer `OCTOBOX_ATTRIBUTE_ENCRYPTION_KEY` (some upgrade instructions or notices would be nice btw).

**Comment by frenck** [comment]
I've been able to fix my issue, which was totally caused by my own doing.
Some "upgrade" notices in the release notes, would be appreciated though.

As far as I'm concerned, this issue can be closed. Nevertheless, @prashuchaudhary issues still seem to be open within this thread.

**Comment by andrew** [comment]
Yeah it’s tricky trying to add upgrade notices when effectively every commit to master is a new release (at least a new build is published to Docker hub). 

I’ll have a think about how best to handle/document upgrades in the future.
