### ISSUE TITLE
Sync button stays black (focus state) after sync has finished

### ISSUE THREAD

**Issue by BenJam** [octobox/octobox#1036]
![image](https://user-images.githubusercontent.com/158833/46282744-3d45f400-c56a-11e8-8869-a709ff56c779.png)

I've taken a look at this before. I'm not sure whether the `e.preventDefault()` call should stop the focus state. I have tried setting `.blur()` after sync is fired to no avail. The only reason the state is getting reset is when the page reloads with turbolinks taking over the page refresh. Should be an easy fix for someone more aux fait with JS.

Originally in #925

**Comment by benortiz** [comment]
@BenJam hello! I'd be interested in picking this issue up and trying to find a solution.

**Comment by andrew** [comment]
@benortiz Go for it 👍

**Comment by benortiz** [comment]
Just wanted to give y'all an update with my progress so far. I was doing some digging to find the root of the problem and my current theory is that this is an iOS/Safari specific bug (please correct me if I'm wrong) related to sticky hover states. It looks like there was [_almost_](https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/#sticky-hoverfocus-on-ios) a solution, but not any more. Still on the hunt for a solution.

**Comment by pradyunsg** [comment]
I'm also seeing this on the current FF on Android 8.1.0.

**Comment by andrew** [comment]
I wonder if we can just disable the hover/focus/active state on the button for small screens as a workaround?
