### ISSUE TITLE
Add the railroady and rails-erd gems

### ISSUE THREAD

**Issue by jhsu802701** [octobox/octobox#1043]
The railroady and rails-erd gems (for drawing block diagrams of the app's structure) are not installed.  Do you want me to submit a pull request or to keep these gems in my own personal branch and use the "git cherry-pick" command?

**Comment by andrew** [comment]
It looks like you can use railroady directly from the command line without needing to add it as a dependency: https://github.com/preston/railroady/blob/master/README.md#alternate-usage

I’d prefer not to add dependencies that aren’t part of the core development process.
