### ISSUE TITLE
Archive icon position incorrect on mobile

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#1052]
![img_1ad726f44ff3-1](https://user-images.githubusercontent.com/1060/46470481-ab8af080-c7ce-11e8-8330-07fa9e2460f7.jpeg)

The position of the "archived" icon isn't right on small screens.

**Comment by prashuchaudhary** [comment]
Updated position of Archive Icon

![screen shot 2018-10-08 at 12 38 33 pm](https://user-images.githubusercontent.com/11884537/46595664-29b10500-caf7-11e8-98eb-4bd01fe55d0a.png)
