### ISSUE TITLE
No more able to refresh notification

### ISSUE THREAD

**Issue by vvo** [octobox/octobox#1067]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
I had to remove all authorizations and re-add them to check if #1066 was triggered because of some bad configuration. Now the refresh button seems to be failing:
![2018-10-09 17 18 00](https://user-images.githubusercontent.com/123822/46679453-504e6900-cbe7-11e8-9454-1a41c3b4755e.gif)

I guess there are new notifications, I get no errors in console or network. Maybe there's a huge crawler in the background that is stuck or something?

Thanks! Looking forward to paid plans too, I am 100% in to pay now :)

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by andrew** [comment]
Just looking at this now, there doesn't appear to be anything backed up in the queue, from your gif it looks like the top left sync button is working as expected from a javascript point of view but the refresh button in the blank slate isn't working. Do you have new/unread notifications showing up in https://github.com/notifications that aren't being pulled in?

**Comment by vvo** [comment]
> Do you have new/unread notifications showing up in github.com/notifications that aren't being pulled in?
Yep like your current comment, or this one:
![image](https://user-images.githubusercontent.com/123822/46694401-04aeb600-cc0d-11e8-9da9-6ca9f2ff89a4.png)

I just solved it by login out and login. Cool! The way I think the bug was triggered was by going to settings of octobox and then remove every GitHub connection (while still being logged in). Then try to re-add them but nothing was showing up afterwards in notifications in Octobox. Thus I had to logout/login.

Hope it helps!

**Comment by vvo** [comment]
Hi @andrew just having this bug again:
![2018-11-14 10 22 45](https://user-images.githubusercontent.com/123822/48473525-eaae5780-e7f8-11e8-9d27-8b6d89859da0.gif)

**Comment by BenJam** [comment]
I can see your last refresh was yesterday and your recent page requests, but no recent sync requests. Have you tried re-authenticating as before? I can't see anything that looks off at the moment.

**Comment by vvo** [comment]
I just removed octobox oauth/app access everywhere and added it back again, but still the same. Everytime I click on sync it just does not do anything (I am used to have "Last sync" be updated when I click on that..)

**Comment by andrew** [comment]
@vvo I believe the same problem happened as before, our redis instance ran out of ram last night due to an influx of new users and your account got stuck in the unique-jobs list despite never actually completing a sync. I cleared that out again and kicked off a sync for your account and will be investigating ways of ensuring this doesn't happen again.

**Comment by vvo** [comment]
Seems to be good now, thanks!
