### ISSUE TITLE
Notification Count Label

### ISSUE THREAD

**Issue by oyeanuj** [octobox/octobox#107]
Hi @andrew @tarebyte! Quick UX question around the notification labels - In several cases, the grey counter next to the labels in left side navigation has a number but clicking on it, shows me no notifications. 

So, is that a number indicating total notifications including archived or read? Or is it the unread notification label and I should expect to see notifications there?

**Comment by andrew** [comment]
It's a bit rubbish at the moment, the counts are unfiltered in some cases then the count will be higher than the possible view, the ideal case should be the number matches how many you would see if you click it.

**Comment by andrew** [comment]
Label counts should be a little more predictable now
