### ISSUE TITLE
Search for self-assigned issues doesn't work without "inbox: true"

### ISSUE THREAD

**Issue by Zimmi48** [octobox/octobox#1071]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

I click on "Assigned to you", then I remove "inbox:true" from the search bar, type Enter, and then I see a lot of notifications which do not correspond to issues / pull requests assigned to me.

🎯 **Goal**

In the current state, it seems to me that the custom filters are broken and I can't use them

Remark in passing: I've added the GitHub App to several organization I'm part of, and yet, I do not see any labels on the corresponding notifications. I've tried logging out and in again, regenerating the OAuth token, fiddling with the App settings, nothing seems to work :disappointed:

**Comment by andrew** [comment]
Thanks for reporting, I’ll check these issues first thing in the morning.

**Comment by Zimmi48** [comment]
I can however see the label you just added to this very issue.

**Comment by andrew** [comment]
@Zimmi48 it could be that Octobox has failed to sync data for your old notifications

**Comment by Zimmi48** [comment]
I'm not sure what you mean: if we are talking about the label question, the problem is there also for newer notifications and it rather looks like Octobox didn't notice it now had access to these organizations. FTR I've tried logging in from a bot account to check if a new user of Octobox would see the labels, but it seems like it isn't the case.

**Comment by andrew** [comment]
I've found the bug that's caused the lack of labels and other issue data to appear, will be pushing a fix soon and will resync all your data for you, then we can take a look at the assignee problem.

**Comment by andrew** [comment]
@Zimmi48 can you paste the query that's prefilled in the search box in here, that's definitely a bug 👍

**Comment by Zimmi48** [comment]
"inbox:true type:pull_request assigned:zimmi48"
URL is: https://octobox.io/?assigned=Zimmi48&type=PullRequest

**Comment by Zimmi48** [comment]
After I type Enter, the URL becomes: https://octobox.io/?q=inbox%3Atrue+type%3Apull_request+assigned%3Azimmi48

**Comment by andrew** [comment]
@Zimmi48 looks like `assigned` should be `assignee`, I'll get a patch in for that shortly.

**Comment by andrew** [comment]
This actually helped me discover a couple more bugs with the params -> search query converter, pr over here: https://github.com/octobox/octobox/pull/1077

**Comment by andrew** [comment]
@Zimmi48 just deploying #1077 now, should be live in a few minutes

**Comment by Zimmi48** [comment]
Thanks! Everything works well know.
