### ISSUE TITLE
I have too many repos, I only want to use ocotobox on a subset of them

### ISSUE THREAD

**Issue by fxdgear** [octobox/octobox#1081]
There's no way to remove repos from the list of all repos cause I only want to use this for a subset of repos and orgs that I belong to.

**Comment by PatrickLang** [comment]
+1 . There are work repos I used to contribute to but are no longer my responsibility. I'd like to delete them from the left bar.

**Comment by andrew** [comment]
If you [delete](https://github.com/octobox/octobox/pull/987) all notification for a repository then it will no longer show up in the sidebar.
