### ISSUE TITLE
Kerning issue

### ISSUE THREAD

**Issue by fxdgear** [octobox/octobox#1082]
The font or what ever you're using to render text is not displaying spaces. 

Thereforealltextlookslikethis.It'ssuperannoyingtoreadandmakesyourproductlooklikeit'snotready

**Comment by andrew** [comment]
Have you got a screenshot? Also what browser and operating system are you using?

**Comment by fxdgear** [comment]
![screenshot_s554w9h5](https://user-images.githubusercontent.com/146550/46756094-e46e0e00-cc83-11e8-8023-362ab27843bb.png)

**Comment by fxdgear** [comment]
```$uname -a
Linux 4.18.12-arch1-1-ARCH #1 SMP PREEMPT Thu Oct 4 01:01:27 UTC 2018 x86_64 GNU/Linux
```
Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)

**Comment by BenJam** [comment]
lol @ this. IfOnlyEveryThingWereAJavaScriptVariable.

**Comment by benortiz** [comment]
I'm wondering if there's something going on with the local `sans-serif` font that is installed. Could you run `fc-match sans-serif` (assuming you have the `fontconfig` library installed) and see what that returns? Maybe it'll return an unexpected or an uninstalled font.

**Comment by fxdgear** [comment]
``` → fc-match sans-serif                                                                                 nick/refactor-jjbb ✗ 0m 
DejaVuSans.ttf: "DejaVu Sans" "Book"
```

**Comment by andrew** [comment]
I don't think this is one we can easily fix, seems like a specific issue for that font stack
