### ISSUE TITLE
Highlighting of issue-under-cursor is almost the same as unread issue

### ISSUE THREAD

**Issue by timhoffm** [octobox/octobox#1083]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
The background color of an issue under the cursor (no matter of read or unread) is almost the same as the background color of an unread issue. This can lead to mistakingly assuming that the issue under the cursor is unread: 

![grafik](https://user-images.githubusercontent.com/2836374/46762764-52dcbb80-ccd8-11e8-8fa0-9198996c78e8.png)

(top: unread, bottom: issue-under-cursor)

Yes, there are other differences such as the black bar on the side and boldface text, but they are subtle.

🎯 **Goal**
The issue under the cursor should not look similar to an unread issue.

💡 **Possible solutions**
Use visually more distinct background colors. Often a light blue is used to indicate current position/focus.

**Comment by BenJam** [comment]
got this covered now ta.
