### ISSUE TITLE
Auto-archive closed/merged issues

### ISSUE THREAD

**Issue by dmathieu** [octobox/octobox#1087]
### What feature you'd like to see

:wave: 
I am watching some repositories with a lot of activity, where my main goal is to go through all the activity quickly, not digging into everything.
Because of that, I'm not archiving anything manually. So I have a lot of notifications that are read, but have no real value anymore.

How about auto-archiving an issue/PR when it has been closed or merged and it is marked as read?
The issue/PR would not be archived as soon as it's status changed. Only once it's marked as read.

## Motivation

This would help me keep track of a lot of notifications without the need to worry about archiving ones that have been resolved.

## Pitch

I feel like I've pitched the feature in the first part already.
But basically, I don't want to have to manually archive issues that have been resolved, and I think this is something octobox should be able to handle automatically.

If this request is deemed interesting, I am interested in looking into implementing it.

**Comment by prashuchaudhary** [comment]
this is a good thing, we can run a daily cron to identify such issues/PR and mark them as Archived. 
We can also have a Cron to delete archived issues which are older then say a month.

**Comment by andrew** [comment]
Related item on the roadmap https://github.com/octobox/octobox/blob/master/docs/ROADMAP.md#notification-filters-and-automated-actions-8 and #8

**Comment by BenJam** [comment]
++ this is one of the first things on the 'automation' things we want to put in.
