### ISSUE TITLE
CI status isn't consistent with the one showed on GitHub pull requests listing.

### ISSUE THREAD

**Issue by Zimmi48** [octobox/octobox#1089]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

I have noticed several pull requests that are shown as "CI passed" in Octobox whereas on GitHub only one CI check is green and the others are pending.

🎯 **Goal**

The rule used by GitHub to aggregate status checks is:

- any failing check -> failing
- no failing and any pending -> pending
- all success -> success

It would be useful if Octobox could use the same rule. In the current situation, this status info is virtually useless to me.

**Comment by prashuchaudhary** [comment]
@andrew I think might not be the issue with Github Status API `combined status flag`. 

It might be actually because of `webhooks for Status event`.  Github might be sending status event for each CI check

**Comment by andrew** [comment]
@prashuchaudhary good point, we should probably be using the webhook as a hint to update the combined status

**Comment by andrew** [comment]
@prashuchaudhary I'll tackle that now

**Comment by prashuchaudhary** [comment]
👍

**Comment by andrew** [comment]
PR over here: https://github.com/octobox/octobox/pull/1093

**Comment by prashuchaudhary** [comment]
@andrew while doing research over this I found there are 2 types of [Status Checks](https://help.github.com/articles/about-status-checks/)

We have to consider both of them for providing complete Status check

**Comment by andrew** [comment]
@prashuchaudhary yeah checks are a slightly different beast, the APIs are only supported for GitHub apps (not oauth apps), I've not used one before but I wonder how the checks combine with existing statuses to show up in the issue/commit list UI

**Comment by Zimmi48** [comment]
My impression (I haven't looked deeply into it) is that Checks add information but still use Statuses to report the main results, thus you should not have to worry about Checks.
