### ISSUE TITLE
Checkboxes not 'checking' on touch devices

### ISSUE THREAD

**Issue by BenJam** [octobox/octobox#1105]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [x] My instance

🐞 **Problem**
Checkboxes do not 'check' on touch devices sometimes. It seems to happen with the entire row is not within the viewport. Instead of checking the checkbox the checkbox seems to shift between a hover/focus state:

![img_5708](https://user-images.githubusercontent.com/158833/46939872-4c936a00-d05f-11e8-912b-55cde9da84d0.PNG)

'touch' the sync issue:

![img_5707](https://user-images.githubusercontent.com/158833/46939877-4ef5c400-d05f-11e8-9e1e-e3f9b87acda8.PNG)

**Comment by andrew** [comment]
I noticed this too, it was introduced with https://github.com/octobox/octobox/pull/1057

I wonder if it's a hover/focus issue where the background colour is being set to white?

**Comment by prashuchaudhary** [comment]
@BenJam @andrew I just checked this functionality on my Phone (Motorola G5) before merging the issue. I was able to check/uncheck the checkboxes. It is working right now too. 

I verified the functionality on other devices provided in the browser responsive mode. 

Will check on other physical devices as well
