### ISSUE TITLE
Supports bot:false

### ISSUE THREAD

**Issue by ForbesLindesay** [octobox/octobox#1106]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io

I saw that you added support for viewing only issues that are from bots, but I wanted to do the inverse. I tried setting `bot:false` in the search parameter, but that seemed to do exactly the same thing as setting `bot:true`. I also tried `-bot:true`, but to no avail.

**Comment by andrew** [comment]
I initially thought this was a bug, but relabelled as a feature (because there's it's from lack of functionality rather than a bug in the existing code), `bot:false` should definitely should be a thing 👍

**Comment by andrew** [comment]
Fixed in #1443, just deploying it to https://octobox.io now, should be live in a few minutes

**Comment by ForbesLindesay** [comment]
Thank you, thank you, thank you! You've made my day!
