### ISSUE TITLE
Show conversation threads for issues

### ISSUE THREAD

**Issue by BenJam** [octobox/octobox#1108]
Quick todo list for myself:

- [x] Add XXL and XXXL mixin for displays
- [x] Render with sidebar shown on /index
- [x] Render with sidebar hidden in /show
- [x] Toggle menu on click of subject to thread view and hide menu
- [x] Back button should not be back
- [x] Add btn styles for merged et al
- [x] Add PR statuses on threads themselves
- [ ] Update currentlySelectedRow in line with changes in selected notification
- [x] Remove message preview is archived/deleted (and update rows)
- [x] Make sure there's something rendered for notifications with no discussions
- [x] Fix viewing threads in archive et al
- [x] add user option for viewing threads in Octobox or GH
- [x] create responsive (mobile) layouts for threads viewed in Octobox
- [x] amend layout (moving back down a breakpoint) if user is viewing threads on GitHub

**Comment by BenJam** [comment]
> Back button should not be back

Or maybe it should...

>  Update row content for thread previous/next buttons
At the moment we re-render the whole page for next/previous. Should we try to xhr these in instead? If so we'll need to reset the cursor position.

**Comment by BenJam** [comment]
<img width="1285" alt="screen shot 2018-10-30 at 10 49 36" src="https://user-images.githubusercontent.com/158833/47713540-77221d00-dc32-11e8-9a5e-4570808247d7.png">

Getting there

**Comment by akoeplinger** [comment]
I enabled the setting on octobox.io but all notifications still open in a separate tab, is there something else to opt into?

**Comment by andrew** [comment]
@akoeplinger do you have the Octobox GitHub app installed on any of your repos? https://github.com/marketplace/octobox

**Comment by akoeplinger** [comment]
@andrew yup that was it, thanks :) would be nice to add a note about this next to the setting.
