### ISSUE TITLE
Also show issue/PR numbers together with title

### ISSUE THREAD

**Issue by boegel** [octobox/octobox#1109]
## Motivation

It would be nice if issue & PR numbers would somehow also be visible together with the title, perhaps in a darker font so it stands out less than the title (should be in a small column left of the title imho).

Personally, I feel that I frequently filter by PR number mentally (i.e. long-running issues/PRs stand out because I start recognizing the number after a while).

In addition, in EasyBuild we frequently rely on PR numbers to test contributions, via the `eb --from-pr` support we have (cfr. https://easybuild.readthedocs.io/en/latest/Integration_with_GitHub.html#using-easyconfigs-from-pull-requests-from-pr).

## Pitch

Also showing issue/PR number would make it easier to "map" between the octobox overview & the GitHub interface, imho.

**Comment by andrew** [comment]
I noticed that this was missing a few weeks back and forgot to open an issue about it 👍 

Implementation note: The response from the notifications API doesn't have a specific field for the number but we can regex it from the `subject_url` field for notifications where the `subject_type` is `Issue` or `PullRequest`

**Comment by chaserx** [comment]
Hi. 👋 I think I have a fix for this by adding to notifications_helper. #1156

**Comment by boegel** [comment]
Thanks a lot for taking care of this @chaserx!

**Comment by chaserx** [comment]
@boegel No problem. I'm happy to help. Thanks for creating the issue.
