### ISSUE TITLE
Automated actions

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#1110]
Now that we have [advanced search](https://github.com/octobox/octobox/issues/742), we can start on the next big feature for Octobox: [Notification filters and automated actions](https://github.com/octobox/octobox/blob/master/docs/ROADMAP.md#notification-filters-and-automated-actions-8)

There's a lot of potential scope to this so I'm going to try and break it down into a few parts in this issue.

Rather than providing a specific set of functions that can be fired when specific events happen, we want to enable people to configure the custom actions they need from a set of building blocks, similar to [Gmail filters](https://zapier.com/blog/gmail-filters/) or [IFTTT](https://ifttt.com/). We can then add more functions and search prefixes over time.

Potential functions we can do now:

- Archive a notification
- Unarchive a notification
- Star a notification
- Unstar a notification
- Delete a notification
- Mark a notification as read
- Mark a notification as unread
- Unsubscribe/mute a notification

Potential events to trigger those functions:

- New notification created
- Existing notification changed
- A notifications subject synced and changed*
- A notifications labels synced and changed*
- A notifications repository synced and changed*

*if subject syncing/github app enabled

The way I imagine this working in essentially is:

- create an action with:
  - a function
  - a search query that will match notifications you want to run the function on
- when an event triggers on a notification
 - for each of your actions
   - see if the notification matches the search query
   - run the function on that notification

One thing that's going to be very helpful to this is an event log. Being able to see what has happened behind the scenes of your octobox account, example of events to be logged:

- New notification synced
- Existing notification synced
- New Subject synced
- Existing Subject synced

And in then as we enable actions we can also add events there too, which will help people understand how their actions are working and when those actions have triggered.

Some functions we may be able to add in the future for issues and pull requests:

- Close/reopen
- Lock/unlock
- Edit description
- Add/update/remove labels
- Add/update/remove milestone 
- Add/update/remove project
- Leave a comment
- Add/update/remove assignees
- Add/remove reaction

<hr/>

Related issues:

- https://github.com/octobox/octobox/issues/8
- https://github.com/octobox/octobox/issues/1087
- https://github.com/octobox/octobox/issues/188
- https://github.com/octobox/octobox/issues/342
- https://github.com/octobox/octobox/issues/599
- https://github.com/octobox/octobox/pull/752
- https://github.com/octobox/octobox/issues/893

**Comment by pradyunsg** [comment]
Something else that would be useful would be time-based/age-based triggers - if a notification is older than 2 months days old, read and unstarred, delete it.

**Comment by Zimmi48** [comment]
I would be wary of taking actions on the repository automatically based on a user's Octobox configuration. What affects the repository's processes should be kept close to the repository and editable by whoever has the admin / write permissions for this (e.g. GitHub actions). I would keep Octobox automatic actions for treatment of personal notifications.

**Comment by thisismydesign** [comment]
Not sure if this is the right place, but I'd definitely use your product if there'd be an option to leave an automatic comment on certain user notifications. Cheers!

**Comment by thisismydesign** [comment]
@andrew why was this closed?

**Comment by andrew** [comment]
Octobox is moving into a maintenance mode as there aren't any resources available for major feature developments like this.
