### ISSUE TITLE
Didn't receive notification about security vulnerability in repository

### ISSUE THREAD

**Issue by gep13** [octobox/octobox#1114]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

I recently received an email from GitHub about a security vulnerability on a repository that I am an admin on (and also an owner of the organisation that the repository lives in), however, I didn't see an equivalent notification in Octobox.

@andrew mentioned on Twitter that this doesn't always work:

https://twitter.com/teabass/status/1052461092864028672

And requested the creation of an issue to track it.

🎯 **Goal**

My personal goal is to completely remove the dependency on email, and have all my GitHub interactions happen via Octobox as it is simply amazing! 😄 

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by andrew** [comment]
Did it show up in https://github.com/notifications for you?

**Comment by andrew** [comment]
Also check the settings on https://github.com/settings/notifications

**Comment by andrew** [comment]
![9711bb5e-3f8f-49a5-bbee-b83565d055d3](https://user-images.githubusercontent.com/1060/47070801-e9820e80-d1e9-11e8-961c-581977f81cd4.jpeg)

**Comment by gep13** [comment]
@andrew no, it didn't show up in Notifications either.

I have just checked my settings, and looks like I didn't have Web selected in the Vulnerability Alerts section, only the UI Alerts.

So, looks like this was an error on my part.

I will keep an eye on this, and report back if/when another alert comes through.  Thanks for your help!

**Comment by andrew** [comment]
We should add that to the documentation to help other people avoid the same confusion  👍

**Comment by BenJam** [comment]
The documentation kinda already says it but I'll add something now with an updated image:

<img width="739" alt="screenshot 2018-11-12 at 14 32 38" src="https://user-images.githubusercontent.com/158833/48353900-6046e600-e688-11e8-9325-eaaa30f4190e.png">

**Comment by gep13** [comment]
@BenJam @andrew just wanted to follow up with this to say that I got a new security vulnerability through Octobox recently, so it is indeed working :+1:
