### ISSUE TITLE
After upgrading to Chrome 70 rendering glitch started to appear on hover

### ISSUE THREAD

**Issue by kiyanwang** [octobox/octobox#1124]
As soon as I hover over my mouse over the search box, the UI seems to magnify and distort:

![fullscreen_19_10_2018__08_19](https://user-images.githubusercontent.com/1135464/47203370-ff253e80-d377-11e8-9d25-cf99dee91b26.png)

This was working fine yesterday, I did upgrade to Chrome 70 this morning and that's when I noticed this but that might be coincidental.

** update **

In fact this happens when I move the mouse from the sidebar to anywhere else on the page.

Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

**Comment by andrew** [comment]
Wow that’s a weird one, is that Mac, Linux or windows?

**Comment by gep13** [comment]
@kiyanwang @andrew I have the same combination of:

* operating system
* chrome
* using octobox.io

but I am not seeing this happen.

**Comment by andrew** [comment]
I can't seem to replicate this either, @kiyanwang have you tried all the usual turning it off and on again things?

**Comment by kiyanwang** [comment]
@andrew 

I did some further testing, and found several tools I use that have hover based interactions were all exhibiting the same behaviour.

restarting chrome didnt fix the problem.

rebooting however did.

have no idea what caused this, but thank you for your patience.
