### ISSUE TITLE
Repo which added Github Repo has some new features but not others

### ISSUE THREAD

**Issue by lannonbr** [octobox/octobox#1125]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
the Microsoft/vscode-docs now has the GitHub app installed to it, and it has the status as you can choose the filter of open/closed/merged, but as seen in the screenshot below, the icon is still black and I don't see the PR author:

![screen shot 2018-10-19 at 8 34 05 am](https://user-images.githubusercontent.com/3685876/47218662-8a073880-d37a-11e8-842a-ce2006044ad9.png)

Here's the PR for reference in the screenshot: https://github.com/Microsoft/vscode-docs/pull/2022

**Comment by andrew** [comment]
Investigating this now, thanks for reporting!

**Comment by andrew** [comment]
@lannonbr looks like there's a race condition in the syncing of subjects for newly installed repositories, I've manually kicked off a sync for all the vscode repos, extra information should start showing up shortly. 

Now to fix the race condition 😅

**Comment by andrew** [comment]
Also very cool that Microsoft are using the Octobox GitHub App 🎉

**Comment by andrew** [comment]
PR to fix the race condition for future installers here: https://github.com/octobox/octobox/pull/1135
