### ISSUE TITLE
[question] Why do I need to install the GitHub App on public repositories?

### ISSUE THREAD

**Issue by liftM** [octobox/octobox#1137]
For issues and pull requests on public repositories, I'm prompted to install the GitHub App in that repository to pull in extra metadata. (Obviously, I can't do this for repositories I don't own.)

Why does Octobox need this? Is this information unavailable through the public API for public repositories?

**Comment by andrew** [comment]
Only the hosted instance at https://octobox.io has this restriction, if you run your own copy of Octobox you can enable `FETCH_SUBJECT` then it will pull public information for issues, pull requests etc

I'm hoping to remove the restriction on Octobox.io soon but the increased cost of syncing all those extra resources for thousands of people is holding us back at the moment.
