### ISSUE TITLE
Use Open Collective GitHub names for orgs 

### ISSUE THREAD

**Issue by BenJam** [octobox/octobox#1140]
`opencollective.rake` needs updating to use the (new) organisation GitHub id from: https://github.com/opencollective/opencollective-api/pull/1479

**Comment by BenJam** [comment]
Pref move to synchronous payment https://github.com/opencollective/opencollective/issues/1402#issuecomment-436570581

**Comment by BenJam** [comment]
note: should include a dialog that makes sure the user includes their personal/organisations GitHub account, not that OC have added it.

**Comment by andrew** [comment]
Closing in favour of #1222
