### ISSUE TITLE
Add ability to show/hide action buttons

### ISSUE THREAD

**Issue by gep13** [octobox/octobox#1142]
### What feature you'd like to see
Allow the user to control which action buttons are shown

## Motivation

Du, in part to some sort of muscle memory, or assumption, on my part, I sometimes find myself clicking the mute action button, when I don't mean to.  I would love the ability to choose in the user settings screen whether a particular action button should be shown or hidden.  This won't make sense for all action buttons, but the mute one in particular I think is an optional action. 

## Pitch

This is related, in part, to this issue: https://github.com/octobox/octobox/issues/741
From time to time, I will inadvertently do something that I didn't mean to, normally muting the selected notifications.  Muting a thread is typically something that I would never do in my normal workflow, so I would be happy if the ability to not show the mute action button at all.  Having the ability to undo the last action would obviously be great, but not allowing the action to happen at all also works 😄

**Comment by andrew** [comment]
I'm not a fan of adding more options to the settings page, if accidental muting is a problem perhaps adding a confirmation would be a better wait to avoid accidental muting, at least until proper undo is implemented?

**Comment by gep13** [comment]
@andrew I would be equally happy with a confirmation prompt 😄

**Comment by andrew** [comment]
PR over here: https://github.com/octobox/octobox/pull/1230

**Comment by gep13** [comment]
@andrew sweet!  Thanks for getting this added!
