### ISSUE TITLE
sync doesn't work on octobox.io

### ISSUE THREAD

**Issue by senid231** [octobox/octobox#1145]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
I click sync  button on https://octobox.io/ but it still shows message
`Last sync: about 19 hours ago` and no new notifications appeared
but I see that I have new notifications on https://github.com/notifications 

🎯 **Goal**
I want my new notifications to be shown on octobox.io when I click sync button

📋  **Steps to solve the problem**
1. goto https://octobox.io/
1. click sync
1. observe that nothing changed

**Comment by cmluciano** [comment]
+1 issue is happening for me too.

I wonder if there is a weird notification sync problem due to the GH outage that happened over the weekend.

**Comment by andrew** [comment]
@senid231 @cmluciano it looks like we had some trouble overnight as a result of the GitHub outage, I've flushed the redis queue and restarted the sync jobs now which should fix your issue.

**Comment by senid231** [comment]
@andrew thanks. All works fine now
