### ISSUE TITLE
Bad "app_url" for my github Enterprise

### ISSUE THREAD

**Issue by thomas-illiet** [octobox/octobox#1147]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**
I my organization Github enterprise app base url is not "apps", to resolve this i change this :
https://github.com/octobox/octobox/blob/d041c22c2353e539b4bd23e8683e3b51448d54e3/lib/octobox/configurator.rb#L134
 to :
```ruby
def app_url
    "#{github_domain}/github-apps/#{app_slug}"
end
```

![image](https://user-images.githubusercontent.com/2133666/47376459-f1aee200-d6f2-11e8-8340-369df44a933a.png)
![image](https://user-images.githubusercontent.com/2133666/47376528-1c993600-d6f3-11e8-9109-1271c060834c.png)

💡 **Possible solutions**

Can you implement a new environment variable to set this or edit GITHUB_APP_SLUG ?

Thx
Thomas

**Comment by andrew** [comment]
Thanks for reporting that, I've not had access to an enterprise install to test the GitHub app setup.

**Comment by andrew** [comment]
@thomas-illiet PR here: https://github.com/octobox/octobox/pull/1148

**Comment by thomas-illiet** [comment]
Perfect 👍
