### ISSUE TITLE
Selected item is all messed up

### ISSUE THREAD

**Issue by Tyriar** [octobox/octobox#1178]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
It's difficult to know what item is selected, looks like weird graphical glitches.

I was on Chrome 70/macOS but I don't think the issue is related to the platform. I've been seeing this for I think around a month. Sometimes the selection doesn't change at all, sometimes it does...

1st item selected:

<img width="131" alt="screen shot 2018-11-01 at 11 00 09 am" src="https://user-images.githubusercontent.com/2193314/47869911-6bb32b00-ddc5-11e8-946a-32c6e346c715.png">

2nd item selected (j):

<img width="107" alt="screen shot 2018-11-01 at 11 00 15 am" src="https://user-images.githubusercontent.com/2193314/47869925-766dc000-ddc5-11e8-96bc-a722082ece24.png">

3rd item selected (j):

<img width="114" alt="screen shot 2018-11-01 at 11 00 19 am" src="https://user-images.githubusercontent.com/2193314/47869934-7b327400-ddc5-11e8-8cf1-44c2f8e1aa84.png">

4th item selected (j):

<img width="116" alt="screen shot 2018-11-01 at 11 00 23 am" src="https://user-images.githubusercontent.com/2193314/47869959-87b6cc80-ddc5-11e8-9e70-3d3bfda31f4d.png">

5th item selected (j):

<img width="114" alt="screen shot 2018-11-01 at 11 00 26 am" src="https://user-images.githubusercontent.com/2193314/47869969-8c7b8080-ddc5-11e8-8a03-e466cb2dbc28.png">

**Comment by andrew** [comment]
I’m tempted to go back to standard checkboxes, those bootstrap ones are so unstable

**Comment by BenJam** [comment]
yup, that's a bit of a mess. Tried tying the border to the TR with no avail. GOing to have to back out twbs checkboxes.

**Comment by pradyunsg** [comment]
Is there some other kind of checkbox that can be used instead of plain checkboxes?

**Comment by BenJam** [comment]
I've got a local branch that backs out the twbs styled checkboxes and I still have this glitch...

**Comment by andrew** [comment]
I can't replicate this in Firefox or Safari but I can see it happening in Chrome

**Comment by andrew** [comment]
Not exactly sure why, but the problem doesn't happen if the border is only 1px wide (it still happens if you make it three pixels wide), PR here: https://github.com/octobox/octobox/pull/1235
