### ISSUE TITLE
Seems failed to sync

### ISSUE THREAD

**Issue by chinesedfan** [octobox/octobox#1185]
### Summary of Problem

(Please answer all 3)

- What are you trying to do?

Clicked `Sync` in the website.

- What happens?

Only notifications of last month. And seems the first notification starts with a blue border, which means unread?

![image](https://user-images.githubusercontent.com/1736154/48004986-40299b00-e14d-11e8-9bed-a091717d936b.png)

- What should have happened?

Show latest notifications. I have at least 10+ notifications this week. And every notification has been read.

### Steps to Reproduce the Issue

(help octobox maintainers reproduce your issue to make it easier to fix)

I have installed Github App and authorized OAuth apps.

### Versions, Operating System and Hardware

- Which version/commit of Octobox are you using?

https://octobox.io/

- Which browser are you accessing Octobo with?

Chrome 70.

- Windows? Linux? Mac?

OSX 10.14.

- How are you deploying Octobox (Docker, Heroku, Openshift, etc)

Visited the website directly.

**Comment by andrew** [comment]
@chinesedfan sorry about that, we had an issue with our redis database, more details here: https://github.com/octobox/octobox/issues/1067#issuecomment-438734606

Looks like your account is syncing correctly now
