### ISSUE TITLE
select a sequence of items by using shift key modifier

### ISSUE THREAD

**Issue by ahmadnassri** [octobox/octobox#1192]
### What feature you'd like to see

allow for selecting multiple items at a time using the `shift` key as a modifier, similar behavior exists in gmail and may other applications

## Motivation

augments the "select all" feature, and allows for subset selection of items, and easier group actions (mark as read, etc ...)

## Pitch

main reasoning: increase productivity for advanced users

**Comment by andrew** [comment]
This functionality should already exist, if it’s not working for you then it may be broken, also we should better document it 😅

**Comment by ahmadnassri** [comment]
yeah, then the feedback is it's not working for me :) what info can I provide to help better debug it?

**Comment by ahmadnassri** [comment]
@andrew I've been attempting a few things to get this working, seems like if I double click it *sometimes* works, but also selects a whole block of the DOM (as per normal browser behavior) 

I can record a screencast and share of the behavior if that's helpful ... any other info I can share to help fix this?

**Comment by andrew** [comment]
Looks like this was broken when https://github.com/octobox/octobox/pull/1057 was merged, just working out how to unbreak it

**Comment by andrew** [comment]
PR to fix over here: https://github.com/octobox/octobox/pull/1231

**Comment by ahmadnassri** [comment]
thank you!
