### ISSUE TITLE
"delete selected" button (+ keyboard shortcut) does nothing

### ISSUE THREAD

**Issue by ahmadnassri** [octobox/octobox#1193]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
using the "delete selected" button grays out the items, but does not actually delete anything

🎯 **Goal**
N/A

💡 **Possible solutions**
N/A

📋  **Steps to solve the problem**

 * go to archive
 * select one or multiple items
 * click "delete selected"
 * items are grayed out, but not deleted
 * also no network call calls sent (dev tools network panel)
 * keyboard shortcut `#` exhibits same behavior

**Comment by ahmadnassri** [comment]
what info can I provide to help debug this further?

**Comment by andrew** [comment]
@ahmadnassri sorry I've been away for a week, will investigate this within the next couple days

**Comment by pradyunsg** [comment]
I can confirm.

**Comment by andrew** [comment]
PR here: https://github.com/octobox/octobox/pull/1229

**Comment by ahmadnassri** [comment]
:clap:

**Comment by ahmadnassri** [comment]
I can confirm the delete button work, though the keyboard shortcut `#` does not seem to work for me (`Linux`, `Google Chrome 70.0.3538.102`)

**Comment by andrew** [comment]
I believe that the `#` delete shortcut is working now too.
