### ISSUE TITLE
delete action should have a confirmation step

### ISSUE THREAD

**Issue by ahmadnassri** [octobox/octobox#1194]
### What feature you'd like to see
when deleting items, prompt the user to confirm the delete action
 
## Motivation
delete is a destructive action, and thus should be confirmed with the user in case of accidental clicks of buttons or keyboard shortcuts

**Comment by pradyunsg** [comment]
While I think a dialog based prompt would be a nice solution, I think it might be nicer to see this as a part of #741 when that happens.

**Comment by andrew** [comment]
@pradyunsg undo is definitely nicer but much more involved, adding a dialog will help until we finally get to implemeting #741

**Comment by BenJam** [comment]
devil's advocate: remove delete function 🤲

**Comment by andrew** [comment]
Just merged a pr to fix this: https://github.com/octobox/octobox/pull/1228

**Comment by ahmadnassri** [comment]
:raised_hands:
