### ISSUE TITLE
Filter by team for team mention notification

### ISSUE THREAD

**Issue by tarebyte** [octobox/octobox#120]
For team mentions (depicted below)

<img width="214" alt="screen shot 2016-12-22 at 00 07 03" src="https://cloud.githubusercontent.com/assets/564113/21415691/9fad14fa-c7da-11e6-93f3-353fb08707bc.png">

It would be awesome if we could store the team that was mentioned and be able to filter by the team name.

This may have to be prefixed with the org name in order to avoid conflicts.

**Comment by andrew** [comment]
Dependent on #4 I think

**Comment by chrisarcand** [comment]
Looked at this; it seems to me that this will actually be somewhat difficult to efficiently implement on the Octobox side. The notifications endpoint only gives the reason (`team_mention`) and the issues endpoint nothing else helpful. Unless I'm missing something, it seems like we'd have to parse through the issue's description *and* all of it's comments (and those all could be edited before we ever make a call, etc).

**Comment by andrew** [comment]
We'll be able to parse subject and comment body once #709 is finished
