### ISSUE TITLE
Implement synchronous donation journey

### ISSUE THREAD

**Issue by BenJam** [octobox/octobox#1222]
Looks like we can create something on par with the GH marketplace journey using https://github.com/opencollective/opencollective/issues/1402

Would need to:

- [ ] log the user in
- [ ] check the current, repeating donations for the user
- [ ] show the user their current donations on an interstitial with a button to:
- [ ] redirect to opencollective and create a new repeating donation for the additional amount
- [ ] check the donation amount on redirect and:
- [ ] allocate an OC plan for the month
- [ ] drop them into the main notifications page with a status update about their news subs.

only thing this misses is one-off donations within the month. I have a preference to send people to a 'repeating' option by default for obvious reasons.

**Comment by BenJam** [comment]
> we should make a specific page that loads their transactions, says thanks and shows if they've donated the required amount to enable the private repository enhancements.

We get to set the transaction amount and type (single, repeat) so we can take the existing, repeat subs and 'top up' the amount. I would say ignore the recent,. single donations as they will end up with us dropping users at the end of the month when that single donation rolls off.

**Comment by andrew** [comment]
Steps:

1. Redirect user to open collective url `https://opencollective.com/octobox/donate/100/month/individual?redirect=https://octobox.io/opencollective/callback`
2. User gets redirected back to `https://octobox.io/opencollective/callback?transactionid=12345` with a transaction id
3. We load the transaction via their api using a privately generated `api_key`: `https://api.opencollective.com/v1/collectives/octobox/transactions/12345?api_key=xxxxx`
4. We then update/create the correct plan and subscription purchase for that user

**Comment by andrew** [comment]
Step 1 currently 404ing on open collective, reported here: https://github.com/opencollective/opencollective/issues/1402#issuecomment-458508463
