### ISSUE TITLE
Notifications need to be enabled for "Web"

### ISSUE THREAD

**Issue by dentarg** [octobox/octobox#123]
This should probably go somewhere in the README (but I'm not sure where to mention it). 

https://octobox.io/ didn't work for me until I checked the "Web" boxes on https://github.com/settings/notifications. I only had email checked because it's distracting for me to see the blue dot every time I visit any page on github.com. 

It would be great to be able to use https://octobox.io/ and not see the blue dot on GitHub.com. But I would guess that's an limitation in the GitHub API?

**Comment by andrew** [comment]
Yeah we should add that to the readme for sure, I believe it is a limitation of the GitHub API.
