### ISSUE TITLE
Alternative layouts when opening threads in ocotbox is enabled 

### ISSUE THREAD

**Issue by bastilian** [octobox/octobox#1247]
### What feature you'd like to see
It would be nice to have alternative layouts to the side pane when threads are enabled in ocotobox.
One alternative could be to simple move the thread-pane to the bottom and/or make it more "modal" and open it only when a notification is opened.

Another solution could be to have threads inline within the notification list, similar to how some RSS reader do it, this would also allow to minimize the amount of the few redundant elements, like status and labels.

## Pitch

On smaller screen the horizontal layout feels cramped when thread are enabled, alternatives to that would allow to adjust what everyone is comfortable with.

**Comment by BenJam** [comment]
Opened up that there issue for you. Also I just noticed that the intended 'peekaboo' sidebar on smaller (L, XL) has been edited out... So I'll take a look at that soon too.

**Comment by andrew** [comment]
Might be an interesting experiment to remove much of the extra details from the notifications table when the thread pane is visible

**Comment by BenJam** [comment]
>  So I'll take a look at that soon too.

So i remember I did start with the sidebar shown (but responsive) on some screens but then you get over/under render problems so I stopped that mess. 

> remove much of the extra details from the notifications table 

Yeah maybe. Thought this would shift a lot more attn to using the sidebar/search to filter. whereas I can get a good visual filter for repo, author, reason atm.

**Comment by BenJam** [comment]
Second idea: combining inline some thread information a la mail clients (again., sketch only):

![slice](https://user-images.githubusercontent.com/158833/48721575-188d0500-ec1a-11e8-9dbe-7d7af0ccac0d.png)

**Comment by BenJam** [comment]
Idea three, include thread text in dropdowns within the notifications window (guess what, yes, this is in sketch too)

![slicer](https://user-images.githubusercontent.com/158833/48722433-ed0b1a00-ec1b-11e8-9de5-c8d91e5e2eb0.png)

**Comment by BenJam** [comment]
@andrew anything to add?

**Comment by andrew** [comment]
@BenJam idea 1 and 2 seem reasonable, not a fan of idea three

**Comment by BenJam** [comment]
let's do 1 to start.
