### ISSUE TITLE
Middle click should mark as read

### ISSUE THREAD

**Issue by BPScott** [octobox/octobox#1275]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**

Clicking a notification opens it in a new tab (focusing that tab) and marks it as read. cmd+clicking a notification opens it in a new tab (in the background) and marks it as read. This is all good.

However my deep-ingrained muscle memory from every other browser interaction is to middle click links I want to see open in a new background tab. Currently this opens the notification in a background tab but does not mark the notification as read.

🎯 **Goal**

Middle clicking a link should be treated the same as cmd + left click (ctrl + left click on windows) - It should mark notifications as read.

💡 **Possible solutions**

Binding an extra mouse event to mark the notification as read when it is middle clicked

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by andrew** [comment]
Thanks for reporting, I think this is related to https://github.com/octobox/octobox/issues/1277

**Comment by aelbakry** [comment]
After having a look at the  [application.js](https://raw.githubusercontent.com/octobox/octobox/master/app/assets/javascripts/application.js); I believe that through the jQuery .which attribute this issue could be addressed properly. The solution I am working on currently looks something like this: 
```javascript
$(document).on('click', 'button.mark_read_selected',  function(e) { 
   if( e.which == 2 ) {
      Octobox.markReadSelected($(this))
   } 
});
```

**Comment by BenJam** [comment]
if you're able to submit a PR @aelbakry that'd be awesome. else we'll do this as the next phase of the thread-view work in the new year.
