### ISSUE TITLE
Viewing a thread doesn't mark it as read on GitHub

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#1277]
When clicking to view a thread, the notification should be marked as read, at the moment it doesn't do that.

**Comment by BenJam** [comment]
++

**Comment by BenJam** [comment]
Double checking this: looks like both the HTML element onClick an the jQuery attached actions are firing on Chrome:

![makr-read-thread](https://user-images.githubusercontent.com/158833/50651294-ccecab80-0f7a-11e9-8500-8640092236e8.gif)

**Comment by BenJam** [comment]
Just took a look at this in chrome, firefox and safari and each one pings `/notifications/X/markread` and updates the UI (success response). Closing for now but please reopen if needed.

**Comment by andrew** [comment]
I’ve definitely experienced this recently, it’s still a bug

**Comment by BenJam** [comment]
IF someone wants to take a look, I can't replicate it reliably.

**Comment by akoeplinger** [comment]
It happens reliably on my repo (mono/mono), when I click an unread issue/PR it updates the octobox UI to show the item as read but on GitHub it's still unread.

I tried with both an issue and a PR, same result even though the mark_read returns 200 OK:
- https://octobox.io/notifications/4462318/mark_read
- https://octobox.io/notifications/5811793/mark_read

**Comment by andrew** [comment]
PR over here: https://github.com/octobox/octobox/pull/1461

**Comment by akoeplinger** [comment]
doesn't seem fixed, I still don't see notifications marked as read on GitHub when I open the thread in Octobox.

**Comment by andrew** [comment]
@akoeplinger it could be that the queue was a little backed up, marking as read on GitHub might not happen instantly.

**Comment by akoeplinger** [comment]
@andrew yup it catched up after a few minutes, thanks. would be interesting to have some way to see the queue backlog, maybe in settings?

**Comment by andrew** [comment]
@akoeplinger the queue is a global one for everyone, so might not be that useful to see a total count, it's also goes up and down quite a lot, for example whenever a new person installs the GitHub app we get an influx of jobs.

What I might do is look at moving the mark as read jobs to a higher priority queue so they happen quicker and the lag becomes less of an issue.

**Comment by akoeplinger** [comment]
cool. maybe just a timestamp of the last processed message? it's probably not helpful for most people but when trying to figure out whether I'm running into a bug or the system is just not caught up yet it might be useful
