### ISSUE TITLE
Highlight security vulnerabilities when they're in the inbox

### ISSUE THREAD

**Issue by BenJam** [octobox/octobox#1284]
In a similar vein to #1267 we may wish to highlight (in red) when a new security vulnerability is present when `unread(this.notificiation)` and `inbox:true`:

<img width="252" alt="screenshot 2018-11-21 at 16 55 21" src="https://user-images.githubusercontent.com/158833/48856428-4440f400-edae-11e8-950e-6fb48acf7dc4.png">

**Comment by andrew** [comment]
👀

**Comment by gep13** [comment]
@BenJam ooo, I like it!

**Comment by Rodrigue-K** [comment]
I'm going to work in it.

**Comment by andrew** [comment]
This is in progress here: https://github.com/octobox/octobox/pull/1352
