### ISSUE TITLE
Default port 3000 is not used when background jobs are enabled

### ISSUE THREAD

**Issue by akerouanton** [octobox/octobox#1296]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**
When I enable the background jobs and I don't provide a port via the `PORT` env var, Octobox starts at port 5000, whereas it starts at port 3000 when I disable them (the default port in `config/puma.rb` is 3000). However, when I provide a port it's always followed.

🎯 **Goal**
I stumble upon this bug while improving the documentation for the prod image. I used the `PORT` env var to fix it, however other people wanting to use Octobox without docker containers might stumble upon the same bug.

📋  **Steps to solve the problem**

I tried to look at other default values, to see if there could be another one overriding `PORT`, but I couldn't find anything. I'm not sure where to look at to find the origin of this "default" port 5000, maybe in the modules used by Octobox? (maybe puma?)

**Comment by andrew** [comment]
I’d guess it’s the foreman gem that’s changing that default

**Comment by andrew** [comment]
I don’t mind that breaking change if it avoids confusion for more people in the future
