### ISSUE TITLE
Let me configure the left side bar

### ISSUE THREAD

**Issue by Tyriar** [octobox/octobox#1297]
### What feature you'd like to see

I would like one of or a combination of the following:

- The ability to rearrange the left side bar
- The ability to collapse portions of the left side bar
- The ability to remove items from the left side bar

## Motivation

I filter almost exclusively filter by repository, as such the layout currently is pushing the repo filters off the screen of my monitor

![image](https://user-images.githubusercontent.com/2193314/49038603-46220300-f172-11e8-8518-22ef3cdab0e1.png)

**Comment by andrew** [comment]
The main thing to consider from a development point of view is how the customisations handle new or updated menu items in future releases
