### ISSUE TITLE
Search partially (not just "words only)

### ISSUE THREAD

**Issue by afilp** [octobox/octobox#1299]
### What feature you'd like to see
Search to be partial too, not "word only", maybe by checking a related checkbox: "Words only"
(I did not find a way to do this)

## Motivation
If I search for "CheckboxGroupInput" I do get results that have this word.
If I search for "GroupInput" I do not get results (which is a part of the name).

## Pitch
Sometimes I am not sure about what term to search for, so partial searching is needed.

**Comment by andrew** [comment]
Looks like this can be enabled with the `:trigram` option for pg_search: https://github.com/Casecommons/pg_search#trigram-trigram-search which requires the `pg_trgm` extension to be enabled in postgres.

That extension is available on heroku postgres so should be easy enough to enable: https://devcenter.heroku.com/articles/heroku-postgres-extensions-postgis-full-text-search
