### ISSUE TITLE
Favicon customization

### ISSUE THREAD

**Issue by pepibumur** [octobox/octobox#1305]
## 💥 Proposal
My org has an internally-deployed version of Octobox. I use that version for all my org-related notifications and the public version of Octobox for my open source repositories. When I have both of them opened, it's very hard to know which one is each one:

<img width="92" alt="image" src="https://user-images.githubusercontent.com/663605/49153328-b87f1880-f315-11e8-9171-183837dfe324.png">

### What feature you'd like to see
It'd be great if the favicon was configurable. That way people could use a different favicon when installing Octobox. Ideally, the favicon would be a combination of the Octobox favicon and the company's favicon.

## Motivation
My main motivation is being able to keep both Octobox tabs pinned on my browser and knowing which one is each without having to open them.

## Pitch
I guess whether it's worth the effort or not depends on how many people are using private and public versions of Octobox. That's my case, and it's a bit unconvenient having both of them opened in two different tabs.

I can see the feature added to some sort of configuration file:

```
# or
favicon: path/to/my_favicon.ico
# or
favicon: https://myorg/favicon.ico
# or
favicon: https://myorg.com # Reading the favicon from the organization website.
```

**Comment by pradyunsg** [comment]
Or an environment variable that provides a working (https) link to the favicon?

Is that a valid way for it to operate?

**Comment by pepibumur** [comment]
Environment variable would also work. If it's not defined, it can default to the Octobox favicon.

**Comment by pepibumur** [comment]
Cool, I'll try to add the contribution myself 😛

**Comment by BenJam** [comment]
this would be cool, but not something we'll do ourselves as our focus is on octobox.io atm (as our primary income). Would be good to see if you have the time @pepibumur ⚡️.
