### ISSUE TITLE
Transferred issues ain't properly tracked

### ISSUE THREAD

**Issue by webknjaz** [octobox/octobox#1315]
If an issue gets transfered to another repo it gets stuck with its last status forever.

Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

1. This issue is shown as "open" in octobox: https://github.com/aio-libs/aiohttp/issues/3403.
2. It became https://github.com/aio-libs/multidict/issues/307 while being open.
3. Now 3403 doesn't get status updates in octobox.

🎯 **Goal**

It should appear under the right filters.

💡 **Possible solutions**

N/A

📋  **Steps to solve the problem**

N/A

**Comment by BenJam** [comment]
urgh: lockstep feature to keep in line with GH :)
