### ISSUE TITLE
Slash ("/") should focus on "Search Box", not show the Help dialog (which is done by "?")

### ISSUE THREAD

**Issue by afilp** [octobox/octobox#1316]
### What feature you'd like to see
The Slash ("/") button to focus on "Search Box"

## Motivation
Now, both the "/" and the "?" (which is "shift-/") keyboard shortcuts show the Help dialog. This is not needed and we lose the "/" for the "Search box".

## Pitch
In many other apps (like Gmail, Google Calendar, etc.) the "/" is the shortcut for the "Search Box".

**Comment by afilp** [comment]
You're welcome. If I may add this here, it is also typical when using the "j/k" for up/down to also have "p/n" for `previous/next`.

![image](https://user-images.githubusercontent.com/7850073/49366102-2732ec00-f6f1-11e8-8223-2688f66f686a.png)

If you feel that this is useful we can have this too and navigate fully using just the keyboard.

Thanks!

**Comment by andrew** [comment]
Just merged a pr by @evexoio that fixes the `/` shortcut and adds the `p/n` shortcuts, deploying to https://octobox.io shortly 🎉
