### ISSUE TITLE
Flexible page size

### ISSUE THREAD

**Issue by nu11p01n73R** [octobox/octobox#132]
Currently the page size is hard coded as 20. 

Most users may want to have a better control over how many notifications are displayed per page. Some think like `page=2&per_page=50` so that the user can change the page size if they want to or resort to default of `20`.

**Comment by briannelson** [comment]
👍  From a UI perspective, I'd add a `<select>` on the right side of the top bar:

![octobox](https://cloud.githubusercontent.com/assets/29120/21433375/a2d371b6-c83d-11e6-8489-555807d51e94.png)

**Comment by andrew** [comment]
Just opened a pr to add the `per_page` parameter (max of 100 per page): https://github.com/andrew/octobox/issues/133

**Comment by nu11p01n73R** [comment]
Works perfect!
I guess this can be closed now.

**Comment by andrew** [comment]
Will leave it open and see if @briannelson wants to add a UI for it, I'd put it at the bottom next to the pagination links instead of the top though.

**Comment by briannelson** [comment]
I do. Leave this open for now plz.

**Comment by tarebyte** [comment]
Closed by #152
