### ISSUE TITLE
404 when selecting unread notification to read thread

### ISSUE THREAD

**Issue by HipsterBrown** [octobox/octobox#1320]
Probably related to https://github.com/octobox/octobox/pull/240. When viewing unread notifications and selecting one to read the thread, there is a 404 response in the console and an infinite spinner in the thread panel of the UI. 

Are you experiencing this issue in octobox.io or your own instance?
 - [X] octobox.io
 - [ ] My instance

🐞 **Problem**
I suspect the issue is related to the scoping of notifications in the `NotificationsController#show` as the selected notification _was_ "unread" before clicked but is changed to "read" as it is clicked to open the thread panel. So the controller cannot find the notification from the request (`https://octobox.io/notifications/:id?per_page=60&unread=true`) because the notification is no longer scoped to "unread". 

💡 **Possible solutions**
For threaded notifications in the app, could there be a way to not scope the requested unread thread in the controller? Because there are notifications that open in a new tab, which you probably want to mark as read immediately, it could be tricky to add logic to the "show" method that find any notification matching that `:id` for the thread panel and ignore the "unread` param. 

📋  **Steps to solve the problem**

I could take a look at a potential fix this week as I've worked in Rails in the past. Maybe using `find_notification` instead of `scope.find(params[:id])` would be the quickest fix but I'm not sure about the impact that would have to the app yet.

**Comment by evexoio** [comment]
@HipsterBrown I can't reproduce this, can you help me with more precise reproduction steps?

**Comment by HipsterBrown** [comment]
@evexoio This happens for notifications that open threads in octobox. 
<img width="1542" alt="screen shot 2018-12-05 at 10 15 14 am" src="https://user-images.githubusercontent.com/3051193/49522906-ab62ac00-f876-11e8-81fc-54db7a0dc9e4.png">

**Comment by evexoio** [comment]
Still couldn't reproduce, can it be repo-specific?

![dec-05-2018 17-35-45](https://user-images.githubusercontent.com/12014839/49525048-90fbf300-f8b5-11e8-8664-38a7665a0983.gif)

**Comment by HipsterBrown** [comment]
@evexoio If you view the unread notifications, then click on a notification, that will reproduce the error. In the search box: "inbox:true unread:true"

Thanks for looking into this. 👍

**Comment by evexoio** [comment]
@HipsterBrown Thanks for clarifying the steps to reproduce the error.
So now I can reproduce the error on octobox.io but not locally.

I can't fix it unless I can reproduce it locally 🤔

**Comment by HipsterBrown** [comment]
@evexoio I get that. I'm not sure how to test the in-app threads locally. 🤷‍♂️

**Comment by evexoio** [comment]
@andrew is there a way to populate the db with in-app threads?

**Comment by BenJam** [comment]
in-app threads? I assume we mean threads in general. Try setting in .env

```
FETCH_SUBJECT=true
INCLUDE_COMMENTS=true
```

**Comment by BenJam** [comment]
I'll pick this up.

**Comment by andrew** [comment]
I've accidentally fixed this when refactoring some of the threadview controller code: https://github.com/octobox/octobox/pull/1411
