### ISSUE TITLE
Marking as read unchecks selection

### ISSUE THREAD

**Issue by crimsonknave** [octobox/octobox#1323]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**

When I mark items as read my selection is unchecked.

🎯 **Goal**

This is a change in behavior and is quite frustrating as I typically mark things as read and then archive them. I now have to select the same items twice to do so.

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by andrew** [comment]
It doesn’t exactly fix your bug but I believe that archiving things also marks them as read behind the scenes

**Comment by crimsonknave** [comment]
@andrew Hmm, so it does. I swear it didn't before... Is that something that's changed recently?

**Comment by andrew** [comment]
It’s been like that for quite a while, perhaps your instance isn’t updated very often?

**Comment by crimsonknave** [comment]
Could be, not sure. Anyway, my concern was not leaving a million notifications unread in GitHub, which doesn't happen, so closing. Thanks!
