### ISSUE TITLE
GitHub API usage estimate

### ISSUE THREAD

**Issue by betatim** [octobox/octobox#1335]
Is there a way to estimate/count the number of API requests Octobox will make for a given user?

I have a self hosted deployment of 5fea753adf10b8e3b9f3ca514213f4cd7c88cbe9 setup as an OAuth GitHub app just for me (no other users I know of, how would I check?) and in the last two or three days I started hitting the API limit. It took me a while to narrow down what was causing this as I have a few apps and personal access tokens running that consume the API. However now I am down to just Octobox as OAuth app (I've regenerated all other access tokens that had traffic in the last week without replacing them in the configs of the respective apps)

When I leave the browser tab open it seems to consume around 20-ish API calls each time I press the refresh button. Does that seem reasonable? Even so it seems hard to imagine that this woudl eat through my 5000 requests limit.

Ideas how to poke at this welcome.

**Comment by evexoio** [comment]
https://developer.github.com/v3/rate_limit/
Does this help?

**Comment by betatim** [comment]
It tells me what I already know: my API limit is exhausted :) I can't find a way to get GitHub to tell me what/who is using up my API calls. For that you have to go back to the individual apps (I think). Hence trying to get an estimate of what Octobox should be using and/or how to query for what it is actually using.

**Comment by betatim** [comment]
When I leave octobox open in a tab for a while (maybe a few hours while working?) I now frequently see "API limits exhausted" error messages in octobox popup :-/

Deploying `master` now to see if that helps.

**Comment by BenJam** [comment]
configured a minimum refresh interval? https://github.com/octobox/octobox/blob/master/docs/INSTALLATION.md#configuration-1

**Comment by betatim** [comment]
Yes, set to 9minutes

**Comment by BenJam** [comment]
this is rather strange. I regularly drop my local db and re-init the lot. I rarely experience this.  Do you have `INCLUDE_COMMENTS` set in your environment?

> no other users I know of, how would I check?

Pull all the users with `User.all` in `rails c` but I doubt that's the problem.

**Comment by betatim** [comment]
> `INCLUDE_COMMENTS`

not set in the environment variables on heroku.

One thing I've noticed is that this might happen (more often) when I have Octobox open in two tabs simultaneously (by accident).

**Comment by BenJam** [comment]
@betatim I've dumped by DB and re-synced everything  twice today plus had a tab open with no issues.  Could you give us more details of your setup (browser, public config variables in your .env file) etc?

**Comment by betatim** [comment]
Env set via heroku config vars:
```
FETCH_SUBJECT=true
MINIMUM_REFRESH_INTERVAL=5
PERSONAL_ACCESS_TOKENS_ENABLED=1
RESTRICTED_ACCESS_ENABLED=1
WEB_CONCURRENCY
```

In the settings (via the web UI) "Automatic Refresh Interval" is set to 9. No Personal Access Token is set.

There is a cron job (Heroku scheduler) set to run every ten minutes with `rake tasks:sync_notifications` as command.

Deployed version: https://github.com/octobox/octobox/commit/27305ad8d2dda5e4fd245bc39558217079c5f762 on a free heroku dyno.

Firefox 65.0b4 (64-bit) on OSX.

I also have https://github.com/sindresorhus/refined-github installed.

**Comment by betatim** [comment]
This seems like a weird thing -> thanks for helping pin point/debug this. I am fairly sure this is some weird config mistake or some such :-/

**Comment by andrew** [comment]
@betatim I believe the issue is with the `MINIMUM_REFRESH_INTERVAL` option, I had to disable it on https://octobox.io as the javascript was causing the page to kick of many more sync's than it should. 

Can you try removing that ENV var and see if that helps?

**Comment by betatim** [comment]
Isn't that setting overridden by me setting "Automatic Refresh Interval" to 9minutes in the config via the web UI?

I'll give it a try.

**Comment by andrew** [comment]
Kinda, the automatic refresh interval feature is disabled when you remove the MINIMUM_REFRESH_INTERVAL config, given that you have a cron job setup already you shouldn’t notice much different other than having to manually refresh the page every so often.

**Comment by betatim** [comment]
Is it possible that Octobox makes unauthenticated API requests from my browsers IP? This just occurred to me as the error seems to appear more often when I am not in my own office (but someone else's with potentially many people hitting the API from the same IP because of NAT).

**Comment by andrew** [comment]
No it does not make any API requests from the browser, all communication with GitHub is made from the server
