### ISSUE TITLE
Octobox issue view doesn't redirect to github when "Open" button is clicked

### ISSUE THREAD

**Issue by evexoio** [octobox/octobox#1336]
"Open" button in top of Octobox's issue view doesn't send to github issue url when "open" button is clicked.

Are you experiencing this issue in octobox.io or your own instance?
 - [X] octobox.io
 - [ ] My instance

🐞 **Problem**
![dec-05-2018 17-43-30](https://user-images.githubusercontent.com/12014839/49524972-6e69da00-f8b5-11e8-9009-434a51e36169.gif)

🎯 **Goal**
Make "Open" Button send to github.

💡 **Possible solutions**
It might be a missing a tag with a href to the github issue or something

**Comment by evexoio** [comment]
@andrew any updates 🙇🏻‍♂️?

**Comment by andrew** [comment]
@evexoio I checked out your PR, to me it feels like the whole thread headers should be clickable, trying to hit the external link target on mobile is tricky!

**Comment by BenJam** [comment]
I'll pick this up
