### ISSUE TITLE
Assignee filter isn't working

### ISSUE THREAD

**Issue by frangio** [octobox/octobox#1339]
I'm experiencing this issue in octobox.io, haven't tried on a local instance.

🐞 **Problem**

I filter by `assignee:frangio` (my username) and I don't see all of the issues that are actually assigned to me on GitHub. It seems to me that only those which I'm following _because_ I was assigned are actually showing up there. So only those which say `Assigned` in the reason column, and not  those with a `Subscribed` reason, for example.

I'm using this mostly with a project owned by an organization. I have installed the app for my user and for the organization as well. Every other "subjects" feature seems to be working well.

🎯 **Goal**
I'm finding Octobox super useful to make my workflow more efficient. The native GitHub notifications are completely useless. Particularly the pinned searches are very useful to tailor the tool to my workflow and processes, and seeing those issues which were assigned to me is a big deal.

**Comment by BenJam** [comment]
thanks for the issues @frangio and apologies for the delay picking this up. Work on @24pullrequests and my being on holiday has put us back. I think this is probably related to #1380 but we'll take a look if there's anything we can do to work around it. Not sure at the moment.

**Comment by frangio** [comment]
You're right @BenJam. Thanks!
