### ISSUE TITLE
Item selection is clear after an action on it

### ISSUE THREAD

**Issue by jchuerva** [octobox/octobox#1348]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] My instance

🐞 **Problem**
It looks like now the select item selector is clear after one action is done in the items selected and another action could be performed in the same items.
It used not to be that way. the selector used to remember the items after perform an action on them.

**Sceanrio:**
* Select few unreal items
* mark them as read
**Issue:**
* The selection is clear

**Comment by BPScott** [comment]
I'm running into this too. It'd be great if the old behaviour of retaining prior selections could be restored.
