### ISSUE TITLE
How do I login in the development environment?

### ISSUE THREAD

**Issue by jhsu802701** [octobox/octobox#1356]
I can get all the tests to pass in the development environment.  I can start the local Rails server and view the home page in my browser at the localhost address.  However, I am unable to login to the local version of the app and instead get the 404 message.

I've configured the .env file to set the GITHUB_APP_ID, GITHUB_APP_SECRET, and PORT number.  The port number is 3000, and I got my GitHub credentails from my OAuth app settings in my GitHub developer settings.  In my Oauth settings, I've set my Homepage URL and Authorization callback URL to the localhost URL I'm using to view the app.

What's the critical detail that I missed?

**Comment by jhsu802701** [comment]
I've tried out the OmniAuth gem on my own.  One of the steps is to add the following line to config/initializers/devise.rb:
```
config.omniauth :facebook, ENV['FACEBOOK_APP_ID'], ENV['FACEBOOK_APP_SECRET'], callback_url: 'http://localhost:3000/users/auth/facebook/callback'
```

However, this app doesn't have a config/initializers/devise.rb file, so there must be something else I'm supposed to do.

**Comment by BenJam** [comment]
this is a bit weird, it /seems/ like you've done everything correctly. double check your app id and app secret on GH. We could do a walk-through setup in the new year if you're still having problems. 

the test will pass even if your config is incorrect as it's just faking the oauth process.

**Comment by BenJam** [comment]
still having issues @jhsu802701? I'll close this issue in a couple of days if there's no reply.

**Comment by jhsu802701** [comment]
OK, I'm back on the project, but I'm still having problems.

Here are the things going right so far:
* The command "bundle install" works.
* The command "rails db:migrate" works.
* The command "DISABLE_SPRING=1 RAILS_ENV=test bundle exec rake --trace rubocop db:migrate test :skip_visuals" works.
* I can view the app on the localhost URL at http://localhost:3008/ .  (I'm using Docker but not in the conventional way.  I have things set up so that port 3000 in Docker equates to port 3008 in the host system.)

Here are the things I've done so far to set up OmniAuth:
* In my GitHub developer settings, I have created the app "octobox".  My client ID is d9e88d43aeefe4c54a69, and my client secret is 48836f5c1d4efbb211eab2469866992ec037a622.  (Now that these are public, I'll have to change them once I figure out that one step I'm missing.)  The homepage URL is http://localhost:3008/.
* The authorization callback URL is http://localhost:3008/users/auth/github/callback.
* Myy .env consists of the following:
```
GITHUB_APP_ID=d9e88d43aeefe4c54a69
GITHUB_APP_SECRET=48836f5c1d4efbb211eab2469866992ec037a622
PORT=3000
OCTOBOX_DATABASE_NAME=octobox_test
OCTOBOX_DATABASE_USERNAME=winner1
OCTOBOX_DATABASE_PASSWORD=long_way_stinks
```

**Comment by jhsu802701** [comment]
OK, now I'm able to get it working.  The authorization callback URL is http://localhost:3008/auth/github/callback, "GITHUB_APP_ID" should be "GITHUB_CLIENT_ID", and "GITHUB_APP_SECRET" should be "GITHUB_CLIENT_SECRET".  Now it's time for me to change my ID and SECRET values to something else and update my build script to reflect these corrections.
