### ISSUE TITLE
Add Service Worker support

### ISSUE THREAD

**Issue by xadamy** [octobox/octobox#138]
Seems like Octobox might be an interesting case for Service Worker support. I'd be interested in how nicely ServiceWorkers played with Turbolinks. 🔌

**Comment by tarebyte** [comment]
Just to make sure I understand what we're talking about is this the [`Service Worker`](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) you're referring to @xadamy?

**Comment by xadamy** [comment]
@tarebyte That's the one, yeah

**Comment by andrew** [comment]
Rather than listing the technology can you say what it will actually enable?

**Comment by xadamy** [comment]
I feel like the very first paragraph of the link @tarebyte posted explains what it would enable succinctly enough. It would potentially allow much of the octobox application to still be operable in areas of poor internet connectivity. 

At the very least this could be done with static asset caching and caching Turbolinks partials so that users can still move between sections offline. Actions like resyncing and "Archive all" could be temporarily deactivated, or synced with the server on a timeout.

**Comment by andrew** [comment]
https://github.com/rossta/serviceworker-rails Looks like a handy plugin for getting it to work with the asset pipeline. 

Is it ok if we rename the issue to something like "Add offline support"?

**Comment by andrew** [comment]
I wonder how well it plays with turbolinks? I get the feeling that this would push us towards client side rendering and doing all things in JavaScript which doesn't sound like fun to me

**Comment by xadamy** [comment]
Just for the record, I would not be interested at implementing this feature myself if it resulted in shifting to more client side rendering. My interest begins and ends with how well it works with Turbolinks.

That being said, Service Workers have always been marketed as a progressive enhancement tool and it would be a major flaw in the spec if it required more client side rendering to achieve it.

At the very least, octobox could benefit from the asset caching alone.

**Comment by andrew** [comment]
Asset caching sounds good 😊 

I can't see it enabling any offline functions like filtering without rebuilding the client to work with JSON responses from the server

**Comment by andrew** [comment]
Going to close this one for now, I don't think we'll get much benefit from it at the moment
