### ISSUE TITLE
An assigned PR does not have "assigned" label

### ISSUE THREAD

**Issue by mbohlool** [octobox/octobox#1380]
Are you experiencing this issue in octobox.io or your own instance?
 - [X] octobox.io
 - [ ] My instance

🐞 **Problem**

I have a PR assigned to me:https://github.com/kubernetes/kube-openapi/pull/124
it does show up in the list, but as "mentioned" not "assigned"

🎯 **Goal**

Labeling is most of the reason I started to use octobox. Right labels is important or I won't trust it.

💡 **Possible solutions**

Assign the right label.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by evexoio** [comment]
@mbohlool as I understand, you'll get an assigned label once an issue is assigned to you only, otherwise if its a comment or a mention on an issue you're assigned to, you'll get comment or mention as the label. so I don't really think that's a bug. but maybe it's non expected behavior for you.

maybe we should support multi labels if that's not already there?

**Comment by andrew** [comment]
@mbohlool there's a bit of a restriction from the github api when it comes to the "reason" filters, basically that value gets updated to what ever the last reason that you got notified was, i.e. if you get mentioned in a thread after you got assigned to it, then the "reason" will be mentioned.

You should still be able to see all the PRs assigned to you with this link: https://octobox.io/?assigned=mbohlool

**Comment by mbohlool** [comment]
I think it is easy to just check the assignee of an incoming PR/Issue. When a PR changed, you can take a look at assigniee and label it as assigned even if github is saying the reason is something else. Assigned label is an important one and I would like to get unreaded PR/Issues that assigned to me.

**Comment by andrew** [comment]
@mbohlool we do store the assignee, but the current behaivour of the `reason` label matches what GitHub tells us and will be quite involved to change that whilst not introducing subtle behviour changes for other users.

You can always access notifications for things assigned to you from the sidebar link:

![screen shot 2019-01-16 at 12 55 24](https://user-images.githubusercontent.com/1060/51250359-0ca98f00-198e-11e9-930c-483e54f4c55c.png)
