### ISSUE TITLE
Why does bot labeling require repo scope?

### ISSUE THREAD

**Issue by misterikkit** [octobox/octobox#1385]
### Summary of Problem

The [documentation](https://octobox.io/documentation#navigating) for octobox states that bot labeling requires repo access, but the section on supported prefixes states that "bot:true" filters users whos "name ends in '-bot'". If it is based on usernames, why is repo access required? Also, should this be able to work on public repos without repo access?

(Please answer all 3)

- What are you trying to do?
I want to ignore notifications from bots in the [kubernetes](http://github.com/kubernetes/kubernetes) repo. e.g.
  1. search "bot:true"
  2. select all
  3. archive
- What happens?
  - Notifications are not labeled as bot notifications.
  - Searching "bot:true" shows no results.
- What should have happened?

### Steps to Reproduce the Issue
1. Subscribe to any recent PR from [k8s](https://github.com/kubernetes/kubernetes/pulls)
2. @k8s-ci-robot will comment on the PR ...[repeatedly](https://gist.githubusercontent.com/misterikkit/1e953c0262247219b65f5bf4fc9beaa5/raw/cb2e6ed9443012e31ed8260cabbeb48b7765c844/k8s-ci-robot-spam.png)
3. attempt to filter bot notifications in octobox.

(help octobox maintainers reproduce your issue to make it easier to fix)

### Versions, Operating System and Hardware

- Which version/commit of Octobox are you using? 
Version: 2bcf298 
- Which browser are you accessing Octobo with?
Chrome
- Windows? Linux? Mac?
Linux
- How are you deploying Octobox (Docker, Heroku, Openshift, etc)
Accessing https://octobox.io

**Comment by BenJam** [comment]
> If it is based on usernames, why is repo access required?

I believe it's because notification scope doesn't provide author info. Are you able to install the GH app on the org?

**Comment by misterikkit** [comment]
@BenJam Thanks for the reply. If that's a limitation in the API, then it makes perfect sense. I don't have the authority to add apps to the k8s org, but I can propose it.

**Comment by BenJam** [comment]
> I don't have the authority to add apps to the k8s org, but I can propose it.

This is indeed a restriction that we would love to be able to work around 👍

**Comment by misterikkit** [comment]
Not trying to reopen this issue, but what prevents this from working on public repos? Is it expensive to check, or maybe it would require a bunch of special-case code?
