### ISSUE TITLE
Check are not align correctly

### ISSUE THREAD

**Issue by Hydrog3n** [octobox/octobox#1397]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**

The checkbox are not align correctly in notification list

![image](https://user-images.githubusercontent.com/1223893/50513269-f5663880-0a96-11e9-9ae6-a9f70944810a.png)

🎯 **Goal**

The checkbox as to be align correctly. 

📋  **Steps to solve the problem**

I use the docker image and the commit version is : Version: eb5dc88

**Comment by evexoio** [comment]
@Hydrog3n I can reproduce the bug, will push a fix ASAP
