### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by jhsu802701** [octobox/octobox#1408]
SimpleCov shows 65.97% test coverage overall.  The breakdown is:
* Controllers: 83.99%
* Channels: 0.0%
* Models: 79.62%
* Mailers: 100.0%
* Helpers: 87.23%
* Jobs: 77.12%
* Libraries: 31.93%
* Ungrouped: 88.73%

**Comment by jhsu802701** [comment]
Channels and libraries are the weakest points.  Should I be concerned, or am I worrying too much about nothing?

**Comment by andrew** [comment]
Test coverage can always be improved but we have a good amount of high level integration tests that catch most issues.

**Comment by andrew** [comment]
When I run simplecov locally it's showing 77.93%:

![screen shot 2019-01-03 at 12 14 41](https://user-images.githubusercontent.com/1060/50637277-38218800-0f51-11e9-8c5e-11b9ff7100e2.png)
