### ISSUE TITLE
Stay on same page when archiving a single entry

### ISSUE THREAD

**Issue by ringods** [octobox/octobox#141]
Using https://octobox.io.

My Inbox has multiple pages of entries. When I'm on page 2 or higher, and I archive an entry using the checkbox, the UI refreshes and I'm back on page 1. Very annoying if you want to process a set of entries on some specific page.

**Comment by andrew** [comment]
Agreed, very annoying! Related to https://github.com/andrew/octobox/pull/139 where @briannelson is going to persist `per_page` and should persist `page` where it makes sense too.

**Comment by andrew** [comment]
This is fixed for things in the inbox now thanks to @karpiu 🎉
