### ISSUE TITLE
hosted octobox having spurious application errors in Chrome

### ISSUE THREAD

**Issue by cmluciano** [octobox/octobox#1427]
### Summary of Problem

- What are you trying to do?
  -  Visit octobox.io
- What happens? 
  - Over the last 2 days I have hit the heroku application error page consistently. At first it just appeared to happen during some filter views but now I cannot hit the homepage either. Githubstatus.com has not shown issues during any of the attempts at loading.

- What should have happened?
  - octobox.io should be reachable

### Steps to Reproduce the Issue

visit octobox.io and note error 
![image](https://user-images.githubusercontent.com/4790487/50713553-6e3f3480-1043-11e9-8237-a6f9d48a268e.png)

### Versions, Operating System and Hardware

- Which version/commit of Octobox are you using?
  - I can't access the main page to tell.
- Which browser are you accessing Octobo with?
  -Chrome Version 71.0.3578.98 (Official Build) (64-bit)
- Windows? Linux? Mac?
  - Mac
- How are you deploying Octobox (Docker, Heroku, Openshift, etc)
  - octobox.io

**Comment by cmluciano** [comment]
I tried this in mobile chrome and incognito mode so it does not appear to be a token or cookie issue.

I changed the title though since opening in Safari worked immediately, so this may be related to a Chrome specific change.

**Comment by cmluciano** [comment]
Ya the browser theory Is incorrect with additional tries :P thanks for taking a look :)

**Comment by andrew** [comment]
![22cbb4ed-8467-4d63-9080-3398e88681cf](https://user-images.githubusercontent.com/1060/50726208-b2910a00-1101-11e9-94bb-9e92ba08e1d0.png)

Response times are looking much better now so going to close this
