### ISSUE TITLE
mysql database connection using docker

### ISSUE THREAD

**Issue by bbrendon** [octobox/octobox#1429]
I'm trying to get the octobox docker container to connect to mysql. I poked around in the code a bit and I'm not sure exactly how it works but from what I can tell mysql would only _maybe_ work as a database URL.  I tried removing all the database entries and added this:

`DATABASE_URL="mysql2://octobox:asdf9jf2l@1.1.1.1/octobox"`

I get an error. `nc: getaddrinfo: Name does not resolve`.

But I went into the docker container and nc'ed to the database server without an issue so it appears the network isn't actually the problem.

**Comment by andrew** [comment]
@bbrendon two related stackoverflow answers that might be helpful:

- https://stackoverflow.com/a/45304286/120434
- https://stackoverflow.com/a/34908724/120434

**Comment by andrew** [comment]
@bbrendon I believe this is more like a specific configuration in docker for your setup rather than a feature, I'm also not that familiar with docker to be able to advise, will see if anyone for experienced can help.

**Comment by kivikakk** [comment]
You could consider having MySQL listen on a socket, then bind mount the socket file into the container?

**Comment by j-mcnally** [comment]
Why do expect MySQL to be at 1.1.1.1?

You’d be better off starting MySQL in a named container like mysql and connecting mysql and Octobox to a network and then using the container name as the host name.  So you’d just punch in mysql rather than 1.1.1.1

**Comment by bbrendon** [comment]
telling you 1.1.1.1 obfuscates my actual server.

**Comment by j-mcnally** [comment]
well i primarily ask because its likely a local network via docker but idk.
