### ISSUE TITLE
Add suggested 'pinned searches'

### ISSUE THREAD

**Issue by BenJam** [octobox/octobox#1431]
Following from my [interview with Pia](https://medium.com/open-collective/stay-calm-untangle-your-github-notifications-bf601dd58c72) it'd be cool to add a couple of pinned searches that help onboard new users. I use

* archivable: `state:closed,merged archived:false` 
* mergeable: `inbox:true status:success`
* my prs: 'inbox:true type:pull_request author:me'
* my reviews: 'inbox:true type:pull_request reason:assigned'

This might also lift the number of users utilising pinned searches, or raise enough eyebrows for us to remove it :)

**Comment by Zimmi48** [comment]
Hasn't this been addressed already?
