### ISSUE TITLE
For the purpose of updates, ignore my own activity

### ISSUE THREAD

**Issue by paulmelnikow** [octobox/octobox#1437]
Hi! Thanks again for the great tool, and apologies if this has already been posted! I searched but did not find it.

### What feature you'd like to see

When I have an issue, with all notifications, and I post a comment, close it, or merge it, I don't want to see the Status Change or e.g. Mention activity that originated by myself.

## Motivation

I process through a massive amount of issues, and have a particular involved relationship with one project which I lead. I generally keep well on top of it by clicking through the GitHub UI, and end up using Octobox to keep track of a few things that need to be followed up on later (e.g. after an automated build finishes).

It means after I finish a round of work, I have a lot of cleanup to do in Octobox. Many notifications sitting there for things I have read. So I select them and archive them.

A meaningful fraction of the notifications that are sitting around were _generated on my own activity_. Often I will close an issue, or was the last person to comment or tag.

If the issue was archived, and then _I_ comment, why should it come back into the inbox? That doesn't seem helpful, and indeed creates noise that I then have to deal with.

I love what Octobox is trying to do, and really think this improvement would make it work better in my workflow.

## Pitch

I think that was the pitch ^^ 😁 

Reduce noise! Don't show changes that arise from my own activities! Make Octobox work better for people who aren't just tracking a lot of issues, but interacting with a lot of them!

**Comment by paulmelnikow** [comment]
Here's an example.

I did some stuff, walked away from the computer for a while, and came back and opened Octobox. The top three updates (which refreshed after I walked away) are all a result of my own activity.

<img width="1117" alt="screen shot 2019-01-08 at 3 21 57 pm" src="https://user-images.githubusercontent.com/1487036/50856631-33960e80-1359-11e9-8472-7eb9a1c2860e.png">

**Comment by andrew** [comment]
@paulmelnikow just want to check, you're not seeing new notifications generated by your own activity? 

For existing things in your inbox getting reordered when you update one, we're kind of at the mercy of the GitHub API there, as we just hear about the `updated_at` changing without knowing why or who updated it.

**Comment by paulmelnikow** [comment]
> you're not seeing new notifications generated by your own activity?

Could you clarify your question?

> For existing things in your inbox getting reordered when you update one, we're kind of at the mercy of the GitHub API there, as we just hear about the `updated_at` changing without knowing why or who updated it.

Ah, that's too bad! I though GitHub had APIs for comments and status updates and I figured that's what you were using. I wonder if there is any other way that this could work.

**Comment by andrew** [comment]
@paulmelnikow I think this will partially be fixed by https://github.com/octobox/octobox/pull/1504

**Comment by andrew** [comment]
@paulmelnikow #1504 is live on https://octobox.io now, can you see if the same behaviour you original reported still happens?

**Comment by andrew** [comment]
@paulmelnikow #1504 is live on https://octobox.io now, can you see if the same behaviour you original reported still happens?

**Comment by paulmelnikow** [comment]
I'll keep an eye on it and let you know!

**Comment by paulmelnikow** [comment]
Yes, I do seem to be getting a lot fewer notifications originating from my own actions!

How about we close this out, and if I find there's a kind of "false positive" that is still showing up, I'll open a new issue?

**Comment by andrew** [comment]
👍

**Comment by paulmelnikow** [comment]
This is making a huge improvement in usability. Thank you so much!
