### ISSUE TITLE
Filter by organization

### ISSUE THREAD

**Issue by whit537** [octobox/octobox#144]
I'd like to be able to see all @Gratipay notices at once, e.g., without having to manually select all Gratipay repos.

![screen shot 2016-12-23 at 7 48 51 am](https://cloud.githubusercontent.com/assets/134455/21454170/464d0432-c8e4-11e6-870d-183ac65144a4.png)

**Comment by andrew** [comment]
We started storing the day for that a few days back in https://github.com/octobox/octobox/pull/74 

Just needs a UI and filter added cc @briannelson @knolleary

**Comment by knolleary** [comment]
I have this as a starter for 10 on the UI side:
<img width="118" alt="cursor_and_octobox" src="https://cloud.githubusercontent.com/assets/51083/21455188/1a9567a8-c916-11e6-9217-680680a78a06.png">

**Comment by andrew** [comment]
👌  @knolleary want me to hook up the filters in the rails controller?

**Comment by knolleary** [comment]
@andrew thanks - was just starting to poke at the edge, but my rails is weak.

The approach I was think was keep it as the 'repo' filter, but in `notifications_controller` check if that filter has a `/` in it, if not, do a `starts-with` type filter, rather than an exact filter. I'm sure in rails there are dozens of proper ways of doing that... so probably best if you just make it happen in one line of code ;)

**Comment by knolleary** [comment]
which is to say, I wasn't thinking we'd add yet another filter arg for owner as the repo name we have already contains the owner details.

**Comment by andrew** [comment]
@whit537 until the UI ships you can see all the gratipay issues by changing the url param: https://octobox.io/?owner=gratipay

**Comment by knolleary** [comment]
@andrew just spotted the 'archive_all' function doesn't take the new owner filter into account.

**Comment by whit537** [comment]
Confirmed, thanks! :-)

**Comment by andrew** [comment]
@knolleary I'm planning on removing "archive all" and replacing it with a "Select all" option to go along with https://github.com/octobox/octobox/pull/150#issuecomment-269000320
