### ISSUE TITLE
How can I negate a set of search terms?

### ISSUE THREAD

**Issue by tripleee** [octobox/octobox#1448]
### Summary of Problem

I participate in a project which receives a lot of routine PRs which are usually quickly handled. I would like to exclude those by default.

- What are you trying to do?

I want to exclude a set of issues which can be isolated with the search

    repo:charcoal-se/smokedetector type:pull_request

Incidentally, if I add `state:merged` or `state:closed` the list is empty; why is that?

Ideally, I would like to add `state:merged` and also `reason:subscribed` if that's the *only* reason I am notified -- but I could be pinged because I am subscribed _and_ pinged, can't I?

So naively something like

    inbox:true -(repo:charcoal-se/smokedetector type:pull_request state:merged -reason:subscribed)

- What happens?

The syntax I am imagine should exist apparently doesn't exist.  Perhaps I am overlooking something in the documentation.

- What should have happened?

### Steps to Reproduce the Issue

In the broadest terms, try to filter out _only_ the most prevalent category of issues from your inbox.

### Versions, Operating System and Hardware

- Which version/commit of Octobox are you using?

It doesn't seem to identify itself clearly; whatever is currently running on octobox.io

As of right now, the latest commit on master is https://github.com/octobox/octobox/commit/df97b99ef3ac4ed59a873e6a34d5684f6be7bd5a

- Which browser are you accessing Octobox with?

Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

- Windows? Linux? Mac?

MacOS High Sierra

- How are you deploying Octobox (Docker, Heroku, Openshift, etc)

I'm not.

**Comment by andrew** [comment]
As mentioned in the search docs:

> Some prefixes also can be negated to exclude certain types of results, for example:
"-repo:splitrb/split -type:commit -owner:octobox -reason:mention". 

So I think you could do:

`inbox:true -repo:charcoal-se/smokedetector -type:pull_request -state:merged reason:subscribed`

**Comment by tripleee** [comment]
I don't want to exclude all pull requests, or all merged tickets. I want to exclude the ones which are in the SmokeDetector repo, ideally which contain ": watch" in the title, and even more ideally which are successfully merged. I was hoping parentheses would allow me to do a grouping like this but they don't seem to be supported, so my question is, is there another mechanism which allows me to do this?

**Comment by BenJam** [comment]
`inbox:true -repo:charcoal-se/smokedetector -type:pull_request -state:merged reason:subscribed watch ` should get you pretty close to what you're looking for. I don't believe notifications are fired from GH for branch deletions https://developer.github.com/v3/activity/notifications/#notification-reasons

**Comment by andrew** [comment]
@tripleee I think I understand what you're asking for (sub-queries), and no there's currently no way to do that, all filters operate on the whole search.

**Comment by tripleee** [comment]
Thanks for confirming. Should I open a wishlist ticket or do you already have something like this in your plans?

**Comment by andrew** [comment]
@tripleee opening a feature request issue would be great thanks 👍
