### ISSUE TITLE
Sidebar filter behaviour

### ISSUE THREAD

**Issue by knolleary** [octobox/octobox#145]
Again with the sidebar filter behaviour.

There remain some (possibly intentional) inconsistencies in behaviour when different filters are clicked. Here is a summary:

**Buckets** : inbox / archive / starred
**Filters** : status, type, reason, repo

1. clicking a bucket clears all existing filters
2. clicking any filter whilst in 'starred' bucket takes you to the inbox
3. clicking any filter clears the current 'reason' filter
4. clicking any filter clears the current 'status' filter, except if you click 'repo' which preserves 'status'

This issue is to either sign-off on these behaviours as intentional, or to find the right set of behaviours.

**Comment by knolleary** [comment]
My preferred set of behaviours would be:

1. clicking a bucket clears all existing filters
2. clicking any filter leaves you in the bucket you were in and leaves other filters alone

**Comment by andrew** [comment]
Sounds like a couple of bugs to me, agree with both expected behaviours 👍

**Comment by andrew** [comment]
Just deployed a fix for this I believe

**Comment by knolleary** [comment]
heh - that'll be the merge conflict I wasn't expecting
