### ISSUE TITLE
No state preserved when sidebar is expanded on small screen sizes

### ISSUE THREAD

**Issue by rhuss** [octobox/octobox#1453]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [X] My instance

🐞 **Problem**

When using a small screen width, octobox's responsive UI shows a menu button to switch on/off the left sidebar for the filter selection. However, when selecting expanding the sidebar and then selecting a filter then the next view is again without the sidebar. As a user, I would expect that Octobox would respect my previous decision to show the sidebar even after selecting a filter.

🎯 **Goal**

It is super tedious to always press the "menu expand" button again after every filter selection.

Another idea would be to make this responsive behaviour to hide the sidebar configurable or make the minimal width configurable at which the button should show up.

💡 **Possible solutions**

📋  **Steps to solve the problem**

* Resize your window to make it smaller so that the expand button shows up

![grafik](https://user-images.githubusercontent.com/99080/51082829-15406200-170f-11e9-88c8-bfbf474f9cd5.png)

* Push the expand button (top left button) to expand the menu

![grafik](https://user-images.githubusercontent.com/99080/51082836-25584180-170f-11e9-8d0f-4869a9369532.png)

* Select any filter on the left side. The sidebar is hidden again now.

![grafik](https://user-images.githubusercontent.com/99080/51082843-3bfe9880-170f-11e9-9ae3-abda33610e89.png)

**Comment by BenJam** [comment]
good point well made.

**Comment by BenJam** [comment]
Implemented this and was reminded this would likely involve an additional click in most cases. On my iPhone SE for example it is terrible.

**Comment by andrew** [comment]
@rhuss it sounds like a regression in a responsive breakpoint change, I don't believe you should be seeing that pop out menu on a screen that wide.

**Comment by rhuss** [comment]
If it helps, the switch to responsive happens for me at 1200px width.

**Comment by BenJam** [comment]
strange, breakpoint is at < 1,200px for this behaviour. We could knock it down to < 992px.

**Comment by rhuss** [comment]
Yep, that would work for me.

**Comment by BenJam** [comment]
<img width="994" alt="screenshot 2019-01-14 at 16 11 09" src="https://user-images.githubusercontent.com/158833/51124768-05ac4080-1817-11e9-86f1-ee1fcf16c756.png">

^ bit of a squeeze at 996-1,200px tho

**Comment by andrew** [comment]
Fixed in https://github.com/octobox/octobox/pull/1458
