### ISSUE TITLE
API page does not have method list

### ISSUE THREAD

**Issue by tripleee** [octobox/octobox#1463]
I am visiting the page https://octobox.io/docs.

It claims it should have a list of API methods down the left side, but it doesn't for me.

I am visiting using Chrome on a Mac High Sierra laptop.

Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

The documentation says

> ### Endpoints
> The endpoints are listed by controller down the left hand side of these docs.

But as per the attached screen shot, there is nothing at all down the left hand side.

<img width="600" alt="screen shot 2019-01-15 at 9 27 12" src="https://user-images.githubusercontent.com/2160915/51165348-95e69600-18a8-11e9-9b85-8ee0aa8394f0.png">

🎯 **Goal**

I would like to find the documentation for your API methods.

💡 **Possible solutions**

Perhaps there is another URL where this is published with the sidebar as intended.

As a workaround, I guess it would not be impossible to find the documentation in the source tree.

**Comment by tripleee** [comment]
The top iframe is actually scrollable, and reveals an error message:

> ### We can't find whatever it was you were looking for.
> In truth, we may never have had what you are looking for. Maybe try [re-syncing your notifications?](https://octobox.io/)

The footer contains this information:

`
Generated on Mon Jan 14 20:52:23 2019 by yard 0.9.16 (ruby-2.6.0).`

**Comment by BenJam** [comment]
looks like the odcs aren't being generated consistently... we'll take a look asap.

**Comment by ghosteathuman** [comment]
@tripleee I think the more accurate link is at [https://octobox.io/docs/](https://octobox.io/docs/). Most of the reference links are corrected to point to this link. From there the API methods are visible.
