### ISSUE TITLE
Make listing match GitHub listing

### ISSUE THREAD

**Issue by whit537** [octobox/octobox#147]
I expect that when I hit Octobox, it will list the same notifications that are present in my GitHub notifications. However, it lists many, many more. Why? How do I make it match my GitHub notifications?

# On GitHub

![screen shot 2016-12-23 at 7 51 33 am](https://cloud.githubusercontent.com/assets/134455/21454228/b42f0068-c8e4-11e6-8f2e-930ab8da497a.png)

# On Octobox

![screen shot 2016-12-23 at 7 52 25 am](https://cloud.githubusercontent.com/assets/134455/21454262/fa07f0d6-c8e4-11e6-8ea6-4d3c42071e91.png)

**Comment by andrew** [comment]
@whit537 that's a feature, the main feature in fact:

> Notifications are marked as read and disappear from the list as soon as you load the page or view the email of the notification. This makes it very hard to keep on top of which notifications you still need to follow up on.

**Comment by whit537** [comment]
Whether notifications are marked as read and disappear from the list is separate from whether they appear in the first place. :-)

What makes a notification appear in the first place on GitHub? It's different than on Octobox, I think ...

**Comment by andrew** [comment]
The first time you login no notifications are archived, the "Read/Unread" filters on the right should match the notifications on GitHub.com, i.e https://octobox.io/?status=true should look the same.

Personally I found many notifications I'd forgotten about or didn't even know existed the first time I signed in and other people have found that too so I think we'll stick with this behaviour for now

**Comment by whit537** [comment]
Hmm ... but the first time I logged in was a while ago. Now I'm trying to reconcile the notifications I see in GitHub with the notifications I see in Octobox (I actually just switched from email to GitHub notifications a week or two ago). So far I don't trust Octobox to show me everything I need to see. Why does GitHub think I have six unread notifications, while Octobox only thinks I have three?

![screen shot 2016-12-23 at 10 15 29 am](https://cloud.githubusercontent.com/assets/134455/21456803/c769fb7e-c8f8-11e6-956f-94e0ac0e7653.png)

![screen shot 2016-12-23 at 10 15 14 am](https://cloud.githubusercontent.com/assets/134455/21456804/c76a0ae2-c8f8-11e6-8edd-5fa1e9065114.png)

**Comment by andrew** [comment]
@whit537 Octobox doesn't sync automatically, have you hit the refresh button?

**Comment by whit537** [comment]
Yes, many times.

**Comment by whit537** [comment]
When I hit the refresh button (the circle-y thing next to "Archive all", right?), it refreshes the page, clearing my filters—but still only showing three unread.

![screen shot 2016-12-23 at 10 20 24 am](https://cloud.githubusercontent.com/assets/134455/21456936/7d17e440-c8f9-11e6-9cb0-cff96a47727f.png)

**Comment by andrew** [comment]
What do your settings look like on this page: https://github.com/settings/notifications

Here's mine: 
![screen shot 2016-12-23 at 3 21 39 pm](https://cloud.githubusercontent.com/assets/1060/21456961/908239de-c923-11e6-8590-b70338c5867a.png)

**Comment by whit537** [comment]
![screen shot 2016-12-23 at 10 24 10 am](https://cloud.githubusercontent.com/assets/134455/21457001/fce266a0-c8f9-11e6-82dc-7959e359dac9.png)

**Comment by andrew** [comment]
And the ones below it? 

![screen shot 2016-12-23 at 3 25 35 pm](https://cloud.githubusercontent.com/assets/1060/21457021/126eb0c6-c924-11e6-80fb-86f1f233d39d.png)

**Comment by whit537** [comment]
@andrew I don't have those because I haven't selected "Email" for either of the above two options—a clue?

**Comment by whit537** [comment]
> a clue?

Seems unlikely, since that options block says "Choose which email updates ...".

**Comment by andrew** [comment]
Ah yes, nevermind, I'm just scanning for checkboxes that might make a difference. 

Time to go poking around in the db!

**Comment by whit537** [comment]
Best of luck! I'm heading afk for the holiday, so no rush on this end. :-)

Have a great Christmas! 🎄  🎅  🎁  💃

**Comment by andrew** [comment]
Ok I know why it's happening, we currently only pull notifications from the github API using the `since` option with a value of 1 month ago, the last update on https://github.com/gratipay/inside.gratipay.com/pull/263 is July 10th 2015 so the downloader would have never got that one.

An unfortunate case of not having full access to the GitHub database I'm afraid

**Comment by whit537** [comment]
@andrew I just refreshed Octobox and my Unread matches my Unread on GitHub. So far so good! I will monitor for a while and report back if I see additional wonkiness. #174 does smell like a good explanation.

**Comment by andrew** [comment]
🙈 
![when_you_assume](https://cloud.githubusercontent.com/assets/1060/21510032/f38ce8ec-cc86-11e6-9e46-79076f9aed0e.png)

**Comment by whit537** [comment]
Pretty sure #174 closes this. Will reopen if not! :-)
