### ISSUE TITLE
'mark as unread' does not propogate status to octobox

### ISSUE THREAD

**Issue by chris48s** [octobox/octobox#1500]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
GitHub has recently introduced a 'mark as unread' feature (Note this is actually a real feature in GitHub now - I'm not just using a browser plugin). I think this has only rolled out in the last day or 2, so I appreciate it is a very new feature. Marking a notification as unread in GitHub doesn't mark it unread in Octobox. To reproduce the issue:

Read a notification on octobox.

In GitHub, go to your read notifications:

![screenshot at 2019-01-18 21-47-59](https://user-images.githubusercontent.com/6025893/51414571-decd7180-1b6a-11e9-9b4e-03c82032d744.png)

Mark the notification as unread:

![screenshot at 2019-01-18 21-46-33](https://user-images.githubusercontent.com/6025893/51414587-e7be4300-1b6a-11e9-8c35-f82ee9e27432.png)

Press sync in octobox.

The notification is still marked as read in octobox.

🎯 **Goal**

Reading a notification in GH marks it read in Octobox. The inverse should ideally be true too. GitHub and octobox should reflect the same reality.

**Comment by andrew** [comment]
I have an idea of how to implement this, will tackle it next week, thanks for opening an issue about it 👍

**Comment by andrew** [comment]
@chris48s just deploying #1504 now which should handle this correctly.
