### ISSUE TITLE
Unique Jobs Digest contiously causes users to get stuck in the queue

### ISSUE THREAD

**Issue by jules2689** [octobox/octobox#1531]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**

The unique jobs digest cache is not expiring. [This comment](https://github.com/octobox/octobox/issues/1067#issuecomment-438734606) seems to suggest this is RAM allocation.

Do you have any more details @andrew ? I'd like to poke this a bit more since adding expiration times do not help.

As it stands, I just clear out the unique digests queue (which is quite tedious).

**Comment by andrew** [comment]
@jules2689 yeah the sidekiq-unique-jobs gem don't seem to have fixed that properly, I'm running a daily cronjob on octobox.io to clear them out at the moment: https://github.com/octobox/octobox/blob/master/lib/tasks/tasks.rake#L52

**Comment by jules2689** [comment]
I'm trying these options locally: https://github.com/Shopify/octobox/commit/ab799e479ec67b3bbc33025eca05bf5944290233

**Comment by andrew** [comment]
I don't believe this is still an issue, closing for now
