### ISSUE TITLE
Mute/hide pinned search results from Inbox

### ISSUE THREAD

**Issue by bastilian** [octobox/octobox#1541]
### What feature you'd like to see

It would be nice to be able to hide certain notifications by default. For this pinned searches could be used with a flag to filter out those notifications out that match the critera out or the results. 

## Pitch

Having this feature would allow to better priorities notifications that really need attention. Using pinned searches for this would make it possible to filter based on organisations and down to certain repositories. It would/should not use GitHubs Mute setting on repositories, but simple hide them for as long as the flag is enabled for a pinned search.

**Comment by bastilian** [comment]
Ps.: If collecting matching notification ids from search results using criteria from pinned searches that have a "hide" flag is an acceptable solution, I might find time to add that. :)

**Comment by andrew** [comment]
That sounds like a reasonable approach to a solution 👍
