### ISSUE TITLE
Labels get repeated

### ISSUE THREAD

**Issue by timhoffm** [octobox/octobox#1554]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

When an issue has multiple labels, one of them is repeated instead of showing all the labels:

![grafik](https://user-images.githubusercontent.com/2836374/52009976-897f5180-24d4-11e9-8066-ef347394d6d1.png)

**Comment by andrew** [comment]
@timhoffm just deploying a fix out for this, have cleaned out the existing duplicates in the database too
