### ISSUE TITLE
Request: Helm chart

### ISSUE THREAD

**Issue by donifer** [octobox/octobox#1577]
### What feature you'd like to see
A Helm chart for installing octobox in a Kubernetes cluster.

## Motivation
The installation guide is awesome and offers a decent amount of ways of getting Octobox self-hosted. It would be awesome if a Helm chart existed to make running octobox in a K8s cluster a breeze.

## Pitch
Elevator pitch: `helm install --name octobox stable/octobox`

**Comment by andrew** [comment]
That sounds like a great idea, are there any online resources to help someone set this up? I’d guess we it’ll be pretty similar to the Docker compose config

**Comment by andrew** [comment]
The might be helpful: https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/#alternative-conversions

**Comment by andrew** [comment]
Looks like @halkeye has mande one available over here: https://github.com/halkeye-helm-charts/octobox

**Comment by halkeye** [comment]
I did I did, you are more than welcome to use it and provide feedback. Its been working for me for a couple weeks now.

https://halkeye.github.io/helm-charts/
