### ISSUE TITLE
Replace "Archive all" with a select all checkbox

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#158]
Now that we have https://github.com/octobox/octobox/pull/150 we have a bit of duplication in the menu:

![screen shot 2016-12-23 at 4 02 31 pm](https://cloud.githubusercontent.com/assets/1060/21457701/3f030772-c929-11e6-92bf-c58fa364fe11.png)

We should remove the "Archive all" button and replace with a gmail-like checkbox to select all the currently showing notifications:

![screen shot 2016-12-23 at 4 04 25 pm](https://cloud.githubusercontent.com/assets/1060/21457748/89c0452c-c929-11e6-8301-d6d3929e1bc0.png)

**Comment by briannelson** [comment]
Yes.
