### ISSUE TITLE
Signing in does not redirect to home page

### ISSUE THREAD

**Issue by purinkle** [octobox/octobox#1580]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

When I sign into Octobox via GitHub, I am being redirected to the GitHub homepage instead of my Octobox inbox.

🎯 **Goal**

I don't want to have to type the Octobox URL in twice every time I sign in.

💡 **Possible solutions**

Redirect to the Octobox inbox after authenticating the person signing in.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by andrew** [comment]
oh that's weird, definitely a bug!

**Comment by andrew** [comment]
Possibly related to this change: https://github.com/octobox/octobox/commit/d497c5ec4eb7bb5121c99f08c5b99d4490e7a51d#diff-d5241d488259f32ecbe2f636133e5ddaL18

**Comment by andrew** [comment]
I believe this has been fixed, please let us know if not.
