### ISSUE TITLE
Bugsnag API key

### ISSUE THREAD

**Issue by jhsu802701** [octobox/octobox#1582]
The test suite passes the first time after I set up Octobox in my local Docker development environment, but it freezes up on subsequent runs.  The test.log file shows the following message:
```
No valid API key has been set, notifications will not be sent
```
However, the app does work on my local browser in the development environment.

**Comment by jhsu802701** [comment]
What are the values of the environment variables BUGSNAG_API_KEY and BUGSNAG_JS_API_KEY?  I don't see any instructions on where to get these Bugsnag API keys.

**Comment by andrew** [comment]
They are only used in production for https://Octobox.io, they shouldn’t be affecting anything else. 

Looks like you’re getting an exception, what’s showing up before that line in test.log?

**Comment by jhsu802701** [comment]
OK, the tests passed again when I reset my development environment.  (Docker is awesome!)
