### ISSUE TITLE
Objects not destroyed between tests

### ISSUE THREAD

**Issue by jhsu802701** [octobox/octobox#1585]
Why aren't objects destroyed between tests?  This makes it impossible to run just one test, and it means that adding tests that involve creating objects throws everything off and causes tests that passed before to fail.  Yes, I know that I can reset the test database with the command "bundle exec rake db:reset RAILS_ENV=test", but the current situation promotes the infamous "but it works on my machine" problem.

**Comment by andrew** [comment]
Sounds like a bug to me, perhaps we need to use something like https://github.com/DatabaseCleaner/database_cleaner

**Comment by jhsu802701** [comment]
Unfortunately, I haven't been able to get database_cleaner to work with Minitest.  (The examples I see are for RSpec.  I've set up database_cleaner with RSpec, but that's not what we're using here.)

My preferred way of doing things in Minitest is to use the "Capybara.reset_sessions!" and "Capybara.use_default_driver" commands in the teardown.  I tried to do that here, but I was getting bombarded with a long list of test failures and errors.  Then again, I may have to bite the bullet and fix all those tests.

I noticed that the Capybara gem is installed but is not used outside of the visual tests.  Is there any particular reason Capybara isn't used for these other tests?

**Comment by andrew** [comment]
No particular reason, many of the tests where written before capybara was added

**Comment by jhsu802701** [comment]
OK, now I understand why Capybara isn't used in most of the integration tests.  When added the teardown commands "Capybara.reset_sessions!" and "Capybara.use_default_driver" in test/test_helper.rb, I was flooded with a cascade of errors and failed tests.  I understand now that the Rails Tutorial playbook is the one to follow.
