### ISSUE TITLE
Intermittent error in notification controller test

### ISSUE THREAD

**Issue by jhsu802701** [octobox/octobox#1586]
It's in the "thread shows five commments" test of test/controllers/notifications_controller_test.rb.
```
Error:
NotificationsControllerTest#test_thread_shows_five_commments:
ActionView::Template::Error: Unidentifiable URL: ''
    lib/octobox/subject_url_parser.rb:22:in `initialize'
    app/models/notification.rb:136:in `new'
    app/models/notification.rb:136:in `web_url'
    app/helpers/notifications_helper.rb:345:in `notification_link'
    app/views/notifications/_notification.html.erb:49:in `_app_views_notifications__notification_html_erb__1176588156493083018_47050180922440'
    app/views/notifications/_list.html.erb:47:in `_app_views_notifications__list_html_erb___1751314935741716488_47050180614480'
    app/views/notifications/show.html.erb:11:in `_app_views_notifications_show_html_erb___1454823464852979011_47050177540300'
    test/controllers/notifications_controller_test.rb:1006:in `block in <class:NotificationsControllerTest>'
```

**Comment by andrew** [comment]
Yeah this one has been very annoying, I've not had time to get around fixing it yet.

**Comment by BenJam** [comment]
I should probably take a look a this since it's 'my' test.

**Comment by BenJam** [comment]
I've just taken a quick look at this and I'm not entirely sure what's going on.

**Comment by ghosteathuman** [comment]
I have done some investigation into this again via PR #2163 and I have narrowed it down to where `expanded_subject_url` in `notification.rb` passes an empty URL to `subject_url_parser.rb`, although still not able to pinpoint the root cause of that.

When running tests locally, I don't get any tests failures. I only get test failures when running in Travis.
