### ISSUE TITLE
Show the issue count for starred issues permanently

### ISSUE THREAD

**Issue by timroes** [octobox/octobox#1588]
### What feature you'd like to see

Currently you only see the count badge behind starred notification when you select that group.
I wish you would see a count badge all the time, e.g. also when "Inbox" is focused it should show the badge for starred notifications.

![screenshot-20190218-105049](https://user-images.githubusercontent.com/877229/52942688-bacc9e00-336b-11e9-812a-c362a9a0ebaa.png)

## Motivation/Pitch

I use starred issues/PRs as kind of a TODO list, so I know which PRs, issues need my immediate interaction (not to confuse with PRs still marked as review). It would be very nice to see if (and how many) starred issues I've still have, even when not being on that "Starred" page, to get an immediate overview of things you are still interested in.

Even if you don't use "Starred" as your TODO backlog, I think most use-cases of how "starred" issues can be used, would benefit from having the count badge available all the time.

## But what about Archived?

Since "Archived" is in that same list, one could potentially ask, whether or not it's reasonable to show the badge also for archived all the time. My personal feeling is, it shouldn't, since if you mark something as "Archived", you basically say "I am done with that", so I don't see a huge benefit of having the number around all the time. Maybe (also for layout purposes) it would then make sense to move "Starred" above Archived, so you're not having badge-no badge-badge in the layout.

**Comment by andrew** [comment]
👍
