### ISSUE TITLE
Show notification content collapsible in list

### ISSUE THREAD

**Issue by timroes** [octobox/octobox#1589]
### What feature you'd like to see

I would like to be able to see the content of a notification (i.e. the content of the comment or description of the issue), inside the table quickly when clicking on a row. That way you would get the same information you get via GitHub notification mails quickly. I sketched this very quickly in the following screenshot:

![screenshot-20190218-111302](https://user-images.githubusercontent.com/877229/52943936-8e665100-336e-11e9-881e-0a8c462d9336.png)

## Motivation/Pitch

I know you can enable to open notification in Octobox (instead of GitHub) in the settings. Why do I still wish for this? I think opening the whole issue/PR in the side panel is way more information then I care about in the notification most of the times. The notification might be the 15th comment in an issue, and I would just want to read that comment. If I open the issue in Octobox I now need to scroll a whole list of 15 comments to read what I am actually interested in.

I think just giving that latest update/information in place and in case the user needs more context they can open the issue still on GitHub (or in Octobox) would provide a more efficient workflow, if you're handling a lot of issues.

**Comment by andrew** [comment]
Did you notice that there's a title on hover that shows the first parts of the description? https://github.com/octobox/octobox/pull/1097

![screen shot 2018-10-12 at 16 20 40](https://user-images.githubusercontent.com/1060/46879606-62761480-ce3e-11e8-9adc-dc330a302496.png)

**Comment by timroes** [comment]
I actually have noticed that, but thanks for pointing it out again (maybe some people reading that haven't). I think there are three drawbacks to the title approach here:

* I personally have the feeling it's cut of too early, but that might just be a personal preference.
* It always shows the description of the issue/PR, not of the latest comment, i.e. if the notification actually was a comment left in that issue, I have no chance to see the comment, only to see the initial issue description.
* Since it's a title, I have no chance of clicking on links in there, which would be very useful. 

I can outline an example for point 3 a bit more: we're getting comments of our CI under PRs in case of success/failure. In the mail notification I can directly then click that link to the build to check its output. That wouldn't work in a title (and also not because of point 2, that it doesn't show the actual update but always the initial issue/PR description).

**Comment by BenJam** [comment]
Thanks for throwing this together. Easy solution might be a popover of the latest comment on the 'comment' icon...
