### ISSUE TITLE
Link to documentation page

### ISSUE THREAD

**Issue by jhsu802701** [octobox/octobox#1594]
### Link to the documentation page from the home page
So far, one gets a link to the documentation page only AFTER logging in.  I propose providing a link on the home page (index page prior to logging in) directly to the documentation page.

## Motivation
This would allow people to read more details without having to log in.  I noticed that when I go to the '/documentation' page without logging in, I get the documentation page and don't get redirected to the home page.  It appears that someone forgot to provide such a link on the home page.

**Comment by jhsu802701** [comment]
I can add this feature AND an integration test for it.

**Comment by andrew** [comment]
👍
