### ISSUE TITLE
personal_access_token_validator_test.rb:22 fails when personal access tokens are enabled

### ISSUE THREAD

**Issue by BenJam** [octobox/octobox#1601]
As above, trace: https://gist.github.com/BenJam/a8fd871bb39da44f506d7542795ba7d4

**Comment by andrew** [comment]
@BenJam you may want to roll that token now that you've posted it in a public gist 🙈

**Comment by andrew** [comment]
Those tests already have `stub_personal_access_tokens_enabled` which does the equivalent of setting `ENV['PERSONAL_ACCESS_TOKENS_ENABLED']` to true, looks like the test is failing because the token being sent in the request isn't the same as the one being stubbed

**Comment by BenJam** [comment]
> https://medium.com/@BenJam/no-more-because-user-needs-3400da428ac9

let's pretend i did that before I posted it. Also: this is an access token bound to a particular app that I own right, rather than a personal access token so not the worst :)

**Comment by andrew** [comment]
PR here: https://github.com/octobox/octobox/pull/1804
