### ISSUE TITLE
The notifications index page has no link to the home page

### ISSUE THREAD

**Issue by jhsu802701** [octobox/octobox#1606]
The notifications index page (the index page you get when you're logged in) does not provide a link to the home page (the index page you get when you're not logged in).  I can provide a pull request that provides this.

**Comment by andrew** [comment]
@jhsu802701 that's by design, because they are both served from the same path `/`, if there's information that's particularly useful on the homepage after you've logged in, it should be available in the documentation.

**Comment by BenJam** [comment]
++ it would take a lot of refactoring for minimal/arguably no benefit. If there's info there that we should reflect elsewhere then please do open a ticket for that 👍
