### ISSUE TITLE
Add support for draft pull requests

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#1613]
GitHub now has a concept of [Draft Pull Requests]() which should up with a grey icon:

![screenshot 2019-02-21 at 16 10 10](https://user-images.githubusercontent.com/1060/53183525-6c313500-35f3-11e9-8dd1-cee59fa894d4.png)

There's also a new `draft` field available in the pull request API: https://developer.github.com/changes/2019-02-14-draft-pull-requests/

Octobox's icon should match the GitHub UI, and also allow filtering by `state:draft` in search and from the sidebar.

**Comment by andrew** [comment]
Just to add a little fly in the ointment, GitHub shows closed draft pull requests slightly differently:

![screenshot 2019-02-21 at 16 15 41](https://user-images.githubusercontent.com/1060/53183944-1c06a280-35f4-11e9-80f2-204dbf17e9a8.png)

For our purposes, I think we can simply to only calling pull requests that are both `open` and `draft` "drafts", closed drafts can just be "closed".

**Comment by BenJam** [comment]
I think closed drafts are kinda non-entities but closed state is most appropriate as in this case it means 'no action required' and 'nothing happening over here' to many people.

**Comment by Zimmi48** [comment]
It's quite unfortunate that GitHub issue search shows closed PRs when looking for draft with `is:draft`, and that `is:open` cannot be used jointly with `is:draft` to reduce the search. I would appreciate if Octobox could deviate from the behavior of GitHub here.

**Comment by andrew** [comment]
Pull request in progress over here: https://github.com/octobox/octobox/pull/1724

@Zimmi48 happy to report that draft is a separate search prefix so you can search for just open drafts, or just closed drafts with `state:open draft:true`

**Comment by Zimmi48** [comment]
Good to know, thanks!
