### ISSUE TITLE
Reply/Comment on GitHub subject not visible on GitHub

### ISSUE THREAD

**Issue by frenck** [octobox/octobox#1632]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

An inline comment/reply box appeared on Octobox.io 🎉 
But it doesn't work 😢 

Responses do show up in Octobox, but not on GitHub.
I've tried re-sync / awaiting a little time to see if things would sync up, but it doesn't.

Visible in Octobox:
![image](https://user-images.githubusercontent.com/195327/53348951-56d24880-391c-11e9-8fad-4d0a0fa7924d.png)

GitHub:
![image](https://user-images.githubusercontent.com/195327/53349140-b9c3df80-391c-11e9-8156-be0007eb5051.png)

🎯 **Goal**

Well, it is an exposed feature, which seems to work, but doesn't.
Which is tricky.

💡 **Possible solutions**

Disable inline issue/pr view.

📋  **Steps to solve the problem**

n/a

**Comment by andrew** [comment]
That form shouldn't be visible yet, we've not upgraded the permissions on the Octobox GitHub app yet, so it won't work.

**Comment by andrew** [comment]
Fix being deployed now
