### ISSUE TITLE
Emoji in issue/PR view

### ISSUE THREAD

**Issue by bobheadxi** [octobox/octobox#1640]
### What feature you'd like to see

It would be nice if the new open-in-octohub mode for issues and PRs supported emoji. Looks like it's already in labels #559, so hopefully this isn't too much?

## Motivation

We use emoji a lot, and it looks rather bare without it rendered:

![image](https://user-images.githubusercontent.com/23356519/53394149-2954c180-3953-11e9-9523-bddcf1116340.png)

## Pitch

💯 🚀 🙏

**Comment by andrew** [comment]
That's weird, emoji are showing correctly in this thread:

![screenshot 2019-02-26 at 10 21 00](https://user-images.githubusercontent.com/1060/53405720-56838d00-39b0-11e9-8d35-a6144dbc5f78.png)

**Comment by andrew** [comment]
I suspect it's only the newer emojis that aren't working as gemoji hasn't been updated with all the new emojis that have come out in the past year: https://github.com/github/gemoji/issues/139

**Comment by bobheadxi** [comment]
🤔 I'm not sure the emoji are that new - we've been using them since December 2017:

https://github.com/ubclaunchpad/inertia/commit/10dfe945df10ef8903646617d8838ed9da0695e0#diff-195a635ad245ded9076330e31134bd80

**Comment by andrew** [comment]
Looks like there's a new version of gemoji coming very soon, hopefully that'll fix this, otherwise https://github.com/octobox/octobox/issues/1800 will.
