### ISSUE TITLE
Still getting dialog to after I added GitHub app

### ISSUE THREAD

**Issue by TylerLeonhardt** [octobox/octobox#1646]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

I still see this dialog even though Octobox free tier was added to the PowerShell org:

![image](https://user-images.githubusercontent.com/2644648/53437632-fe5a8400-39cb-11e9-9fa3-fa6db18006e6.png)

Is there something I'm missing?

🎯 **Goal**

Figure out what enabling the GitHub app gives me

💡 **Possible solutions**

Not sure

📋  **Steps to solve the problem**

Not sure!

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by BenJam** [comment]
hey @TylerLeonhardt, have you installed the GH app on the repo for that particular notification? URL: https://github.com/apps/octobox

**Comment by TylerLeonhardt** [comment]
That seemed to work!!

![image](https://user-images.githubusercontent.com/2644648/53503399-fbb86700-3a7d-11e9-96fa-e3e1c4776b72.png)

What does that do exactly? Is that written up somewhere?

**Comment by TylerLeonhardt** [comment]
gentle ping 😄 just curious what adding the app to a particular repo does.


cc @andrew

**Comment by BenJam** [comment]
Hey @TylerLeonhardt, you need to install the GitHub app on each account/repo that you wish to use octobox with to get the most from it. We clarified this on the pricing page but I'll run through other docs and make sure it's all linked up.

**Comment by BenJam** [comment]
>  just curious what adding the app to a particular repo does.

it gives us the additional permissions needed to pull comments, labels, authors etc into notifications.

**Comment by TylerLeonhardt** [comment]
Sounds good! Thanks for the info 😊
