### ISSUE TITLE
Issue hidden when moving from checkbox to title

### ISSUE THREAD

**Issue by spalger** [octobox/octobox#1647]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
I regularly use octobox to triage issues by subject, marking the issues I suspect I will archive with a check and then clicking through the link in another tab to double check before coming back to continue down my list. In the last couple months as the Github App has been implemented I keep tripping up on the very eager tooltips on the issue/pr icon that interupts my flow

![2019-02-26 15 50 42](https://user-images.githubusercontent.com/1329312/53455410-361ef700-39df-11e9-80ba-586fff7f86ae.gif)

🎯 **Goal**
I'm unable to install Github Apps for our organization, Octobox is currently in review and hopefully we'll be able to activate the Github App for our org soon but in the meantime I'm feeling quite overwhelmed by the number of reminders to activate the Github App which I can do nothing about. And they're especially hard to ignore when they get caught under my mouse and prevent me from clicking the issue.

💡 **Possible solutions**
I'm thinking a 2 or 3 second delay on showing popovers would be appropriate, similar to the delay browsers use before showing alt text. (I'm thinking this should also be applied to the "Star" label on the obvious star icon). Alternatively, the prompt to install the Github App could be shown as a modal or something on page load, or maybe a header bar of some sort that can be dismissed.

📋  **Steps to solve the problem**

I'd be happy to submit a PR if someone would please let me know what the desired end state is. If it's just a delay then I should be able to implement that no problem here: https://github.com/octobox/octobox/blob/master/app/assets/javascripts/octobox.js

**Comment by spalger** [comment]
Created https://github.com/octobox/octobox/pull/1648 to address this

**Comment by BenJam** [comment]
👍
