### ISSUE TITLE
Can't build using docker on Windows

### ISSUE THREAD

**Issue by TylerLeonhardt** [octobox/octobox#1651]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**

I typically use a Mac but I wanted to do some streaming from my PC - that's when I realized I wasn't able to build on Windows (Mac worked just fine).

a `': No such file or directory` seems to be showing up.

Here's the build log:
```
PS C:\Users\tyleonha\Code\Ruby\octobox> docker-compose up --force-recreate --build
WARNING: The GITHUB_CLIENT_ID variable is not set. Defaulting to a blank string.
WARNING: The GITHUB_CLIENT_SECRET variable is not set. Defaulting to a blank string.
Building app
Step 1/9 : FROM ruby:2.6.1-alpine
 ---> 708614d8fa07
Step 2/9 : ENV APP_ROOT /usr/src/app
 ---> Using cache
 ---> 2b398169ac74
Step 3/9 : WORKDIR $APP_ROOT
 ---> Using cache
 ---> 08f257977326
Step 4/9 : COPY Gemfile Gemfile.lock $APP_ROOT/
 ---> Using cache
 ---> 5a8fa0cbfdb9
Step 5/9 : RUN apk add --update     build-base     netcat-openbsd     git     nodejs     postgresql-dev     mysql-dev     tzdata     curl-dev  && rm -rf /var/cache/apk/*  && bundle config --global frozen 1  && bundle install --without test --jobs 2  && gem install foreman
 ---> Using cache
 ---> c0855905c3b7
Step 6/9 : COPY . $APP_ROOT
 ---> Using cache
 ---> eb15ebbe25a7
Step 7/9 : RUN RAILS_ENV=production bundle exec rake assets:precompile
 ---> Using cache
 ---> faade6c6d55e
Step 8/9 : RUN RAILS_ENV=development bin/rails api_docs:generate  && chgrp -R 0 $APP_ROOT  && chmod -R g=u $APP_ROOT
 ---> Running in 1cc7babc7d0f
': No such file or directory
ERROR: Service 'app' failed to build: The command '/bin/sh -c RAILS_ENV=development bin/rails api_docs:generate  && chgrp -R 0 $APP_ROOT  && chmod -R g=u $APP_ROOT' returned a non-zero code: 127
```

Most is cached at this point but I do remember grabbing some of the log from the first run:
```
Step 6/9 : COPY . $APP_ROOT
 ---> cd76189d53e8
Step 7/9 : RUN RAILS_ENV=production bundle exec rake assets:precompile
 ---> Running in f102a8af9644
': No such file or directory
Files:           2
Modules:         0 (    0 undocumented)
Classes:         2 (    2 undocumented)
Constants:       0 (    0 undocumented)
Attributes:      0 (    0 undocumented)
Methods:        16 (    3 undocumented)
 72.22% documented
I, [2019-02-28T05:01:15.438875 #1]  INFO -- : Writing /usr/src/app/public/assets/light-c4452b28ed0b4e52b198440da0540d219a77c2ff3a48b7cea3bf86c4e62d76e0.css
I, [2019-02-28T05:01:15.439833 #1]  INFO -- : Writing /usr/src/app/public/assets/light-c4452b28ed0b4e52b198440da0540d219a77c2ff3a48b7cea3bf86c4e62d76e0.css.gz
I, [2019-02-28T05:01:16.958023 #1]  INFO -- : Writing /usr/src/app/public/assets/dark-a41190151697ad6d9c00ce63644247bb4ca9e5e94ef9a3723df6bf18a3aa6f94.css
I, [2019-02-28T05:01:16.958688 #1]  INFO -- : Writing /usr/src/app/public/assets/dark-a41190151697ad6d9c00ce63644247bb4ca9e5e94ef9a3723df6bf18a3aa6f94.css.gz
I, [2019-02-28T05:01:16.964055 #1]  INFO -- : Writing /usr/src/app/public/assets/app-icon-2-9954c614903c914ed43daa54bd2bdc69400df7f9a8dd49c80b547171880eb209.png
I, [2019-02-28T05:01:16.967274 #1]  INFO -- : Writing /usr/src/app/public/assets/app-icon-069717a58a1c4d9184f16e4e0760bafa71efa55c196ec4c2ed19d78d7b205ce7.png
I, [2019-02-28T05:01:16.969652 #1]  INFO -- : Writing /usr/src/app/public/assets/emoji/basecamp-523f1f595869fef8c63ea84ef6fb383876e14813b2ee4bd37806f03e9ad99366.png
I, [2019-02-28T05:01:16.971611 #1]  INFO -- : Writing /usr/src/app/public/assets/emoji/basecampy-0542b1dbd5b8051c6098ba4895ba806e88eef2f63bd76209f3e67fcefb6857c4.png
I, [2019-02-28T05:01:16.975018 #1]  INFO -- : Writing /usr/src/app/public/assets/emoji/bowtie-b1c36f5dfd0854dfea3cdf0dea11791238abce49ef32d8e3852ac6f3d21d26c6.png
I, [2019-02-28T05:01:16.979264 #1]  INFO -- : Writing /usr/src/app/public/assets/emoji/feelsgood-d8fb99df37d3f006c0560433bd459278349aa182161cb05505a965c2c290d7a3.png
I, [2019-02-28T05:01:16.983831 #1]  INFO -- : Writing /usr/src/app/public/assets/emoji/finnadie-3422c8df4919108a297b25e065e19f40c00a917c7ddb00dc72f1914895b3575a.png
I, [2019-02-28T05:01:16.989158 #1]  INFO -- : Writing /usr/src/app/public/assets/emoji/goberserk-356928420e9f3464101b464d97fcab509a4a4270ded191a52c5971d0aa593635.png
I, [2019-02-28T05:01:16.992274 #1]  INFO -- : Writing /usr/src/app/public/assets/emoji/godmode-b1302a9c967fadac664fc1685d8bb351cc68c170cfa0b62f83e8f1096e00fd01.png
I, [2019-02-28T05:01:16.995491 #1]  INFO -- : Writing /usr/src/app/public/assets/emoji/hurtrealbad-e86bc96b7c8e6e473a8d6c9d9f5aa573eae1bde19fe05c2e18c023654c408374.png
I, [2019-02-28T05:01:16.998552 #1]  INFO -- : Writing /usr/src/app/public/assets/emoji/neckbeard-424d544b88c312f84fbdfe19059a0d45dfe149d96e33d4fbf7168f94963887f3.png
I, [2019-02-28T05:01:17.001704 #1]  INFO -- : Writing /usr/src/app/public/assets/emoji/octocat-45bebdb2ae403a054b2b9bc3f689f5db2d4e1047c85bfcbe8f556880813e7745.png
I, [2019-02-28T05:01:17.005731 #1]  INFO -- : Writing /usr/src/app/public/assets/emoji/rage1-6f5d5da4f8583fe2a072bb11f355c6eacf2497aefa56f629b96cb3d15fa306a2.png
I, [2019-02-28T05:01:17.009617 #1]  INFO -- : Writing /usr/src/app/public/assets/emoji/rage2-ac3197c73b85450a12c716c1bcf5cc606ee080ddcc5532b91112898ee8559ec4.png
I, [2019-02-28T05:01:17.015476 #1]  INFO -- : Writing /usr/src/app/public/assets/emoji/rage3-84282c4a6c702e0967bab5e58617a5c410831483d3b64bceba22f35eb1ae1802.png
I, [2019-02-28T05:01:17.019366 #1]  INFO -- : Writing /usr/src/app/public/assets/emoji/rage4-f5862049f9a68a4e7cbb74edd814ba9f5852ff4cfe1cce038783c71ce60e8689.png
...
```

I don't know why this would happen since... ya know... Docker should "just work"... but if you need me to do anything to test things out, let me know. I'm more than happy to. I've tried recloning the repo and everything!

🎯 **Goal**

I'd like to be able to build the project on Windows

💡 **Possible solutions**

I don't know

📋  **Steps to solve the problem**

I don't know!

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by jhsu802701** [comment]
Install VirtualBox, and then install a Linux virtual machine.  I've explained how to do this in my [VirtualBox Tutorial](https://www.virtualboxtutorial.com/).  Then install Docker on the Linux virtual machine.  I've covered this in my [Different Docker Tutorial](https://www.differentdockertutorial.com/).

You can be ready to roll in minutes with my procedure at https://www.legacyrailsapps.com/docs/a-octobox.html .

**Comment by TylerLeonhardt** [comment]
If this is the recommendation on Windows, can the installation steps be updated?

I'd rather not install VirtualBox and Docker on the VM just to get this working. It works fine on my mac so I'll just stay there... I just wont be able to stream 😢 

Thanks for the quick reply.

**Comment by jhsu802701** [comment]
I'm not one of the collaborators.  My procedure is 100% unofficial.

If you install a Linux virtual machine on your Windows host machine, you bail yourself out of the responsibility of having to learn the Windows way.

That said, I believe that very few are using Docker in Windows.  As is the case with Ruby on Rails, the vast majority use a Mac, a substantial minority (including myself) use Linux, but hardly anyone uses Windows.

**Comment by andrew** [comment]
@TylerLeonhardt That looks like a bug rather than a windows issue so to speak, as you say, docker should work no matter which platform. 

Have you tried using one of the prebuild docker images from https://hub.docker.com/r/octoboxio/octobox/ rather than building it yourself?

**Comment by TylerLeonhardt** [comment]
@andrew here's something that's interesting... when I get rid of the `docker-compose.override.yml`, which I'm guessing just pulls from the prebuild docker images, everything works AS EXPECTED.

So I wonder if there's something wrong about the `docker-compose.override.yml` that doesn't work on Windows for some reason?

**Comment by andrew** [comment]
@TylerLeonhardt did you have any luck with this in the end?

**Comment by TylerLeonhardt** [comment]
I gave up shortly after my discovery with the override.

**Comment by andrew** [comment]
Ok thanks for reporting back, going to close this for now.
