### ISSUE TITLE
When posting a comment fails, can't post further comments

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#1659]
I tried to reply to a pull request with a comment from the threadview this morning and got an error flash message (not sure why), after that error, the comment field disappeared from the threadview for that PR.

![screenshot 2019-03-04 at 08 25 25](https://user-images.githubusercontent.com/1060/53720289-46f4c000-3e58-11e9-8752-1c1bb706d5b5.png)

The comment boxes still showed up on other pull requests from the same repository, so it must have been something that happened to that particular subject.

Also note that screenshot shows that the notification in question (top one) has null comment count, not zero or invisible, just the icon with no count, I suspect that something is changing the subject data when posting a comment fails.

The comment form and comment count came back the next time the subject was synced after I merged it from the GitHub UI.

**Comment by BenJam** [comment]
I'm gonna guess this is due to the comment counts not including the original subject body. So when we do comment.destroy at the end of the comments worker (when failing) it pulls that comment count. 

Just a guess.

**Comment by BenJam** [comment]
> Just a guess.

nope https://github.com/octobox/octobox/pull/1645/commits/ac27ffbd4c2f620c82bda5318889982fd4e7feeb

**Comment by BenJam** [comment]
> got an error flash message (not sure why)

The only way this looks like it would happen would be if `notifications_controller:138` flashed you. 

It's possible that, between rendering the thread and posting something, #1478 is happening in the background.

**Comment by BenJam** [comment]
Just tested this by replacing the rest of the controller with the fail section, still allows you to submit. The root cause is more likely to be #1478 so we can pick up there.
