### ISSUE TITLE
Archiving all notifications on last page incorrectly tells you your octobox is open

### ISSUE THREAD

**Issue by TalAter** [octobox/octobox#166]
#### To replicate:
1. Have at least 2 pages worth of notifications.
2. Go to last page.
3. Archive all notifications on that page.

#### What should happen:
Octobox should show the previous page (the new last page)

#### What happens:
Octobox shows a notification telling you: You're in the clear! There are no notifications that need your attention.

#### Easier way to replicate:
1. Visit https://octobox.io/?page=20000

_If this page still shows notifications... you have bigger problems than this bug to deal with._

**Comment by karpiu** [comment]
Interesting bug. I will give it a go.
