### ISSUE TITLE
Thread view doesn't show who closed an issue/PR

### ISSUE THREAD

**Issue by akoeplinger** [octobox/octobox#1660]
Are you experiencing this issue in octobox.io or your own instance?
 - [X] octobox.io
 - [ ] My instance

🐞 **Problem**

When I look at a PR or issue I often need to check _who_ closed it, e.g. the original reporter or some team member. Currently I don't see any indication of the close event in the thread view like on GitHub.

🎯 **Goal**

The thread view should show a timeline entry for the close event, like on GitHub.

**Comment by BenJam** [comment]
Yeah we haven't got anything in thread view yet other than comments. Would love to add that at some point.
