### ISSUE TITLE
Clicking on username in thread view and then navigating back in Chrome results in broken octobox

### ISSUE THREAD

**Issue by akoeplinger** [octobox/octobox#1661]
Are you experiencing this issue in octobox.io or your own instance?
 - [X] octobox.io
 - [ ] My instance

🐞 **Problem**

1. Open a notification in thread view.
2. Click on the username of one of the participants
3. The browser navigates to the github profile page
4. Click back button in browser
5. Octobox now looks broken:

<img width="840" alt="screen shot 2019-03-04 at 13 53 06" src="https://user-images.githubusercontent.com/1376924/53734720-12e3c400-3e85-11e9-96b6-389d8b44585a.png">

Chrome 73, macOS Mojave 10.14.3

**Comment by BenJam** [comment]
I think this might be happening because when we open a thread we only really receive the thread part of the view and render it. It looks like only the components we were sent to render (the thread) are being rendered with a back button.

Reloading the page reloads the whole thing and it works fine.

**Comment by andrew** [comment]
Opened a PR with a kinda-fix, opening user links in a new tab: https://github.com/octobox/octobox/pull/1706
