### ISSUE TITLE
Syncing forever

### ISSUE THREAD

**Issue by Kubuxu** [octobox/octobox#1689]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

The octobox never finishes syncing after selecting filter and removing it.
Steps to reproduce:
1. Select filter (Mention, Assign and so on).
2. Remove it.
3. Click refresh in octobox.

I've discovered that disabling browser cache (using dev tools solves the issue)
Browser FF 66b6

See the screenshot. The requests between 304 codes are repeated forever if cache is not disabled in dev tools.
![octoboxsyncing](https://user-images.githubusercontent.com/2259282/54785675-1f0ea600-4c27-11e9-8fba-4ae507d8d6dc.png)

**Comment by BenJam** [comment]
Hey @Kubuxu thanks for logging this. I've just given it a go on FF and sync is 423ing until it 200s. Hmmm

**Comment by Kubuxu** [comment]
Ahh, figured out additional step for the bug. One has to be on https://octobox.io/?reason= page. How to get there, select filter, for example, `Assigned` and then remove it.

**Comment by BenJam** [comment]
Just tried that as mentioned, can't seem to replicate it here on Firefox or Chrome. But I can see you're successfully syncing your notifications in the logs.

**Comment by Kubuxu** [comment]
I am when I am not on the https://octobox.io/?reason=. I might just write userscript to redirect me off it to https://octobox.io.

**Comment by Kubuxu** [comment]
The issues seems to have resolved. No idea why, I will reopen if it repeats.
