### ISSUE TITLE
Button Archive for selected post not working

### ISSUE THREAD

**Issue by TakeMeNL** [octobox/octobox#1693]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

Archiving selected issue not archiving?
When you select a item/post you have the option to archive that item/post.
The request is done `https://octobox.io/notifications/archive_selected?per_page=100` successfully. But the item/post still exists in the inbox.

🎯 **Goal**

When clicking archive selected, archive selected post to archive tus remove it from the inbox.

💡 **Possible solutions**

Seems like a backend problem not handeling the POST request correctly?
Form data
```
id[]: 1724684
value: true
```

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by BenJam** [comment]
Confirmed. Thanks for reporting.

**Comment by BenJam** [comment]
looking at this now

**Comment by TakeMeNL** [comment]
Thank you! Working now 💯
