### ISSUE TITLE
Desktop App?

### ISSUE THREAD

**Issue by Charlotteis** [octobox/octobox#17]
**NB: Not a feature or a support request, more a question/discussion**

This is _fantastic_, thanks so much, Andrew!.

I would really like to be able to have this as an app on my desktop, like you can do with [Electron]. I have no idea how to achieve this but if someone could point me in the right direction, I'd be willing to take a look / work with someone to do this.

Would this be of use to anyone? Know where to get started?

[Electron]: https://github.com/electron/electron

**Comment by Charlotteis** [comment]
It looks like I could make this even simpler by hosting my own version on Heroku, and just creating a Desktop app out of it using Chrome?

**Comment by andrew** [comment]
If you deploy it to heroku and point electron at the domain you could use it as an app specific browser like http://fluidapp.com

Otherwise if you want to run it locally with postgres and rails I'd guess Docker would be the way to go, otherwise it'd be easier to rewrite the whole thing in JavaScript

**Comment by Charlotteis** [comment]
@andrew Thanks! Just deploying as we speak :) Rewriting in JavaScript would be a very fun hobby project...

**Comment by xadamy** [comment]
I understand the technical limitations preventing this, but my 2 cents would be that this does seem like something that is more suited to being self-contained in a desktop app or similar...

**Comment by andrew** [comment]
This project will always be web based, I want to access the inbox from my phone or laptop. It could also provide an API that a desktop app could be built on top of at some point

**Comment by johnthepink** [comment]
Nativefier is also a great solution for something like this https://github.com/jiahaog/nativefier

**Comment by pezholio** [comment]
An API would be awesome. I really enjoy tinkering with Electron, so I'd love the opportunity to build or collaborate on a desktop version of Octobox 👍🏻

**Comment by andrew** [comment]
@pezholio just opened an issue for it here: https://github.com/andrew/octobox/issues/39

**Comment by pezholio** [comment]
Awesome. Might give this a crack over the holidays 👍🏻

**Comment by andrew** [comment]
🎅

**Comment by andrewhathaway** [comment]
I've been working on an Electron based app for Notifications for a little while now, I'll post a link here when I have more information!

**Comment by m1guelpf** [comment]
@andrew I have a modified version of nativefier that allows top menu editing. If you want, I can post an octobox.io version in which the help menu links o this repo issues section.

**Comment by andrewhathaway** [comment]
Hey guys. Just released the Electron app I spoke about above for handling GitHub notifications. Check it out! :) https://harksys.com/labs/introducing-hawk-eye-a-useful-app-for-github-notifications/

**Comment by andrew** [comment]
I'm going to close this out for now as there seem to be a lot of ways of running this on the desktop or alternative desktop clients in the wild already
