### ISSUE TITLE
No Docker images pushed since 7 days

### ISSUE THREAD

**Issue by rhuss** [octobox/octobox#1700]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [X] My instance

🐞 **Problem**

`octoboxio/octobox:latest` has been updated seven days ago for the last time. I remember darkly that there was a job who did this on every merge on master, but I can't find it in the travis configuration.

How is the image built ? It's not an automated Docker build either.

🎯 **Goal**

I wanted to have the latest changes in the Docker image so that I can consume it on my private instance.

**Comment by andrew** [comment]
Oh weird, docker hub automatically builds new images on every push to a branch on GitHub, I wonder why it’s stopped...

**Comment by andrew** [comment]
Looks like Docker Hub screwed up: https://success.docker.com/article/i-have-issues-triggering-autobuilds

Will try and re-enable them

**Comment by andrew** [comment]
My mistake, looks like the recent ruby upgrade broke Docker builds: https://cloud.docker.com/u/octoboxio/repository/registry-1.docker.io/octoboxio/octobox/builds/4191aedd-c536-4ed6-8504-8b85949c110d

Will fix it in the morning if no-one else fixes it before me

**Comment by rhuss** [comment]
thanks for the quick response, and no worries, its not urgent.

For the long term: Maybe it might make sense to add the image creation into the CI via Travis ? That way image build failures would be detected as CI failures. Setting this up is not hard, credentials would be injected via env variables.

If interested, I could contribute here the Docker build & push integration we did (for circle but porting to travis should be easy).

**Comment by andrew** [comment]
That’d be great 👍

**Comment by 3minus1** [comment]
A workaround that worked for us was to remove `http://httpredir.debian.org/debian jessie-updates` from `/etc/apt/sources.list`. 

We did this by adding `RUN sed  -i  '/jessie-updates/d' /etc/apt/sources.list` to our dockerfile.

**Comment by andrew** [comment]
PR to fix docker builds here: https://github.com/octobox/octobox/pull/1705
