### ISSUE TITLE
Improve “Add to homescreen” icon

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#1713]
![E3A62AC6-43DA-40FD-B2D6-3E0F6FAF7E12](https://user-images.githubusercontent.com/1060/55324608-87a52080-547a-11e9-91e5-eb739f001939.jpeg)

When you add Octobox to your homescreen on iOS 12.2 you get an ugly white border on the icon, probably better to have a black square for that.

**Comment by GiacomoLaw** [comment]
So you just want the icon to be the same color without the border?

**Comment by andrew** [comment]
@GiacomoLaw looks like it's using https://octobox.io/apple-icon-144x144.png which is round

**Comment by GiacomoLaw** [comment]
Ah, okay. I can make it all grey when I get home if you would like.

**Comment by GiacomoLaw** [comment]
Sorry, forgot to do today. Will do it again tomorrow afternoon. Sorry about that!

**Comment by BenJam** [comment]
Just in case it's useful: I wrote a quick script to generate icons over at https://github.com/octobox/octobox/blob/master/bin/generate_icons.sh

**Comment by GiacomoLaw** [comment]
That’s great. Can I use that for other sites?

**Comment by BenJam** [comment]
Sure, do you need me to push it elsewhere under a non aGPL ?

**Comment by GiacomoLaw** [comment]
Sorry, I don't understand lol

**Comment by BenJam** [comment]
No worries, use it however you like.

**Comment by GiacomoLaw** [comment]
Awesome, appreciate it. Thank you!

**Comment by andrew** [comment]
@GiacomoLaw thanks for tackling this 👍
