### ISSUE TITLE
Seed data for development

### ISSUE THREAD

**Issue by tarebyte** [octobox/octobox#172]
It would be great if we could generate some seed data for users so that they don't have to wait for notifications to come in to see it on the page.

**Comment by andrew** [comment]
👍

**Comment by technicalpickles** [comment]
> Also how do you plan to login with that dummy user, the only way as far as I see is with Github right?

One way would be to add a `/auth/developer/callback` that signs in the dummy user by setting `session[:user_id]`, and only have that work in development.

With that, there could be a link to it on the homepage to login next to 'Sign in with GitHub'.

**Comment by jhsu802701** [comment]
An example on how to seed a database of an app with OmniAuth is CodeTriage.  The script is at https://github.com/codetriage/codetriage/blob/master/db/seeds.rb .

I will adapt the CodeTriage script for OctoBox.

**Comment by BenJam** [comment]
that would be an excellent contribution @jhsu802701 👍
