### ISSUE TITLE
Automatic sync and notifications on web version?

### ISSUE THREAD

**Issue by GiacomoLaw** [octobox/octobox#1721]
Hi all, just a quick question. I started using Octobox when it first came out, but then stopped using it for a while. However, I've come back to see it's greatly approved and have two questions.

1. Will Octobox sync in the background?
2. When I get a new GitHub notification, will I get an alert on my Windows desktop?

Thanks!

**Comment by andrew** [comment]
Octobox does sync in the background, but it doesn't do any kind of alerting or push notifications

**Comment by GiacomoLaw** [comment]
Okay, thank you very much!
