### ISSUE TITLE
Sync PR review status

### ISSUE THREAD

**Issue by ahayworth** [octobox/octobox#1731]
### What feature you'd like to see

Octobox could/should show me if a PR still needs a review, or if a review has been given (whether that review be a 👍, a 👎 , or just some comments).

## Motivation

My team receives frequent review requests on multiple repositories. When using octobox to review outstanding work at the beginning of my day, I must open each PR individually on GitHub to see if a review request is still outstanding, or if it has been reviewed. This is a time sink. :)

## Pitch

I believe this feature would benefit power users - like myself - who deal with many PRs daily. Knowing whether or not I still need to take action on a review would save me a great deal of time, and I suspect would save others a great deal of time as well. The information is available in the API, and as such seems somewhat straightforward to implement.

I believe this information can be ascertained from both the [PR API](https://developer.github.com/v3/pulls/) and the [PR Review API](https://developer.github.com/v3/pulls/reviews/#list-reviews-on-a-pull-request). I'm not 100% sure of the interplay there, but looking through a few PRs on a repo I watch I noticed a few things:
- A PR that has reviews requested but not yet completed had items in the `requested_users` and/or `requested_teams` fields on the PR API response
  - This is also available in the review requests [endpoint](https://developer.github.com/v3/pulls/review_requests/#list-review-requests)
- PRs that had completed reviews (regardless of the status of those reviews) were found in the `/reviews` endpoint response

The graphql API may be easier to use here, since you could compose a single query that gets all required state.

**Comment by andrew** [comment]
@ahayworth do you know which permissions are needed to get that data from the GitHub api as a GitHub app?

**Comment by ahayworth** [comment]
@andrew Oh wow - sorry for missing this for so long. I don't know the exact permissions required, but my reading of the docs indicates that it'd just be `Read` on `Pull Requests`.

**Comment by BenJam** [comment]
#1859 should make this a little easier.
