### ISSUE TITLE
Removed labels still show up

### ISSUE THREAD

**Issue by timhoffm** [octobox/octobox#1763]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

Labels that are removed on github still show up in octobox.
This is a bit annoying for labels that are used only temporarily such as „needs clarification“ or „needs review“.

**Comment by andrew** [comment]
@timhoffm do you have the Octobox [GitHub app](https://github.com/apps/octobox) installed on those repositories?

**Comment by timhoffm** [comment]
@andrew Yes, I do have the GitHub app installed. Might be that this is a syncing issue because I've not been using the "Sync" button but just reloaded the page (c.f. #1764). I'll recheck and report back.

**Comment by timhoffm** [comment]
Still happening. For example  I removed a label here https://github.com/matplotlib/matplotlib/pull/14001#event-2300367308. Then clicked the sync button, waited until the sync was complete, but the label is still displayed. Also a page reload does not fix it (so it's not a stale GUI problem either).

**Comment by timhoffm** [comment]
Note: Also a changed issue title is not updated by the sync mechanism.

**Comment by andrew** [comment]
@timhoffm definitely sounds like a permissions issue, can you list the repositories that you are having problems with so I can debug further?

**Comment by timhoffm** [comment]
Mainly working on https://github.com/matplotlib/matplotlib currently. That's the one I've had the problems with. Can't say anything about other repos.
