### ISSUE TITLE
Sync via button is slow

### ISSUE THREAD

**Issue by timhoffm** [octobox/octobox#1764]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
Updating via the sync button in the UI takes ~10s. In contrast, reloading the complete page takes < 1s.

🎯 **Goal**

💡 **Possible solutions**

Not too important since I now just always reload the page. However, it makes a bit of a bad user experience when the button is spinning for a long time. If it‘s not worth fixing it, maybe just remove the button? It‘s not strictly necessary and better not having that button than a no-working one.

**Comment by andrew** [comment]
The sync button is doing more work that just refreshing the page, it's going to GitHub, checking all your notifications to see if they have been marked as read/unread and then syncing the issue/pull request details for each updated notification.

**Comment by timhoffm** [comment]
Thanks for the answer. In that case, it's ok. If you have any idea how to make this more obvious (e.g. a more descriptive tooltip - maybe even just "Sync with Github"; or a progress bar), IMHO that would improve the user experience. Otherwise this can be closed.
