### ISSUE TITLE
Private repo access not working for non-org-admins?

### ISSUE THREAD

**Issue by Qard** [octobox/octobox#1781]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
All the issues from my work repos show the `Private notification on org/repo, upgrade to unlock.` message and according to my settings page we have no plan. However, we _do_ have a plan and our infra team uses octobox regularly. For some reason it seems to just be inaccessible for me. I'm just a regular member, not an org admin, so I'm unable to access billing settings on Github. Do I need to be an org admin to be able to use Octobox?

🎯 **Goal**
I want to be able to use Octobox for my issue and pull request management at work.

**Comment by andrew** [comment]
Can you check the permissions for your oauth login here, you may need your GitHub admin to grant you full access: https://github.com/settings/connections/applications/3ab10eeb090c850faa7f

**Comment by Qard** [comment]
Octobox appears in "Installed Github Apps" and "Authorized Github Apps" but nothing in "Authorized OAuth Apps" at all.

**Comment by Qard** [comment]
Logged out and back in, now it asked to re-authorize. Maybe it expired or something? Anyway, now I can _get_ to that page. I see a green check mark best the org name and it says I have "access notifications" permission. Still unable to view those notifications in the Octobox UI though. 🤔

**Comment by andrew** [comment]
You shouldn’t need to be an admin, will check out your account details tomorrow

**Comment by Qard** [comment]
Should having a "Personal Projects" plan grant me access to private repos of orgs I'm a member of, or does the org itself need a plan? By the sound of it, our infra team uses it regularly but everyone just uses the "Personal Projects" plan. It sounds like maybe we don't actually have an org plan? Not sure. 🤔

**Comment by Qard** [comment]
I tried getting the "Personal Projects" plan, even though I don't have any of my own personal private repos to track issues on, but I still don't have access to the issues from the org projects.

Any idea what I need to do to get this working? It's a huge pain that I have several important work repos which I can't get notifications from and therefore need to spend time checking manually every day. 😞

**Comment by Qard** [comment]
Hey, just checking in again. Do I need to get our org admins to do something? I'm a paying user, but not getting access to any of the private issues I want access to. 😞

**Comment by andrew** [comment]
@Qard can you check that the oauth app has been approved by the admin of your org: https://github.com/settings/connections/applications/3ab10eeb090c850faa7f

**Comment by Qard** [comment]
My private repo access seems to magically be working now. Not sure why, but thanks for trying to help anyway. I'll let you know if I have any further issues. 😅 

Thanks for building octobox, it's a great service! 😄
