### ISSUE TITLE
Really tall sidebar

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#179]
My sidebar gets really long in archive view because of all the repos/orgs I have notifications from:

![screen shot 2016-12-27 at 11 16 29 pm](https://cloud.githubusercontent.com/assets/1060/21510467/ad9f630a-cc8b-11e6-971b-fd1bb58b5ac4.png)

Maybe we should take another page out of Gmails book and add a scrollbar or collapse/expand to the sidebar if it's taller than the window?

**Comment by briannelson** [comment]
If folks are ok with it, we could do a two-pane Flexbox layout with each pane being individually scrollable. Should be supported in any browser our users are using.

**Comment by andrew** [comment]
Sounds good to me @briannelson!

**Comment by andrew** [comment]
🏖

**Comment by andrew** [comment]
Fixed by #186
