### ISSUE TITLE
Delayed comments 

### ISSUE THREAD

**Issue by BenJam** [octobox/octobox#1791]
There's sometimes a delay between comments appearing on an issue/pr and their appearing on my octobox account. I've had reports of the same (some spanning hours) too:

<img width="1532" alt="Screenshot 2019-04-30 at 10 48 28" src="https://user-images.githubusercontent.com/158833/56954554-f5567200-6b36-11e9-9495-66ab9a387ffd.png">

<img width="1532" alt="Screenshot 2019-04-30 at 10 48 23" src="https://user-images.githubusercontent.com/158833/56954556-f8516280-6b36-11e9-8cac-5eaab499aefa.png">

Comment looks like it was left 18 hours ago, last sync on octobox was 5 minutes ago.  I've got some time to investigate today, any ideas welcome @andrew.

**Comment by BenJam** [comment]
Would like to address this before #1645 is completed.

**Comment by andrew** [comment]
@BenJam should be noted that my comment in the first screenshot is actually a pull request review comment, not a regular comment, I don't believe octobox will ever sync that one as we have no support for pull request review comments yet

**Comment by BenJam** [comment]
Good point, i was quite sure I'd seen it before on an issue. I'll take a look at what it would take to add to a PR because I think it would be amiss not having that before launching conversations.

**Comment by BenJam** [comment]
>  I don't believe octobox will ever sync that one as we have no support for pull request review comments yet

I _still_ haven't got around to looking at this yet but: I can see all the PR comments for https://github.com/octobox/octobox/pull/1141 except the final one 

![image](https://user-images.githubusercontent.com/158833/57711601-ed362080-7666-11e9-8238-5dc473563859.png)

I guess that _review_ comments are different from general comments on the PR (which is actually just an issue).
