### ISSUE TITLE
Repetitive results when negating labels

### ISSUE THREAD

**Issue by spalger** [octobox/octobox#1792]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
When trying to hide notifications with a specific label the search comes back with one result for each label the matching notifications has:

![image](https://user-images.githubusercontent.com/1329312/56966291-a64b1580-6b13-11e9-8418-3923e924f107.png)

🎯 **Goal**
Notifications should only be listed once.

**Comment by andrew** [comment]
Yep, that's a bug, thanks for reporting!

**Comment by andrew** [comment]
Looks like it's only happening for notifications with more than one label, I'm fairly sure it's a problem with the sql query, likely that a `distinct` needs to be added in.

**Comment by misterikkit** [comment]
Not sure whether I should file a separate bug, but I also noticed that notifications containing the negated label are shown in search results (provided they have at least one other label).

In other words, it appears that the filter is searching for any notification with (a label that does not match the filter).

**Comment by andrew** [comment]
I think it’s the same bug
