### ISSUE TITLE
Broken UI for Google Chrome

### ISSUE THREAD

**Issue by abunashir** [octobox/octobox#1799]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io

🐞 **Problem**

First of all thanks a lot for this amazing tool, I've been using it for a while and I love it so far. The problem I'm having is more related to the UI, so if some issue / PR title has more than a certian number of characters then the UI looks broken to me and I can't even scroll to it either. For example:

<img width="1280" alt="Screenshot 2019-05-03 16 12 30" src="https://user-images.githubusercontent.com/1220911/57143622-8a6b9c00-6dbf-11e9-808f-fa208a6852cf.png">

🎯 **Goal**

To have a consistent UI, that includes the type of the issue, commenter/creator and time. I assume this is happening for the title, so maybe truncate the title to a certain length?

Thanks again, and please let me know if this is desirable then I can probably submit a pull request.

**Comment by andrew** [comment]
Thanks for reporting, looks like a problem with the way that [`overflow-wrap: break-word`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) handles `underscored_words`.

I think adding something like this will fix it:

```css
.notification-subject{
  word-break: break-all;
}
```
