### ISSUE TITLE
More obvious AJAX progress

### ISSUE THREAD

**Issue by boffbowsh** [octobox/octobox#18]
I barely noticed the (Turbolinks?) progress bar at the top of the page. It'd be good to make the notification fade out with a spinner or similar instead

**Comment by andrew** [comment]
I'm trying to keep the JavaScript to a minimum for my own sanity, I think there's a standard loading spinner function in bootstrap we can use for that

**Comment by xadamy** [comment]
@andrew Turbolinks has its own CSS hook for this https://github.com/turbolinks/turbolinks#displaying-progress

**Comment by andrew** [comment]
We have a spinner on the sync button now
