### ISSUE TITLE
Docker image for ARM architectures

### ISSUE THREAD

**Issue by jesusbotella** [octobox/octobox#1818]
Hello!

I have just started using Octobox this week and I absolutely love it.

## 💥 Proposal
I tried to install an Octobox instance on my Raspberry Pi but I couldn't because it seems like the Docker image is not compatible with ARM architecture. So, would it be possible to generate and upload one to Docker Hub so anyone can install Octobox using a ARM architecture?.

I generated the image myself and I was able to install and run Octobox in my Raspberry Pi without any major problems so far.

### What feature you'd like to see
An ARM compatible Docker image for Octobox.

## Motivation
The motivation is to ease the process of installing Octobox using Docker in a device with ARM architecture.

**Comment by andrew** [comment]
@jesusbotella do you have any insight in how to cross-compile docker images as I don't have an ARM device

**Comment by jesusbotella** [comment]
Sorry for the late reply.

I found [this article](https://medium.com/@imDurgadas/multi-architecture-docker-image-using-cross-compilation-part-1-65bd26d4b017) about cross-compiIing Docker images and I don't know if it would work in this case, but maybe it's worth a try.

I'll try and see what happens :)
