### ISSUE TITLE
When set RAILS_ENV=production, 'Too Many Redirects' occurs.

### ISSUE THREAD

**Issue by mzch** [octobox/octobox#1841]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [✓] My instance

🐞 **Problem**

When set RAILS_ENV=production, 'Too Many Redirects' occurs.

🎯 **Goal**

This issue causes misleading to even experienced users.

💡 **Possible solutions**

Even when set RAILS_ENV=production, octobox should work correctly.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by andrew** [comment]
Can you provide the url that you’re being redirected to?

**Comment by mzch** [comment]
Hi,

I set RailsEnv production directive again and reloaded apache. And somehow everything went well...
Sorry.
