### ISSUE TITLE
Saved label searches have quotes stripped out

### ISSUE THREAD

**Issue by jasonrhodes** [octobox/octobox#1846]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
When I do a search for a label like ":apm" or ":Logs UI", the search initially works and the filter above the search results shows `Search: inbox:true label:":Logs UI"`, but the search box itself will have stripped out the quotes, so if you refresh, you get no results and the filter now shows `Search: inbox:true label::Logs UI` which I believe is an invalid query.

This same problem happens when you save the search, which means saved searches like these will never return results. 

<img width="1235" alt="Screen Shot 2019-05-23 at 9 16 21 AM" src="https://user-images.githubusercontent.com/159370/58256117-66570700-7d3c-11e9-8186-c6af2eb444cc.png">
<img width="1205" alt="Screen Shot 2019-05-23 at 9 16 40 AM" src="https://user-images.githubusercontent.com/159370/58256128-6c4ce800-7d3c-11e9-8c94-f573bc8b36c0.png">

🎯 **Goal**
Anyone who uses labels with special characters in them (spaces, colons, etc) can only save searches for those labels if this is fixed.

💡 **Possible solutions**
I imagine the code just needs to stop stripping quotes out of the search string.

📋  **Steps to solve the problem**

If someone points me to where this code lives, I'd be happy to take a stab at fixing it. My Ruby is a bit rusty but I can possibly figure it out if someone can push me in the right direction :)

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by andrew** [comment]
PR for a fix over here: https://github.com/octobox/octobox/pull/1847 

Should get it live on octobox.io within the next 10 mins or so.

**Comment by andrew** [comment]
Deploying now :shipit:
