### ISSUE TITLE
Hide repositories from the settings

### ISSUE THREAD

**Issue by karthik** [octobox/octobox#1861]
### What feature you'd like to see
As someone invited to participate in numerous organizations, there are plenty of repos that I don't watch as I am not actively involved. Octobox lists every last one of them in the sidebar, creating the same feeling of being overwhelmed as my GitHub notification folder (thereby defeating the purpose of Octobox). 

## Motivation

It would help Octobox cut the noise, rather than repackage the noise into one dashboard. 

## Pitch

Since you are reading all this from the API, perhaps there could be check boxes nexts to orgs, and repos within orgs that would allow a user not to be notified of issues. That will help keep Octobox clean allowing devs to focus on key issues.

As as additional feature, it would be great to organize them into folders/tags (Current, urgent, not important, etc) but this is a secondary feature. Purpose of this will be to break the default sort order.

**Comment by BenJam** [comment]
hey @karthik 👋

thanks for the propoal: in the meantime you might want to uncheck the automatic following bits from your notifications settings in github: https://github.com/settings/notifications 

you might also want to pin a search for the repo's you're actively participating in like `inbox:true repo:user/repo,org/repo...`
