### ISSUE TITLE
Can't access issue and PR status in octobox.io after subscription

### ISSUE THREAD

**Issue by mserranom** [octobox/octobox#1863]
### Summary of Problem

(Please answer all 3)

- What are you trying to do?
Setup a paid Octobox account
- What happens?
I can't see PR and issue status (open, closed, merged,...) 
- What should have happened?
I'd have expected to see those statuses, as I was able to in my personal OpenShift installation

### Steps to Reproduce the Issue

I subscribed to gihub, and I can't see the status of PRs or issues. I get the popup instead to subscribe my organisation (screenshot attached).

It all worked perfectly fine in my OpenShift installation without requesting anything to my organisations.

<img width="744" alt="Screenshot 2019-05-29 at 15 58 34" src="https://user-images.githubusercontent.com/5948929/58562990-a29dd200-822a-11e9-8870-24332c161e92.png">

### Versions, Operating System and Hardware

- Which version/commit of Octobox are you using?
Current hosted at octobox.io
- Which browser are you accessing Octobo with?
Chrome
- Windows? Linux? Mac?
Mac
- How are you deploying Octobox (Docker, Heroku, Openshift, etc)
N/A

**Comment by BenJam** [comment]
hey @mserranom you can enable the app for all repositories on an org or select in the config settings: https://github.com/apps/octobox

**Comment by mserranom** [comment]
Thanks. This is done, but statuses in private repos are still not visible, now with a different popup:

<img width="691" alt="Screenshot 2019-05-30 at 14 27 32" src="https://user-images.githubusercontent.com/5948929/58632882-3c2ab980-82e7-11e9-8f96-377df099a1b0.png">

**Comment by BenJam** [comment]
which repo? I can see your paid plan is hooked up our side.

**Comment by mserranom** [comment]
It seems now status on PR and Issues are reflected as expected, but that "subscribe Now" popup is still visible, but only for private repositories belonging to an organisation I'm a member of.

**Comment by BenJam** [comment]
I suspect you need to auth the GH app on those repos.

**Comment by mserranom** [comment]
What do you mean? The GH app is already installed in those repos, what else is needed? Everything looks fine, all the information is there, just seeing the popup.

**Comment by BenJam** [comment]
Looking again now, looks like a weird one.

**Comment by BenJam** [comment]
bug found, pushing fix now. ta!

**Comment by BenJam** [comment]
deploying now.

**Comment by mserranom** [comment]
Fixed, thanks!

**Comment by BenJam** [comment]
👍
