### ISSUE TITLE
RFE: link to the repository in header

### ISSUE THREAD

**Issue by whitel** [octobox/octobox#1868]
### What feature you'd like to see
(A clear and concise description of what the proposal is.)
I think it would be handy if you are on the "list" for a particular repo a link to the repo itself at the top of the page would be handy. 

## Motivation
(Please outline the motivation for the proposal. It's interesting knowing what people are working on and also could help community members make suggestions for work-arounds until the feature is built)

As someone else mentioned, I am a member of many orgs and I don't always even remember what project is what. As a result, I sometimes need to navigate to the project itself to get context for the issues/prs.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

I think I explained above.

**Comment by BenJam** [comment]
Thanks for the proposal. I guess we could do a hover/popover on repo name with the repo description in much the same way we do in the main notification window for subjects.
