### ISSUE TITLE
Multiple reasons

### ISSUE THREAD

**Issue by WillAbides** [octobox/octobox#187]
The reason field on a notification can change.  For instance if comment on an issue and then you are directly mentioned by somebody else the reason will change from 'comment' to 'mention'.

It would be nice to keep all the reasons that octobox has seen for a notification.  That way,  the issue in the example above will still show up if I filter for 'comment'

**Comment by WillAbides** [comment]
That's interesting insight. I'd like to figure out how to have both an uncluttered UI and be able to single out activity on PRs I created.

**Comment by andrew** [comment]
Going to close this for now as I can't see us doing it in the short term, but if anyone really wants it and is willing to have a go at implementing it then drop a comment and we'll open it back up.
