### ISSUE TITLE
All shortcuts seems to have stopped working

### ISSUE THREAD

**Issue by maestromac** [octobox/octobox#1875]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

Noticed today that none of the shortcuts is working at all. I've tested it on chrome, firefox, and safari.

🎯 **Goal**

To get it working again.

💡 **Possible solutions**

n/a

📋  **Steps to solve the problem**
n/a

**Comment by andrew** [comment]
Looks like a javascript error, will check it out when I can get to a computer

**Comment by andrew** [comment]
Should be fixed now, I turned on the Rocket Loader feature in Cloudflare a couple hours ago, obviously it didn't play well with our javascript 🙈

**Comment by maestromac** [comment]
Thanks for the fast fix! 
Confirmed it's working now.

**Comment by creachadair** [comment]
Thank you so much for the quick fix!

Not that I really need to know, but I'm curious: Do you have a sense of what the root cause was? E.g., was CF filtering out some important library? I ask because I didn't see any errors in the JS console at all during the outage.

**Comment by andrew** [comment]
@creachadair I didn't see any errors either, looks like turbolinks and rocket loader don't play well together and the `turbolinks:load` event never fires: https://github.com/turbolinks/turbolinks/issues/62
