### ISSUE TITLE
Octobox can't detect when some PRs are merged, still show up as open

### ISSUE THREAD

**Issue by carlossanlop** [octobox/octobox#1878]
Are you experiencing this issue in octobox.io or your own instance?
 - [X] octobox.io
 - [ ] My instance
 

I do not own an Octobox subscription.

🐞 **Problem**

Several of my merged PRs from the dotnet/dotnet-api-docs repo are still showing up as open in octobox (green icon), even though they already have the purple icon in the PR page, and I even deleted the branch.

I expect Octobox to be able to refresh the merge status too so those PRs stop showing in the Open filter.

Example of a PR that has already been merged but Octobox is still showing as merged (even after I refresh): dotnet/dotnet-api-docs/pull/2336

🎯 **Goal**

I use Octobox with the purpose of tracking my open issues. If I can't filter open vs merged, then octobox loses its purpose.

Fixing this bug would benefit anyone who is trying to filter their open or merged PRs accurately.

💡 **Possible solutions**

No idea. This is a bug on the octobox side, because GitHub is able to filter open vs merged accurately.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by carlossanlop** [comment]
@andrew why was this closed?

**Comment by andrew** [comment]
This issue is over a year old and either has been fixed or is unlikely to get fixed due to the limited amount of time available to work on the project.
