### ISSUE TITLE
Docker custom postgres port

### ISSUE THREAD

**Issue by Hydrog3n** [octobox/octobox#1891]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance
 
If your issue is related to an Octobox.io subscription purchase please ensure you have installed the [Octobox GitHub App](https://github.com/apps/octobox) for the repositories concerned.

🐞 **Problem**

I want to use a saas postgres instance but it's impossible to setup a port different than 5432
https://github.com/octobox/octobox/blob/be369c1c7e02b44f47aa7913c6f7cd459d4d5324/bin/docker-start#L5

🎯 **Goal**

I want to add a env like this OCTOBOX_DATABASE_PORT=61089

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by andrew** [comment]
@Hydrog3n would you be up for sending a pull request to make that possible?

**Comment by Hydrog3n** [comment]
@andrew Hi, I sorry but for now I can't make this PR :/ 
It's not urgent for me so if nobody to do it maybe I would do it :)

**Comment by Hydrog3n** [comment]
@Themodem thank you for the PR :) 
I need to try :D
