### ISSUE TITLE
Improve Desktop PWA Icon

### ISSUE THREAD

**Issue by bnb** [octobox/octobox#1916]
### What feature you'd like to see
Currently, the icon is very boxy and doesn't necessarily fit in with other native or Desktop PWA-ified applications:

![image](https://user-images.githubusercontent.com/502396/60733514-119dd300-9f1b-11e9-9820-852bbbc25778.png)

I would love to see a more native-feeling icon for non-mobile PWA users, including Chrome/Edge Desktop PWAs.

## Motivation
I'd love to keep Octobox as a Desktop PWA on my Mac, pinning it to my tray. The icon doesn't really fit and feels like a favicon that was just made much larger. I'd love to see an icon that reflects how awesome Octobox truly is ❤️ 

## Pitch

Change the icon for desktop-loaded PWAs to either just the logo _or_ put it in a circle with the same background color that already exists.

**Comment by BenJam** [comment]
Cool ta, i’ll take a look next week. I suspect it’s just a case of rounding off the edges on our own icons. Hopefully I can get imagemagik to do the work :)

**Comment by andrew** [comment]
This should be live on octobox.io in 15 mins or so 🚀
