### ISSUE TITLE
Suggestion: Sync notifications on every new login

### ISSUE THREAD

**Issue by demoneaux** [octobox/octobox#193]
After logging in, it would be great to have the notifications synced to make it more convenient. Syncing on every load would be too much, but syncing on every login seems very reasonable to me.

**Comment by andrew** [comment]
Agreed, it's always the first thing I do after logging in 👍

**Comment by andrew** [comment]
@demoneaux just merged and deployed this to https://octobox.io thanks to @tarebyte

**Comment by demoneaux** [comment]
Wow, thanks for the fast update!! Happy New Year!! 🎉🎉🎉
