### ISSUE TITLE
export/import notifications

### ISSUE THREAD

**Issue by WillAbides** [octobox/octobox#194]
I would like to be able to export my notifications to a file and import them on another instance.  I see two use cases for this.

1. I go from a self-hosted instance to octobox.io and want to bring my archive with me.

2. I'm developing on octobox and want to see how my notifications look.  This is related to #172

**Comment by andrew** [comment]
I think the only data that would need to be exported/imported for this would be the `Notification` records for that user, most likely as a JSON file. 

And then when importing, if done by a logged in user via the settings page, every field can be imported except the `user_id` which needs to be changed to the id of the new local user importing it.

Then, if `FETCH_SUBJECT` is enabled everything else can be pulled down from GitHub on the next sync.
