### ISSUE TITLE
Support GitLab

### ISSUE THREAD

**Issue by ferventcoder** [octobox/octobox#1962]
### What feature you'd like to see
It would be awesome to see gitlab notifications etc right in there with our github notifications. I know the APIs are fundamentally different, but the end result could definitely be sweet for folks using both GitHub and GitLab.

We tend to use both systems and having a single place to see those and work with those notifications that is not in our email inbox would be beneficial! 

## Motivation
☝️

## Pitch
Depending on how this is set up currently, these could share a similar interface, then the workings of each API could be handled separately. Supporting this would also set Octobox able to do something unique - or more unique than what it does already. It also gives it legs should GH ever enhance notifications.

**Comment by andrew** [comment]
I think this is outside of the scope of this project now I'm afraid
