### ISSUE TITLE
Delete associated subjects when deleting notifications

### ISSUE THREAD

**Issue by pradyunsg** [octobox/octobox#1966]
## What feature you'd like to see

Currently, deleting archived notifications from Octobox only deletes the notifcation rows. This can be seen in the Admin panel for the same.

I'd like to see Subjects also go to 0 when I delete notifications.

## Motivation & Pitch

Allows (broke college students like) me to use a personal deployment of Octobox on Heroku, on the free tier, while still being fairly extensive users of their personal deployment.

Other than that, there's technical reasons like it trims unnecessary data in the database, saves space and all that. :)

**Comment by andrew** [comment]
Sounds reasonable, as long as those subjects aren’t referenced by any other users notifications (which shouldn’t affect your single user instance)

**Comment by andrew** [comment]
PR over here: https://github.com/octobox/octobox/pull/1969

**Comment by pradyunsg** [comment]
✨❤️

Hurrah!

Now I just need to wait for a notification I want to delete. Thanks so much for the quick resolution! 🙃

**Comment by pradyunsg** [comment]
Okay, this works for *that* notification. Any suggestions on how to clean existing unreferenced subjects?

**Comment by andrew** [comment]
@pradyunsg I have a script you can run in the console, will paste it here when I’m back on my laptop tomorrow

**Comment by andrew** [comment]
@pradyunsg one-liner for `heroku run rails console`:

```
Subject.left_outer_joins(:notifications).where(notifications: {id: nil}).find_each(&:destroy)
```

**Comment by pradyunsg** [comment]
Thanks @andrew! ^>^

**Comment by pradyunsg** [comment]
@andrew That didn't seem to do much but `Subject.where(notifications: nil).count()` seems to have worked well for me. :)
