### ISSUE TITLE
Allow user to automatically sync periodically

### ISSUE THREAD

**Issue by WillAbides** [octobox/octobox#198]
I'd like to be able to keep octobox in the background and glance at it periodically to see if anything new is on top.

If I could schedule the sync to every n minutes, I wouldn't have to change window focus and hit the refresh button.

**Comment by andrew** [comment]
@WillAbides there's a rake task here for that if you run it yourself: https://github.com/octobox/octobox/pull/173

For http://octobox.io that's a pretty intensive task for the 1000+ users

**Comment by WillAbides** [comment]
I mean on a per-session basis.  Something in javascript that would run whatever function the refresh button triggers on an interval.

Also, 1000+ users...that's impressive for such a new project.

**Comment by andrew** [comment]
Ah yeah doing it in js would be good, might want to avoid refreshing if any tick boxes are marked by the user, and the active filters should be kept

**Comment by WillAbides** [comment]
I was going to ask about the active filter.  The active filter is lost when you sync using the button.

**Comment by andrew** [comment]
Yeah we should fix that

**Comment by WillAbides** [comment]
I'm working on this in https://github.com/WillAbides/octobox/tree/auto-refresh
