### ISSUE TITLE
Allow addding hostname via environment variable

### ISSUE THREAD

**Issue by rhuss** [octobox/octobox#2011]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [X] My instance
 

🐞 **Problem**

When running the latest version of octobox on OpenShift I run into this error:

![grafik](https://user-images.githubusercontent.com/99080/64479223-53b1f200-d1b4-11e9-904a-8e0e449291db.png)

The reason is this new Rails feature: https://www.fngtps.com/2019/rails6-blocked-host/

I.e. one would have to add either the hostname of the reverse proxy to this list or enable a full whitelist. Ideally, this could be done via an environment variable (e.g. `OCTOBOX_HOSTNAME` or `OCTOBOX_NO_HOSTAUTHORIZATION`)as there is no easy way to edit this configuration file when installing octobox as it is part of the Docker image.

An alternate solution would be to adapt the OpenShift installation to include a local slim reverse proxy which calls rails on localhost. This might be the more generic solution.

**Comment by andrew** [comment]
Env sounds like a good solution for this 👍

**Comment by acidicX** [comment]
Same issue on Docker. I'd prefer an ENV solution, too.
