### ISSUE TITLE
Octobox not fitting screen correctly

### ISSUE THREAD

**Issue by GiacomoLaw** [octobox/octobox#202]
Octobox isn't showing correctly on my pc:

https://gyazo.com/12e45391cf861e06c1ae81d072346238

I've cleared cookies, tried on other pc's, still the same.

**This only shows on the inbox screen.**

**Comment by tarebyte** [comment]
This looks related to #186 

/cc @briannelson

**Comment by GiacomoLaw** [comment]
Just seen it only shows on screens that don't have any notifications on them.

**Comment by andrew** [comment]
@GiacomoLaw can you provide more details on OS and browser versions?

**Comment by GiacomoLaw** [comment]
@andrew Windows 10, Chrome 55.0.2883.87 m

**Comment by GiacomoLaw** [comment]
Seems to be working again. I'll close this for now.
