### ISSUE TITLE
Intermittent "Private notification on ..., upgrade to unlock" notifcations with paid subscription

### ISSUE THREAD

**Issue by jimmidyson** [octobox/octobox#2025]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance
 
If your issue is related to an Octobox.io subscription purchase please ensure you have installed the [Octobox GitHub App](https://github.com/apps/octobox) for the repositories concerned.

**Problem**

I love this project and it has become essential to my day to day work. Thank you very much for all your hard work on this!

I pay my subscription through opencollective, and yet regularly notifications from private repos are hidden with `Private notification on ..., upgrade to unlock`. After some time and many refreshes, this goes away and notifications are shown properly again. This happens on both my laptop and phone so not environment related.

**Comment by andrew** [comment]
This should be fixed now
