### ISSUE TITLE
Refresh on refresh

### ISSUE THREAD

**Issue by whit537** [octobox/octobox#205]
The first thing I do every time I load https://octobox.io/ is to click the ![refresh](https://cloud.githubusercontent.com/assets/134455/21592021/b055f474-d0d7-11e6-98f9-339d8fbe45c1.png) button. Open to automating that `onload`?

**Comment by andrew** [comment]
Related to https://github.com/octobox/octobox/pull/200 possibly, my worries with making refresh more frequent is the extra load of the server and the rate limit on the GitHub API

**Comment by WillAbides** [comment]
Do you have metrics on how often pages are loaded and how often notifications are refreshed?

**Comment by andrew** [comment]
![screen shot 2017-01-02 at 4 13 21 pm](https://cloud.githubusercontent.com/assets/1060/21592572/78fac0b6-d106-11e6-85b7-8dd70833fd2f.png)
![screen shot 2017-01-02 at 4 13 41 pm](https://cloud.githubusercontent.com/assets/1060/21592571/78fa8268-d106-11e6-81d8-a09284aefec6.png)

**Comment by andrew** [comment]
I don't have metrics for how often the page is refreshed, just often / is loaded

**Comment by andrew** [comment]
For a user with a lot of notification activity within the past week, it could take ~6 seconds and 10 http requests to check their notifications, if that happens every time they open octobox from fresh, say they have it as their new-tab/window page in their browser, they could produce a lot of extra activity

On a personal note, I like the current behaviour as it puts me back in control of asking for updates rather than having them thrust upon me

**Comment by WillAbides** [comment]
Those are good points.  Especially your personal note.  That point of view had not occurred to me, but it makes sense.

Maybe we could make "refresh on refresh" another user setting.  If you use octobox the way that @whit537 and I do, it is a small pain to have to hit refresh after loading the page.

**Comment by andrew** [comment]
User preference sounds good 👍

**Comment by andrew** [comment]
Have been pondering how to implement this and I can't think of a clean way to do it which makes me question if we should implement it at all at the moment, I don't want to add a feature that will be difficult to maintain going forwards if it's not got a lot of demand for it to exist.

**Comment by whit537** [comment]
So far two of the three people participating on this thread have expressed an interest in this feature. ☺️ 🙇

**Comment by j-mcnally** [comment]
Seems pretty representative of the community.

**Comment by andrew** [comment]
There are about 1,200 people using the hosted version...

**Comment by WillAbides** [comment]
Sample size of three and 1,200 users.  That's a margin or error of only 57%.  :trollface:

**Comment by andrew** [comment]
Going to close this for now, I don't think the long term maintenance of the technical debt required to enable this feature is worth it.

@whit537 if you're running your own version you could use the rake task to sync notifications every few minutes to achieve a similar effect: https://github.com/octobox/octobox#sync-notifications-automatically
