### ISSUE TITLE
Disabling private repo notifications

### ISSUE THREAD

**Issue by tsloughter** [octobox/octobox#2066]
Are you experiencing this issue in octobox.io or your own instance?
 - [X] octobox.io
 - [ ] My instance

### Summary of Problem

- What are you trying to do?

Use octobox for my public repositories.

- What happens?

Notifications on from private repos are displayed, they are properly disabled and with the message to upgrade if you want to be able to see the actual notification.

- What should have happened?

"Should". I don't know if this is me missing something or should be a feature request. I expected to be able to disable repos/organizations so I don't have an in inbox that half of the entries are private because it includes my work organization, which I don't want.

Am I supposed to be able to disable specific orgs? Disable displaying private notifications?

Also, I have not installed/enabld the github octobox app for the work organization, so that isn't it.

Maybe it is because Github only lets you route organization notifications to different email addresses but not disable web notifications by organization?

**Comment by nathanshelly** [comment]
If you're interested in changing this only within Octobox you can at least filter out notifications from private repos with the visibility filters:

![visibility](https://user-images.githubusercontent.com/9750687/71759370-f3c91080-2e60-11ea-96f9-56bc9cad238f.png)

**Comment by tsloughter** [comment]
@nathanshelly right, but you can't set any default filter for the `Inbox`, correct?

**Comment by nathanshelly** [comment]
@tsloughter not that I'm aware of, think the closest you could come at the moment is to visit https://octobox.io/?is_private=false (could bookmark it or use something like Alfred to create an expanding snippet). Not quite as convenient as a setting to toggle somewhere though.

**Comment by tsloughter** [comment]
Is this closed as a won't fix or was there a PR that didn't get linked to here?

**Comment by andrew** [comment]
@tsloughter I made it so your private notifications shouldn't show that message anymore ;)

**Comment by tsloughter** [comment]
Ah I see, thanks!
