### ISSUE TITLE
Update Favicon on Refresh with Unread Count/Indicator

### ISSUE THREAD

**Issue by michaelw90** [octobox/octobox#211]
I have 6 tabs that are pinned within Chrome, and one of them is now Octobox, one of the issues that I have is I need to keep checking the tab to see if there are any new notifications etc. 

It'd be great if the tab updated with a count of the total unread notifications, or an indicator at least. There should be two options to users, to remove this indicator either when the tab is viewed, or for the indicator to always be persistent based on the notification status. 

I sometimes like to leave them unread, but might not want the status indicator to be there all the time. 

If no one gets round to it, I'd potentially look at implementing something, but my rails knowledge is limited!

Thanks. <3

**Comment by andrew** [comment]
@michaelw90 it should be noted that octobox doesn't sync in the background by default, you can have it refresh every X minutes if you're hosting it yourself thanks to https://github.com/octobox/octobox/pull/200

Still having a unread count in the favicon would be neat 👍

**Comment by karpiu** [comment]
@andrew @michaelw90 Would it not be better to update the page title with the unread count and change the favicon to indicate that there are (some) unread messages? Changing count in the favicon itself means we need to prepare a lot of favicons.

**Comment by michaelw90** [comment]
The reasons for changing the Favicon are stated in the opening post. To be honest, it shouldn't be that difficult to update the favicon using some JS canvas?

**Comment by karpiu** [comment]
Maybe we can use this:

https://github.com/peachananr/notify-better

**Comment by andrew** [comment]
This should be enough: http://stackoverflow.com/questions/6296574/dynamic-favicon-using-image-manipulation-similar-to-gmail-adding-a-count

**Comment by karpiu** [comment]
It has been two weeks and nobody has done this issue yet. @andrew can I take this one?

**Comment by andrew** [comment]
Sure!

**Comment by karpiu** [comment]
I just noticed that we have a LOT of favicons defined in the header:

```
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
```
Some are also defined in `public/manifest.json` for android.

The problem is that I cannot find a way to dynamically get the currently used favicon (so I can update it). Google gives me nothing and updating them all every time the unread count changes is an overkill. Anybody has a solution to this?

**Comment by andrew** [comment]
@karpiu almost all of them are just for mobile homescreen related things, travis-ci seems to use these two:
```html
<link rel="mask-icon" href="https://cdn.travis-ci.org/images/favicon-c566132d45ab1a9bcae64d8d90e4378a.svg" color="black">
<link rel="icon" type="image/png" href="data:image/png;base64,esdfsdfsd">
```
