### ISSUE TITLE
Move the cursor down after marking a notification

### ISSUE THREAD

**Issue by WillAbides** [octobox/octobox#214]
Marking a notification by keying `x` should move the cursor to the next notification.

**Comment by chrisarcand** [comment]
🤔 I can definitely see the appeal; would it be weird given that it's a deviation from what something like Gmail does (the current interface is very Gmail-like)? (Does that matter?) Thinking out loud.

**Comment by WillAbides** [comment]
Yes that would be weird. I guess I don't mark messages on gmail with my keyboard. 

I would rather leave it to match what people are used to.
