### ISSUE TITLE
Muted and archived notification get unarchived when there is new activity

### ISSUE THREAD

**Issue by WillAbides** [octobox/octobox#215]
After I archive a notification then use the unsubscribe button on the subject issue to ignore it on GitHub, the issue will unarchive when there is new activity even though it remains ignored on GitHub.

I don't immediately see a way around this behavior aside from querying /notifications/threads/:id/subscription for every notification on sync.

This has ramifications for #7.  When that is implemented, we should separately track which threads we are ignoring instead of relying only on the attribute.

**Comment by andrew** [comment]
Wow, that's surprising behaviour from the GitHub API!

**Comment by WillAbides** [comment]
It really is.  I haven't dug into it yet because I'm trying to get some 💰  work done today, but I'm interested to find out why.

**Comment by andrew** [comment]
Should be noted that I have not experienced that behaviour on octobox.io, I unsubscribed from a thread over xmas that has remained active and it didn't show up in octobox again for me

**Comment by WillAbides** [comment]
I confirmed this behavior with the platform team.  The API will serve previously delivered notifications even if you have since ignored them.  The updated_at attribute will continue to change when the thread is updated just as if it weren't ignored.  However, the unread attribute will remain false even when there is new activity.

Thus when an ignored item is updated, the next sync will see it as having a newer updated_at and will flip the archived bit to true.

We could use the fast that unread doesn't change to correct for this with something like https://github.com/WillAbides/octobox/commit/d4f13cce0e180e72dec6e32c2846ec8df35d843f.  That would get rid or the undesired behavior of unarchiving muted notifications.  

However I think it would also have the side effect of not unarchiving a notification for a non-ignored thread that was both updated and read between syncs.  I'm not sure what the desired behavior is there.  If you have already seen the new activity, do you want the notification unarchived?

If you do want that case to unarchive a notification, then something like https://github.com/WillAbides/octobox/commit/6570cbbd19f467daaefbc0778e0609f7eea44193 should work.

**Comment by andrew** [comment]
@WillAbides does https://github.com/octobox/octobox/pull/227 fix this?

**Comment by WillAbides** [comment]
I was just about to close it.
