### ISSUE TITLE
Make the UI cooler

### ISSUE THREAD

**Issue by m1guelpf** [octobox/octobox#216]
#### Images:
![Screenshot](http://i.imgur.com/Ex2DKdU.png)
---
![Screenshot](http://i.imgur.com/OliRR1U.png)
#### Images:
![Screenshot](http://i.imgur.com/T8uBOm4.png)
---
![Screenshot](http://i.imgur.com/xeEZjWF.png)

**Comment by tarebyte** [comment]
I'm personally really happy with how the UI looks. Thank for the suggestions, but I think we'll pass on these.
