### ISSUE TITLE
Filter out self-inflicted notifications

### ISSUE THREAD

**Issue by OliverJAsh** [octobox/octobox#217]
GitHub does not send me email notifications for actions that are inflicted, e.g. if I commented on an issue I'm subscribed to. It would be nice if Octobox did the same. (In my observations it doesn't.)

**Comment by andrew** [comment]
@OliverJAsh I believe that's dependent on #4 as it's a limitation of the GitHub Notifications API which behaves slightly differently to the web/email notifications from Github.com or at least is lacking information in the response for us to know who triggered the update.

**Comment by whit537** [comment]
Side note: GitHub actually [added](https://github.com/blog/2203-email-updates-about-your-own-activity) the option to self-inflict emails, [for Guido](https://twitter.com/gvanrossum/status/553433955374874624). ;-)

**Comment by andrew** [comment]
This is do-able now that #411 has been merged.

**Comment by OliverJAsh** [comment]
I don't think so, thanks!
