### ISSUE TITLE
Current `latest` docker image fails to start

### ISSUE THREAD

**Issue by jakubgs** [octobox/octobox#2174]
I'm running Octobox via Docker using [`octoboxio/octobox:latest`](https://hub.docker.com/layers/octoboxio/octobox/latest/images/sha256-d1ca2d0dc1786bbcf644981b6088ace520aa5595b5347fce34d80884852d2e0e) and I can't get it to start.

First I got this error:
```
bin/docker-start: exec: line 27: rails: not found
Unable to start, see the Skylight logs for more details
No valid API key has been set, notifications will not be sent
```
And I realized that `rails` is available under `/usr/src/app/bin` so I restarted the container with `PATH` adjusted to include that path. But then I got:
```
ArgumentError: Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered
```
You can find the full error log [here](https://github.com/octobox/octobox/files/4021282/octobox.log).

**Comment by andrew** [comment]
Thanks for reporting, it looks like a bundler error (https://github.com/bundler/bundler/issues/7484), I wonder if [octoboxio/octobox:ruby-2.7.0](https://hub.docker.com/layers/octoboxio/octobox/ruby-2.7.0/images/sha256-055031893063e3d0a1b1cdfd22bc5c7191a3e7856f6d1ed4fbb8111c4160c25a) will fix it.

**Comment by andrew** [comment]
@jakubgs I've tested and updated the ruby-2.7.0 branch with docker and got it working, will merge it shortly.

**Comment by jakubgs** [comment]
It works! Thanks for the quick fix!
