### ISSUE TITLE
Time zone reverts to UTC when changing filters

### ISSUE THREAD

**Issue by WillAbides** [octobox/octobox#218]
Thanks to #197, notification times are initially displayed in my local time zone, but when I change the filter the time zone changes to UTC.

![timezone](https://cloud.githubusercontent.com/assets/233500/21645456/a3b12adc-d257-11e6-924e-e3d2965c5c66.gif)

**Comment by andrew** [comment]
I'd guess the js function needs to be ran on turbolinks load rather than doc ready

**Comment by andrew** [comment]
@WillAbides just deployed a fix for that, can you double check it works?

**Comment by WillAbides** [comment]
works on my machine 👍
