### ISSUE TITLE
Rethinking stopgap fix for syncing old notifications

### ISSUE THREAD

**Issue by WillAbides** [octobox/octobox#221]
I'd like to rethink #127.  A simpler solution may be to have two different requests on sync.

The first request would get only unread notifications since last sync with parameters like `{ all: false, since: user.last_synced_at.iso8601 }`.

The second request would be the same as the current request for all notification, but its results would only be used to sync the read status.  The one change I would make to this request would be to make it request since user's oldest unread notification.

I think this change would have a couple of benefits.  First, it would reduce complexity that leads to issues like #215.  Second, it will lead to faster syncs when the user only has very recent unread items (or none at all).

We could also make the syncs appear much faster if we make the second request a background task with the tradeoff being that items aren't marked read until the next refresh.

**Comment by andrew** [comment]
Sounds good to me @WillAbides but I'd like to avoid adding background queues at the moment, perhaps we can use the `concurrent_ruby` gem to do the requests in parallel?

**Comment by WillAbides** [comment]
I'll work on this using `concurrent_ruby`
