### ISSUE TITLE
Keeps syncing, never finishes

### ISSUE THREAD

**Issue by frenck** [octobox/octobox#2219]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance
 
If your issue is related to an Octobox.io subscription purchase please ensure you have installed the [Octobox GitHub App](https://github.com/apps/octobox) for the repositories concerned.

🐞 **Problem**

My account keeps syncing (icon keep rotating), and never stops since 7 hours ago.
Nothing new comes in, I can also now not sync anymore.

![image](https://user-images.githubusercontent.com/195327/73636928-55022080-4667-11ea-9b45-92f85cce691d.png)

Keeps throwing a 423 (Locked) in my console:

![image](https://user-images.githubusercontent.com/195327/73637068-b3c79a00-4667-11ea-84fd-b06a6320f10c.png)

🎯 **Goal**

Well, a working system is awesome of course 😉 

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by frenck** [comment]
Update: the spinning sync icon stopped.
However, I cannot sync. Hitting the icon refreshes the page; nothing happens.
The locked message in the console is gone as well.

**Comment by andrew** [comment]
@frenck I've kicked off another sync of your notifications from the console, it took a lot longer for github to respond than for a regular user but did complete successfully.

**Comment by frenck** [comment]
Thanks! Now it also works again, thanks! 👍

**Comment by frenck** [comment]
It just stopped working again.
I've clear out all archived notification as well, so my account should now be completely empty. However, nothing happens.

**Comment by andrew** [comment]
@frenck can you email support@octobox.io with more details (notifications/repos you expect to see in your octobox inbox but are not)

**Comment by frenck** [comment]
Well, hours later, everything shows up again and everything seems OK.
It acts flaky beyond usage.

Some repos:

- `home-assistant/*`
- `hassio-addons/*`

Which are good fur hundreds of notifications a day?

Also:

- `octobox/octobox`

Didn't show up.
