### ISSUE TITLE
Settings Save Issues

### ISSUE THREAD

**Issue by johnthepink** [octobox/octobox#223]
It seems like #200 may have added some issues for instances without auto refresh enabled.

1) The "Save" button doesn't totally make sense on the settings page:

![screen shot 2017-01-05 at 11 15 00 pm](https://cloud.githubusercontent.com/assets/816517/21707468/4dcb892c-d39d-11e6-876c-462bd87b5a35.png)

2) Clicking the "Save" button results in an error:

![screen shot 2017-01-05 at 11 15 05 pm](https://cloud.githubusercontent.com/assets/816517/21707471/6063a344-d39d-11e6-98f0-ec1b7d4fb1b2.png)

I'd be happy to send a PR soon :)

**Comment by andrew** [comment]
Just deployed @tarebyte's fix for this, thanks for reporting!
