### ISSUE TITLE
Very old unread notifications aren't marked read

### ISSUE THREAD

**Issue by WillAbides** [octobox/octobox#230]
If you have unread notifications that are too old to show up in `GET https://api.github.com/notifications?all=1`, they will never have their read status synced unless they get new activity.  I have three ideas for dealing with this:

1. Individually query the thread urls for unreads that are older than the last notification in `GET https://api.github.com/notifications?all=1`.

2. Let the user manually mark them as read.

3. Add an action to sync selected notifications.

I don't know which of these options I like the least.  We can mitigate the api impact of option 1 by using etag when checking for updates, but for some users coming back from vacation or dealing with a shitstorm, that could be hundreds of queries they are waiting on for a sync.  Option 2 is pretty hacky, but at least it would keep a user from having to deal with the annoyance of persistent unread notifications.

I thought of option 3 as I was writing this.  I think I like it better than 1 or 2.  It's benefit is that it doesn't force a huge number of queries every time the user syncs, but the downside is that it still takes manual intervention and is probably more code to maintain.

**Comment by andrew** [comment]
Any idea what the limit is for `https://api.github.com/notifications?all=1`? is it a max number of pages or some other undocumented limit? Perhaps we can only sync back as far as that to avoid hitting things that would never get updated otherwise?

**Comment by andrew** [comment]
I think we can close this now, please feel free to re-open if not
