### ISSUE TITLE
New color or Subscriptions and Team mention

### ISSUE THREAD

**Issue by tarebyte** [octobox/octobox#231]
Right now my labels look like this:

<img width="170" alt="screen shot 2017-01-09 at 15 59 26" src="https://cloud.githubusercontent.com/assets/564113/21783281/a45d6406-d684-11e6-97f4-c2a692ffff16.png">

And it's kind of bumming me out.

@briannelson do you have a suggestion for what colors we could use?

**Comment by WillAbides** [comment]
For reasons we don't have defined we could throw caution to the wind and go pseudo-random:
`color = Digest::MD5.hexdigest(reason)[0..5]`

With that code, `Team Mention` would be: ![](http://hexcolor16.com/8826dc-100x20.png)

and `Subscribed` would be ![](http://hexcolor16.com/808c74-100x20.png)

We can probably do better than that.
