### ISSUE TITLE
Hide 'Filter:' when it's empty

### ISSUE THREAD

**Issue by WillAbides** [octobox/octobox#233]
![2017-01-10 at 7 46 am](https://cloud.githubusercontent.com/assets/233500/21808474/1ae533ae-d709-11e6-90e0-3b891f4abd40.png)

When viewing the archive, the 'Filter:' UI element is displayed without showing a filter.  In the same spirit as #232, it would be great to not see that.

**Comment by tarebyte** [comment]
@WillAbides the only time I can make that happen is when I click on the Archive link? Is that the same for you?

**Comment by WillAbides** [comment]
Yes.  That's the only place I've seen it.

**Comment by andrew** [comment]
:shipit:
