### ISSUE TITLE
YAML parse error

### ISSUE THREAD

**Issue by chrisarcand** [octobox/octobox#236]
Hi! I'm setting up octobox beyond running it on localhost and have run in to an issue.

~~Upon trying to run Rails in the production environment (`RAILS_ENV=production`) with `OCTOBOX_DATABASE_PASSWORD` available,~~ any loading of Rails fails with the following message:

```
Running via Spring preloader in process 30482
rake aborted!
YAML syntax error occurred while parsing /home/chris/octobox/config/database.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): found character that cannot start any token while scanning for the next token at line 35 column 13
-e:1:in `<main>'
Psych::SyntaxError: (<unknown>): found character that cannot start any token while scanning for the next token at line 35 column 13
-e:1:in `<main>'
Tasks: TOP => db:migrate => db:load_config
```

I don't actually see any egregious errors in the YAML; I've also tried just putting the password directly in to the file. 

~~**Note that running it in development works just fine, only `RAILS_ENV=production` gives this error**~~ This was wrong. It's whenever OCTOBOX_DATABASE_PASSWORD is supplied.

As an aside, I open this issue because the database.yml is a version-controlled file so I'm assuming someone else has this issue. Perhaps a template file should be used and the actual database.yml kept out of version control for whatever purpose you want.

**Comment by chrisarcand** [comment]
I seem to only be running in to this issue in my Fedora environment, and not locally while in production mode on my MacOS machine. The plot thickens.

**Comment by andrew** [comment]
@chrisarcand is this using Docker or just running the app directly on the OS?

**Comment by chrisarcand** [comment]
Directly on the OS! Fedora 23. Still investigating. This might be a generic issue with Psych and Fedora and unrelated to Octobox; I'll update when I find out more.

**Comment by andrew** [comment]
I'm away traveling today but will try and have a better poke around tomorrow

**Comment by chrisarcand** [comment]
Ugh. Figured it out. 

I had an invalid character in my generated database password. You can't have `@` (and probably other types of chars) or it gives this parse error. The most confusing part (and why I reported this) about this is that I thought I debugged properly and the OS bit threw me off, I must have done something different in my local environment. 

It does the same thing on MacOS as well. No issue with Octobox, apologies for the issue report! 💙
