### ISSUE TITLE
Too many notifications synced on initial signup

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#242]
Another side effect of https://github.com/octobox/octobox/pull/227 is that we pull in **all** the users notifications the first time they sign up, for very active github users this either takes ages, timeouts or crashes the rails app completely, need to add a limit back in!

**Comment by WillAbides** [comment]
I ran across this too. I'm thinking the limit should be a number and not a time limit. 

The problem is especially bad when there are thousands of unread as it doesn't seem to purge old unread notifications like it does with read ones.

**Comment by chrisarcand** [comment]
[Same.](https://github.com/octobox/octobox/issues/237#issuecomment-272521520) I had hundreds of thousands of unread web notifications (was using email and didn't turn web off) and it didn't go well.

**Comment by WillAbides** [comment]
I was just looking at implementing a max count to fetch and don't see a simple way to do that with octokit. 

I'll submit a PR with a 1 month limit later today.

**Comment by andrew** [comment]
Reopening this for testing purposes
