### ISSUE TITLE
[Mobile] Pin controls to top

### ISSUE THREAD

**Issue by chrisarcand** [octobox/octobox#243]
In mobile views, the controls for refreshing, archiving, etc should be part of a bar pinned to the top of the screen as you need to scroll all the way back up each time you want to do anything.

![](http://screenshots.chrisarcand.com/perm2IMG_3349.jpg)

**Comment by andrew** [comment]
👍

**Comment by chaserx** [comment]
I think this can probably be closed now due to merging #261 

Thoughts? @chrisarcand @andrew

**Comment by andrew** [comment]
Done!
