### ISSUE TITLE
Show author of issue/PR

### ISSUE THREAD

**Issue by chrisarcand** [octobox/octobox#244]
I find it interesting to see the author of PRs/issues while perusing them, as knowing the author usually gives quite a bit of context in addition to the issue's title. I propose that we add authors to the list view in some way.

Some considerations, however:

* It may or may not be appropriate to add authors as Just Another Column™ in the list view. *We should experiment with it*, but I wouldn't want the list view to become this mangled mess of narrow columns giving too much information. Perhaps if #209 is added that would be sufficient enough (could quickly mouseover, I guess)
* This may or may not require #4

**Comment by andrew** [comment]
Duplicate of https://github.com/octobox/octobox/issues/83

**Comment by chrisarcand** [comment]
🙇
