### ISSUE TITLE
Archive shortcut choice

### ISSUE THREAD

**Issue by chrisarcand** [octobox/octobox#247]
So, I really want to ask this but I totally understand that what's done is done and suddenly changing it may or may not be kosher, but... 

Why is the Archive shortcut 'y'?

Following what we've sort of been following with Gmail convention, I keep hitting 'e' (that's what it is in Gmail) since the interfaces are so similar.

**Comment by WillAbides** [comment]
I don't know the real answer, but being used to vim I think of it as (y)anking the notification to the archive.  That isn't what yank means in vim at all, but that's how I remember it.

**Comment by andrew** [comment]
cc @karpiu who I think added the original shortcuts, I don't see why we can't have both?

**Comment by karpiu** [comment]
@chrisarcand I was using this list as a guide: https://shortcutworld.com/en/Gmail/mac/all

Now I read it again and I see that I added archiving with `y` by mistake :) I missed `e` shortcut and misinterpreted what `y` does. 

Also in the original issue (#20) @boffbowsh explains how he uses shortcuts in Gmail and he uses `y` at the end, so this also fooled me :P

**Comment by WillAbides** [comment]
`e` isn't spoken for yet.  Maybe we should make it a second mapping for archive.

**Comment by andrew** [comment]
e is merged now

**Comment by chrisarcand** [comment]
Well I'm glad I asked ;) Thanks.
