### ISSUE TITLE
Multiple account support

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#250]
I have a second github account that I do somethings with (@bertie), I wonder how hard it would be to allow connecting of multiple accounts into the same inbox or at least with a quick switching UI with a unified overview?

Another underlying thought here is that as I start to use GitLab and Bitbucket more I'm pondering if we can add support for those, although they don't seem to have a similar API for grabbing notifications directly.

**Comment by andrew** [comment]
The main blocker for multiple GitHub accounts is that your browser can only be logged into one account at a time, so clicking out to the issue link wouldn't really work, would need something like https://github.com/octobox/octobox/issues/69 so you can read the issue/pr thread directly in the octobox UI which becomes a whole lot more involved

**Comment by metaskills** [comment]
I have a second one that I created called `rails-sqlserver` to give that overall project an identity/home outside of my personal moniker. I suspect others do this as well for large projects.

**Comment by andrew** [comment]
@metaskills I've moved most of my projects into orgs for the same reason

**Comment by IOAyman** [comment]
This would be awesome!

**Comment by stevelacey** [comment]
I would really love to never have to look at GitLab again, if you're interested in supporting GitLab, I'm down to help

**Comment by chrisarcand** [comment]
@stevelacey PRs accepted! 😄 Would love that, though do note what Andrew said in the description: it might not be feasible given GitLab's API.

**Comment by juliquiron** [comment]
Isn't this looking like a proper GitLab API to implement this feature? https://docs.gitlab.com/ee/api/

**Comment by andrew** [comment]
GitLab does have an [events API](https://docs.gitlab.com/ee/api/events.html) but it doesn't look or act much like the GitHub API, I can't see there being an easy path to supporting both platforms in one app. 

I suspect the solution would be a separate fork of Octobox (maybe called something like Labbox) that worked with GitLab events, but I don't think it'll happen any time soon.
