### ISSUE TITLE
Does Octobox notify when starred but unwatched project has new release?

### ISSUE THREAD

**Issue by Geremia** [octobox/octobox#254]
Does Octobox notify me when my starred, but possibly unwatched, projects have a new release?

**Comment by andrew** [comment]
Nope, you have to be watching it to trigger notifications

**Comment by Geremia** [comment]
> Nope, you have to be watching it to trigger notifications
"Watching: Be notified of all conversations" or would "Ignoring: Never be notified" work, too?

**Comment by andrew** [comment]
I don't believe so

**Comment by Geremia** [comment]
A new comment, :+1:
