### ISSUE TITLE
wss://octobox.io/cable returning 301

### ISSUE THREAD

**Issue by nornagon** [octobox/octobox#2606]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance
 
If your issue is related to an Octobox.io subscription purchase please ensure you have installed the [Octobox GitHub App](https://github.com/apps/octobox) for the repositories concerned.

🐞 **Problem**

![image](https://user-images.githubusercontent.com/172800/110166156-cbaca880-7da8-11eb-8370-aa1de05c2267.png)

I'm seeing this message repeatedly in the console, and the state of the app isn't updating—it's showing me only issues from when I last used octobox in 2019.

**Comment by nornagon** [comment]
This looks like it might be a cloudflare configuration issue?

```
$ curl -v https://octobox.io/cable
[...]
< HTTP/2 301
< location: https://octobox.io/cable
```

the page is 301 to itself.

**Comment by andrew** [comment]
@nornagon thanks for reporting, I believe I've fixed the websocket issue, it was a config issue on my nginx webserver behind cloudflare.
