### ISSUE TITLE
Difficult to determine read / unread status

### ISSUE THREAD

**Issue by ryankurte** [octobox/octobox#2612]
hey thanks for making a neat thing! not sure this is a bug report but, also wouldn’t seem to be a significant change.

🐞 **Problem**
when deep in the issue mines it’s difficult to determine from highlighting and font changes whether an issue is read or unread (or has new notifications) without remembering what meaning is ascribed to different text highlighting, for example:

![9BE6EB9E-28C2-42ED-B652-32A131F1BC4C](https://user-images.githubusercontent.com/860620/110539493-32a3d600-818a-11eb-92a2-18138eb61c69.png)

doesn’t seem to make it clear which is which.

🎯 **Goal**

to be able to determine read / unread status without having to differentiate between shades of blue, useful for low contrast devices and people who struggle with colour differentiation  as well as viewing the website while outdoors or wearing sunglasses. 

💡 **Possible solutions**
perhaps a sigil as popularised by the email clients of old to indicate read / unread status?

**Comment by andrew** [comment]
Agreed, that's really hard to tell which is which in dark mode

**Comment by andrew** [comment]
I think https://github.com/octobox/octobox/pull/2677 should help solve this

**Comment by ryankurte** [comment]
yep that should do it, thanks for following up ^_^
