### ISSUE TITLE
Pinned searches: `inbox:true` added to my search query by Octobox

### ISSUE THREAD

**Issue by ringods** [octobox/octobox#2645]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance
 
🐞 **Problem**

Octobox is adding `inbox:true` to the search query for a pinned search I set up

🎯 **Goal**

I create a pinned search named "Tracked Releases" which follows the GH release notifications of a few tools I'm interested in. But I can't create a pinned search only containing `type:release archived:true` in the search query. Octobox always appends `inbox:true` to it.

**Comment by andrew** [comment]
Definitely a bug, I was just able to replicate this myself, will try to find some time to fix it this week

**Comment by andrew** [comment]
Note to myself for later, the bug is in these two lines: https://github.com/octobox/octobox/blob/master/app/models/search.rb#L77-L78

**Comment by ringods** [comment]
@andrew I was trying to debug a bit myself. However, I don't understand the search tests:

https://github.com/octobox/octobox/blob/master/test/models/search_test.rb

Why are some parts the `query` and some other parts the `params`? In this bug case, my query text from the input field is `type:release archived:true`. Is this all passed to what you consider the lines at fault as `query`, or is it split between `query` and `params`?

**Comment by andrew** [comment]
@ringods so there's a bit of a legacy left over, in a perfect world, each filter link in the octobox UI would simply transform the query param, but for now many sidebar links change the url params and the search box uses those params to make the visible query in the search box match with your current active filters.

**Comment by andrew** [comment]
@ringods opened a PR over here: https://github.com/octobox/octobox/pull/2652

**Comment by ringods** [comment]
@andrew thanks for the explanation. The build of your PR seems to be OK. Can you get this merged & released? 🙏

**Comment by andrew** [comment]
:shipit:

**Comment by ringods** [comment]
Tnx!! I can use my Pinned Search now! 👍
