### ISSUE TITLE
Javascript tests

### ISSUE THREAD

**Issue by WillAbides** [octobox/octobox#268]
I'd like to add some tests for functions in application.js.  The need became apparent in this [unfortunate](https://github.com/octobox/octobox/pull/248) [series](https://github.com/octobox/octobox/pull/252) of [PRs](https://github.com/octobox/octobox/pull/253).

I'm thinking of using [mocha](https://github.com/mochajs/mocha), but I'm up for other suggestions.

**Comment by andrew** [comment]
👍

**Comment by johnthepink** [comment]
I've been using [Jest](http://facebook.github.io/jest/) recently. It has a great command line interface, it's very fast, sane defaults, and super easy mocking.

**Comment by andrew** [comment]
Needs to work with Ruby on Rails test suite btw for stubbing and mocking http requests

**Comment by WillAbides** [comment]
Since this has some interest, I created a WIP PR to show where I've gotten with this.  #287

**Comment by technicalpickles** [comment]
Would javascript unit tests guard against the type of problems you are trying to prevent? Or do you think it needs full browser tests with something like capybara + selenium/poltergeist?

**Comment by WillAbides** [comment]
The particular issues that caused me to open this issue would be caught by unit tests, but browser tests would catch a lot more.

**Comment by samjacobclift** [comment]
Why not both :D unit and browser ones, we could add unit ones for now and then add browsers ones if need be
