### ISSUE TITLE
Notifications on Chrome

### ISSUE THREAD

**Issue by GiacomoLaw** [octobox/octobox#269]
It would be awesome if you were notified when you had a new notification on Chrome.

**Comment by GiacomoLaw** [comment]
Kind of needs this to work: https://github.com/octobox/octobox/issues/270

**Comment by andrew** [comment]
This needs to be optional, I can't stand push notifications!

**Comment by GiacomoLaw** [comment]
@andrew I'm pretty sure that you can either allow or decline Chrome notifications, so you could just disallow. 😄

**Comment by tkbremnes** [comment]
First, I want to add that this is not at all Chrome only – this works in most (if not all) Chromium based browsers, as well as Firefox.

There are two different "versions" of notifications. One is simple, just a manner of running a `new Notification("You got mail!");` on an event. This is the (Web Notification API)[https://developer.mozilla.org/en-US/docs/Web/API/notification]. This however requires that Octobox is open in a tab somewhere.

To be able to receive _push_ notifications when a tab is not open anywhere, you'll need the (Push API)[https://developer.mozilla.org/en-US/docs/Web/API/Push_API]. This requires a server process that communicates with a push server somewhere, which then will send the notification to the browser that subscribes to the notification. More complicated, but more powerful.

And yes, both of these methods require that the user explicitly accept notifications.

**Comment by andrew** [comment]
Going to close this for now as I can't see us doing it in the short term, but if anyone really wants it and is willing to have a go at implementing it then drop a comment and we'll open it back up.
