### ISSUE TITLE
Security@octobox.io does not work

### ISSUE THREAD

**Issue by jules2689** [octobox/octobox#2747]
Hello!

I tried emailing security@octobox.io, but it bounced. I have a minor security PR I wanted to discuss, but I can't seem to do that as per the vulnerability disclosure guidelines.

cc @andrew

**Comment by andrew** [comment]
cc @BenJam looks like something's gone weird in google apps, I can't see the security group anymore but I also can't recreate it, any ideas?

**Comment by andrew** [comment]
@jules2689 can you try again, I've tweaked some settings in google apps, it appears to work now

**Comment by jules2689** [comment]
Let me know if you got it this time around :)

**Comment by andrew** [comment]
Yep that works again now, got your email.
