### ISSUE TITLE
Clearer source link

### ISSUE THREAD

**Issue by WillAbides** [octobox/octobox#278]
From [the license](https://github.com/octobox/octobox/blob/f3101457f174c0ad56166f8841a2a5f40b21f045/LICENSE.txt#L650-L656):

>   If your software can interact with users remotely through a computer
network, you should also make sure that it provides a way for users to
get its source.  For example, if your program is a web application, its
interface could display a "Source" link that leads users to an archive
of the code.  There are many ways you could offer source, and different
solutions will be better for different programs; see section 13 for the
specific requirements.

Octobox almost does this through the 'Octobox support' menu link to GitHub issues, but it could do better by adding a link to the code and labeling it 'Source'.

I would also like to make the link configurable through an environment variable so that forks can comply without having to modify that part of the source.

**Comment by andrew** [comment]
Would be great to have something like "© 2017 Andrew Nesbitt, [source](https://github.com/octobox/octobox) available under [AGPL 3.0](https://github.com/octobox/octobox/blob/master/LICENSE.txt)" in the footer of the main page

**Comment by chrisarcand** [comment]
I just discovered the Affero license the other day and was thinking this same thing :) Good call.

> configurable through an environment variable

Note on this, I'd like to add some easier configuration setup beyond just environment variables soon. I'll open a separate issue, maybe I can get that done before another is added

**Comment by chrisarcand** [comment]
#280 💙
