### ISSUE TITLE
Sync icon turn clock-wise while arrows point counter-clockwise

### ISSUE THREAD

**Issue by ringods** [octobox/octobox#2824]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance
 
If your issue is related to an Octobox.io subscription purchase please ensure you have installed the [Octobox GitHub App](https://github.com/apps/octobox) for the repositories concerned.

🐞 **Problem**

I noticed a small UI discrepancy: the arrows on the sync icon point counter-clockwise, but when you click the button, the icon rotates clockwise.

🎯 **Goal**

I know this is a small detail, but arrow direction & rotate direction should be aligned. 😉 

💡 **Possible solutions**

Provide an updated sync icon with the arrows pointing clockwise.

📋  **Steps to solve the problem**

 * Configure an updated sync icon.

**Comment by andrew** [comment]
Deploying a fix now
