### ISSUE TITLE
Mobile side menu height bug

### ISSUE THREAD

**Issue by senid231** [octobox/octobox#283]
On mobile height of the side menu depends on height of main content

[![Screenshot_20170121-184910.png](https://s5.postimg.org/x7mytxz2f/Screenshot_20170121_184910.png)](https://postimg.org/image/slqulldj7/)

Screenshot from latest chrome on Nexus 5x (Android 7)

**Comment by WillAbides** [comment]
Confirmed here too.  Here's a gif

![sidescroll](https://cloud.githubusercontent.com/assets/233500/22177115/a58b3d5a-dfdd-11e6-8ae0-a5762de8e894.gif)

**Comment by andrew** [comment]
@willabides what do you use to record your gifs?

**Comment by chrisarcand** [comment]
@andrew One of the remotees best friends, IMO: https://itunes.apple.com/us/app/monosnap/id540348655

**Comment by WillAbides** [comment]
I use the [giphy capture app ](https://giphy.com/apps/giphycapture).  It seems ok, but I've only had it for a couple of weeks so I can't fully recommend it.
