### ISSUE TITLE
The label "Login to GitHub app" is rendered incorrectly in notification row

### ISSUE THREAD

**Issue by tombruijn** [octobox/octobox#2831]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

The octobox.io issue view shows the label `Login to the GitHub App ">` in almost every row. See screenshot. This started happening yesterday.

<img width="1660" alt="image" src="https://user-images.githubusercontent.com/282402/140477071-c6e60ccc-476c-497a-9623-a8d0fd097bad.png">

🎯 **Goal**

The rendering of the notifications rows is very tall now, which makes it less convenient to use.

💡 **Possible solutions**

I think it relates to this change from the 4th of November: [fix githubapp omniauth buttons ](https://github.com/octobox/octobox/commit/34e89c69417290ce751ce68f7b96ece6752975ef)

My guess is that it previously worked because the quotes in the `a` element where single quotes and the `link_to` helper now returns double quotes. The parent attribute of the icon uses double quotes as well, and doesn't escape the rendered partial.

https://github.com/octobox/octobox/blob/34e89c69417290ce751ce68f7b96ece6752975ef/app/views/notifications/_notification.html.erb#L30

The rendering of that table cell is now like the content below:

```erb
<a tabindex="0" class="" role="button" data-toggle="popover" title="Login to the GitHub App" data-content="<p>
  The GitHub App is installed on this repository, authorize it to see state, labels, authors, assignees and CI status on this notification.
</p>

<a class=" btn btn-primary btn-sm" rel="nofollow" data-method="post" href="/auth/githubapp">Login to the GitHub App</a>
">
<svg height="16" class="octicon octicon-git-pull-request" viewBox="0 0 16 16" version="1.1" width="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.177 3.073L9.573.677A.25.25 0 0110 .854v4.792a.25.25 0 01-.427.177L7.177 3.427a.25.25 0 010-.354zM3.75 2.5a.75.75 0 100 1.5.75.75 0 000-1.5zm-2.25.75a2.25 2.25 0 113 2.122v5.256a2.251 2.251 0 11-1.5 0V5.372A2.25 2.25 0 011.5 3.25zM11 2.5h-1V4h1a1 1 0 011 1v5.628a2.251 2.251 0 101.5 0V5A2.5 2.5 0 0011 2.5zm1 10.25a.75.75 0 111.5 0 .75.75 0 01-1.5 0zM3.75 12a.75.75 0 100 1.5.75.75 0 000-1.5z"></path></svg>
</a>
```

📋  **Steps to solve the problem**

- Adding a `html_escape` around the return value from `render 'notifications/login_prompt'` may fix it, but I haven't had time to try and make a fix myself.

**Comment by andrew** [comment]
yeah that's my bad, will get a fix in for it this evening

**Comment by andrew** [comment]
Fix incoming: https://github.com/octobox/octobox/pull/2832

**Comment by tombruijn** [comment]
Thanks for the quick fix @andrew!
