### ISSUE TITLE
Update ruby to 3.1.0

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#2861]
https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

**Comment by olgachmaj** [comment]
can I pick this up? It would be my first issue :)

**Comment by andrew** [comment]
@olgachmaj sure! You can see an example of where I previously upgraded the ruby version here: https://github.com/octobox/octobox/commit/98606ecd9310cd540197464a3c0747dff213bed8
