### ISSUE TITLE
Search parsing breaks on certain characters

### ISSUE THREAD

**Issue by balazsorban44** [octobox/octobox#2870]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance
 
🐞 **Problem**

If a label contains a colon (`:`) or a hyphen (`-`), the search parser transforms the label, making Octobox return the wrong results. I can only verify the problem with these two characters, but there might be other cases as well.

Example queries:
1. 
My query: `label:"kind: bug"`
Transformed query: `label:" kind:bug"`

2.
My query: `label:"created-by: Next.js team"`
Transformed query: `label:"created -by:Next.js team"`

🎯 **Goal**

Defining pinned searches show 0 results for most of my use cases. Typing these manually into the search bar does not work either. The returned result should match the exact query given by the user.

💡 **Possible solutions**

The problem seems to come from `lib/search_parser.rb`, from this change:

https://github.com/octobox/octobox/commit/d76db3d6a92dd8102a1b25bf6c82386b5d82ca75#diff-44b2718766fa20dc1d7738a61afb283b787bcb352a378de349ace75e8a55c455R11

I recently started using Octobox, but one of my colleagues reported the issue being present since that commit has landed.

📋  **Steps to solve the problem**

The Regular Expression that parses the search query should take into account that certain characters can also appear as part of the label (and other groups) terms.

I am currently looking into this myself, but as I have no experience with Ruby local development, it might take longer for me to figure out how to set it up than for the author to find a fix. Unless it's confirmed as being worked on by someone else, I'll continue trying to create a fix, and if I manage to, I'll open a PR.

**Comment by andrew** [comment]
Thanks for reporting, that change was made due to a denial of service attack vector in the previous regex, those are good test cases you've provided, should be able to fix those soon.

In the short term, i believe you can bypass the search query parser by adding the `label` parameter to the url itself, for example: https://octobox.io/?inbox=true&label=kind:%20bug

**Comment by andrew** [comment]
I've got a branch up with your test cases added: https://github.com/octobox/octobox/pull/2871

Hoping to tackle this within a few days, sorry for the delay, having surgery on my broken wrist later today

**Comment by andrew** [comment]
@balazsorban44 I've deployed a fix for this to octobox.io, can you reopen it's not working as expected?

**Comment by balazsorban44** [comment]
I'll check right away!

**Comment by balazsorban44** [comment]
I had to update my pinned searches under https://octobox.io/settings, but after that, it all seems to work. Thank you! :+1:
