### ISSUE TITLE
'Mute Selected' doesn't clear selected notifications

### ISSUE THREAD

**Issue by chrisarcand** [octobox/octobox#288]
~~I often like to select a number of notifications to be muted and then archived. Unfortunately, when you mute notifications those notifications are currently deselected so you then have to select all the ones you just had picked out to be then archived.~~

~~Muting should not deselect my selected notifications. To signal that notifications were muted, we could just have a flash message saying "The selected notifications have been muted" or some such.~~

~~Considering this a bug as Mark as Read does the correct behavior while this does not.~~

**Update**: Mute selected is intended to archive messages as well; the bug here is that when you mute, the notifications selected are muted and archive yet remain on the page deselected until you refresh the page.

**Comment by WillAbides** [comment]
I think the bug is slightly different from what you described.  Mute is supposed to archive as well.  When I tried it just now, it did archive, but didn't refresh the page.  Once I hit refresh on the page, the notification I had muted was gone.

**Comment by chrisarcand** [comment]
Oh whoa, good catch. I wouldn't have thought that from the button name but I suppose that makes sense.

**Comment by andrew** [comment]
I've noticed this happen when doing a regular archive, where the page refreshes but it doesn't hide them until after refresh

**Comment by andrew** [comment]
Maybe turbolinks related?

**Comment by WillAbides** [comment]
Another data point:  It works when I step through in the chrome debugger but not when I don't.

**Comment by WillAbides** [comment]
I've got this fixed in #289
