### ISSUE TITLE
Footer license/copyright looks weird on big screens

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#291]
![screen shot 2017-01-24 at 9 33 29 am](https://cloud.githubusercontent.com/assets/1060/22241660/39cf346c-e218-11e6-81b3-c491dc80b647.png)

Only just saw the updated footer on desktop, and the stretchy spacing looks really off on large screens.

Mostly leaving this issue to bug myself to fix it 😬

**Comment by WillAbides** [comment]
I tried to model it after GitHub's.  I agree something is a bit off about it, but I can't put my finger on it.

GitHub's footer for comparison:

![2017-01-25 at 10 40 am](https://cloud.githubusercontent.com/assets/233500/22299756/ea48fabc-e2ea-11e6-8fc1-5b7a1743d8ae.png)

**Comment by andrew** [comment]
In the github footer the text is left and right aligned I believe

**Comment by chrisarcand** [comment]
I think there's just a maximum amount of whitespace between the logo and links on either side that you can allow before it starts to look weird.

![](http://screenshots.chrisarcand.com/i33d0.jpg)

Also Github's might look more natural given the slightly increased logo size and lighter tint.

**Comment by chrisarcand** [comment]
> In the github footer the text is left and right aligned I believe

I think you're right, given the uneven whitespace on either side of logo but both text edges are flush with the footer line.

**Comment by andrew** [comment]
Also the text could be more muted/smaller in our version, no need to draw lots of attention to it

**Comment by GiacomoLaw** [comment]
I've done a fix here: https://github.com/octobox/octobox/pull/301

Hope it helps 😄

**Comment by chrisarcand** [comment]
Fixed in https://github.com/octobox/octobox/pull/346
