### ISSUE TITLE
Differentiate unread in sidebar counts/categories

### ISSUE THREAD

**Issue by chrisarcand** [octobox/octobox#293]
I find myself constantly thinking that the counts on the different states in the sidebar are *unread* counts, clicking in to them to find that there are issues I've seen before but haven't archived (because I need to take action on them at some point):

![](http://screenshots.chrisarcand.com/permepibr.jpg)

These are unarchived counts. I'd personally find it better to just be *unread* counts, but understand that some people might really like the count of 'unarchived things that you've seen and just haven't attended to yet' In that case, any sort of other indicator that there are unread messages present in a category ("Hey look, I have some unread MENTION notification") would be good. 

Bolden the sidebar button? Maybe a change of color in the count square? Something.

**Comment by andrew** [comment]
The counts are kinda weird as they are just at the top level, not how many results you'd see if you clicked it, happy to have it how ever makes sense as long as it's not incredibly slow on the sql requests
