### ISSUE TITLE
Add Development doc

### ISSUE THREAD

**Issue by WillAbides** [octobox/octobox#300]
We should add a document for how to set up a development environment and run tests locally

**Comment by andrew** [comment]
👍  We have a few bits in https://github.com/octobox/octobox/blob/master/CONTRIBUTING.md that are related

**Comment by technicalpickles** [comment]
Here's some quick notes from setting up just now:

```
rbenv install
gem install bundler
rake db:create db:migrate
```

- register a new application at https://github.com/settings/developers with callback url of http://localhost:3000/auth/github/callback
- create a new .env with:

```
GITHUB_CLIENT_ID=some-id
GITHUB_CLIENT_SECRET=some-secret
```

Run with `rails server`

Would y'all be open to [scripts to rule them all](https://github.com/github/scripts-to-rule-them-all) for this project?

**Comment by chrisarcand** [comment]
> Would y'all be open to scripts to rule them all for this project?

I'm in favor, sure.

**Comment by andrew** [comment]
We have a [`docker-compose-dev.yml`](https://github.com/octobox/octobox/blob/master/docker-compose-dev.yml) file that has everything you need to install, we just need a markdown file that's similar to https://github.com/octobox/octobox/blob/master/INSTALLATION.md#using-docker for development specifically
