### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by johnthepink** [octobox/octobox#302]
I've been getting a lot of errors today. Pretty much every time I force a sync I got a 500 error. I will try to reproduce locally.

![unspecified-1](https://cloud.githubusercontent.com/assets/816517/22359037/a7ed7b02-e411-11e6-99e9-36935f5cbcb3.png)

**Comment by andrew** [comment]
Looks like you're hitting the rate limit, do you have a lot of other GitHub integrations hooked up to your account?

**Comment by andrew** [comment]
Fixed a particular exception that happened for the whole site if the github api wasn't happy on boot, should help reduce 500 errors going forward
