### ISSUE TITLE
Add configurator tests

### ISSUE THREAD

**Issue by chrisarcand** [octobox/octobox#303]
[Mostly a reminder to myself that] tests should be added to cover the new configurator and top level helpers from #286, as admittedly I've destroyed our code coverage %.

**Comment by WillAbides** [comment]
#304 has a configurator test in it.

**Comment by chrisarcand** [comment]
That'll improv-

![](http://screenshots.chrisarcand.com/permmmzqa.jpg)

😭 

:trollface:

**Comment by chrisarcand** [comment]
Oh it just doesn't statically find that we're utilizing the helper class. I'll tweak that while I do the rest.

**Comment by andrew** [comment]
Pretty sure this has been done
