### ISSUE TITLE
Sync Octobox's Archive action with Github's Done state

### ISSUE THREAD

**Issue by cortinico** [octobox/octobox#3036]
### What feature you'd like to see
As the title says, I'd like to have a way to mark as "done" the notifications on Github's end. What is happening instead is that, when archiving on Octobox's end, notifications are not removed by Github's inbox. They're just marked as "read".

## Motivation

This is making really hard to keep the two inboxes in sync. I have to manually go back to Github's inbox and mark as done every notification I read. 

## Pitch

I wish Octobox could fully replace Github's notification interface. But if the two are not properly in sync, it makes hard for me to really understand which notification I handled and which not.

**Comment by andrew** [comment]
I'd love for this functionality too but I don't believe github provide any kind of api to access or update "done" in their notifications, might be worth contacting them to encourage them to add that.

**Comment by naupaka** [comment]
+1 for this if it ever becomes possible

**Comment by aspiers** [comment]
This seems like a pretty huge gap.  Did anyone post a feature request to GitHub yet?  See also https://github.com/PyGithub/PyGithub/issues/1980

**Comment by andrew** [comment]
The GitHub mobile app has the ability to make notifications as done if anyone fancies attempting to reverse engineer what endpoint they use?

**Comment by aspiers** [comment]
Ooh, great point and idea!  Here are some possible techniques which could be used:

https://stackoverflow.com/questions/9555403/capturing-mobile-phone-traffic-on-wireshark

**Comment by aspiers** [comment]
Actually no need to reverse engineer the mobile app - as shown in the PyGitHub issue I linked above, there is already a beta API which https://github.com/notifications is already using.  And I bet this is what the mobile app is using too.

I have filed a request for this to be brought out of beta and documented:

https://github.com/orgs/community/discussions/50224

but in the mean time I think it would be easy to make octobox take advantage of this.

**Comment by andrew** [comment]
This can finally be implemented: https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28#mark-a-thread-as-done

**Comment by andrew** [comment]
Work in progress here: https://github.com/octobox/octobox/pull/3634

**Comment by naupaka** [comment]
🎉

**Comment by andrew** [comment]
Merged, but not yet deployed to octobox.io as I need to do a few infrastucture changes there, should be live in a couple days.

**Comment by maxshelley** [comment]
> not yet deployed to octobox.io as I need to do a few infrastucture changes there

@andrew Is this now available on octobox.io? 'Marking as done' wasn't happening for me and wanted to check before looking into it. Thank you!

**Comment by andrew** [comment]
@maxshelley no it's not live yet, had some issues with the deployment that I've not had time to fix yet, hoping to get it done by the end of the week.

**Comment by aspiers** [comment]
Any update @andrew ?
