### ISSUE TITLE
Make the sync situation clearer to users

### ISSUE THREAD

**Issue by WillAbides** [octobox/octobox#309]
It isn't entirely obvious that new notifications don't show up on page load.  We should make that clear somehow.

One possibility is to have a flash display the first time somebody loads a page with a last_synced_at over an hour old.

![2017-02-07 at 7 55 am](https://cloud.githubusercontent.com/assets/233500/22693943/ec182c12-ed0a-11e6-85f6-22cb7fdf8a00.png)

**Comment by chaserx** [comment]
How would y'all feel about putting the last synced at front and center? Something like this:

![screen shot 2018-05-28 at 8 12 03 pm](https://user-images.githubusercontent.com/7292/40632361-0dadb7be-62b4-11e8-9dd0-1ecf1db94d12.png)

**Comment by andrew** [comment]
@chaserx that sounds like a great idea, probably wants to disappear/move on mobile/small screens as space is limited 👍
