### ISSUE TITLE
Auto refresh fails when leaving a tab open

### ISSUE THREAD

**Issue by chrisarcand** [octobox/octobox#310]
I haven't looked in to how auto refresh is actually implemented, so submitting this without knowing how easy or difficult it would be to fix.

I leave a Chrome tab pinned to Octobox all the time, and I imagine other people do as well. When I leave my machine for an extended period of time, I frequently come back to this in my pinned tab:

![](http://screenshots.chrisarcand.com/permwhsw0.jpg)

This is really irritating as not only do I have to reload the page, but I can't just reload it as the url isn't the actual path required to get me to my inbox. So I frequently trim off the path and access the page again. Seems unimportant, but doing it over and over and over again gets really old.

Note also that I use my own Octobox hosted with Heroku, so maybe my dyno is falling asleep and this doesn't occur on octobox.io or other hosted scenarios that don't do that sort of thing? I would suggest we still address it if possible as I'm sure plenty of people would love to continue hosting this on their hobby tier Heroku without this issue.

**Comment by davidcelis** [comment]
This seems to be happening more frequently, in my experience. I'll have navigated away from my Octobox tab for maybe only five minutes. When I return, I'm greeted with this:

![](https://cdn.davidcel.is/screens/Screen-Shot-2017-08-30-11-31-37.png)

I can navigate back and then re-sync, but I think that something is messing up with syncing while the tab is in the background.

**Comment by andrew** [comment]
How frequently do you have it refreshing? I would guess that the heroku dyno is running out of ram and hitting swap, which slows down the sync and it ends up taking longer than 30 seconds. How much ram is available on your dyno?

**Comment by davidcelis** [comment]
Looks like we have two 2X dynos, each of which has 1GB of RAM. But you're right that RAM usage is very high, and I do see related timeouts:

![](https://cdn.davidcel.is/screens/Screen-Shot-2017-08-30-11-50-15.png)

**Comment by chrisarcand** [comment]
Yeah, I just use a single free dyno for myself and the memory usage tops out with PumaKillerWorker coming in to clean up. I've also noticed it failing more often.

**Comment by andrew** [comment]
Deployed #432, appears to have reduced the amount of time spent making http requests:

![screen shot 2017-08-30 at 9 13 04 pm](https://user-images.githubusercontent.com/1060/29892932-4d89572e-8dc8-11e7-8a9a-ee4de23f16af.png)

I'm guessing you both are running with subject syncing enabled, which I've not put into production yet so I don't have any stats around that.

**Comment by davidcelis** [comment]
@andrew Yeah, we enabled subject syncing

**Comment by chrisarcand** [comment]
So, I actually saw my window fail on refresh in this way last week. Upon immediately checking the logs I found a 503 from GitHub was the culprit. I made up a quick patch to catch these and deployed it on my box and since then haven't seen this failure at all.

I just set a flash message as my fix (which gets wiped on the next refresh) and my free dyno logs are tiny, so I actually don't have any proof that this is indeed the problem :) Chatting with @andrew to see if metrics from octobox.io might support it. 

Fingers crossed 🤞  I'll probably throw up a PR soon as catching such an error would be good to do regardless.

**Comment by davidcelis** [comment]
Unfortunately, this is still happening to me regularly 😿

**Comment by andrew** [comment]
@davidcelis you've deployed the latest changes in master?

**Comment by davidcelis** [comment]
@andrew Yeah; I deployed as soon as this PR was merged, and again a couple days later… There must be some other kind of error happening, but logs move by so fast that I haven't been able to capture it.

At this point I would probably recommend catching any Octokit error (in the 500 range, at least). I can submit a PR if that sounds like a good approach. I'm not sure where else to go without being able to see this in my logs

**Comment by andrew** [comment]
I'd suggest adding bugsnag or something similar to catch the exceptions, we're pretty much catching all of the Octokit exception apart from ones that are due to permission errors now

**Comment by chrisarcand** [comment]
Ugh. 😕

**Comment by andrew** [comment]
Possibly related to this: https://github.com/octobox/octobox/issues/458

**Comment by davidcelis** [comment]
I installed error monitoring a few days ago; any unrescued exception gets slurped up. While I've experienced the auto-refresh error page several times, our error reporting system shows no related exceptions. In fact, it shows zero exceptions that are linked to my user account. I no longer have a good idea as to what's going on here. The only thing I can think of is some sort of timeout that causes a Heroku error but not an internal application error, but I have no way to test or verify that

**Comment by chrisarcand** [comment]
@davidcelis Grep your logs for "H12" and look for something like this:

```
2017-09-28T03:08:15.118238+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/notifications/sync"
```

TIL [The Heroku router purposely cuts off requests longer than 30 seconds, sending the user to an error page and putting that error code in the logs.](https://devcenter.heroku.com/articles/request-timeout)

I found this while trying to fix our less than desirable onboarding experience for users with tons of notifications: https://github.com/octobox/octobox/pull/474 Wondering if that's also the problem here, where perhaps random syncs might be taking longer (more requests, requests going slower, whatever)

**Comment by davidcelis** [comment]
@chrisarcand Ahhh yeah it does seem like the H12 error is what I was experiencing. I experience this far less (if at all) after disabling subject syncing, tho!

**Comment by andrew** [comment]
🎉
