### ISSUE TITLE
Blockquotes without style in comments

### ISSUE THREAD

**Issue by endorama** [octobox/octobox#3118]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance
 
If your issue is related to an Octobox.io subscription purchase please ensure you have installed the [Octobox GitHub App](https://github.com/apps/octobox) for the repositories concerned.

🐞 **Problem**

Blockquotes in notifications are shown without any style, making them confusing as they are like usual paragraphs.
![Screenshot from 2022-09-07 17-57-12](https://user-images.githubusercontent.com/526307/188924675-ecc1ad41-e791-4414-a0cf-a75c5abff1dc.png)

🎯 **Goal**

Get better blockquotes!

💡 **Possible solutions**

I noticed in that there is a  `.blockquote` class
https://github.com/octobox/octobox/blob/3f2f796495786ba2c3abff04ad28a211106a26ef/app/assets/stylesheets/_application.scss#L45-L47

but is not present in the HTML output from [`parse_markdown` within a comment](https://github.com/octobox/octobox/blob/f2e30ed94683a9b1d618b38711c70a7dcf276a93/app/views/notifications/_comment.html.erb):
![Screenshot from 2022-09-07 17-59-03](https://user-images.githubusercontent.com/526307/188925015-9013b004-96b1-4586-8934-e1ac7afbdd17.png)

I don't know if it's possible to add the class, otherwise this little CSS did the trick and may be easily added:
```css
.card-body blockquote {
  margin: 0 0 1rem;
  line-height: 2rem;
  background: var(--light);
}

.card-body blockquote p {
  margin: 0;
  padding: 1rem;
}
```

Result:
![Screenshot from 2022-09-07 18-01-49](https://user-images.githubusercontent.com/526307/188925619-500e3aa2-740d-4b23-9ddc-9b0d12adcb58.png)

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

PR on the way, please let me know if this approach is ok!

**Comment by andrew** [comment]
Thanks for reporting 

I believe the html comes straight from the GitHub api so adding your css would be the easiest fix

**Comment by andrew** [comment]
@endorama I've opened a PR for the change: https://github.com/octobox/octobox/pull/3121

**Comment by endorama** [comment]
@andrew thanks!

**Comment by andrew** [comment]
Deploying the fix to octobox.io 🚀
