### ISSUE TITLE
Auto sync doesn't appear to work unless there's at least one notification in the inbox

### ISSUE THREAD

**Issue by davidcelis** [octobox/octobox#312]
I've noticed that Octobox will not attempt to automatically sync notifications, even if configured to do so, unless there is at least one notification that's visible in the inbox. If the inbox is empty, Octobox doesn't appear to ever attempt to sync. I can leave my browser after about an hour, refresh, and see "Last sync: about an hour ago". When I manually sync, I'll then get a bunch of notifications to go through.

On the other hand, if at least one notification (unread _or_ read, it makes no matter) is visible in the inbox, I'll get an automatic sync at my specified interval and receive new notifications as they come in.

**Comment by chrisarcand** [comment]
Hmmm I can't seem to recreate that. I just cleared mine out and within my interval threshold it brought in new notifications just fine.  😕 

However, that's just sitting there waiting at the screen. I have had other such annoyances with leaving it open in a tab for a long, long period of time. See also #310

**Comment by andrew** [comment]
I think this is related to https://github.com/octobox/octobox/issues/241
