### ISSUE TITLE
Lost a bunch of notifications

### ISSUE THREAD

**Issue by arthurnn** [octobox/octobox#315]
I am not sure how to simulate this again, as I was using it and it happened. 

- I had about 500+ open notifications, I could see them on github.com/notifications.
- I was triaging some open notifications, marking them as read.
- One of the teams/tabs, I selected all the notifications and clicked on the top left option where you select more notifications from the next pages.
- I clicked 'mark as read'
- Now I go to github.com/notifications and i only have about 80 open notifications.

I still can see them on, because I didn't archived them. But, I guess it was a bug on the mark-as-read option.

**Comment by andrew** [comment]
I believe that this has been fixed by https://github.com/octobox/octobox/pull/440
