### ISSUE TITLE
Hitting 'e' to archive without any selected notifications archives notification under cursor

### ISSUE THREAD

**Issue by technicalpickles** [octobox/octobox#318]
I'm not sure if this is a bug or working as expected and I need to change my expectations.

When viewing a list of notifications, I've found myself accidentally hitting `e` out of habit, except there are no notifications selected. It ends up archiving the message under the cursor.

![](https://cl.ly/1Z410L2A0T0o/Screen%20Recording%202017-02-22%20at%2012.13%20PM.gif)

My expectation is that it wouldn't archive. If you compare to gmail, there's a flash notice that no message was selected.

**Comment by tarebyte** [comment]
<img width="300" alt="screen shot 2017-02-22 at 12 32 31" src="https://cloud.githubusercontent.com/assets/564113/23224107/0d59f2ce-f8fb-11e6-8924-4d714a2e28ff.png">

It's technically working as expected @technicalpickles, you can see all of the shortcuts with the `?` key.

**Comment by technicalpickles** [comment]
Sounds like I need to change expectations then 😁  I filed https://github.com/octobox/octobox/issues/319 about the idea of way to undo for when I do accidentally archive stuff.

**Comment by chrisarcand** [comment]
> My expectation is that it wouldn't archive. If you compare to gmail, there's a flash notice that no message was selected.

Yes, the Gmail interface was the inspiration for the 'e' shortcut; I believe the 'archive the **current**/marked notification(s)' was already there, unfortunately.
