### ISSUE TITLE
Undo archival, mute, and other actions

### ISSUE THREAD

**Issue by technicalpickles** [octobox/octobox#319]
Whenever I run into https://github.com/octobox/octobox/issues/318 I've wanted to undo to get the message I accidentally archived back.

I'm not sure what this would look like implementation wise, or if it's even possible with the API.

**Comment by andrew** [comment]
I failed to search for dupes before opening https://github.com/octobox/octobox/issues/741, but it has more details there so I'm going to close this one instead.
