### ISSUE TITLE
Question: Status vs Unread

### ISSUE THREAD

**Issue by jules2689** [octobox/octobox#321]
Going through the app, I clicked "unread" in the index view. I was a bit confused at why `status=true` was what was used. Am I missing a reason why status != unread?

re: https://github.com/octobox/octobox/blob/master/app/controllers/notifications_controller.rb#L10

I can change it up to make the variable names make more sense (if I'm not missing something of course!)

**Comment by jules2689** [comment]
PR if needed https://github.com/octobox/octobox/pull/322

**Comment by andrew** [comment]
@jules2689 I don't remember why it's like that tbh, but definitely makes sense to change it to line up with the name of the db attribute 👍

**Comment by tarebyte** [comment]
#322 was merged ⚡️
