### ISSUE TITLE
Notifications don't link to the updated part

### ISSUE THREAD

**Issue by dwijnand** [octobox/octobox#323]
If I click on a notification, that I got because of a new comment on a PR/issue, I get lead to that PR/issue. I don't get lead directly to the new comment.

With GitHub's email or web notifications the link includes a fragment identifier, such as `#issuecomment-282543202`.

(For me this severely limits the utility of Omnibox, and I was surprised to not find an issue open for this already.)

**Comment by andrew** [comment]
This is also annoying for me, for now we're at the mercy of the GitHub Notifications API until https://github.com/octobox/octobox/issues/4 is implemented.

**Comment by dwijnand** [comment]
I see, GitHub's own services have access to detail you don't. Shame.

Thanks for connecting the dots for me @andrew.

**Comment by andrew** [comment]
@dwijnand on a totally separate note, would be good to pick your brains some time on adding sbt support to https://libraries.io, primarily for parsing sbt files to find the dependencies of a repository.

**Comment by dwijnand** [comment]
Feel free to ping me, elsewhere.

**Comment by andrew** [comment]
This is now fixable since #411 has been merged

**Comment by chrisarcand** [comment]
I'm currently testing an implementation of this.
