### ISSUE TITLE
Ability to reorder teams

### ISSUE THREAD

**Issue by sharwell** [octobox/octobox#328]
Currently the teams are listed in ordinal order, which for English is similar to alphabetical order except that capitalized teams are closer to the top. It would be nice if the teams could be reordered, perhaps via a drag-and-drop operation.

**Comment by hd719** [comment]
Hello I am new to Open Source and I would like to contribute to this project.

-Thank you!

**Comment by andrew** [comment]
@sharwell would case-insensitive ordering be a good halfway measure?

**Comment by sharwell** [comment]
@andrew Sure
