### ISSUE TITLE
Can't see notifications from private repos with OpenCollective subscription

### ISSUE THREAD

**Issue by aspiers** [octobox/octobox#3282]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

If your issue is related to an Octobox.io subscription purchase please ensure you have installed the [Octobox GitHub App](https://github.com/apps/octobox) for the repositories concerned.
- I have done this, and also tried reinstalling the app for that organization. 

### Summary of Problem

- What are you trying to do?
  - Use Octobox on my work organization's private repos 
- What happens?
  - They don't show up.  I can only see notifications from my work organization's public repos.
- What should have happened?
  - I should see both public and private notifications.

### Steps to Reproduce the Issue

1. Install the app on my work organization in GitHub (perhaps the problem is that I did this *before* setting up the subscription not after?)
2. Set up a $10 subscription on OpenCollective
3. Resync
4. Observe no private repo notifications from work organization
5. Try to reconfigure Octobox's access to work repos:
   ![image](https://user-images.githubusercontent.com/100738/225628977-dfbea50c-2444-48f0-b165-64ec0b235a48.png)
6. Hit the Save button
7. View an error:
   ![image](https://user-images.githubusercontent.com/100738/225629064-809e84ba-2583-44a1-8eec-9b5ee2a83dc2.png)
8. Repeat steps 3-7 with various different configurations:

   - Access to only one private repo in the org
   - Access to all repos in the org
   - Uninstalling the app and then reinstalling

   None of these helped :-( 

### Versions, Operating System and Hardware

- Which version/commit of Octobox are you using?
  - Whatever's on https://octobox.io/
- Which browser are you accessing Octobox with?
  - Chrome Version 110.0.5481.96 (Official Build) (64-bit)
- Windows? Linux? Mac?
  - Linux (openSUSE Tumbleweed)
- How are you deploying Octobox (Docker, Heroku, Openshift, etc)
  - Using https://octobox.io/

**Comment by aspiers** [comment]
Thanks!

**Comment by andrew** [comment]
@aspiers can you try following this line: http://octobox.io/auth/githubapp, it should no longer error for you

**Comment by aspiers** [comment]
Can confirm this URL doesn't error; still can't see private repos though.

**Comment by andrew** [comment]
@aspiers just want to make sure, are those notifications from Discussions? As those are not supported (Github doesn't make notifications about Discussions available in the API)

**Comment by aspiers** [comment]
No they're notifications about PRs.

> And does the org show up with a green tick here: [github.com/settings/connections/applications/3ab10eeb090c850faa7f](https://github.com/settings/connections/applications/3ab10eeb090c850faa7f)

Ahah!  No, but I've granted it now.

> and in this list: [github.com/organizations/ToucanProtocol/settings/oauth_application_policy](https://github.com/organizations/ToucanProtocol/settings/oauth_application_policy)

Yes that one was correct.

Still can't see private notifications though.

**Comment by aspiers** [comment]
OK now I see the ToucanProtocol organization in my settings, and I see no plan set for that even though I have a personal plan.  Does that mean I need a separate subscription for every org with private repos?  I don't need a personal plan since I don't need notifications for my personal private repos, only for the ToucanProtocol ones.

**Comment by aspiers** [comment]
Also I notice the "Install GitHub App" button at the top-right is now no longer visible, which is good.  Not sure what caused it to vanish though.

**Comment by aspiers** [comment]
Logging out and in again worked!  Thanks so much!!

**Comment by andrew** [comment]
No worries, sorry for all that confusion, unfortunately GitHub haven't made any changes to the notifications api in years so it's tricky connecting all the dots!

**Comment by andrew** [comment]
Ok to close this now?

**Comment by aspiers** [comment]
Yep!
