### ISSUE TITLE
Inconsistent tooltips on small screen

### ISSUE THREAD

**Issue by gep13** [octobox/octobox#330]
I have just docked my browser to the right hand side of my screen, and selected an item:

![image](https://cloud.githubusercontent.com/assets/1271146/23954437/3189e128-098f-11e7-9d13-296073de3db6.png)

In this size screen, I wasn't sure which icon was which, as I normally see the text.  So I hovered over one of the buttons and there was no tooltip.  I hovered over another button and there was a tooltip:

![image](https://cloud.githubusercontent.com/assets/1271146/23954498/57089e44-098f-11e7-85b4-638fbeaed61e.png)

I think that this should be consistent, one way or the other.  My vote would be to include them.

**Comment by gep13** [comment]
Sweet! Thanks for fixing this!

@andrew quick question...  I have Octobox running as a docker image on my Synology Home Server.  What do I need to do in order to bring down the latest changes?  Thanks!

**Comment by andrew** [comment]
@gep13 I'm not a Docker user myself but it looks like you can use `docker pull octoboxio/octobox`

**Comment by gep13** [comment]
@andrew thanks, I will give it a try :+1:
