### ISSUE TITLE
Filter repo count indicators on read and type. 

### ISSUE THREAD

**Issue by jamielennox** [octobox/octobox#333]
Hi,

So far i'm loving the project - thanks for your efforts. 

I get a fairly high volume of traffic from a limited number of projects which means that i occassionally miss something from smaller ones. 

In the left column where my repos are listed they have a number indicating the number of items in that project that are linked to me. What I would like to see is if i press the unread and pull request filters that number change to only show me the number of unread PRs related to that project - not just the number of entries in that folder.

Currently I use a filter like unread PRs and then see a 3 besides a low traffic repo and have to actually click the link to get the nothing to see here message which ideally i could see at a glance.

**Comment by jamielennox** [comment]
Actually thinking about it, that number could reasonably be changed to always show an unread count. I don't care that i have 200 things in that folder i've dealt with. I care that there are 2 things I have to do.

**Comment by chrisarcand** [comment]
Dupe of https://github.com/octobox/octobox/issues/293

**Comment by jamielennox** [comment]
Ah, I did look and didn't spot it. 

Closing as it's an exact duplicate.
