### ISSUE TITLE
Remember login

### ISSUE THREAD

**Issue by acrobat** [octobox/octobox#334]
It would be cool if octobox could remember that you were logged in. It's no huge effort to click the github login button each time but if it would remember I was logged in that would be even better :)

Great work by the way! :tada:

**Comment by chrisarcand** [comment]
🤔 Is this on octobox.io? I have not had this issue on my own hosted service at all.

**Comment by acrobat** [comment]
Yes on octobox.io!

**Comment by chrisarcand** [comment]
Have to toss this off to @andrew then :) 👐

**Comment by andrew** [comment]
There's no difference in between octobox.io and everyone else around the session, I suspect we need to increase the expires timestamp on the session cookie

**Comment by chrisarcand** [comment]
Hmm odd then, I've left it for days and haven't had it expire. Will stop jabbering before looking at the code now ;)

**Comment by acrobat** [comment]
Isn't the problem the cookie is a session cookie? So the browser will "forget" it after the browser is closed? https://en.wikipedia.org/wiki/HTTP_cookie#Session_cookie

**Comment by andrew** [comment]
@acrobat just shipped #364 which fixes this :shipit:

**Comment by acrobat** [comment]
Thanks @andrew I will check it!

**Comment by acrobat** [comment]
@andrew logout doesn't seem to work anymore, maybe because the user_id cookie is not deleted on logout?

**Comment by andrew** [comment]
@acrobat pr in progress here: https://github.com/octobox/octobox/pull/369
