### ISSUE TITLE
what does "mute" and "archive" mean?

### ISSUE THREAD

**Issue by sam-github** [octobox/octobox#335]
This shouuld be documented in the README, since they have no github equivalents the terms aren't meaningful without some description.

I thought Muted meant Unsubscribed, but PRs I've unsubscribed from are still showing up in Unread, so what does it mean?

I haven't started experimenting to see what Archive means yet, I'd appreciate it if someone could tell me to make my octobox evaluation a bit faster.

**Comment by chrisarcand** [comment]
Muting an unread notification in your inbox should mark it as read, archive it, and unsubscribe you from the Github issue as you expect. Note that if something in Github that would trigger you to receive another notification from the muted thread (ie, a mention, etc) it'll behave as normal and show up in your unread inbox again. If you aren't experiencing what I've just gone over, it's a bug and I'd love to hear more details about it. 

Archiving, solely an Octobox feature (no equivalent Github feature attached to it), is best explained by the README: 

> Octobox adds an extra "archived" state to each notification so you can mark it as "done". If new activity happens on the thread/issue/pr, the next time you sync the app the relevant item will be unarchived and moved back into your inbox.

Does that help?

**Comment by andrew** [comment]
Mute should match the mute function on https://github.com/notifications, Archive is similar to Gmail's archive, essentially means "done" where GitHub has no concept of that on their end.

**Comment by chrisarcand** [comment]
Closing this, as it's an open question that's getting old. @sam-github please feel free to reopen if that doesn't answer your question. Thanks!

**Comment by pdecat** [comment]
> Archive is similar to Gmail's archive, essentially means "done" where GitHub has no concept of that on their end.

Now that Github Notifications has a "done" concept, could it be synced with octobox's "archive" concept?

See https://github.blog/2019-11-13-universe-day-one/#notifications
and https://github.com/notifications?query=is%3Adone
