### ISSUE TITLE
[Feature request]  "Releases" view

### ISSUE THREAD

**Issue by jmreicha** [octobox/octobox#342]
I just discovered this project and I'm really loving it so far, I've been looking for something like this for awhile.

Are there any plans around adding a way to view versions and release notes updates for a given project?  It would be really nice to be able to quickly see new versions and changes for various projects that have been starred.

**Comment by arcticicestudio** [comment]
A *Releases* filter already exists. It shows new tags if you've set the notifications level of a repository to *Watching* to receive all kind of project activities (new issues, releases and PRs).
![ghi-342-scrot-release-filter](https://cloud.githubusercontent.com/assets/7836623/25199092/ec356724-2549-11e7-8cfa-830be46af5c7.png)

**Comment by jmreicha** [comment]
@arcticicestudio Thanks that's useful.

I think this approach will be very spammy for larger projects where I would only be interested in tracking releases and not other activities.  Do you know if there is a way to handle that type of scenario?

**Comment by arcticicestudio** [comment]
Unfortunately GitHub currently does not provide a feature to let the user choose which types of repository activieties they want to be notified for. If you'd like to only see new versions you should just let the *Release* enabled and ignore everything else. Just go ahead like once a month and mute all other notifications to clean up your inbox.

**Comment by chrisarcand** [comment]
👍 I like this idea; I also find myself wanting to be notified on releases even while I'm not interested in the day-to-day of a project.

Perhaps with a org/repo "options" screen in Settings we could have checkbox option for 'Releases only' (To start; I guess theoretically we could generalize that beyond releases too)

**Comment by andrew** [comment]
Perhaps it's a good time to implement filters? https://github.com/octobox/octobox/issues/8

**Comment by andrew** [comment]
I'm going to close this for now as I can't see us doing it in the short term, but if anyone really wants it and is willing to have a go at implementing it then drop a comment and we'll open it back up.
