### ISSUE TITLE
Search should show results that match the Inbox and Archive

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#351]
![screen shot 2017-05-04 at 10 27 48 pm](https://cloud.githubusercontent.com/assets/1060/25725671/04f9dd82-3119-11e7-8f8d-c7efd5dabd09.png)

Confused myself earlier, searched for "puma" and didn't get any results, turns out it was because I had archived all the puma notifications, we should probably default to searching everything, perhaps with archived things last?

**Comment by samjacobclift** [comment]
https://github.com/octobox/octobox/pull/361
