### ISSUE TITLE
Reduce docker image size

### ISSUE THREAD

**Issue by thiesschneider** [octobox/octobox#355]
Hi,

would it be possible to reduce the docker image size?
At the moment its 843MB.

Thx!

**Comment by andrew** [comment]
@thiesschneider any tips on how to do that, I'm not very experienced with docker

**Comment by kkostov** [comment]
It may be possible to reduce the overall image size by opting for a different base ruby image variant. For Example here: https://hub.docker.com/_/ruby/ we can see a recommendation to use ruby:alpine when final image size is important:

> This image is based on the popular Alpine Linux project, available in the alpine official image. Alpine Linux is much smaller than most distribution base images (~5MB), and thus leads to much slimmer images in general.

> This variant is highly recommended when final image size being as small as possible is desired. The main caveat to note is that it does use musl libc instead of glibc and friends, so certain software might run into issues depending on the depth of their libc requirements. However, most software doesn't have an issue with this, so this variant is usually a very safe choice. See this Hacker News comment thread for more discussion of the issues that might arise and some pro/con comparisons of using Alpine-based images.

> To minimize image size, it's uncommon for additional related tools (such as git or bash) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the alpine image description for examples of how to install packages if you are unfamiliar).



I haven't tried it though.

**Comment by thiesschneider** [comment]
It should be built on ruby:alpine (or perhaps ruby:slim) I think. 
But I am also not that experienced :)

**Comment by andrew** [comment]
@thiesschneider have got a branch that uses ruby:2.4.1-alpine over here: https://github.com/octobox/octobox/pull/357

**Comment by thiesschneider** [comment]
Did you push it to docker hub? Can I use it as a tag?
e.g. `octoboxio/octobox:alpine`

**Comment by andrew** [comment]
@thiesschneider yeah it's pushed there automatically, looks like the build failed though, missing the postgresql-dev package, will push a new build in just a minute.

**Comment by andrew** [comment]
@thiesschneider that's pushed on the alpine tag, reduces the build size to 466mb

Suspect it can be reduced further with alpine-postgres but not sure if that means people will lose data if they update their image and the database docker changes?

**Comment by thiesschneider** [comment]
The postgres container is separated from the image. So I think you have to make "netcat nodejs" smaller?! ;)
Thx so far!

**Comment by andrew** [comment]
@thiesschneider opened one more pr to make a small tweak: https://github.com/octobox/octobox/issues/355

Dockerhub is showing it at 150mb now: https://hub.docker.com/r/octoboxio/octobox/tags/

Breakdown of the layers here: https://microbadger.com/images/octoboxio/octobox

I think we can save a few more megabytes by deleting some of the apk packages after bundle installing (build-base, git, postgresql-dev) but that might mean putting almost the commands into one line, not sure if that's a bad thing?
