### ISSUE TITLE
Update the screenshot

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#360]
Now that we have the new black header we should update the screenshot in the readme and on the homepage, I've taken a new one: 

![screen shot 2017-05-09 at 11 04 45 am](https://cloud.githubusercontent.com/assets/1060/25845986/feeca52c-34a7-11e7-82cf-d9b64546e4f6.png)

url: https://cloud.githubusercontent.com/assets/1060/25845986/feeca52c-34a7-11e7-82cf-d9b64546e4f6.png

Just needs to be updated in the [readme](https://github.com/octobox/octobox/blob/master/README.md) and replace [screenshot.png](https://github.com/octobox/octobox/blob/master/app/assets/images/screenshot.png)

**Comment by PandelisZ** [comment]
Okay! I shall take this one on. 

I've noticed there is also a screenshot on the homepage before login so I'll also replace that
