### ISSUE TITLE
Getting "ActiveModel::RangeError in NotificationsController#sync " errors

### ISSUE THREAD

**Issue by joaopgrassi** [octobox/octobox#3612]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

If your issue is related to an Octobox.io subscription purchase please ensure you have installed the [Octobox GitHub App](https://github.com/apps/octobox) for the repositories concerned.

### Summary of Problem

(Please answer all 3)

- What are you trying to do?
Refresh the page or trigger sync manually

- What happens?
I get a error page "ActiveModel::RangeError in NotificationsController#sync "

```
2148162568 is out of range for ActiveModel::Type::Integer with limit 4 bytes

  def sync(remote_subject)
    update({
      repository_full_name: extract_full_name_from_remote_subject(remote_subject),
      github_id: remote_subject['id'],
      state: remote_subject['merged_at'].present? ? 'merged' : remote_subject['state'],

Rails.root: /usr/src/app

Application Trace | Framework Trace | Full Trace
app/models/subject.rb:48:in `sync'
app/models/subject.rb:75:in `sync'
lib/octobox/notifications/sync_subject.rb:25:in `update_subject_in_foreground'
app/workers/update_subject_worker.rb:8:in `perform'
config/initializers/custom_sidekiq_worker.rb:9:in `perform_async_if_configured'
lib/octobox/notifications/sync_subject.rb:14:in `update_subject'
app/models/notification.rb:160:in `update_from_api_response'
app/services/download_service.rb:65:in `block in process_notifications'
app/services/download_service.rb:60:in `each'
app/services/download_service.rb:60:in `process_notifications'
app/services/download_service.rb:47:in `fetch_new_notifications'
app/services/download_service.rb:26:in `download'
app/models/user.rb:88:in `sync_notifications_in_foreground'
app/controllers/notifications_controller.rb:139:in `sync' 
```

- What should have happened?

No errors when syncing 

### Steps to Reproduce the Issue

Not sure exactly, I subscribe to several repos and sometimes this is happening. I didn't upgrade the version or anything. 

### Versions, Operating System and Hardware

- Which version/commit of Octobox are you using?
Docker image [january-2024](https://hub.docker.com/layers/octoboxio/octobox/january-2024/images/sha256-dd52d695869eae1e2bc581ec765da752b43f7dc23e75a277a7d8d3cc868f5cc0?context=explore)

- Which browser are you accessing Octobo with?
Firefox 122.0.1

- Windows? Linux? Mac?
 Windows
 
- How are you deploying Octobox (Docker, Heroku, Openshift, etc)
Docker

**Comment by andrew** [comment]
I fixed it in https://github.com/octobox/octobox/commit/202d5f64a395b7eb6ba0e72cf8e0b189a3c48d46 last night, would you like me to publish a new docker image?

**Comment by joaopgrassi** [comment]
Wow nice! Yeah if that is not a hassle, it would be great! Thanks for the great work!

**Comment by andrew** [comment]
@joaopgrassi here it is: https://hub.docker.com/layers/octoboxio/octobox/range-error-fix/images/sha256-5ec962119ea0c1f5e611d72a7febccef614cd235286f3acf73ac52fdada05824?context=explore

**Comment by joaopgrassi** [comment]
Seems to work now! Thanks for the quick fix
