### ISSUE TITLE
background jobs don't work with the provided `docker-compose.yml` for multiple reasons

### ISSUE THREAD

**Issue by dljsjr** [octobox/octobox#3632]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**
Sidekiq background jobs don't currently work with the given example docker-compose file.

The main issue is that `octobox:latest` is baking Rails 7/Sidekiq 7 in to the image, which require Redis 6+.

But upgrading to Redis 6+ has more stringent typing constraints on boolean values. This is fixed in Sidekiq itself with the versions being used, but the version of `sidekiq-uniquejobs` pinned in the Gemfile is too old. It runs in to this: https://github.com/mhenrixon/sidekiq-unique-jobs/issues/816

It was fixed here: https://github.com/mhenrixon/sidekiq-unique-jobs/pull/815

Git hash `https://github.com/mhenrixon/sidekiq-unique-jobs/commit/b31e80bc5542188573614adfa77a834a7268ccdf` in the Gemfile is way behind that PR.

🎯 **Goal**
Background jobs don't work with the given collection of dependencies.

💡 **Possible solutions**
Put an upper bound on Sidekiq to make it use an older version, or use a newer sidekiq-unique-jobs

📋  **Steps to solve the problem**
https://github.com/octobox/octobox/pull/3631

**Comment by andrew** [comment]
Thanks for the PR, I've merged that now and updated sidekiq-unique-jobs to the latest
