### ISSUE TITLE
Duplicated items when searching with multiple labels 

### ISSUE THREAD

**Issue by legendecas** [octobox/octobox#3664]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [x] My instance
 
🐞 **Problem**

If an issue or a pull request is labeled with multiple labels, like "foo" and "bar", searching in octobox with the query "label:foo,bar" resulted in showing the item twice.

🎯 **Goal**

Only show matched items once even if they are matched with multiple labels.

**Comment by andrew** [comment]
Thanks for reporting, this is most likely an issue with the sql query which could come from the label scope here: https://github.com/octobox/octobox/blob/master/lib/octobox/notifications/inclusive_scope.rb#L67-L74
