### ISSUE TITLE
How to enable periodic notification refreshes in docker?

### ISSUE THREAD

**Issue by wasgehthierab** [octobox/octobox#374]
Hi there,

it seems that periodic notification refreshes are not working with docker.
I added `-e MINIMUM_REFERSH_INTERVAL=15 \` but this does not work.
There are also no settings. So I cant modify 'Notification Refresh Interval'.

Any ideas?

thx!

**Comment by thiesschneider** [comment]
Would be interesting for me also.

**Comment by karuppiah7890** [comment]
@wasgehthierab How did you set it ? You need to include the environment variable in the [docker-compose.yml file](https://github.com/octobox/octobox/blob/master/docker-compose.yml)

**Comment by wasgehthierab** [comment]
Thx for the answer!
I use systemd in coreos and added it in the docker command:

```
ExecStart=/usr/bin/docker run \
    -e OCTOBOX_DATABASE_HOST=database.service.octobox.internal \
    -e OCTOBOX_DATABASEstuff.... \
    -e MINIMUM_REFERSH_INTERVAL=15 \
    -e RAILS_ENV=development \
    -e RESTRICTED_ACCESS_ENABLED=1 \
    octoboxio/octobox:latest \
    ./bin/docker-start
```

do you have any suggestions? :)

**Comment by karuppiah7890** [comment]
@wasgehthierab I just noticed the issue, it's not a docker problem. You have tried to set it right, and that's how it is set when using the `docker run` command, yes. But you misspelled the word "refresh" as "refersh". Change that and you should see it working. And only after this is set, you will see the settings for it in the app from what I read here : https://github.com/octobox/octobox/blob/master/INSTALLATION.md#allowing-periodic-notification-refreshes

@thiesschneider What was your issue ?

**Comment by thiesschneider** [comment]
I fixed it. You can close it

**Comment by chrisarcand** [comment]
Thanks @karuppiah7890 ! Feel free to reopen if you're still having issues @wasgehthierab
