### ISSUE TITLE
Shift-click to select range

### ISSUE THREAD

**Issue by whit537** [octobox/octobox#375]
I'd like to click to select one item, and then click to select another, non-adjacent item, and thereby select the range (inclusive) bounded by the two items. Currently it only selects the two single items.

![n8dzxfzvso](https://cloud.githubusercontent.com/assets/134455/26359295/147f5cf8-3fa3-11e7-82e7-7262384ba3b8.gif)

**Comment by whit537** [comment]
Desired behavior (from GitHub):

![ueosaa603h](https://cloud.githubusercontent.com/assets/134455/26359689/20e7149e-3fa4-11e7-8976-d58ea8fd03b8.gif)

**Comment by andrew** [comment]
Sounds good to me 👍

**Comment by samjacobclift** [comment]
little PR here https://github.com/octobox/octobox/pull/383
