### ISSUE TITLE
Indicate total number of items

### ISSUE THREAD

**Issue by whit537** [octobox/octobox#376]
I don't see any indication of the total number of items. I end up having to add "Read" and "Unread." Perhaps "Inbox" could have the total number next to it?

![screen shot 2017-05-23 at 10 33 56 am](https://cloud.githubusercontent.com/assets/134455/26359416/67586a46-3fa3-11e7-8393-54f6abac8b27.png)

**Comment by andrew** [comment]
Sounds reasonable!

**Comment by andrew** [comment]
🚢
