### ISSUE TITLE
"unread" pane disappears when i have no unreads

### ISSUE THREAD

**Issue by ljharb** [octobox/octobox#377]
I want https://octobox.io/?unread=true to be my homepage, and I really almost never want to look at any other page. However, the instant I achieve my goal of Notification Zero, it disappears from the left nav, and clicking "refreshing" dumps me on the inbox.

Can this just permanently stick around?

**Comment by chrisarcand** [comment]
> and clicking "refreshing" dumps me on the inbox.

I can't confirm this bit; if you have the querystring in the url and hit refresh, it respects that for me. However, it does make the sidebar button disappear (intentionally - there are no unreads anymore).

> I want https://octobox.io/?unread=true to be my homepage, and I really almost never want to look at any other page

I've actually had this in the back of my mind for a while - it might be very useful to have a way to 'pin' sidebar buttons if you find one particularly useful. I, too, have a preferred set of notifications I want to *always* have selected, even if there aren't any currently; for example, when I'm working during the day I only want to see notifications for my work organization.

**Comment by andrew** [comment]
👍 currently just groups by the data that's available, read/unread would be easy to add as fixed items to the sidebar

**Comment by andrew** [comment]
@chrisarcand first step towards "pinned" searches in the sidebar here: https://github.com/octobox/octobox/issues/742

Still a relevant issue here so not going to close this yet.

**Comment by andrew** [comment]
Opened up a PR to keep the read/unread sidebar menu items there all the time: https://github.com/octobox/octobox/pull/745
