### ISSUE TITLE
"Mark as unread"?

### ISSUE THREAD

**Issue by ljharb** [octobox/octobox#379]
I realize Github doesn't offer a "mark as unread" - but I thought it was worth bringing up. Is this something we could get added to the API, even if they don't want it on the website?

**Comment by andrew** [comment]
Yeah it's worth requesting it with the GitHub support/API teams, I think they are currently working on some changes/updates to notifications internally at the moment

**Comment by laughedelic** [comment]
I think Github has "Mark as unread" button from quite some time ago..

<img width="183" alt="screen shot 2017-09-06 at 15 25 56" src="https://user-images.githubusercontent.com/766656/30114288-b4217f6c-9317-11e7-9f0d-f236429d3ae6.png">

**Comment by tarebyte** [comment]
@laughedelic that's definitely not a GitHub feature, are you sure you're not running some kind of Chrome plugin?

**Comment by laughedelic** [comment]
Right. Sorry, this if from the [Refined Github](https://github.com/sindresorhus/refined-github) extension 😟

**Comment by andrew** [comment]
Going to close this one as I don't think it's possible via the API at the moment
