### ISSUE TITLE
octobox and github have different ideas of unread

### ISSUE THREAD

**Issue by sam-github** [octobox/octobox#386]
![github-unread](https://cloud.githubusercontent.com/assets/17607/26736836/90661a92-477c-11e7-8721-c3821bd2197a.png)
![gmail-unread](https://cloud.githubusercontent.com/assets/17607/26736837/906a3afa-477c-11e7-9bd1-84a5726d61d5.png)
![octobox-unread](https://cloud.githubusercontent.com/assets/17607/26736838/9074b0b6-477c-11e7-9ca2-f2af10af9c1c.png)

So, gmail shows the thing that are unread, and that I would like to mute. I was hoping in octobox to see at least the issues that I know are unread because I just got mail notifications for them, and don't want to read, or see again unless I'm mentioned.

But octobox doesn't show those issues as unread, it shows a different much smaller list. What I would expect it to show me is the list of ones currently unread in gmail, plus all the issues in the past that I didn't read in gmail, and just deleted. But, it doesn't do that, you can see there are 1000s of those from the screenshot of github notifications.

Is this a bug, a limitation, or a misunderstanding on my part of what octobox considers unread?

**Comment by andrew** [comment]
That looks like a bug, or at least missing data, are you using the hosted http://octobox.io or running your own instance?

**Comment by sam-github** [comment]
Hosted. I just tried local, but even though I've got ubuntu and docker, I couldn't figure out how to make the docker-compose command work. I tried running it in a git checkout of octobox, and standalone. I don't see how it is supposed to know to run an octobox image.

**Comment by sam-github** [comment]
I just revoked and re-authed to see if it was a permissions problem, and perhaps it is:

![auth](https://cloud.githubusercontent.com/assets/17607/26739005/13cb223a-4785-11e7-8113-ce3e4139c113.png)

I suspect that red X may be  the problem, any suggestions?

**Comment by andrew** [comment]
@sam-github yeah it looks like the nodejs org doesn't allow https://octobox.io to access your notifications for their repos.

Have you followed the install guide for Docker: https://github.com/octobox/octobox/blob/master/INSTALLATION.md#using-docker

If so do you have a terminal log of the commands and output when you run the docker-compose command? (make sure to scrub the auth tokens before posting here)

**Comment by sam-github** [comment]
```
s/octobox (master u=) % docker-compose up --build
Builds, (re)creates, starts, and attaches to containers for a service.

Unless they are already running, this command also starts any linked services.
... etc, etc
s/octobox (master u=) % docker-compose --version
docker-compose version 1.5.2, build unknown
```

**Comment by andrew** [comment]
@sam-github are you still having issues with this?

**Comment by sam-github** [comment]
> yeah it looks like the nodejs org doesn't allow https://octobox.io to access your notifications for their repos.

Didn't try, the above makes octobox unworkable for me, fine to close.
