### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by ignacio-chiazzo** [octobox/octobox#387]
Would be good to implement the "Drag and Drop" in the section "Repos".

**Comment by andrew** [comment]
@ignacio-chiazzo we don't store the order of the repos at the moment, they are just ordered alphabetically based on the notifications that have got in you inbox, would need to start persisting repo names to a table if we wanted to make that feature possible.

**Comment by andrew** [comment]
Going to close this for now as I can't see us doing it in the short term, but if anyone really wants it and is willing to have a go at implementing it then drop a comment and we'll open it back up.
