### ISSUE TITLE
notifications for private repositories?

### ISSUE THREAD

**Issue by cyberhck** [octobox/octobox#389]
I tried updating personal_access_token in `users` table, and ran a sync, which didn't show me any private notifications, but when I send a GET request to `api.github.com/notifications` with my `personal_access_token` it gives me results. But when I sync it from octobox, it doesn't show anything.

Is there a limitation on this?

**Comment by cyberhck** [comment]
edit: even though I have a cron running, it doesn't sync new data from github BUT, if I manually click sync, it does the trick. Why isn't cron not working? (I do know that it's actually running ` rake tasks:sync_notifications`)

But no new data is available.

**Comment by andrew** [comment]
@cyberhck Did you have any luck with this?

**Comment by cyberhck** [comment]
yes, sorry I didn't update it. No matter how hard I tried it didn't work, so I tried to docker exec into database, select * from users revealed my column and I went to github, created a token, then set that token to two columns (because I wasn't sure which one), personal access token and one more you'll know. Let me know if you find something :)

**Comment by andrew** [comment]
@cyberhck did running the rake task output anything?

**Comment by cyberhck** [comment]
I just did it again, it didn't output anything, (maybe because I don't have any new notifications?), I'll try again in a while when I do have notifications and will notify you :)

**Comment by cyberhck** [comment]
@andrew if you want, I can help you do a quick setup, I'm already using octobox with docker and it's working quite good :)

**Comment by cyberhck** [comment]
I did try again since I just got a notification, it didn't output anything. But if I click on refresh, it does output bunch of stuff on my docker stdout.

**Comment by andrew** [comment]
@cyberhck did you get this working in the end?

**Comment by cyberhck** [comment]
Yes, I'm using octobox locally in docker, and it's GREAT! Loving it.

**Comment by cyberhck** [comment]
But it's not the way it's recommended in readme, so maybe we'll have to verify if it's working properly.
I'll try to verify once again during this weekend and see if official way still works, and I'll send a PR if info is not enough.

**Comment by cyberhck** [comment]
this is working for me at least the way I've configured, so I'll close this issue for now, if someone else encounters it, they can reopen
