### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by maxime1992** [octobox/octobox#393]
I've been using octobox for month now and I'm pretty sure I didn't have that layout before : 
![octobox-bug](https://user-images.githubusercontent.com/4950209/27024032-5af19cd4-4f55-11e7-9a3b-341dcc62e7bd.png)
(end of the screen capture here)

I do have a vertical screen and it seems that now, the layout only takes the required space vertically which is really weird :)

**Comment by andrew** [comment]
I'm pretty sure this was caused by my pull request yesterday: https://github.com/octobox/octobox/pull/391, I'll revert it for now

**Comment by andrew** [comment]
@maxime1992 out of interest, is that on windows or do you have a mouse with a scrollwheel?

**Comment by andrew** [comment]
Deployed that revert

**Comment by maxime1992** [comment]
@andrew Ubuntu 17.04 and yes I do have a mouse with scrollwheel but ... I don't see why you're asking me that :D ?

(everything's back to normal :tada: thx!)

**Comment by andrew** [comment]
@maxime1992 having a scrollwheel mouse attached on the mac makes scrollbars appear all the time, where they hide if you have a trackpad/magicmouse

**Comment by maxime1992** [comment]
Never had a mac, thanks for clarification :)
So here on ubuntu no matter if my mouse is connected or not it was always here :)
:clap: for reverting and fixing that so quickly
