### ISSUE TITLE
Individual notifications for activity within pull request/issue

### ISSUE THREAD

**Issue by OliverJAsh** [octobox/octobox#397]
When I receive multiple comments on a pull request, I would like to have a notification for each one so I don't forget to view/reply to all.

When there is only one notification to signify "activity" on a pull request, it is easy to miss a comment, especially if it was a reply to a thread in code review where that code has since been collapsed.

Is this something Octobox can achieve, or does it need more work from GitHub?

**Comment by andrew** [comment]
@OliverJAsh Notifications from the GitHub API are a pointer to the last activity on a thread (kinda like HEAD in git), so we can't that extra information at the moment, making it difficult enough that this will probably won't be doable.

**Comment by laughedelic** [comment]
I'm not sure, but I think you could query the newsfeed/dashboard activity. It would be nice to have threads of notifications in octobox. Somewhat similar to how this extension groups activity on the dashboard: https://github.com/bfred-it/github-clean-feed
