### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by torfsen** [octobox/octobox#398]
This looks like a great tool, but it's not directly clear to me how to use it. For example, what do *archive* and *mute* do? It would be really nice to have some kind of (minimal) user documentation. This could, for example, be part of the existing keyboard shortcuts popup.

**Comment by chrisarcand** [comment]
True, beyond the [info in the README](https://github.com/octobox/octobox#why-is-this-a-thing) there's little explanation, and a link to either a Github Wiki or a help page in Settings or something to go over these details might be nice.

**Comment by salman-bhai** [comment]
Is this Issue taken up by someone or open to PRs?

**Comment by chrisarcand** [comment]
@salman-bhai Not being worked on that I know, PRs are most certainly welcome! 💙

**Comment by salman-bhai** [comment]
Sure not a problem! Is there any particular that you want the README to be or any partivular sections/format to be added/used for the README!

**Comment by salman-bhai** [comment]
Also @chrisarcand @torfsen where should the Documentation be added! Any particular file or folder that you're looking at?

**Comment by chrisarcand** [comment]
@andrew might want to weigh in here but I would imagine a user guide similar to [how the install guide works](https://github.com/octobox/octobox#install) (just a separate markdown file linked in the README) would be fine.

**Comment by salman-bhai** [comment]
Alright will wait for @andrew 's reply and then probably start working on this!

**Comment by andrew** [comment]
@salman-bhai A separate markdown file sounds good to me, we can link to it from the readme and possibly the menu for logged in users too 👍

**Comment by salman-bhai** [comment]
Cool I'll make a base files and then we can add further documentation to it

**Comment by andrew** [comment]
🚢 by @BenJam https://octobox.io/documentation
