### ISSUE TITLE
Visual feedback for non-instant actions

### ISSUE THREAD

**Issue by torfsen** [octobox/octobox#401]
Some actions (in particular marking multiple messages as read) take a noticeable time to perform. That's not a problem in itself, but I'd love to get some visual feedback that something is happening. Something like a different cursor or a small animation on the affected messages. Otherwise I'm always wondering whether I pressed the wrong keyboard shortcut because (so it seems) nothing is happening.

**Comment by andrew** [comment]
@torfsen agreed, an animation would definitely help to make it clear what, if anything, is going on.

**Comment by radvc** [comment]
we should close this issue

**Comment by chrisarcand** [comment]
@radvc Thanks!
