### ISSUE TITLE
uninitialized constant DownloadService::PageLimitingOctokitClient

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#404]
![img_5015](https://user-images.githubusercontent.com/1060/28582875-087969a8-7135-11e7-92d4-0dde5208f760.PNG)

Only just deployed recent changes, this seems to happen in production

**Comment by chrisarcand** [comment]
Hmmm maybe something having to do with the production autoloading that I missed (My changes made it so it should autoload `/lib/page_limiting_octokit_client.rb`, `::PageLimitingOctokitClient`. Maybe roll back changes on octobox.io and I'll look at it soon.

**Comment by chrisarcand** [comment]
> something having to do with the production autoloading that I missed

Yuuup. 😄
