### ISSUE TITLE
Marking last item read causes focus to be lost

### ISSUE THREAD

**Issue by kynan** [octobox/octobox#416]
When "clearing" the last item in the main list view e.g. marking it as read does not move the focus to the previous second-to-last and now last item. Instead the focus is "lost" and it's no longer possible to use the keyboard to navigate.

**Comment by chrisarcand** [comment]
@kynan Which browser are you using? I can't recreate this, everything seems to work as expected, both archiving or just marking as read.

**Comment by kynan** [comment]
Fails for me consistently on Firefox, Chrome and Chromium. My normal "use case" is applying a filter e.g. for a given repo and then when I first open and archive the last item in the list I hit this.

**Comment by andrew** [comment]
I can't replicate this either, @kynan would you be able to record a gif of the steps you're taking with https://www.cockos.com/licecap

**Comment by kynan** [comment]
That tool seems to be OSX or Win only :(

**Comment by kynan** [comment]
Turns out peek doesn't work with i3, so I had to temporarily switch to a compositing window manager.

So this shows the issue:
![losing focus after marking notification as red](https://user-images.githubusercontent.com/346079/30129892-5dcd19f0-933f-11e7-9222-3b73557fce63.gif)

**Comment by chrisarcand** [comment]
I've recreated your issue, got it. ✔️ 

I always select (checkbox) the issue I want to do something with (with 'x') before archiving/marking as read, which does work correctly.

**Comment by andrew** [comment]
Just deployed the fix to https://octobox.io 🚤

**Comment by kynan** [comment]
Works a treat, thanks!
