### ISSUE TITLE
Opt-in OAuth scopes for repo access

### ISSUE THREAD

**Issue by chrisarcand** [octobox/octobox#417]
With #411 merged, we now need the other half of it - the ability to use more permissions to Github beyond the notification scope, to use repo permissions for access to pull down subjects and other useful info for private repositories. This should be opt-in. 

Completing this task should allow features like #411 to be enabled on octobox.io

**Comment by andrew** [comment]
@chrisarcand you read my mind, literally just came here to open this issue!

**Comment by chrisarcand** [comment]
✨ 🔮 ✨

**Comment by chrisarcand** [comment]
Closing this as a duplicate of #472
