### ISSUE TITLE
Bubble up API errors to the end user

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#421]
There are a couple classes of errors that happen which aren't technically application errors but we throw 500s for them:

- when the GitHub API is down
- when the API key is invalid

We should gracefully handle those errors and report them in the UI rather than throwing 500 errors

**Comment by chrisarcand** [comment]
Duplicate of #382, going to close this one but add your points here :)

**Comment by andrew** [comment]
👍 That'll teach me to open issues from my phone!
