### ISSUE TITLE
Filtering Issues by labels

### ISSUE THREAD

**Issue by tojochacko** [octobox/octobox#422]
Is there a way I can filter issues by labels in Octobox ? This feature would greatly help me in searching through my large list of issues.

**Comment by chrisarcand** [comment]
You mean by GitHub's issue labels? There currently is not, no.

Given that labels are included on the issues/pull requests endpoint we might be able to add that to our subjects' metadata on syncs. The real challenge, however, is the UX with labels added; we already have a plethora of information on the screen about notifications and I'd be concerned given the large number of custom labeling across all projects that our console could become quite the cluster.

I see how it could be useful though!

**Comment by andrew** [comment]
I was thinking about this one yesterday too, now that #4 is in we can add a `labels` column to the `subjects` table as a postgres array to be able to filter notifications by label, as chris said, we'll need to work hard to fit it into the UI properly as you'll likely have quite a long left column but would be handy for triaging 👍

**Comment by tojochacko** [comment]
Regarding the UX, we can override the search box to auto suggest labels when we search or maybe search using some prefixes to my search keyword that will allow me filter by label/project/milestone/assignee.

**Comment by andrew** [comment]
I took a stab at syncing the labels on issues and pull requests this morning, unfortunately there's a subtle difference between the issue/pr responses from the GitHub API, namely that the pr endpoint  doesn't include `labels`, you can get them by loading the issue endpoint for the pr number but then you don't get the `merged` state, so basically syncing labels for pull requests will require 2 http requests each 😑

Looks like this can be done with the graphql v4 endpoint which returns labels on pull request objects, so might have to switch to that.

Here's the branch if you want to take a look: https://github.com/octobox/octobox/compare/subject-labels

**Comment by rhuss** [comment]
Are you guys still working on this feature? I really love Octobox, but since we have moved to a Monorepo where issues and PRs are separated by labels (reflecting the previous repos), it would be awesome if one could filter on labels (even when the maybe do not show up in the UI).

Another idea for presenting labels and preserve screen estate would be only to show their colour in small squares (with tooltips for the full name)

**Comment by chrisarcand** [comment]
@natemcmaster No one is currently working on this, to my knowledge. Have at it! ❤️

**Comment by natemcmaster** [comment]
I took a stab at it: https://github.com/octobox/octobox/pull/529

**Comment by andrew** [comment]
This has been implemented by @natemcmaster, available if you are self-hosting and have subject-syncing enabled
