### ISSUE TITLE
Automatic refresh

### ISSUE THREAD

**Issue by gudetimes1234** [octobox/octobox#424]
Sort of related issue: https://github.com/octobox/octobox/issues/309

Would be cool to have an optional automatic refresh. Going to clone this evening and try to add a feature in Settings so that users can turn on automatic refreshes if it's desired.

**Comment by chrisarcand** [comment]
Automatic refreshes is already implemented (https://github.com/octobox/octobox/pull/200). This option is available under Settings - but *not* available on octobox.io. Please see the note in the README.

Thanks for the issue, though! Closing this, but please feel free to reopen if you meant something different.

**Comment by whit537** [comment]
Dupe of https://github.com/octobox/octobox/issues/205 fwiw.
