### ISSUE TITLE
Favicon distorted

### ISSUE THREAD

**Issue by chrisarcand** [octobox/octobox#428]
The favicon in Chrome tabs is extremely distorted compared to basically anything else. I'm on a retina Macbook Pro.

![](http://screenshots.chrisarcand.com/3z50l.jpg)

(Note that my screenshot above really doesn't do the contrast justice.)

**Comment by andrew** [comment]
Did that change recently or has it always been like that?

**Comment by andrew** [comment]
Looks ok on my retina screen: 
<img width="289" alt="screen shot 2017-08-30 at 10 00 38 am" src="https://user-images.githubusercontent.com/1060/29864320-3391902e-8d6a-11e7-8330-bd53ae61c23e.png">

**Comment by vitalkanev** [comment]
For me in Lubuntu Zesty 1366x768 15 inch screen it looks like *this*: 
![image](https://user-images.githubusercontent.com/18398761/29878498-5fb24c34-8dab-11e7-9942-808060338ac8.png)

Proably not distorted

**Comment by chrisarcand** [comment]
Alright, you've convinced me, I'm just crazy. 😜

**Comment by chrisarcand** [comment]
Ah ha! Proof!

![](http://screenshots.chrisarcand.com/lyhp9.mp4)

The pixelated image, is, funny enough, on the screen we're complaining about in #400 
So let's fix that one ;)

**Comment by andrew** [comment]
@chrisarcand is this still happening?

**Comment by pradyunsg** [comment]
It did for me recently. I'll try to see how to reproduce this tonight.

**Comment by BenJam** [comment]
bump. Anyone still experiencing this?

**Comment by chrisarcand** [comment]
I haven't noticed it recently; though TBH the new logo helps as with less distinct edges it's really hard to tell if it's 'blurry' or not at this point. Closing this, @pradyunsg feel free to reopen something if you find it does still occur.
