### ISSUE TITLE
The "Mention" label is some times set when it's really a review request

### ISSUE THREAD

**Issue by tkbremnes** [octobox/octobox#429]
I have several messages in my inbox right now that are tagged as "Mention", when I've actually been added as a reviewer. There's no mention of my handle in the PR.

Note: I'm not familiar with the Github API, so for all I know it might be a bug on their end.

**Comment by andrew** [comment]
I believe this is a bug in the GitHub API rather than Octobox, at least according to @davidcelis in https://github.com/octobox/octobox/issues/400
