### ISSUE TITLE
[QUESTION] How to update docker image

### ISSUE THREAD

**Issue by gep13** [octobox/octobox#433]
A while back, I followed the instructions on how to set up a docker image to run Octobox locally on my server:

https://github.com/octobox/octobox/blob/master/INSTALLATION.md#using-docker

That has been working really well for me.  Are there any instructions on how you should update the docker image to use the latest code from Octobox?

Ideally, this would be a complete set of steps, which could then be added to the instructions.  I would be happy to do that work via a PR, just need to know what the steps are first.

Thanks

**Comment by gep13** [comment]
The main concern here is losing information stored in the second database image that is being used during the upgrade.  i.e. I would prefer not to lose anything 😄

**Comment by andrew** [comment]
I'm interested in this answer too, I'm not a docker user myself, this stackoverflow answer seems helpful: https://stackoverflow.com/a/43515922/120434

**Comment by karuppiah7890** [comment]
@andrew Actually, the database container should store the data in the host. Some volume mounting has to be done for this, where in your mount a folder in the host to the folder in postgres container which stores the DB data.

@gep13 You want to update the application alone right ? And have the database contents intact ?

**Comment by reicheltp** [comment]
With `docker-compose build app` you rebuild the app image. Then with `docker-compose up app` you just recreate the app image and keep the Postgres one.

For a long term solution you should add a volume to the Postgres to keep all data across container recreation.

**Comment by karuppiah7890** [comment]
@reicheltp :+1:

**Comment by linuxjuggler** [comment]
I do have one question why don't you @andrew push a new image to docker hub each time you release a new version or update? this will make it easier for anyone who is using docker

**Comment by andrew** [comment]
@linuxjuggler that's setup to happen automatically after every commit to master: https://hub.docker.com/r/octoboxio/octobox/builds/

**Comment by linuxjuggler** [comment]
@andrew then docker-compose should reflect to using that image instead of rebuilding the image locally.

so using this :

```
  app:
    image: octoboxio/octobox
```
will always pull the image from docker hub, and all they need is to pull the new image and restart the instance.

am testing small modifications to `docker-compose` locally and will send a PR if things went as planned.

**Comment by andrew** [comment]
@linuxjuggler ok great, looking forward to your PR, thanks for looking into this 👍

**Comment by karuppiah7890** [comment]
@andrew I think the current `docker-compose.yml` is more of a development asset and for local testing. May be rename it and use it for development. And have `docker-compose.yml` changed like @linuxjuggler mentions, or people will have to build the image which is usually takes more time than downloading the already built image.

**Comment by linuxjuggler** [comment]
@karuppiah7890 what you said is somehow correct, except that in version 3 of docker-compose you can use the same `docker-compose.yml` file to deploy a stack to docker swarm without having to do a lot of configuration.
but you are correct the current status of the `docker-compose.yml` file is more for developers who want to contribute to the development.

am trying to tweak it a bit, and I'll also try to update the Installations docs to give more info about how to use docker if you just want to use the image and not help with the development.

**Comment by karuppiah7890** [comment]
@linuxjuggler Also do volume mounting for postgres DB

**Comment by andrew** [comment]
@karuppiah7890 thanks for pointing that out, at this point I'd prefer to optimize for a better experience as a user than a contributor as there are many more people running it than developing on it.

**Comment by linuxjuggler** [comment]
@karuppiah7890 thats the plan, a small changed to the `Dockerfile` and adding `volumes` to the `docker-compose.yml`

**Comment by linuxjuggler** [comment]
@andrew can you have a look at https://github.com/octobox/octobox/compare/master...linuxjuggler:master before I send the PR

**Comment by karuppiah7890** [comment]
@linuxjuggler Why can't you just use the `docker-compose` command along with the new docker-compose file ? Why create network interface and stuff and run containers one by one, when it can all be done with `docker-compose.yml`

**Comment by linuxjuggler** [comment]
@karuppiah7890 docker-compose file is still there and can be used to achieve the same thing but you will have to do one of the following:

1. clone the repository to your local server, and you will only use one/two files from the whole code.
2- or you will have to download the `docker-compose.yml` file from the repo alone.

so you still have the option to use docker-compose as documented when you want to contribute to the development.

**Comment by karuppiah7890** [comment]
@linuxjuggler Oh yeah, about that, we can provide a link to the docker-compose.yml file from the repo, to download it. And then it will be just a single command. I think it's okay

**Comment by linuxjuggler** [comment]
@karuppiah7890 done, I just sent a PR https://github.com/octobox/octobox/pull/434 for everything I have changed.

**Comment by gep13** [comment]
>@karuppiah7890 said...
You want to update the application alone right ? And have the database contents intact ?

Yes, that is exactly right.

So, if I have followed along with the comments in this thread, and in the Pull Request, am I right in saying that I can simply update the local clone of the octobox repository that I have, and run `docker pull` and all should be well?  i.e. all of the items that I have starred, archived etc, will remain in tact?

**Comment by karuppiah7890** [comment]
@gep13 Do what @reicheltp said

>With `docker-compose build app` you rebuild the app image. Then with `docker-compose up app` you just recreate the app image and keep the Postgres one.

**Comment by gep13** [comment]
@karuppiah7890 @reicheltp so, I will have to do that each time I want to update to latest version of octobox?

If I ditch what I currently have, and start with the newest docker file from the PR, will I be able to keep the data that I accumulate and simply do a docker pull?

Sorry for naive questions! Still getting my head around docker.

Thank you for your time, and patience.

**Comment by karuppiah7890** [comment]
The answer is - Yes, if you are gonna use the old docker-compose.yml file.

And I still have to check how to get the postgres data out of the isolated container into the host. Or you could do a manual dump using `pg_dump`  and you can import it later. 

And to use the easier method, the one in the PR, you just need the docker-compose.yml and you will just have to do `docker-compose pull app` and then `docker-compose up`

**Comment by gep13** [comment]
@karuppiah7890 ok, I will try the first approach, but in the long run, I might cut my losses once caught up with notifications, and switch to newer way of doing it.

**Comment by karuppiah7890** [comment]
@gep13 You can actually connect to the postgres container using it's IP and use `pg_dump` and get to the new one easily

**Comment by linuxjuggler** [comment]
@karuppiah7890 adding the volume to pg is easy all you have to do is to edit the old `docker-compose.yml` file and add it to point to a directory on the host.
the downside of this is that you will lose the old data ( unless you have a backup using pg_dump ) since you have 
also moved the path for the data directory 

an example:

```yml
    volumes:
       - ./pg_data:/var/lib/postgresql/data
```

your last long options is to look at which volume pg container is using, it will be local one but will not have a name, then move the data from out there to your `pg_data` directory

**Comment by karuppiah7890** [comment]
@linuxjuggler I was talking about mounting volumes into an existing container, and I haven't done that. And I am not sure if we will lose data, since I haven't tried it. But the `pg_dump` is the best bet for a backup.

**Comment by gep13** [comment]
@karuppiah7890 would you have a complete set of steps of exporting the current data that I have, and importing into the new image that I assume will be created if I switch to new PR?  SQL Server guy here, so completely new to postgres :-D

**Comment by linuxjuggler** [comment]
@karuppiah7890 I think I do understand what you are saying, but even if you have mounted a named volume into a running pg container, the data will still be saved on the old path.

but I guess if you are willing to test, all you have to do is to edit your `docker-compose.yml` file and add the volume then restart your container and see if it will save the data in the new local directory or not

**Comment by karuppiah7890** [comment]
@linuxjuggler Yeah, gotta experiment that.

@gep13 Sorry man, I am gonna sleep now. It's midnight. I will put it up tomorrow may be

**Comment by gep13** [comment]
>@karuppiah7890 said...
Sorry man, I am gonna sleep now. It's midnight. I will put it up tomorrow may be

Not a problem at all, I am in no immediate rush.  I appreciate your time.

**Comment by karuppiah7890** [comment]
@gep13 Follow this 
```
$ docker-compose up -d
$ docker ps # see if two octobox containers are running using the names
```
Now use the database container's name in the below `inspect` command. For me it's `octobox_database_1`
```
$ docker inspect octobox_database_1 | grep IPAddress
```
And then use the IP in the below `pg_dump` command. For me it's `172.18.0.2`. 
```
$ pg_dump -h 172.18.0.2 -U postgres -d postgres -a -f data.sql # password: development
```
Now stop stop and remove all existing containers using 
```
$ docker-compose down
```


Now, get new docker-compose.yml from https://github.com/linuxjuggler/octobox/blob/13c4e31d204dbdc9fe43b537a17dbe5fa435cc21/docker-compose.yml and do the following (mostly similar to the previous steps)

```
$ docker-compose up -d
$ docker ps # see if two octobox containers are running using the names
$ docker inspect database.service.octobox.internal | grep IPAddress
$ psql -h 172.18.0.2 -U postgres -d postgres < data.sql # password: development
```

And to disconnect from the server in the `psql` command, use `\q` command. And there will one error for importing data. Some metadata importing stuff. It didn't cause any issues in the application though

**Comment by karuppiah7890** [comment]
@andrew People can use the above as a small migration guide to switch to the new docker-compose file when it's PR is merged

**Comment by andrew** [comment]
@karuppiah7890 brilliant, thanks for looking into this 🙏

**Comment by linuxjuggler** [comment]
Postgres will be accessible via local host no need to get the internal IP at least this is on mac

**Comment by karuppiah7890** [comment]
@linuxjuggler How come ? `localhost` is `127.0.0.1` and the docker containers have their own IP, and to access them through `localhost`, some port forwarding has to be done, which is done only for `app` container now. I think getting the IP will be needed?

**Comment by linuxjuggler** [comment]
@karuppiah7890 when you run your container it will bind localhost to the container itself, so when you expose the port to ports outside the container `-p 3000:3000` your container will be accessible via `0.0.0.0:3000` that's why you access the octobox app on `localhost:3000`.

in my `docker-compose.yml` [file](https://github.com/linuxjuggler/octobox/blob/13c4e31d204dbdc9fe43b537a17dbe5fa435cc21/docker-compose.yml) I didn't expose the port externally which means that you can't access the container via `localhost: 5432` but if I changed the database section to be something like:

```yml
  database.service.octobox.internal:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=development
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal
    ports:
      - 5432:5432
```

Then you will be able to access the database via `localhost: 5432`

**Comment by linuxjuggler** [comment]
This image shows exactly what am talking about

![screen shot 2017-09-01 at 17 00 53](https://user-images.githubusercontent.com/27624/29973142-2a3c8d70-8f37-11e7-90cb-f932173cc985.png)

**Comment by karuppiah7890** [comment]
@linuxjuggler Well, that can be done temporarily, but should not be done in production, because if you port forward localhost's port to container's port for the database container, then anyone will be able to hack the database as it's not password protected and even if it's password protected, people can try brute force attacks

**Comment by andrew** [comment]
@gep13 does this answer your question now?

**Comment by linuxjuggler** [comment]
@karuppiah7890 it's not about doing it temporarily, it's how Docker works when both containers are on the same network you don't need to have any port expose to the host, but when you have to backup your data, either you should create another container which communicates with your DB container and dump the data or you will have to export the port.

at the end remember all the information about the database are ***stored*** within `docker-composer.yml` file, including the database ***password***.

I do advise that you check this [course](https://www.udemy.com/docker-mastery/) about docker by one of the **Dockers' Captain**.

or you can check [Painless Docker](http://painlessdocker.com)

**Comment by karuppiah7890** [comment]
Right. I think you misunderstood what I said. And I think I know enough basics of Docker to talk about port exposing and networks. And I know about the facts that you are talking about, and I meant - it's only a vulnerability if the ports are exposed for DB server in production. And thanks for the links.

**Comment by linuxjuggler** [comment]
@karuppiah7890 am sorry if I misunderstood what you said.

it was nice to talk to you and have a productive discussion like this one.

**Comment by gep13** [comment]
> @andrew said
@gep13 does this answer your question now?

I think it almost certainly will, yes.  I need to sit down and walk through the steps.  Will try and do this over the weekend, and I will report back here if it all works.

**Comment by linuxjuggler** [comment]
> when you run your container it will bind localhost to the container itself, so when you expose the port to ports outside the container -p 3000:3000 your container will be accessible via 0.0.0.0:3000 that's why you access the octobox app on localhost:3000.

Just to be clear, after reading a lot again, I found out that this may vary between Linux and Mac/Windows as Linux will have direct (I guess) access to the IP of the container.

**Comment by karuppiah7890** [comment]
Yes, Linux has direct access to the IP of the container. There's a separate network interface (virtual netwok I guess?) in the host which is connected to the same network as the containers.

**Comment by andrew** [comment]
Going to close this one as I think we've settle this 👍
