### ISSUE TITLE
Allow option to authenticate with a personal access token

### ISSUE THREAD

**Issue by WillAbides** [octobox/octobox#44]
Add the option to authenticate with a personal access token.  This was lost in #25.

**Comment by jlmitch5** [comment]
As far as I can tell, there's no way to provide the "notifications scope" mentioned in the readme.md anymore with the deploy to heroku button now, as it doesn't seem like there's a way to set that in the "Register a New oauth application" screen. This may not matter, but just wanted to write a note in case it does.  These are the config vars you get in heroku now:

<img width="962" alt="screen shot 2016-12-19 at 12 51 17 pm" src="https://cloud.githubusercontent.com/assets/1342624/21323126/1d786bfc-c5ea-11e6-9059-32f5c43aef90.png">

Readme.md should also probably be updated to explain the new config vars.

**Comment by andrew** [comment]
@jlmitch5 ah good catch, that's definitely got a bit out of sync today, the app now defaults to `notifications` as the scope so you don't need to set it, and the readme is definitely out of date around the heroku button

**Comment by jlmitch5** [comment]
Sounds good!  Would pr a change to the readme, but it sounds like there's probably active development/changes around adding the personal access token config back in, so I thought it best to hold off until that lands.

**Comment by andrew** [comment]
@jlmitch5 I think the PR will add the ability into the UI rather than via ENV, will happily merge a quick update to the readme now

**Comment by WillAbides** [comment]
I'm going to have a go at this one.  @tarebyte, do you have any words of wisdom since you touched this part recently?

**Comment by tarebyte** [comment]
@WillAbides shouldn't be too bad honestly. I [started a branch](https://github.com/octobox/octobox/tree/tarebyte/edit-account) but got sidetracked.

The only thing I would make sure to do is to make sure the users token doesn't get overridden once they do the oauth dance a second time.

**Comment by andrew** [comment]
Maybe store it in a separate column?

**Comment by andrew** [comment]
Fixed by @WillAbides
