### ISSUE TITLE
Prevent user from accidentally muting the thread

### ISSUE THREAD

**Issue by simplesmiler** [octobox/octobox#442]
Sometimes I accidentally click "Mute" when I wanted to click "Archive".

Until https://github.com/octobox/octobox/issues/319 is implemented, it would be nice of Octobox to ask twice for "destructive" actions (I don't think there is a way to unmute the thread).

I can imagine this as a confirmation modal.

**Comment by chrisarcand** [comment]
Agree that Undo functionality would be ultimately nicer.

If this is to be added in interim, I'd strongly prefer it to be toggled via [application] configuration (which @andrew can enable on octobox.io if he chooses). Requiring confirmation would sort of ruin my own workflow at this point and would be removed anyway once undo functionality is written :)

**Comment by andrew** [comment]
Agree with @chrisarcand, let's focus on adding #319 and close this one
