### ISSUE TITLE
Shift+click selection does not work

### ISSUE THREAD

**Issue by simplesmiler** [octobox/octobox#443]
It looks like Shift+click selection (implemented in #383) does not work on https://octobox.io/
Is it not published, or got broken?

Browser: Chrome 60.0.3112.113

**Comment by andrew** [comment]
Sounds like a bug to me

**Comment by samjacobclift** [comment]
seems ok to me in latest chrome, note need to only press shift for the final click

i.e click checkbox for first issue, then shift-click the last item you want to select to's checkbox

![shift-click-v2](https://user-images.githubusercontent.com/1868592/30108516-9062d35e-92fa-11e7-8bae-719493b6a082.gif)

**Comment by chrisarcand** [comment]
Note that it's not the most robust implementation; if you have shift held down on the first click it doesn't work, if you click multiple times in different areas with shift held down it's quite finicky, etc. 

I confirm that it appears to be working normally, though - a single shift-click select does the job.

**Comment by simplesmiler** [comment]
Oh, I see. I'm used to gmail's implementation, where it works with the initial shift. But no-shift on first click is fine too.

**Comment by samjacobclift** [comment]
@simplesmiler maybe we should make that change though, it though there might worth it wdwt
