### ISSUE TITLE
Automatically archive issue after visiting a link

### ISSUE THREAD

**Issue by borekb** [octobox/octobox#445]
On `https://github.com/notifications`, an item becomes "read" after I click the link – it is grayed out until I refresh the page and goes away entirely after refresh. I think Octobox could behave the same: it already does in the first part (the item transitions from bold to normal) but after refresh, it could be auto-archived. I currently do that manually and find it redundant.

Awesome project, BTW!

**Comment by laughedelic** [comment]
From the readme:

> Notifications are marked as read and disappear from the list as soon as you load the page or view the email of the notification. This makes it very hard to keep on top of which notifications you still need to follow up on. 

I think that's why it's marked as `wontfix`. But it still could be an opt-in setting...

**Comment by borekb** [comment]
Ah, makes sense. The main value in Octobox for me is categorization of the notifications, not that they stay in the inbox and I have to archive them manually. But the current philosophy makes sense for sure.

**Comment by andrew** [comment]
Sorry didn't get chance to follow up with a comment (traveling atm), @laughedelic is right, Octobox wants to avoid that functionality that GitHub notifications has as you loose control of your todo list, so it's not something I want to go back on, even as an optional feature.
