### ISSUE TITLE
Snoozing notifications 

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#452]
Throwing this out there to see if anyone but me would find this interesting. 

I really like the snooze feature of Google Inbox to hide an email until tomorrow or next week, we could potentially do the same thing for notifications in Octobox.

**Comment by pradyunsg** [comment]
I'm definitely interested in this. :)

**Comment by pradyunsg** [comment]
(As in both, trying to implement and as a user; though I'm not sure how long it'd be before I can do the former)

**Comment by andrew** [comment]
From an implementation point of view, here's my thinking:

- Add a `datetime` column to the notifications table called `snooze_until`
- Inbox view should only show notifications where `snooze_until` is less than `Time.now` or NULL
- create a `snooze_selected` controller action that sets the  `snooze_until` field on those notifications to the datetime passed though
- Create a `Snooze selected` button in the UI similar to `Archive selected that posts to the `snooze_selected` controller action but also has a dropdown to choose how long to snooze
- Create a `snoozed` scope that finds notifications where `snooze_until` is greater than `Time.now`
- Add a sidebar link to `Snoozed` that only shows notifications that have been snoozed (using the `snoozed` scope
- Add a `snoozed:true` search filter (assuming #775 has been merged)

**Comment by pradyunsg** [comment]
Additionally noting here that this would also need some updating of the documentation (README, OpenCollective page etc), since Octobox would start doing more than just add an archived state.

> Inbox view should only show notifications where snooze_until is less than Time.now or NULL

Ideally, we also should present that this notification was snoozed and showed up now; marking it unread perhaps would hightlight it?

Gmail shows a separate piece of text, until you open the mail again.

<img width="270" alt="screen shot 2018-08-16 at 4 36 53 pm" src="https://user-images.githubusercontent.com/3275593/44205049-af0cde80-a172-11e8-887f-62818bb468ad.png">

> Add a snoozed:true search filter (assuming #775 has been merged)

I think it'd be useful to have the ability to sort them based on `snooze_until`

Perhaps it'd also help to be able to filter things snoozed for next week when searching, something like: `snoozed:>09-22-2018`?

**Comment by andrew** [comment]
👍

**Comment by prashuchaudhary** [comment]
@andrew @pradyunsg this is the design I came up with for  Snooze Dropdown. A user can select `minutes, hours, days or week` using a dropdown and use `+/-` button to select duration. Also we can provide some quick tips for common snooze timings. 

I wanted to keep it simple right now, so I am ignoring the use case like 1.5 hours etc.
 
![img_20181005_185159584-min](https://user-images.githubusercontent.com/11884537/46573196-3fb3ae00-c9af-11e8-8783-0cdb23f09243.jpg)

**Comment by andrew** [comment]
cc @BenJam ☝️

**Comment by prashuchaudhary** [comment]
> @andrew @pradyunsg this is the design I came up with for Snooze Dropdown. A user can select `minutes, hours, days or week` using a dropdown and use `+/-` button to select duration. Also we can provide some quick tips for common snooze timings.
> 
> I wanted to keep it simple right now, so I am ignoring the use case like 1.5 hours etc.
> 
> Please provide feedback
> 
> ![img_20181005_185159584-min](https://user-images.githubusercontent.com/11884537/46573196-3fb3ae00-c9af-11e8-8783-0cdb23f09243.jpg)

@BenJam can you please review the design for Snooze Dropdown ??

**Comment by scopatz** [comment]
This would be great to have!

**Comment by andrew** [comment]
Restarting the snooze pr over here: https://github.com/octobox/octobox/pull/1858

**Comment by pradyunsg** [comment]
Thanks for your patience @prashuchaudhary! Thanks for restarting work on this @andrew! Super excited!

> Please provide feedback

I'd prefer to snooze input to be for an exact date-time, with quick tips suggesting a list of "common" scenarios that the user might want to snooze to.

---

The design I had in mind was to do something like what Google Calendar shows on "Add Reminder", with quick tips under it.

<img width="199" alt="Screenshot 2019-05-27 at 5 49 33 PM" src="https://user-images.githubusercontent.com/3275593/58440408-ce447f00-80a7-11e9-8184-38b19bb43321.png">

(clicking on the date brings up a date picker, clicking on the time shows 30 minute increments; both allow text input)

---

<img width="260" alt="Screenshot 2019-05-27 at 5 44 49 PM" src="https://user-images.githubusercontent.com/3275593/58440468-33987000-80a8-11e9-97fe-c83638b4a5c3.png">

^ GMail's snooze suggestions are based on what time of the day it is, Octobox could probably use similar suggestions.

**Comment by scopatz** [comment]
I'd like to second @pradyunsg's summary

**Comment by alcuadrado** [comment]
I came here to open a feature request about this. Happy to see that it's being worked on. It's the only feature Octobox misses to be "the Gmail of GtiHub", letting you work with an inbox zero workflow.

I really like what @pradyunsg suggested. Gmail's snooze is always super easy to use.

**Comment by scopatz** [comment]
Yeah, this would truly be great!

**Comment by scopatz** [comment]
Was this implemented?

**Comment by pradyunsg** [comment]
Idk, looks like ~85 other issues were closed around the same time as this one.

**Comment by andrew** [comment]
No, most paying users have jumped to the new GitHub notifications beta so there’s no resources left to implement new features any more

**Comment by scopatz** [comment]
That's too bad. I would rather not jump as well.

**Comment by scopatz** [comment]
@andrew - are you planning on shutting octobox down?

**Comment by andrew** [comment]
@scopatz not shutting it down, but scaling it back in terms of new users to reduce maintenance overhead
