### ISSUE TITLE
Unread count in title

### ISSUE THREAD

**Issue by roblourens** [octobox/octobox#454]
First of all, I just discovered Octobox and I'm already in love with it, thanks!

It would be awesome if it would show the unread count in the window title - `Octobox (2)` - I think Facebook does this for example. Would be most effective when used with automatic refresh enabled.

**Comment by andrew** [comment]
Waiting on https://github.com/octobox/octobox/pull/457

**Comment by roblourens** [comment]
Sorry, fixed
