### ISSUE TITLE
Sidebar height on mobile restricted by list of issues on the right

### ISSUE THREAD

**Issue by ringods** [octobox/octobox#456]
When the list of issues/PR on the right is short, the sidebar on the left is only as high as the list is. I would expect the sidebar would still use the whole height of the screen.

Screenshot of this behaviour on my iPhone 6s with Chrome. I see the same behaviour on my iPad Mini 2 Retina in portrait mode.

![img_5153](https://user-images.githubusercontent.com/77923/30249632-2d25b4e8-9640-11e7-8e28-402d46f06c74.JPG)

**Comment by andrew** [comment]
Yeah that looks like a bug, which version of iOS are you using? Is it only happening for you in Chrome or Safari as well?

**Comment by ringods** [comment]
Both my iPhone and iPad are running the same versions:
* iOS 10.3.3
* Google Chrome 61.0.03163.73

Tested it too with Safari and have the same results:
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1
