### ISSUE TITLE
"Sorry, something went wrong" when refreshing direct mentions

### ISSUE THREAD

**Issue by jmarlena** [octobox/octobox#464]
To see my direct mentions, I clicked the mentions option on the left  and then clicked the "refresh" button. I was redirected to a "Sorry, something went wrong" page. 

Let me know if there's more info I should add or any theories on why this might have happened.

**Comment by bernars** [comment]
:raised_back_of_hand: I'm also seeing this.

**Comment by andrew** [comment]
@jmarlena is this on https://octobox.io or a version you are hosting yourself? I can't see any errors in the bugsnag logs, but that could be a heroku error rather than an application one.

**Comment by jmarlena** [comment]
This is on a version of Octobox that our company is using. 🤔

**Comment by andrew** [comment]
https://github.com/octobox/octobox/pull/466 has been merged which should give a better error message explaining why it's failing if you want to give that a try?

**Comment by jmarlena** [comment]
Thanks for looking into this @andrew! It seems to be working now and there's no longer an error message. 😸

**Comment by chrisarcand** [comment]
@jmarlena I'm going to close this then, but please feel free to reopen if you encounter it again!
