### ISSUE TITLE
Add terms and privacy policy

### ISSUE THREAD

**Issue by stevelacey** [octobox/octobox#470]
Add a privacy policy 🙊️

...so that my org admin will approve access request 😁

**Comment by andrew** [comment]
@stevelacey good call, I'm literally working on this for Libraries.io at the moment, so will do a similar thing here.

**Comment by stevelacey** [comment]
Yes, I noticed, your URL for it is very guessable :)

**Comment by andrew** [comment]
@stevelacey PR opened here: https://github.com/octobox/octobox/pull/477

**Comment by andrew** [comment]
🚢
