### ISSUE TITLE
Per-user API tokens

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#471]
Following on from https://github.com/octobox/octobox/issues/39 which was mostly solved in  https://github.com/octobox/octobox/pull/320, as noted in the pr: 

> Lastly, this does not handle any authentication mechanism dedicated to JSON. I suspect we could add an API token mechanism to the user profile and auto-generate a key on create. The key would be shown in the user's profile. This will be handled later.

An API key should be generated for each user and then that can be used for making requests to the API rather than using a shared session with the web UI, should also include a section in the settings page for finding and refreshing your API key when logged in.

**Comment by jules2689** [comment]
This is done: https://github.com/octobox/octobox/pull/546

**Comment by Alexkho82** [comment]
#471
