### ISSUE TITLE
Support for optionally enabling downloading subjects

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#472]
The last piece of the puzzle to enable #4 on https://octobox.io is to optionally allow users to give `repo` scope access to Octobox so it can sync the status for issues and pull requests on private repositories. 

In practise what this means is configuring two different oauth apps and allowing the user to choose which one they login with, which is what I've done on both https://libraries.io and https://dependencyci.com, works well given the current state of the GitHub oauth API scopes.

This also means that a user can potentially be logged in via both, once they upgrade their access, so they will have two different token fields on their database record and the one with the higher access will be used if present.

Semi-related to https://github.com/octobox/octobox/issues/250, would certainly allow configuring of one Octobox instance to talk to Github.com and a GitHub Enterprise install at the same time if done right.

**Comment by chrisarcand** [comment]
Dupe of https://github.com/octobox/octobox/issues/417 but this one is more thorough, so closing that one.

**Comment by andrew** [comment]
Sorry, I'm the worse 🙈  working backwards through the issues list to close out old ones, forgetting what things have been opened already

**Comment by yonaskolb** [comment]
Are there any updates on this?

**Comment by tsupertramp** [comment]
@andrew - Wouldn't it make sense to remove the experimental flag (FETCH_SUBJECT=true) and make this default for all users, instead of a complex two way system? - I could PR this and add some text why this is happening for users where scope has to be upgraded.

The second option would be allow upgrading the scope in the settings of the user maybe, I would prefer option one.

Greetings, Thomas

**Comment by andrew** [comment]
@tsupertramp the main thing holding back switching the default on is the github permissions model for oauth apps, for anyone with access to private repos, they need to give a lot of access to code as well as issues and pull requests often to multiple orgs, I'm investigating getting it working as a GitHub App to allow for fine-grain permissions then we can definitely have FETCH_SUBJECT default to true

**Comment by andrew** [comment]
I'm actively working on this now, subject syncing will be enabled for any repos that have an Octobox GitHub app installed, so orgs can opt-in to this behaviour rather than users having to agree to `repo` scope, hoping to have something to show in the next week or so

**Comment by andrew** [comment]
@tsupertramp I've got this working (but hidden) on https://octobox.io now, let me know if you'd like to test it out.

**Comment by tsupertramp** [comment]
Hey @andrew - Totally!

**Comment by andrew** [comment]
https://github.com/octobox/octobox/pull/806 has been merged and is in the process of being rolled out to https://octobox.io so I'm going to mark this as done.

**Comment by tsupertramp** [comment]
Thanks a lot! Works like a charm!

**Comment by polyzen** [comment]
@andrew, is there a way to know the progress of the deployment?

**Comment by polyzen** [comment]
Actually, based on the settings page, it appears it has already been deployed. It is my understanding that #806 is what was needed to show the state of issues/PR's, but that doesn't seem available.

**Comment by andrew** [comment]
@polyzen it's in production for https://octobox.io, you can install it on open source repositories via https://github.com/apps/octobox, links will be added to the site this week

**Comment by polyzen** [comment]
@andrew, ah, thank you. It seems then this should also be updated:
https://octobox.io/documentation#navigating

**Comment by andrew** [comment]
This is now fully live and public on https://octobox.io 🎉
