### ISSUE TITLE
Sync via background jobs

### ISSUE THREAD

**Issue by chrisarcand** [octobox/octobox#476]
At some point we need to add background jobs for syncing user notifications.

Currently we sync in the request, and depending on the number of notifications or how slow the GitHub API is or how much load is on the Octobox instance, this has a very good chance of timing out when Octobox is deployed on Heroku:

https://devcenter.heroku.com/articles/request-timeout

TL;DR: Heroku cuts off requests longer than 30 seconds. If syncing isn't complete by then, you get an application error (logged as an `H12` error in the application logs).

Using a proper background job queue (ex: Sidekiq) would solve this issue.

[Potentially] related issues:
#310 
https://github.com/octobox/octobox/pull/474
https://github.com/octobox/octobox/issues/475

**Comment by ntomas** [comment]
Hi! I would like to help with this. 

Have a few questions around what we do in the UI. After there's a request to sync we can add a flash message telling we're syncing the notifications. But after that do we do some kind of ping to check if the job is done so we can auto-refresh? Or we have a flag telling those user notifications are being synced and ask the user to refresh after some time? 

Thanks!

**Comment by chrisarcand** [comment]
> But after that do we do some kind of ping to check if the job is done so we can auto-refresh?

I would personally prefer this, yes. Honestly if it behaved the exact same way (currently, sync button spins, page is updated) that'd be lovely.

**Comment by jules2689** [comment]
#543 adds the basic pipeline for this. https://github.com/octobox/octobox/pull/603 adds what is described here.
