### ISSUE TITLE
user linking to a bot/app account creates an invalid link

### ISSUE THREAD

**Issue by Fryguy** [octobox/octobox#478]
<img width="1342" alt="octobox 255 2017-09-29 16-20-48" src="https://user-images.githubusercontent.com/52120/31034453-3218feaa-a532-11e7-9dcf-859fa7a4a234.png">

The link is linking to https://github.com/greenkeeper[bot] which doesn't exist, but *should* be linking to https://github.com/apps/greenkeeper

Additionally, albeit minor, but there is no space between the "name" and the "[bot]" part, which is a little strange.

**Comment by radvc** [comment]
may I know which part is it?

**Comment by andrew** [comment]
Just deployed the fix https://Octobox.io

I wonder if we should highlight the fact that it’s a bot action with an icon?

**Comment by Fryguy** [comment]
an icon (🤖 ?) might be nice, but I'm fine with the [bot] designation too.

**Comment by andrew** [comment]
There's also this little octicons hubot icon: https://octicons.github.com/icon/hubot/

**Comment by vitalkanev** [comment]
Yep. But it's generally used by the GitHub itself (See one of the PR's by \@\hubot (Remove trailing backslash) in [`github/dmca` repo](/github/dmca)
