### ISSUE TITLE
Allow selection of multiple "reason" filters

### ISSUE THREAD

**Issue by gareth** [octobox/octobox#484]
Specifically there are times I want to be able to hide the "Subscribed" notifications without actually unsubscribing to them forever.

But more generally, it would be good to be able to select more than one "reason" and have a view showing the union of all of those filters e.g. to be able to see `Assign`, `Mention`s and `Review requested`s in one view.

**Comment by andrew** [comment]
@gareth this was completed by @rawburt in #497 but it took a while to get merged, just wrapped it up today.

Going to deploy it to https://octobox.io shortly 🎉
