### ISSUE TITLE
No content in Octobox at all

### ISSUE THREAD

**Issue by Floppy** [octobox/octobox#486]
For some reason I don't see anything in my Octobox dashboard - no repos, no issues, no labels, nothing. Others are also seeing nothing for some repositories under an org that should have access - see https://github.com/theodi/toolbox/issues/23. Any ideas what might cause that?

**Comment by Floppy** [comment]
I've revoked the OAuth permissions and reconnected - no change.

**Comment by Stephen-Gates** [comment]
Oh! that made the Toolbox repo show for me 
<img width="219" alt="screenshot 2017-10-05 23 12 38" src="https://user-images.githubusercontent.com/9379524/31229038-cf6c0d1a-aa22-11e7-877d-76e0f3342827.png">

**Comment by Stephen-Gates** [comment]
Perhaps its a time-based thing as I see my most recent issue 

<img width="1142" alt="screenshot 2017-10-05 23 16 11" src="https://user-images.githubusercontent.com/9379524/31229214-54f2537c-aa23-11e7-96a9-ff39bb25c208.png">

but not [others I have authored](https://github.com/theodi/toolbox/issues/created_by/Stephen-Gates)

**Comment by chrisarcand** [comment]
* Is this on octobox.io or your own instance?
* Regarding your notifications, do you have web notifications enabled on your GitHub account? See https://github.com/octobox/octobox#requirements
* Regarding the others who can't see anything for *some* repositories, are those repositories private ones?

**Comment by Stephen-Gates** [comment]
For me
- octobox.io
- no private repos

<img width="762" alt="screenshot 2017-10-06 00 21 57" src="https://user-images.githubusercontent.com/9379524/31232248-ad47d6e2-aa2c-11e7-9993-b7206289ff67.png">

@Floppy wasn't seeing anything

**Comment by Floppy** [comment]
Yes, on octobox.io. I didn't have the web notifications on (oops), but now I do and it's still the same. Perhaps I'll just try deleting the account and setting up from scratch now I've done the right notifications first.

**Comment by chrisarcand** [comment]
>  I didn't have the web notifications on (oops), but now I do and it's still the same. 

I'd expect it to be the same; turning on web notifications now won't make GitHub show you the notifications you would have stored in the API had you turned it on previously. I'm afraid I don't think you'll be able to get recent notifications that you've had in to Octobox at this point (there's nothing to draw from) and starting from now will have to suffice.

**Comment by chrisarcand** [comment]
> Others are also seeing nothing for some repositories under an org that should have access

Is this resolved, then? If not, those users should check to make sure they are actually subscribed ("Watching") to those repositories.

**Comment by andrew** [comment]
I wonder if having your web notifications turned off then turning them on leaves your `last_synced_at` timestamp in place so basically it won't find any of your old notifications anymore?

**Comment by andrew** [comment]
@chrisarcand I'm a bit busy to look at this today but I can add you to the heroku instance for octobox.io if you would like to poke around in the database?

**Comment by Stephen-Gates** [comment]
I think it's mainly resolved for me @chrisarcand 

- I now have new issues from [theodi/octopub](https://github.com/theodi/octopub) repo appearing 

- I can't get issues from https://github.com/theodi/pathway to appear despite adding a new issue https://github.com/theodi/pathway/issues/356

**Comment by Floppy** [comment]
Ah, yes, I've now got things appearing too. Excellent!

**Comment by Floppy** [comment]
A thought on this - it might be sensible for Octobox to warn users about setting up web notifications in the app, if there's nothing to display. Anyone who goes straight to octobox.io (as I did) wouldn't see the README.

**Comment by andrew** [comment]
Maybe we can add something to the [empty view](https://github.com/octobox/octobox/blob/master/app/views/notifications/index.html.erb#L75) if we see that you don't have any notifications

**Comment by Floppy** [comment]
Maybe if there's nothing in the inbox *or* the archive?

**Comment by chrisarcand** [comment]
@Floppy Yep, that's right.

**Comment by 3minus1** [comment]
@andrew @chrisarcand  Has this been done yet or may I get at it?

**Comment by andrew** [comment]
@3minus1 no, it's not been tackled yet, feel free to go for it!

**Comment by 3minus1** [comment]
@andrew Awesome! I'm on it.

**Comment by Floppy** [comment]
The new help text is great, thanks @3minus1. I will very happily close this now :)
