### ISSUE TITLE
Add Issue template

### ISSUE THREAD

**Issue by chrisarcand** [octobox/octobox#487]
Adding a simple GitHub Issue template with *at least* whether or not someone is having trouble on octobox.io or their own instance (if the issue is a bug report) would be helpful, as this question is basically asked every single time an issue is opened anyway.

**Comment by andrew** [comment]
Yeah can do, in my experience with using issue templates on Libraries.io, most people completely ignored them or deleted them, making more mess than help but it might be different on this project

**Comment by chrisarcand** [comment]
> most people completely ignored them or deleted them

Yeah I agree, really. TBH I really do just want "Are you using octobox.io?" 😄

**Comment by Roshanjossey** [comment]
This is the issue template I use in my project
https://github.com/Roshanjossey/first-contributions/blob/master/ISSUE_TEMPLATE.md

We could tweak this to better suit octobox. Like adding a question like
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [ ] My instance

Here's a sample issue
Roshanjossey/first-contributions#802

🐞 Problem

🎯 Goal

💡 Possible solutions

📋 Steps to solve the problem

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - Addresses #<put issue number here>
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

This is working extremely well for me. I've written a blog post about it
https://medium.com/@roshanjossey/how-better-issues-improve-collaboration-5a4e6ff95e90

Do reply if you like it. I'll submit a pull request to include this

**Comment by andrew** [comment]
@Roshanjossey looks good, a pull request to add that would be 👌

**Comment by andrew** [comment]
Fixed in #490
