### ISSUE TITLE
A refined UI and probably a desktop application

### ISSUE THREAD

**Issue by nshntarora** [octobox/octobox#488]
Hi!

First of all, thanks a lot for Octobox :smiley: 
I have a few suggestions for the project and would love to know what you guys think about it.

**An immersive organisation experience.**
Think how Slack let's you switch between multiple organisations on the their desktop application.
Would help keep your personal repos and work separated.
Different themes for different work modes.

**A night mode**
For the night owls among us

**Open and reply to issues within the app**
I don't know if there are limitations on the GitHub API front but it'd be great if it's possible.

**SPA, no page reloads.**
We'll probably get better performance out of it. Plus, better UX.

**A desktop application**
The only thing I'd love with this is system notifications whenever something new happens.
You could obviously snooze them in a focus mode.

These are just some ideas off the top of my head.
We can surely brainstorm on this.

**Comment by andrew** [comment]
Most of these items have now been opened as individual issues so I’m going to close this one.
