### ISSUE TITLE
Reduce http request size.

### ISSUE THREAD

**Issue by fanthos** [octobox/octobox#492]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
Each time when I switch the tab, the script will make a request to load the full new HTML page with header, scripts and other blocks. Header and scripts already loaded by first visit. Make the xhr load only useful data will reduce server bandwidth use.

💡 **Possible solutions**
Let the xhr load only used HTML tag or JSON instead a full HTML page.

**Comment by mdjalal** [comment]
rtrtrtt

**Comment by andrew** [comment]
I don't think we'll be changing the rendering approach in the short term so closing this
