### ISSUE TITLE
Ability to add missing (old) issues manually

### ISSUE THREAD

**Issue by Southclaws** [octobox/octobox#493]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
(I'm not sure if this is just a limitation of the hosted service but I didn't notice it mentioned anywhere.)

I noticed it only picked up x issues that were on my GitHub, which is fair enough as I can imagine pulling everything would hit rate limits for some users. After the initial setup, issues outside of the range or quite old (not sure what metric affects which issues get added to Octobox setup)

🎯 **Goal**
There are a couple of issues I'm working on for other repos that slipped my mind and upon remembering them, I'd like to manually add them by URL to the Octobox tool, just so they are there to remind me and I can star them, mark as unread, etc. I could imagine many users have issues a couple of weeks old that don't get picked up on the initial setup and would like to add them either by hand or with an automated process.

💡 **Possible solutions**
Either:
- "Add Issue" button, paste URL or `user/repo#issue` format string
- "Load Older" button, set date range or issue/PR amount to add

**Comment by chrisarcand** [comment]
This is currently determined by the `MAX_NOTIFICATIONS_TO_SYNC` configuration option, which defaults to 500 (note this number is a little misleading, see #475) but may be set differently on octobox.io. Anything older than that will not be synced in to Octobox.

**Comment by Southclaws** [comment]
Ah, that makes sense, thanks for the clarification!

Still, I think a way to arbitrarily add a specific issue without setting the config (and presumably restarting the instance) would be useful, probably not a super high priority feature though.

**Comment by Alexkho82** [comment]
#493
