### ISSUE TITLE
Hide the mute button

### ISSUE THREAD

**Issue by Fryguy** [octobox/octobox#500]
This is a feature request to be able to hide the mute button.  I rarely actually use the mute feature, personally, and very so often I've accidentally clicked mute instead of archive.  For me, since I use mute so rarely, I can just go to the GitHub native UI and do it.

I'm not sure of the best way to implement this, whether through user settings, global settings, both, or perhaps other buttons should be lumped in with mute as well, so I figured I'd open this issue for discussion.

**Comment by Fryguy** [comment]
Yay, issue #500 🏆

**Comment by chrisarcand** [comment]
I only use the keyboard shortcuts, so being a neutral party as to the usefulness of the mute button as a clickable button I’d say that the most logical thing to do if that’s truly a big annoyance is just to provide a means to enable/disable buttons on that action bar in settings - per user.

**Comment by Alexkho82** [comment]
#500

**Comment by Qkyrie** [comment]
hi @chrisarcand, would it be ok for fundrequest.io to add a little bit of funding to this issue, so maybe the community can pick it up?

**Comment by Alexkho82** [comment]
#500

**Comment by chrisarcand** [comment]
@Qkyrie I don't mind really; @andrew ?

**Comment by andrew** [comment]
@Qkyrie sure!

**Comment by andrew** [comment]
Thinking about this again, we could either:

- [ ] add a confirmation to the mute button
or
- [ ] add an undo function to enable rolling back of mistakes made

**Comment by andrew** [comment]
Closing in favor of #741 as I don't think we want to maintain lots of configuration that shows/hides different parts of the UI, it makes visual testing all the different possibilities a nightmare.
