### ISSUE TITLE
Ability to see what version number of Octobox is running in the UI

### ISSUE THREAD

**Issue by gep13** [octobox/octobox#503]
Show current Octobox version number in the main UI.

Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [x] My instance

🐞 **Problem**
I am currently running Octobox in a Docker image.  I "think" I have the most recent version running, but I have no real way of knowing if I am.  i.e. there is nothing displayed in the Octobox UI which says "Version x.x.x.".

🎯 **Goal**
I think it would be very useful to surface this information into the UI, as then there would be no ambiguity about what version is running on any given instance.

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by chrisarcand** [comment]
Octobox is (so far) a versionless/releaseless application that's just deployed on an ongoing basis, so I think the most accurate thing here would be to include the Git commit SHA as a version, perhaps in Settings, which can be linked as well. 👍

**Comment by gep13** [comment]
@chrisarcand sounds like a good idea to me!

**Comment by gep13** [comment]
@lewispb @andrew can you please confirm is this has shipped?  I "think" I have just installed the latest version, but I am not seeing the version SHA in the top right hand corner.

**Comment by lewispb** [comment]
Yes but if there’s any error caused by the git directory or git itself not being present on the server, the SHA won’t be displayed.

**Comment by gep13** [comment]
@lewispb where would I see that error message?  And what would I need to do in order to ensure that the necessary applications are installed in order for it to show?  Thanks

**Comment by lewispb** [comment]
In the directory where the application is located I would suggest you verify that running ‘git rev-parse HEAD’ works.

**Comment by gep13** [comment]
>@lewispb said...
In the directory where the application is located I would suggest you verify that running ‘git rev-parse HEAD’ works.

Sorry for asking questions, I just want to make sure that we are talking about the same thing...

I am running Octobox within a docker container.  When you say `in the directory where the application is located` are you referring to the host machine where I have cloned the Octobox repository into, or are you talking about within the docker image where the application is running?

If the latter, assuming that git is a requirement now, am I not right in saying that this should be added to the docker yml file?  /cc @andrew

**Comment by lewispb** [comment]
Yes it would need to be available whereever the application is actually running but sorry I’m not very familiar with docker.

**Comment by gep13** [comment]
>@lewispb said...
sorry I’m not very familiar with docker.

Neither am I 😄 

I thought running Octobox in a Docker image would help me get to grips with it, but still learning.  I will wait and see if someone else can add anything here.

**Comment by chrisarcand** [comment]
@gep13 I have little experience with Docker but I would venture to guess this is because [the .git directory is not included in the image because it's in .dockerignore](https://github.com/octobox/octobox/blob/d76bf25df157ddff096dee938f0728fb595496d2/.dockerignore#L1); however, a friend of mine says you might be able to `docker exec -it /bin/bash` into the container and check the sha from the command line here (there would have to be a PR opened to have the code conditionally use this if it does actually work...).

**Comment by gep13** [comment]
@chrisarcand I have tried what you suggested, but what I get back is...

```
"docker exec" requires at least 2 argument(s).
See 'docker exec --help'.

Usage:  docker exec [OPTIONS] CONTAINER COMMAND [ARG...]

Run a command in a running container
```

Any ideas?

**Comment by chrisarcand** [comment]
I don't, sorry!

**Comment by pirogoeth** [comment]
@gep13 `docker exec -it <your container name> /bin/bash`

**Comment by gep13** [comment]
@lewispb @chrisarcand @pirogoeth thanks everyone! When I run `git rev-parse HEAD` I get the following output:

```
fatal: Not a git repository (or any of the parent directories): .git
```

So looks like it is as @chrisarcand suggested.  Should we raise a different issue for this, or should we re-open this one?

Thanks

**Comment by andrew** [comment]
Looks like we should remove .git from the dockerignore file

**Comment by gep13** [comment]
@andrew happy to test this out, if/when it is ready for testing.

**Comment by andrew** [comment]
@gep13 fancy opening another issue so this doesn’t get lost?

**Comment by gep13** [comment]
@andrew sure thing.
