### ISSUE TITLE
Show issue/PR status in Octobox UI

### ISSUE THREAD

**Issue by Floppy** [octobox/octobox#504]
I use @dependabot, and so when I get behind in Octobox, there are often a bunch of notifications for issues that have already been closed. The GitHub UI shows the issue/PR status in its list - it would be great if Octobox could do the same.

Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
Without clicking through it's impossible to know if a notification is for a closed issue.

🎯 **Goal**
I would like to be able to know if I don't need to look at a notification so I can batch-close a load at once.

💡 **Possible solutions**
Show the issue state icon in Octobox, like so:

![screen shot 2017-12-03 at 12 26 09](https://user-images.githubusercontent.com/3565/33525348-8963a64e-d825-11e7-8e31-192711473047.png)

We already have the type - we could add colour, and perhaps a filter type in the sidebar for open/closed/merged.

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Floppy** [comment]
Ah, OK, I went to have a look at doing something about this and discovered quickly that GitHub don't put that in the [Notifications API](https://developer.github.com/v3/activity/notifications/#list-your-notifications), so it would take a lot of extra API calls to find out the information. How very annoying.

**Comment by Floppy** [comment]
I've asked nicely if they can add it ¯\_(ツ)_/¯

**Comment by andrew** [comment]
@Floppy this is a feature that's already available if you run your own instance of octobox: https://github.com/octobox/octobox/blob/master/INSTALLATION.md#downloading-subjects 

It's not enabled on octobox.io at the moment as it's pretty intensive to sync subjects for 6000+ users

**Comment by Floppy** [comment]
Ah, brilliant. Precisely because it's not in the API, I guess. 👍

**Comment by atuttle** [comment]
@Floppy could you provide a link to where you've requested that they add it to their API? Maybe getting a bunch of us to 👍 on it would help.

**Comment by Floppy** [comment]
No link unfortunately, they don't have a public issue tracker. It was just a support mail.
