### ISSUE TITLE
Feature: Add push notifications

### ISSUE THREAD

**Issue by mxschmitt** [octobox/octobox#505]
Hello,

with this request I want to add push notifications to the octobox web application. So there are needs to use service workers to fetch the updates from the backend every X minutes / seconds. 
It should be a combination of the Push API to get notified when the page is closed in combination with the Service worker API and the actual Notification API.

The aim is to support:
- Chrome
- Firefox
- Safari

I know that for this is a big change in the coding required.

**Comment by chrisarcand** [comment]
As long as they can be disabled! I loathe notifications 😉

**Comment by dctucker** [comment]
This would also be nice for use within Wavebox, since (if I'm not mistaken) they use notifications to set the account badge as having activity. Chrome support should be enough to make this work.

**Comment by mattdrose** [comment]
Adding notifications would be great to have. Even if it simply does ``new Notification(`New Github notification: ${title}`);``. I'm wrapping Octobox in an electron app, which supports HTML5 notifications (they bubble up as native os notifications).

I found it brought up as a suggestion in the past https://github.com/octobox/octobox/issues/269

**Comment by 3minus1** [comment]
May I take this up?

**Comment by arthurnn** [comment]
Would be awesome if I could setup pushes only for a type of notifications, for instance, activity on the notifications I had stared.

**Comment by MVrachev** [comment]
Are there any updates on this?
