### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#52]
Without opening a huge can of worms or adding any extra dependencies I wonder if we can add a basic search using a postgres full text search index: http://rachbelaid.com/postgres-full-text-search-is-good-enough/

**Comment by m1guelpf** [comment]
![search-dfQwvk9YLzVmM](https://media2.giphy.com/media/dfQwvk9YLzVmM/giphy.gif)

**Comment by andrew** [comment]
This gem might make managing search queries and combinable filters nicer: https://github.com/marcelocf/searrrch

> Allow you to receive a query string using the syntax similar to gmail's filters and parse it without going crazy.

> The following search string is supported:

    user_id: 123 user_name: omg user_id: 124 free text here
> The user can also put the value between quotes, in which case nested escaped quotes are supported.

**Comment by andrew** [comment]
Fixed by @samjacobclift
