### ISSUE TITLE
Filters + smaller width = row cut off

### ISSUE THREAD

**Issue by chrisarcand** [octobox/octobox#528]
The first row of notifications is cut off when a filter is selected AND the window size reaches the point that the CSS readjusts for mobile. Looks like the filter markup in the bar pushes the bar down over it:

![](http://screenshots.chrisarcand.com/qf6qd.jpg)

**Comment by rubenlozano** [comment]
I can help and fix that at some point during the week, Chris.

**Comment by rubenlozano** [comment]
Working on it 👍

**Comment by Alexkho82** [comment]
#528

**Comment by existentialmoron** [comment]
I inspected this issue. And what's actually happening is a row is partially cut off when window width is below 768px. While, the whole first row in hidden when width is 768px or above. May I be assigned this issue?

**Comment by andrew** [comment]
@existentialmoron feel free to tackle this one 👍

**Comment by andrew** [comment]
I think this has been fixed now 🎉
