### ISSUE TITLE
Filter and archive by Open/closed for prs and issues

### ISSUE THREAD

**Issue by davejlong** [octobox/octobox#54]
In combination with #53, I want to be able to quickly archive closed issues and PRs, especially when initially syncing the notifications from GitHub.

**Comment by andrew** [comment]
Dependent on https://github.com/andrew/octobox/issues/4

**Comment by andrew** [comment]
First part of this has been merged in #411 and is available behind the `FETCH_SUBJECT` env var feature flag, docs here: https://github.com/octobox/octobox/blob/master/INSTALLATION.md#downloading-subjects

Still working on getting it available on https://octobox.io

**Comment by prydonius** [comment]
+1 for filtering and seeing the state of PRs

**Comment by chrisarcand** [comment]
Closing this as it's now merged in to master and is [referenced in the README.](https://github.com/octobox/octobox#octoboxio)

Use on octobox.io is just dependent on adding optional oauth scopes or a migration path for asking people for increased permissions, which is up to @andrew

**Comment by jusunglee** [comment]
@chrisarcand @andrew How does one enable these features after changing the `GITHUB_SCOPE` to `notifications,repo` and `FETCH_SUBJECT` to `"true"` ? I don't see any difference

**Comment by jusunglee** [comment]
@chrisarcand Hey chris, thanks for the screenshot and reply. I did a quick bit of research and it looks like you have to give users read AND write permissions with the `repo` scope, is that correct? Am I also correct in saying that there is no read-only repo scope?

**Comment by chrisarcand** [comment]
@jusunglee That's correct; GitHub doesn't provide a read-only repo scope that I am aware of. See https://developer.github.com/apps/building-oauth-apps/scopes-for-oauth-apps/
