### ISSUE TITLE
Every refresh causes "Sorry, something went wrong" message

### ISSUE THREAD

**Issue by rallytime** [octobox/octobox#544]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

I have been using Octobox for many months and it is great! Thank you! However, the last couple of days I have noticed a problem where every time I refresh the page, I see the "Sorry, something went wrong" message and prompts me to file an issue.

This happens with I use the `r` key from my keyboard, click the refresh button in the webpage, and when I manually refresh the browser page.

It also takes a very long time to load, then the error pops up. I have a bookmark for my Octobox link. When I go to the bookmark, I can still use Octobox and it contains the "refreshed" content, but this has become a bit tedious.

I thought it would maybe resolve itself or that maybe GitHub was being slow. That happens sometimes, but it doesn't seem to be going away and is happening consistently.

🎯 **Goal**

I would like to use Octobox without seeing that error each time and return to refreshing the page normally. :) 

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by rallytime** [comment]
Oh, also an added data point is that once I have "archived" the items, I am seeing `Last sync: 5 days ago`. Which isn't right since I sync multiple times per day.

**Comment by rallytime** [comment]
@andrew Yeah. It says `Last sync: 5 months ago` now.

I am pretty sure that @Ch3LL says it's happening for her as well.

**Comment by andrew** [comment]
@rallytime after a bit of digging, I found the bug, the subject of one of your notifications contained a null byte character that postgres wasn't happy with, https://github.com/octobox/octobox/pull/705 should fix it, will deploy it later today.

**Comment by rallytime** [comment]
Awesome! Thanks @andrew!

**Comment by andrew** [comment]
Just deployed this and tested out the notification syncing on both @rallytime and @Ch3LL's accounts, looks like it's fixed it

**Comment by rallytime** [comment]
yes, it's fixed! Thank you @andrew!
