### ISSUE TITLE
Add a filter for closed/merged issues/PRs

### ISSUE THREAD

**Issue by dctucker** [octobox/octobox#545]
Encouraged by @tarebyte to write up this issue.

🎯 **Goal**

As I'm going through my inbox and filtering down to things that I'd like to archive and/or mute, I find myself wanting to select all merged issues and archive them so I can decrease my unread count.

💡 **Possible solutions**

One thing that may help with this would be a filter for `Closed` or `Merged` issues, effectively a negated `Open` filter.

This might be the simplest way to introduce such a feature, although to generalize it would also be nice to be able to negate other filters such as Author to see everything that isn't mine, or anything that doesn't Mention me (just a few extra thoughts).

**Comment by chrisarcand** [comment]
Oh man, I must have been super tired when I saw this originally. Yes @dctucker this feature is already implemented, it's just not available on octobox.io. You can run Octobox yourself and [enable subject fetching](https://github.com/octobox/octobox/blob/7a6b3e894bc5a747bb28dc1e90730038c4f4485f/INSTALLATION.md#downloading-subjects)

Closing this but feel free to ask any other questions you might have!
