### ISSUE TITLE
Navigation builds on filters

### ISSUE THREAD

**Issue by davejlong** [octobox/octobox#55]
Steps for issue:

1. Click Pull Request
2. Click Assign
3. Click Read

## Expected result:

When I click through the nav elements, I expect to see the same amount of notifications as what's in the count indicator to the right of the nav element.

## Actual result:

After clicking Pull Request, the rest of the pages only show Pull Request notifications. The only way to clear out the filter is to go back to the home page.

**Comment by davejlong** [comment]
I went to submit a PR to fix this, but noticed that it seems to be by design. So I guess there are 2 possible solutions:

1. Don't cache type filter across requests. The type is pulled from the query params to build URLs for the other nav elements.
2. Make the count indicator more usable by pointing out how many notifications the user should expect to see. Commonly this is shown as `2/7` to say that there are 7 total notifications, but with the current filters you, the user, will see 2 of them.

**Comment by andrew** [comment]
Agree it's confusing right now, this was the result of not making the code to complex or hitting the database too hard, needs some thought into exactly what should be filterable by what that can be done in a performant way

**Comment by davejlong** [comment]
I can totally see value in saving the notification type (PR/Issue) and the reasons. Most of the time, I just want to look at PRs where I'm assigned or Issues where I'm the author/subscriber. I think the latter solution of showing the count of notifications with the current filters along with total notifications would impose the best usability. That also would need to include a way to clear out filters.

**Comment by andrew** [comment]
I think this has been mostly fixed by @knolleary now 🌮
