### ISSUE TITLE
No notification for subscribed issue being closed

### ISSUE THREAD

**Issue by dracan** [octobox/octobox#550]
Hi. Following on from [this Twitter thread](https://twitter.com/teabass/status/968114348756529152) - I had created [this GitHub issue](https://github.com/GitTools/GitReleaseManager/issues/105), and was subscribed to it. When it was closed, the notification _was_ in my "All Notification" section in Github, but didn't appear at all in Octobox.

---

Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

**Comment by chrisarcand** [comment]
Can't recreate this running locally, seems to work fine 😕 Tried both with and without subject syncing.

**Comment by dracan** [comment]
@chrisarcand I didn't get a notification about your comment either. I have everything ticked in my notification settings. I've only recently started using this, but I have had notifications before (I can see them now in my archived items) for issues I've been watching. New ones (eg. this thread) just aren't appearing at all in the Octobox webapp.

**Comment by chrisarcand** [comment]
I should ask, have you tried manually clicking the sync button yourself? (IIRC autorefresh is disabled on octobox.io, so if you're waiting for notifications to just appear, they won't).

**Comment by dracan** [comment]
Yes, of course :) I've even tried deleting my cookies and re-authenticating. Octobox seems to have no knowledge whatsoever of this thread (or the thread I mentioned in my initial post above).

**Comment by dracan** [comment]
I am getting watch notifications for issues I've been subscribed to in the past. It might not be this, but it's possible that it's only happening with recently subscribed issues. I've just had a couple of notifications for activity on a much older issue (different repo).

**Comment by andrew** [comment]
@dracan is this still happening to you, was it on a public or private repository?

**Comment by dracan** [comment]
@andrew To be honest, I stopped using it because of this issue, so I don't know. It was your hosted version.

**Comment by andrew** [comment]
Ok I’m going to close it if you’re not using it anymore, if you change your mind and want to try it out again and run into this problem again feel free to reopen.
