### ISSUE TITLE
Support emoji in labels 🏷

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#559]
<img width="414" alt="screen shot 2018-03-18 at 17 47 58" src="https://user-images.githubusercontent.com/1060/37569013-a2a1ceea-2ad4-11e8-99ef-27b355c997f6.png">

Just noticed that we don't turn `:+1:` into the correct emoji when used in a label since support for emoji in labels was added to GitHub last month: https://blog.github.com/2018-02-22-label-improvements-emoji-descriptions-and-more/

**Comment by andrew** [comment]
We can probably use https://github.com/github/gemoji to do a lot of the heavy lifting for us

**Comment by chaserx** [comment]
this looks like fun. I'll take a crack at it.
