### ISSUE TITLE
UI Updates

### ISSUE THREAD

**Issue by jaymiejones86** [octobox/octobox#56]
I wanted to start this discussion about a direction for the UI as it is an area that can provide great discussion and can be a moderately easy area to start contributing to for new contributors to open source to get into (YMMVY).

Please add your thoughts on UI direction below with reasoning for the change or direction.

**Comment by jaymiejones86** [comment]
I would like to make the focus a bit stronger on the messages view as that is the primary area of focus.

I would also like to look at updating the container styling to accommodate some colour, for example (rough in browser mock of the top bar):
![image](https://cloud.githubusercontent.com/assets/1390569/21329817/cd46c78c-c68e-11e6-89c8-c02127a228d0.png)

I outline the above as these can be seen as fairly low hanging fruit but will provide a good impact to the project. What are your thoughts and design approaches?

**Comment by tarebyte** [comment]
@jaymiejones86 ❤️ the direction this is going.

Would it be helpful to show display the user's login with avatar on the navbar for their context?

**Comment by jaymiejones86** [comment]
@tarebyte that is a great suggestion for usability, showing who you are logged in as.

**Comment by andrew** [comment]
Looking good, reminds me of a previous version of outlook.com 👍

**Comment by tarebyte** [comment]
Also reminds me of Fastmail

<img width="1440" alt="screen shot 2016-12-19 at 17 30 24" src="https://cloud.githubusercontent.com/assets/564113/21331523/dbab677a-c610-11e6-86fe-f9a47466209d.png">

**Comment by briannelson** [comment]
Working on this for #15 

<img width="1206" alt="octobox" src="https://cloud.githubusercontent.com/assets/29120/21352527/e25eea54-c68f-11e6-9633-2078c3d1fb18.png">

**Comment by jaymiejones86** [comment]
This is great @briannelson.

Do we want to add some colour or keep the colour scheme fairly minimal to keep the focus on the messages themselves?

**Comment by briannelson** [comment]
@jaymiejones86 I've since added some styles to make the UI a lot closer to Github's design, which should (theoretically) be less of a taxing context-switch.
