### ISSUE TITLE
Missing notifications and labels

### ISSUE THREAD

**Issue by rhuss** [octobox/octobox#561]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [X] My instance

🐞 **Problem**

When switching on `FETCH_SUBJECT=true` then each label appears only exactly once in the overview:

![image](https://user-images.githubusercontent.com/99080/37609884-8d54f52e-2b9e-11e8-9b20-13040145c092.png)

In the screenshot above, many issue e.g. carry the label `group/ui` but it is shown only on the first line.

**Comment by rhuss** [comment]
Also, I have the feeling that when `FETCH_SUBJECT=true` is switched on, that I miss notifications in the view. See below two screenshots from two different installation, one with FETCH_SUBJECT switched on, the other one without (right after a fresh refresh on both)

<img width="867" alt="image" src="https://user-images.githubusercontent.com/99080/37682082-ce92d87c-2c88-11e8-8672-18a2408417d8.png">

<img width="864" alt="image" src="https://user-images.githubusercontent.com/99080/37682065-c530341e-2c88-11e8-95d3-e05f954f7ac2.png">

**Comment by aslakknutsen** [comment]
I can confirm this behavior. I was running a local v with the Labels PR merged and FETCH_SUBJECT on. It essentially grinded to a halt performance wise after some time and I was missing 'most' of the notifications.

Didn't debug the issue much, but one thing I noticed was that the check for duplicate labels didn't match how they were stored. So the check thought the label wasn't there, attempted to insert it, which caused a unique constraint violation and a Postgres rollback.

```

database.service.octobox.internal_1  | ERROR:  duplicate key value violates unique constraint "labels_pkey"
database.service.octobox.internal_1  | DETAIL:  Key (id)=(627758081) already exists.
database.service.octobox.internal_1  | STATEMENT:  INSERT INTO "labels" ("id", "name", "color", "subject_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"
app_1                                |   SQL (1.6ms)  INSERT INTO "labels" ("id", "name", "color", "subject_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["id", 627758081], ["name", "SEV2-high"], ["color", "666666"], ["subject_id", 881], ["created_at", "2018-03-25 12:05:15.112115"], ["updated_at", "2018-03-25 12:05:15.112115"]]
app_1                                |    (0.4ms)  ROLLBACK
```

**Comment by rhuss** [comment]
I can confirm the same issue here for me.

First I thought it might be an issue with transaction isolation levels (i.e. having a level of READ_COMMITTED or larger and no first level cache, you won't find objects with a select (without 'FOR UPGRADE' suffix which you have created in the same transaction), but actually the insert fails on already existing labels. And tbh, I have no ideas how ActiveRecords does its transaction handling or first level caching.

So my next suspection is, that the ORM mapping are wrong. The error messages above are happening while persisting an Notification, so it's probably ActiceRecord itself that thinks that he has to create a new Label object instead of correlating it to an already existing one.

Not sure how the ownership for relations is handled in ActiveRecord, but shouldn't in https://github.com/octobox/octobox/blob/bd6c2cbc4745363240482f36210509830d0c4bc1/app/models/subject.rb#L1-L3

be also a reference to the `primary_key` like for the `notifications` mapping, as the key actually is not managed by rails, but an external one ?

Again, I can be completely off here. would be awesome if some ActiveRecord guru could have a look on the mappings and whether they are are correct and we should look elsewhere.

**Comment by rhuss** [comment]
Actually, looking in the generated schema for the table `labels` backs my assumption that the mappings are wrong:

```
postgres-# \d labels
                                     Table "public.labels"
   Column   |            Type             |                      Modifiers
------------+-----------------------------+-----------------------------------------------------
 id         | bigint                      | not null default nextval('labels_id_seq'::regclass)
 name       | character varying           |
 color      | character varying           |
 subject_id | bigint                      |
 created_at | timestamp without time zone | not null
 updated_at | timestamp without time zone | not null
Indexes:
    "labels_pkey" PRIMARY KEY, btree (id)
    "index_labels_on_name" btree (name)
    "index_labels_on_subject_id" btree (subject_id)
Foreign-key constraints:
    "fk_rails_36daa92989" FOREIGN KEY (subject_id) REFERENCES subjects(id) ON UPDATE CASCADE ON DELETE CASCADE
```

A label is actually independent from a `subject` and can be reused of course in many issues/pullrequests. So there must be no column `subject_id`

Actually, the relationship between label:subjects is N:M and not N:1. I would expect to have a dedicated relationship table for this kind of N:M mapping.

'guess this needs a bit more work to get it running again and I wonder how it could have ever worked initially // cc @natemcmaster

**Comment by rhuss** [comment]
Maybe something like 

```ruby
class Subject < ApplicationRecord
  has_many :subjectlabels
  has_many :labels, through: :subjectlabels
end

class Label < ApplicationRecord
  has_many :subjectlabels
  has_many :subjects, through: :subjectlabels
end

class SubjectLabel < ApplicationRecord
  belongs_to :subject
  belongs_to :label
end
```

?

**Comment by andrew** [comment]
I think I can see the issue here, `label.id` is being stored as the remote label id from github, which explains why things are disappearing, we should probably be storing the id from github as `github_id` rather than in `id` here: https://github.com/octobox/octobox/blob/master/app/models/subject.rb#L17

I'll take a stab at tackling this tomorrow morning if no-one else

**Comment by rhuss** [comment]
@andrew but then, wouldn't you end up re-creating a the same label for every subject if the label is used multiple times ? 

I really believe that the domain model is wrong here:

* A subject (pr/issue) can have one or more labels
* A label can be used for one ore more subjects (pr/issue)

But currently it's modelled has the labels attached to a subject as specific to this subject only. 

This means, even when you change the id to a surrogate id under control from Octobox, you can't filter on labes anymore (as you have now many same-named labels but with different ids). When you select such a filter you only will find a single subject (that to which the labels belongs to).

There are other issue, e.g. when the label get renamed.

I really would go for a many-to-many relationship between subject and label, as this is the way how GitHub handles it. And taking over the GitHub label id is actually the correct way IMO.

If I only would know rails more, I really would help here (shouldn't be hard). 'guess it's now time to confess that I am a old-time Perl lover and earn my money mostly with Java coding (so if this would be Hibernate or another Java ORM, I would be probably of more help).

**Comment by andrew** [comment]
We filter labels by their name, rather than id now: https://github.com/octobox/octobox/blob/master/app/models/notification.rb#L37

I'm imagining that we'd also change this line: https://github.com/octobox/octobox/blob/master/app/models/subject.rb#L14 so that way, we'd end up automatically picking up when a label's colour or or name has changed whilst still attached to the same subject

**Comment by rhuss** [comment]
> We filter labels by their name, rather than id now: /app/models/notification.rb@master#L37

yes, that makes perfectly sense to catch cross-repo, same-named labels.

> I'm imagining that we'd also change this line: /app/models/subject.rb@master#L14 so that way, we'd end up automatically picking up when a label's colour or or name has changed whilst still attached to the same subject

Actually, if you go the denormalized route (e.g. having the same github labels multiple times per subject which use them), then you probably need to update or find multiple labels here (by their github id) and update them.

Well, no more speculating, curious to see which what you come up ;-)

thanks, its really something I'm looking forward to (and was the primary reason to go for an own installation).

**Comment by andrew** [comment]
@rhuss started a branch over here if you'd like to try it out locally: https://github.com/octobox/octobox/pull/575

**Comment by andrew** [comment]
This got closed automatically but I think it solves the issue as @rhuss tested out the branch and it seemed to fix the problem.

**Comment by rhuss** [comment]
Yes #575 fixes the described issues.

Trying now from `master` and would reopen it or create a new issues if this would be different.

**Comment by Alexkho82** [comment]
#561
