### ISSUE TITLE
[enhancement] Repository audit from @mntnr

### ISSUE THREAD

**Issue by RichardLitt** [octobox/octobox#585]
Hello there! :wave:

This is audit from @mntnr. This was requested by @andrew through Open Collective, on Twitter. 

Let me know if you have any questions!

## Repository Review: octobox/octobox

> :postbox: Take back control of your GitHub Notifications

_For notes on anything crossed out, look below. Note: I use `[~]` to mean that I have proposed a fix in a PR. I know it doesn't render properly in Markdown, but it works pretty well otherwise for that purpose._

### Reviewing the Repository Docs

- [x] Is there a README?
  - [ ] Is it standardized?
    - _No, but this is totally fine. I think what it has is good._
  - [x] Is it spellchecked?
- [x] Is there a Code of Conduct? https://github.com/simonv3/covgen
  - [x] Is it mentioned in the Contribute section of the README?
  - [x] Does it reference an email address for violations?
  - [ ] Does it reference a second email address?
- [x] Is there a `LICENSE`?
  - [x] Is this matched in the `package.json`?
  - [x] Is the year correct?
  - [x] [`licensee`](https://github.com/jslicense/licensee.js) throws no egregious errors?
- [ ] Is there a `.github` folder?
  - [x] Is there an `ISSUE_TEMPLATE.md`?
  - [ ] Is there a `PULL_REQUEST_TEMPLATE.md`?
- [x] Is there a `CONTRIBUTING.md` file?
- [ ] Is there a `CHANGELOG`?
- [ ] Does this pass [`alex`](https://github.com/wooorm/alex) adequately? Run `alex *.md`.
  - _More or less. You could use 'turned off' instead of 'disabled'._
- [x] Does the repository name itself pass on http://wordsafety.com?

### Process
- [x] Can I install easily?

### Issues and Pull Requests
- [x] Are there an acceptable amount of pull requests?
- [x] Are there an acceptable amount of issues?
- [x] Are an acceptable amount of issues less than six months old?
- [x] Are there useful issue labels?
- [x] Are the labels being used?
- [ ] Is there a `good for beginners` or `up-for-grabs` label?
- [ ] Is there a `waiting on contributor` label?

### Bots 

_Note: Neither of these are necessary, but they can help with some things. Check out https://probot.github.io/ for some tools._

- [ ] Are there bots enabled?
- [ ] Is there a CLA?
  - [ ] Is there a bot to help with the CLA?

### Metadata
- [x] Is there a description on GitHub?
  - [~] Does the description match the README?
- [x] Are the topics useful?
- [x] Is there a website?
  - [x] Does the website match the project?

### Package Metadata

Note: These should apply to `package.json` (JavaScript), `*.cabal` (Haskell), `metadata.yml` (Perl), and gemspec files (Ruby).

- [ ] Does the description match the gh-description?
- [ ] Is there a `bugs` field?
- [ ] Is there a `homepage` field?
- [ ] Are there appropriate keywords?
  - [ ] Do these match the keywords on GitHub?
- [ ] Run [`depcheck`](https://www.npmjs.com/package/depcheck); do the deps make sense?

#### Generic
- [ ] Consider adding a secondary email to the Code of Conduct as a contact - someone may have an issue with _you_ but not want to tell you directly. I know, this idea may be awkward. But you will give them an option in case they do have an option, and this may be good for the overall health of the project.
- [ ] Consider adding `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md` files to your repository. It looks like you have your PRs well under control, but these may help you in the future. At the least, ask them to run the tests, first, and to read the Usage guides.
- [ ] Consider adding a `CHANGELOG`.
- [ ] Consider adding a CLA or asking for signed commits, if you're worried about legality. This is generally only needed when you are building a business out of a code base. In your case, I think you're OK.
- [ ] Add a `Gemspec` or `metadata.yml` file. Right now, there isn't a clear file for metadata. This can limit usage.

#### Issues
- [ ] Add 'discussion' labels to longstanding issues. For instance, __#issues__
- [ ] Add a couple of small, scoped issues and label them as `up-for-grabs`. See http://up-for-grabs.net. This will help more people interact with your code, and lead to small, iterative work done by others. It may take some time to set up initially - thinking of scoped issues - but the payback should be worth it.
- [ ] I label pull requests where I am waiting on the Contributor to respond `waiting-on-contributor`. This helps alleviate pressure on you to close them.

#### Conclusion

Overall, I think this is well done. The README is very clear, and shows a lot of love. I've highlighted some small things that may help. Let me know if you want help with them.

**Comment by andrew** [comment]
Awesome, thanks @RichardLitt! 

One error I noticed, we do have an [ISSUE_TEMPLATE.md](https://github.com/octobox/octobox/blob/master/ISSUE_TEMPLATE.md) but it's in the route instead of `.github` folder, and according to GitHub documentation `docs` folder is also a valid location for it.
