### ISSUE TITLE
Can't mark a message as read when I don't have access to the repo anymore

### ISSUE THREAD

**Issue by di** [octobox/octobox#591]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
I have a number of notifications in Octobox from repositories that I no longer have access to (no longer a member of the parent organization).

Attempting to mark any of these as "read" results in this error:

> Your GitHub token seems to be invalid. Please try again.

🎯 **Goal**
I'd like to mark these old notifications as read -- I don't care about them anymore.

💡 **Possible solutions**
Instead of raising an error message, Octobox should allow me to mark the issue as read, or just remove them entirely.

(btw, thanks for a really nice tool!)

**Comment by Alexkho82** [comment]
#591

**Comment by andrew** [comment]
@di I've opened a PR with a fix for this over here: https://github.com/octobox/octobox/pull/670
