### ISSUE TITLE
[idea] Provide a switch to show/hide notifications from bots

### ISSUE THREAD

**Issue by vvo** [octobox/octobox#599]
Hi!

Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io

🐞 **Problem**
I use a lot https://renovateapp.com/docs/ from @rarkins. And I use a lot Octobox (I only use Octobox for every notifications on GitHub).

Here's an example repo I contribute to:
![image](https://user-images.githubusercontent.com/123822/38626278-7f7c7826-3dac-11e8-9b56-98801ee3f18c.png)

Because renovate creates a lof of PRs, I get a lot of notifications. I do want to go through them but not at the same priority than other issues. So it's a struggle for me to got through my good notifications first and then handle renovate PRs.

🎯 **Goal**
I would like to be able to have a switch that says "Display notifications from bots", and by just activating/deactivating it would completely change the current view by not showing notifications from a list of predefined usernames.

Is anyone else having this kind of issues? If so jump in so I can if this is popular.

💡 **Possible solutions**
Provide a switch in the UI to show/hide notifications from bots. So that I can first hide them all, deal with "real notifications from people" and then deal with renovate.

📋  **Steps to solve the problem**
None taken for now but raising the issue.

Thanks a lot!

**Comment by andrew** [comment]
https://github.com/octobox/octobox/pull/770 has been merged now so you can filter by bots from the sidebar, although it's not available on https://octobox.io just yet.

**Comment by andrew** [comment]
Going to close this as it'll be available on https://octobox.io very soon

**Comment by vvo** [comment]
@renovate-bot I failed at understanding what you meant here sorry (for real what do you mean :D)
