### ISSUE TITLE
Allow archiving multiple notifications simultaneously

### ISSUE THREAD

**Issue by jdm** [octobox/octobox#60]
I'm envisioning pressing `x` to mark the checkbox for a notification, then `y` will archive all of the currently selected notifications.

**Comment by andrew** [comment]
Sounds good, making the checkboxes behave more like gmail with an archive button ftw

**Comment by pirate** [comment]
I thought the current behavior was a bug when I first used it.  I think most users don't expect the checkbox to immediately perform an action, they expect it to mark a selection for later actions (a la gmail, iTunes, Windows file manager, etc.) so this is a good fix.

**Comment by karpiu** [comment]
@andrew You still need help with this one? I can do it, if nobody is working on it.

**Comment by andrew** [comment]
@karpiu sure, I don't think anyone is working on it right now

**Comment by karpiu** [comment]
@andrew Should this behaviour only apply to keyboard actions (marking with `x`) or also to mouse clicks? If both, then how will the archiving with mouse work? Should a button 'Archive selected' appear after clicking on at least one checkbox?

**Comment by andrew** [comment]
@karpiu I'd make it work the same for both mouse and keyboard, as you said, an "Archive selected" button should appear if once one checkbox is selected 👍

**Comment by andrew** [comment]
This is live now thanks to @karpiu  🎉

**Comment by karpiu** [comment]
@andrew unarchiving is still one click at a time though :worried:

**Comment by andrew** [comment]
@karpiu Reopened, sorry I'm too eager!

**Comment by karpiu** [comment]
@andrew Heh. I tought you would make another issue for it, but this is fine too. I will fix unarchiving shortly.
