### ISSUE TITLE
Restricting to multiple orgs possible?

### ISSUE THREAD

**Issue by Skeyelab** [octobox/octobox#623]
**Question**
We have multiple orgs in our company.  Is it possible to pass multiple org ID's?

Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

**Comment by andrew** [comment]
@Skeyelab looking at the code, it currently only supports one org but that sounds like a good feature to add 👍

**Comment by Alexkho82** [comment]
#623

**Comment by BenJam** [comment]
bump: not sure this is still relevant given some of the github app based work...

**Comment by andrew** [comment]
@BenJam it's related to [this](https://github.com/octobox/octobox/blob/master/docs/INSTALLATION.md#limiting-access) feature which is useful when you're running your own instance on the public internet but want to limit who can use it.
