### ISSUE TITLE
Show icons to act on a notification when hovering over it

### ISSUE THREAD

**Issue by pradyunsg** [octobox/octobox#648]
Are you experiencing this issue in octobox.io or your own instance?
 - ✅ octobox.io
 - My instance (not yet; any way to deploy it for free?)

**Problem**

Show archive and mute buttons for an entry when hovering over it.

**Goal**

This would optimize my workflow where I open an issue, check and see if there's anything actionable. If I'm not interested, I mute it otherwise, once I close an issue, I archive it. I'd guess this to be a common workflow among the users.

Currently the last part of it (archiving/muting a single notification) takes 2 fairly separated, small targets to be clicked. Getting a single icon that can be clicked when hovering over a notification would help simplify that workflow.

In terms of UX, archiving/muting a single notification is likely a common operation and making it easier to do is a good thing. :)

**Possible solutions**

Might be a purely frontend change. If so, it'd just need to have an element that gets shown when hovering over an entry and then that when clicked dispatches the same request as selecting and archiving would; I guess.

**Comment by andrew** [comment]
@pradyunsg yeah I think this is a good idea, gmail does a very similar thing:

<img width="402" alt="screen shot 2018-07-27 at 11 47 53" src="https://user-images.githubusercontent.com/1060/43316964-fc1c2aea-9192-11e8-81e1-354e7e75947b.png">

**Comment by pradyunsg** [comment]
Indeed.

@andrew I'm not super familiar with this codebase but if you could point me to the appropriate section of code here, I could take a stab at this.

**Comment by andrew** [comment]
@pradyunsg I think @BenJam is going to tackle this as he's implementing those buttons in https://github.com/octobox/octobox/pull/709 already and can just port them over

**Comment by pradyunsg** [comment]
Awesome. Glad to hear that. :)

**Comment by andrew** [comment]
Made a start on this as I think #709 is going to take a bit longer: https://github.com/octobox/octobox/pull/823

**Comment by pradyunsg** [comment]
Hurrah!
