### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by fd0** [octobox/octobox#652]
This is not a bug report or other issue: I'd like to thank you so much for making GitHub notifications usable again! As the main author of [restic](https://github.com/restic/restic), a fast and secure deduplicating backup program, I quickly lost track of what I still need to respond to versus what can be left alone until something else happens. Thanks for adding the distinction between `archived` and `unread`!

(issue can be closed at will)

**Comment by andrew** [comment]
Thanks so much! ❤️

**Comment by tsupertramp** [comment]
Thanks for this awesome tool. I really enjoy using it every day! <3

**Comment by dictvm** [comment]
Thanks for this awesome project. It's saving me a lot of time since my employer started going all in into Github! <3

**Comment by pbollenbeck** [comment]
Thank you very much for your contribution! It's a great tool and it improves my work life every day.
❤️

**Comment by arthurnn** [comment]
Thanks to you all ❤️
