### ISSUE TITLE
[feature] Filter & visualize PR/issue status (open/merged/closed)

### ISSUE THREAD

**Issue by marnovo** [octobox/octobox#653]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

This feature solves the problem of not knowing which PRs and issues are merged/closed, thus probably not worth reading or worth (bulk) archiving straight away.

🎯 **Goal**

This is important because, differently from GitHub notifications that use color coded icons for open/merged/closed issues and PRs, right now you have to open each issue or PR on Octobox to see if it has been merged/closed or if it is still open.

Most of the times, feedback/input is unlikely or unnecessary after PRs/issues have been closed or merged, thus it is very useful to be able to filter these out beforehand.

This is the case of most of the people I know and have worked with, and would save people a ton of time (and would allow many of us to finally retire GitHub notifications).

💡 **Possible solutions**

This feature could be implemented either/both:

1. a filter on the left side panel
2. the color coding GitHub already uses in the icons

Both would be very useful for two different use cases: bulk filtering/archiving (1) visual screening (2).

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by andrew** [comment]
@marnovo this feature is already available if you run your own version of octobox, see [Downloading subjects](https://github.com/octobox/octobox/blob/master/docs/INSTALLATION.md#downloading-subjects) and will be coming to Octobox.io next month
