### ISSUE TITLE
Add a 'Filter by' icon next to a repo in the List

### ISSUE THREAD

**Issue by afilp** [octobox/octobox#661]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **ENHANCEMENT**

Add an icon here (see screenshot) so that we can filter for that `repo` immediately.
![image](https://user-images.githubusercontent.com/7850073/41648421-83b38b12-7481-11e8-98d3-68b60262c34d.png)

This new **feature** will help us to immediately select and mark all new watched posts of a `repo` as `read` or as `archived`. Now I have to search for the `repo` by name to filter it, etc.

After clicking on this small icon, we will be in the `filter` screen:

![image](https://user-images.githubusercontent.com/7850073/41648537-dcac9b82-7481-11e8-91b3-46b7fde57dda.png)

So, now it is easier to mark all of them. 

It is a nice/quick shortcut to deal with posts of a particular repo ASAP.

Thanks!

**Comment by andrew** [comment]
Closing this now as clicking on the repo link always filters the UI instead of opening the repo in a new tab
