### ISSUE TITLE
Broken Link in website "open an issue"

### ISSUE THREAD

**Issue by movermeyer** [octobox/octobox#663]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io

🐞 **Problem**

The "open an issue" link on https://octobox.io/ is broken:

* It is currently: https://octobox.io/#https://github.com/octobox/octobox/issues/new
* It should be: https://github.com/octobox/octobox/issues/new

None of the other links are broken.

**Comment by andrew** [comment]
Thanks for reporting, just deploying a fix now
