### ISSUE TITLE
UX question

### ISSUE THREAD

**Issue by M-Zuber** [octobox/octobox#68]
I did not find that a checkbox to archive was intuitive enough (especially considering that #60 has not yet landed so only one can be selected at a time)

Related (as this is my current blocker to making a pr) is there any way to work with just the client side and have it connect to octobox.io or similar?

**Comment by andrew** [comment]
Making the checkboxes act more like gmail with an archive button at the top would be good

There's no way to run the clientside without the rails app as they are one and the same

**Comment by M-Zuber** [comment]
🤔 Let us see how work goes today, I might be tempted to try and pr anyways. (have 23 left for 24pullrequests 😨 )
