### ISSUE TITLE
Toggle between light and dark theme from the settings

### ISSUE THREAD

**Issue by Ullaakut** [octobox/octobox#699]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [x] My instance

🐞 **Problem**
I really like Octobox, and it's awesome that it's possible to self-host it. The only missing feature for me is the possibility to switch between a dark/light theme in the settings.

🎯 **Goal**
Dark themes are not just something for edgy people who like the dark, it's actually a good feature to have to avoid straining on the eyes, especially for people that often work in a low-light environment. (For example, I usually start working around 6am while it's still dark, so I try to avoid black text on white background as much as possible).

Something to keep in mind though is the contrast between the background and text colours, as well as font size and other accessibility factors. They should comply with W3C’s AA-level standards.

Since Octobox is a professional tool that is probably mostly used throughout the day for extended periods of time, reducing screen glare is important. That's why Photoshop, Adobe products and even more recently MacOS are introducing dark themes.

💡 **Possible solutions**
Someone actually already made a [dark theme UserStyle](https://userstyles.org/styles/156469/octobox-io-dark-tst2005) for Octobox, which requires the use of the Stylish or Stylus browser extensions, and since it isn't directly within the repository, changes to the UI will break this dark theme implementation.

I think the best way to add this feature would be to have a toggle in the settings, and from the quick look I gave to the data models in the db it looks like we could store it into a boolean value in the `users` table.

As for the sass, I guess we could use variables for the backgrounds, font colors, etc. and compile it once while importing a `light_theme.scss` file that would set those variables for the light version, and once while importing a `dark_theme.scss` file. This way, we generate both sets of css.

Now as for switching to the right css depending on the theme, I'm afraid I don't know enough of how the frontend works for Octobox, but I could look into it.

<img width="1474" alt="screenshot 2018-07-23 at 06 25 06" src="https://user-images.githubusercontent.com/6976628/43057235-4cb4b7e2-8e41-11e8-8d3d-aa33889d3bc1.png">

Dark theme implementation from [tst2005](https://github.com/tst2005)

📋  **Steps to solve the problem**

Not started yet. I'd like to get some feedback on the feature request first, as well as maybe some technical insights as to whether or not the solutions I described above make sense.

**Comment by andrew** [comment]
@Ullaakut I think the best way to make the switch would be if there was a class of `dark` on the `<body>` element of the page, I can add the user preference to switch between dark and light modes in the settings that adds that class.

**Comment by Ullaakut** [comment]
Sounds good!

Then I guess I'll get started on making a custom set of stylesheet changes when I have some time and ask you for some feedback before making changes to the `scss` files and opening a PR.

Thanks @andrew ! 👍

**Comment by andrew** [comment]
Sweet, looking forward to it

**Comment by Ullaakut** [comment]
Turns out my personal situation changed, so I won't be working on this for a while. It would probably be wise to change the label, sorry about that 😅

**Comment by andrew** [comment]
ok, thanks for letting us know @Ullaakut, I'll try to pick this up next week
