### ISSUE TITLE
Muting

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#7]
Allow muting of a notification or thread, either via the github watching/not watching functionality or something built into the app that stops the notification becoming unarchived again automatically.

**Comment by WillAbides** [comment]
It would be nice to sync this with the ignored attribute on the [thread subscription api](https://developer.github.com/v3/activity/notifications/#parameters-4).  Unfortunately that isn't available on the list of notifications, so syncing that would require an api call per notification.

**Comment by andrew** [comment]
@WillAbides dependent on #4 then

**Comment by WillAbides** [comment]
@andrew:  I don't think this is actually dependent on #4.  #4 is about grabbing the target, but this would be a separate call to /threads/:id/subscription.

I don't think it would be worth adding N queries when syncing just to get the ignore status.  Add a mute option that makes the api call to set the thread to ignore=true and then archives the notification locally.

**Comment by andrew** [comment]
@WillAbides sounds like a good idea, a "blind mute" if you will
