### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#703]
It'd be great to be able to be able to offer support languages other than English in the interface and make the app more friendly to people from all around the world.

Rails has good I18n support, details in the guide here: https://guides.rubyonrails.org/i18n.html

I've also been through the process with one of my other open source projects, [24pullrequests](https://github.com/24pullrequests/24pullrequests), which has been translated into [18 different languages](https://github.com/24pullrequests/24pullrequests/tree/master/config/locales)!

The first step will be to move all the strings from the views and controllers into an `en` local file, then can reach out to some multi-lingual users to get help with the translation and add a local switcher once we have more than one.

I suspect the only tricky part will be localizing the strings that come from the GitHub API, like the `reason` and subject `state` fields. 

Let's avoid trying to translate user generated content at this point (`subject_title` or label content) for example)

**Comment by pradyunsg** [comment]
I'm up for doing a Hindi translation but I'm yet to see someone file an issue in Hindi on GitHub so, I don't know if it'd be useful.

**Comment by bestest-mensch** [comment]
Hey @andrew, I would be up for moving the string into the local file if this still needs to be done.
