### ISSUE TITLE
Add 404, 422 and 500 error pages

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#710]
Our current html error pages are the rails default ones and look a bit sad, would be nice to have something a bit more in-keeping with the Octobox style.

![screen shot 2018-07-30 at 16 23 01](https://user-images.githubusercontent.com/1060/43406919-2f8edb14-9415-11e8-893c-a2d5ba5a0c20.png)

**Comment by pradyunsg** [comment]
Is this just a matter of adding self-contained .html files in some directory? If so, I'd be happy to do this. :)

**Comment by pradyunsg** [comment]
In fact, I'd be happy to contribute/suggest some UI related changes to Octobox in general but I'm not super familiar with Ruby/Rails so I'm not sure how I can get started.

Any pointers?

**Comment by andrew** [comment]
@pradyunsg here are the current self-contained .html files if you'd like to take a stab:

- https://github.com/octobox/octobox/blob/master/public/404.html
- https://github.com/octobox/octobox/blob/master/public/422.html
- https://github.com/octobox/octobox/blob/master/public/500.html

Alternatively we can render them with rails and get access to layouts, stylesheets etc, here's an example of how that was added to Libraries.io:

https://github.com/librariesio/libraries.io/commit/268cadab07ae4742e738f8eda70522517f5d96aa#diff-c972bc2ac8aea20490c3d38669180d96

**Comment by pradyunsg** [comment]
I'll take a stab at static pages sometime this weekend.

The layout based approach seems simple but I'll tackle that in a follow up PR to the other. :)

**Comment by andrew** [comment]
👍

**Comment by chrisarcand** [comment]
@DoctaCloak Unless you're thinking of something rather sophisticated, if you'd love to help out I would go ahead and implement your ideas and open a PR with screenshots and we'll iterate on your work :) Go for it!

**Comment by BenJam** [comment]
Bump. I'll pick this up.

**Comment by andrew** [comment]
Fixed in 
https://github.com/octobox/octobox/pull/1053
