### ISSUE TITLE
Octobox Heroku Deploy OAuth Question

### ISSUE THREAD

**Issue by audiolion** [octobox/octobox#718]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**

I seem to be having a bit of a chicken-and-egg problem where to deploy to Heroku I need a github OAuth client id/secret, and to create a github OAuth token I need the app homepage url and the github callback url.

![image](https://user-images.githubusercontent.com/2430381/43559649-dad77026-95dc-11e8-92b4-dff0c7f6cba4.png)

![image](https://user-images.githubusercontent.com/2430381/43559657-e4e81444-95dc-11e8-886c-064446413524.png)

🎯 **Goal**

Get updated documentation on deploying through the deploy button on Heroku, particularly I couldn't find the link to creating a new oauth token (https://github.com/settings/applications), and I am not sure how you solve the url being required on both ends and needing the token to deploy and needing the deployed url to make the token.

💡 **Possible solutions**

📋  **Steps to solve the problem**

**Comment by chrisarcand** [comment]
We can make this clearer in the docs, for sure.

By default, a Heroku app is available at its Heroku domain, which has the form `[name of app].herokuapp.com`; thus, your OAuth urls will just be dependent on whatever you enter in for the app name. The link for creating an OAuth token on GitHub is found in the local installation section but as someone who's just wanting to look how to deploy to Heroku instantly, it's easy to miss.

**Comment by audiolion** [comment]
Ok cool, I figured it was `[appname].herokuapp.com` but I didn't know that the homepage url and authorization callback url are just `[appname].herokuapp.com`, I thought it might be `[appname].herokuapp.com/auth/github/callback` or something
