### ISSUE TITLE
Long repo names cause sidebar to become too wide

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#719]
![screen shot 2018-08-02 at 09 19 08](https://user-images.githubusercontent.com/1060/43571697-87d4aaf2-9635-11e8-9d39-4167826be80b.png)

When there's a very long repo/org name in the filters, it extends the width of the sidebar instead of overflowing just that repo name, not a show stopper though.

cc @BenJam as I think this came in with the BS-4 upgrade in #366

**Comment by BenJam** [comment]
Boo... I'll take a look.

**Comment by BenJam** [comment]
Looks like Firefox only... 

<img width="437" alt="screen shot 2018-08-02 at 09 29 18" src="https://user-images.githubusercontent.com/158833/43572099-8d6d9914-9636-11e8-92d4-280d4e466847.png">

**Comment by pradyunsg** [comment]
Can confirm this occurs on FF.

FWIW, `.nav-item { max-width: 100% }` seems to do the trick. I've been injecting this CSS using Stylus since the day this got deployed and forgot to report this issue. :3

**Comment by andrew** [comment]
Thanks @pradyunsg, I'll get that added shortly
