### ISSUE TITLE
Horizontal scrollbar at Sidebar for long repo names

### ISSUE THREAD

**Issue by rhuss** [octobox/octobox#738]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [X] My instance

🐞 **Problem**

With the new layout (which is awesome btw, except maybe the bright aggresive blue ;-), for long repository names, a horizontal scrollbar is created and the box is clipped

![image](https://user-images.githubusercontent.com/99080/43644779-350a7cba-9730-11e8-82b2-51e46a57b858.png)

Also, the repo names overlap with the issue count

![image](https://user-images.githubusercontent.com/99080/43644684-efdee3a6-972f-11e8-8c79-14e390ce5ba4.png)

🎯 **Goal**

Would be nice if long repo names don't destroy the layout. Unrelated, but why are the issue counts so small ?

💡 **Possible solutions**

Truncate long repo names in the left sidebar

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by andrew** [comment]
Looks like a duplicate of https://github.com/octobox/octobox/issues/719

**Comment by rhuss** [comment]
yup, sorry for the noise.

**Comment by andrew** [comment]
@rhuss I just commited a fix for this to master
