### ISSUE TITLE
Undo function

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#741]
Borrowing yet another feature from Gmail, it'd be great to be able to undo a function that you did by accident, things like:

- Undo archiving one or more notification threads
- Undo muting one or more notification threads
- Keyboard shortcut for undo as well

And once #709 is complete, potentially even being able to "undo" posting a reply to a message (by delaying actual API call for 30 seconds), similar to the [Gmail Labs feature](https://www.pcworld.com/article/3197375/software-productivity/how-to-unsend-gmail-messages-with-the-undo-send-feature.html) 

Reminded of this as an alternative to https://github.com/octobox/octobox/issues/500 (hiding the mute button)

**Comment by pradyunsg** [comment]
Sounds good to me.

**Comment by franzliedke** [comment]
I'd love to see this as well, it happens quite often that I accidentally archive the wrong ticket (probably because a mouseover selected a different issue on the left than what I was looking at on the right), and then have a hard time finding it again.
