### ISSUE TITLE
When I click on an action such as "mute" or "archive" or "view details" the position of the navigation bar scrolls all the way back up to the top forgetting the position that I had scrolled to.

### ISSUE THREAD

**Issue by ghuntley** [octobox/octobox#757]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

When I click on an action such as "mute" or "archive" or "view details" the position of the navigation bar scrolls all the way back up to the top forgetting the position that I had scrolled to.

See https://youtu.be/pOmJd7K3lMc?t=7441

🎯 **Goal**

Don't make the user find their position after a navigation or mute/archive event.

**Comment by andrew** [comment]
💯 : for the video example!

**Comment by andrew** [comment]
I’m hoping there’s an option in turbolinks that can solve this easily, like: 

`Turbolinks.visit(location.href, {scroll: false});`

**Comment by andrew** [comment]
Similar issue: 
https://github.com/octobox/octobox/issues/495

**Comment by Robert-M-Muench** [comment]
This is really an annoying one when you track a couple of repos.
