### ISSUE TITLE
Sticky per-page settings

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#779]
I noticed that power users who get loads of daily notifications often set their per-page to 100 🏋️‍♀️ 

Only problem with that is that it's only persisted in the url, so if you go to the settings page or just click the logo you loose your per-page preference. 

We could easily save their per-page preference to their `User` record in the database after they change it from the dropdown and then use as their default for ever more (until they change it).

**Comment by pradyunsg** [comment]
I would really like this. :)

**Comment by andrew** [comment]
Thinking about this, it should probably just be stored in localstorage so users don't end up loading 100 notifications on mobile by accident 😅
