### ISSUE TITLE
Switch dashboard context

### ISSUE THREAD

**Issue by mycaule** [octobox/octobox#780]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
When I go to the app, my default account dashboard context shows up. I only have notifications from this space. For professional usage, I would like to be able to swtich dashboard context as my company uses a GitHub organization.

🎯 **Goal**
To be able to provide notifications for work only or for personal open source activities only.

💡 **Possible solutions**
Being able to switch dashboard context or organizations as Github allows it.

📋  **Steps to solve the problem**
- Modify Settings Page to be able to select an organization or dashboard context
- Filter only notifications related to that organization or dashboard context

**Comment by andrew** [comment]
I was only talking to @BenJam about this the other day, would be a great feature to help with focus 👍

**Comment by mycaule** [comment]
I am trying to use it with https://github.com/danielbayley/franz-recipe-octobox
I use Franz to I aggregate all my messaging service: email, slack, etc..
It would be time saving if I could have my (work related) github notitifcations there as well

**Comment by mycaule** [comment]
Something similar to https://github.com/kamranahmedse/git-standup but to search for recent issues, instead of recent commit would be great for stand-up meeting.
