### ISSUE TITLE
Display recent changelog entries within the UI

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#786]
Show users what's new in Octobox without needing to go to the open source project with some kind of changelog that remembers when a user last looked at it.

Something like https://headwayapp.co without actually using a third party service, ideally just pulling data for the releases section of the repo on GitHub.

**Comment by pradyunsg** [comment]
What's your thought on tagging rolling releases?

**Comment by andrew** [comment]
What I'd like to get to is a more human curated list of improvements rather than just a summary of the commits.

**Comment by pradyunsg** [comment]
https://github.com/hawkowl/towncrier is something pip's using lately.
