### ISSUE TITLE
Link to Octobox filters instead of Github profiles/project pages from Notification Row

### ISSUE THREAD

**Issue by pradyunsg** [octobox/octobox#788]
<img width="1390" alt="screen shot 2018-08-15 at 5 18 03 pm" src="https://user-images.githubusercontent.com/3275593/44146880-3e883a10-a0af-11e8-9ad3-f992652f55a5.png">

See above (ignoring that I right aligned the labels and haven't centered it; yet :P):

- 'andrew' links to @andrew's GH profile
- 'octobox/octobox' links to https://github.com/octobox/octobox

Proposed Change in behaviour:

- Notifications for things authored by `andrew`
- Notifications for things in the repo `octobox/octobox`

Reasoning:

- More often than not, I'd want to be filtering issues by repo. Clicking the name in the notification row; where my focus is currently is IMO much better than trying to search for it in a long tree of names.
- If I get a notification due to a user, I almost always want to see other notifications caused by that user; not their user profile on GitHub, which is what happens when I click their name. I understand that this is something that can't be done currently.

**Comment by andrew** [comment]
👍

**Comment by andrew** [comment]
@pradyunsg fixed in https://github.com/octobox/octobox/pull/790 and https://github.com/octobox/octobox/pull/791

**Comment by pradyunsg** [comment]
Both LGTM based on my fairly ridimentary rails knowledge. :)

**Comment by andrew** [comment]
Merged them both :shipit:
