### ISSUE TITLE
Style the checkboxes to be more consistent and easier to deal with aesthetically

### ISSUE THREAD

**Issue by pradyunsg** [octobox/octobox#792]
<img width="69" alt="screen shot 2018-08-16 at 3 11 07 pm" src="https://user-images.githubusercontent.com/3275593/44201361-add5b480-a166-11e8-8828-b96cf2cb9208.png"><img width="89" alt="screen shot 2018-08-16 at 3 11 21 pm" src="https://user-images.githubusercontent.com/3275593/44201363-af06e180-a166-11e8-9b72-68a2ca6ad581.png">

From the above screenshots, IMO having both the star and the checkbox be styled in the same manner, by the web application, is more aesthetically pleasing than having one be styled by the OS and the other be styled as a part of the web app. It'd also provide a more consistent experience across platforms. :)

Nit Picking: the spacing between the checkbox and the star is a little too big. :P

**Comment by andrew** [comment]
I think bootstrap has a custom checkbox style that will help here

**Comment by pradyunsg** [comment]
It does. https://getbootstrap.com/docs/4.1/components/forms/#checkboxes

**Comment by existentialmoron** [comment]
I would like to take this up :)

**Comment by andrew** [comment]
@existentialmoron go for it!

**Comment by prashuchaudhary** [comment]
#953 added Bootstrap Custom Checkboxes

**Comment by prashuchaudhary** [comment]
@andrew this is ready now.

**Comment by BenJam** [comment]
Bump. @pradyunsg can you submit a PR for this if ready?

**Comment by pradyunsg** [comment]
@prashuchaudary's PR does this IIUC.

**Comment by andrew** [comment]
This branch has an almost finished implementation: 
https://github.com/octobox/octobox/compare/custom-checkboxes

**Comment by prashuchaudhary** [comment]
@BenJam created PR #1057 with final changes. Added Screenshots for Both Light and Dark UI. Please review.

**Comment by andrew** [comment]
Fixed in #1057
