### ISSUE TITLE
Switch to a fixed width layout

### ISSUE THREAD

**Issue by pradyunsg** [octobox/octobox#793]
Currently, the notification rows are very wide. It makes it a little difficult to read the actual content.

<img width="1680" alt="screen shot 2018-08-16 at 3 48 04 pm" src="https://user-images.githubusercontent.com/3275593/44203176-cb594d00-a16b-11e8-8d5e-24009e3724c3.png">

Github handles this by putting the entire notifications UI in a centered layout, grouped by repository.

<img width="1680" alt="screen shot 2018-08-16 at 3 45 56 pm" src="https://user-images.githubusercontent.com/3275593/44203134-b381c900-a16b-11e8-84b7-bf07fb7658b1.png">

I'm trying to think of a more ergonomic layout, that exposes all the intended information without being overwhelming to the user. Just wanted to file this early so that I can see what others think about this.

I feel this should be applied uniformly for all users.

**Comment by andrew** [comment]
I find the really thin fixed with notifications on GH to be pretty annoying, often cutting of the full text of the title:

![screen shot 2018-08-16 at 11 48 55](https://user-images.githubusercontent.com/1060/44204443-76f1a580-a14a-11e8-8477-2fb5e2375f86.png)

**Comment by pradyunsg** [comment]
I got bored remembering the capabilities of 802.11 protocols so, I tried a little something regarding this:

<img width="806" alt="screen shot 2018-08-17 at 12 23 08 pm" src="https://user-images.githubusercontent.com/3275593/44252035-5bed6700-a218-11e8-9a90-dc3ce83e60a0.png">

**Comment by pradyunsg** [comment]
2 concerns I can think of, with what I posted above:

- Wrapping title + labels?
  - I think we should move all the context information to be lower down, like we do currently, which is probably gonna be a fun thing to implement
- Where do we put the "Archived icon" from #775? Options:
  - Make the "icon + reason" section wider and accomodate an extra icon, that is occasionally present
  - Have an alternate way to indicate archived status.

**Comment by pradyunsg** [comment]
Iteration 2. This isn't polished (the inconsistency in whitespace and too little of it -- is cramped). It's more of a rough draft.

![web 1920 my idea](https://user-images.githubusercontent.com/3275593/46009937-a6e37f80-c0de-11e8-90e7-b3ebe75e6eca.png)

Resolution of previous bullet points:

- Wrapping of the title/labels is the most sensible thing to do here.
- Turns out, "Review Requested" status is long. We can space the icons carefully and accomodate an extra icon when we're in that context.

Additional notes:

- The hover icons added in #823 can replace the reason badge, bringing all possible actions on the notification closer. The current UX of having to go to the other end of the notification isn't very convenient. ([Fitt's Law](https://en.wikipedia.org/wiki/Fitts%27s_law))
- The checkboxes are aligned to not move when the 3 or 4 icons are present. That's not needed per-se but would make life easier when styling the page.
- I feel that the "reason" boxes should be less brightly colored to capture less attention.

Other than that, I think the search/filter/menu could use improvement overall. I have some ideas and I'll post them in a new issue.

**Comment by pradyunsg** [comment]
It's weird how I end up doing these random design mockups _during_ exams. 🤔

**Comment by andrew** [comment]
@pradyunsg I like the exploration of how to improve the notification display 👍 

I don't think we'll actually implement a fixed width layout, so we can either rename this issue or close it as `wontfix` and open a new one for notification list redesign and responsiveness.

**Comment by pradyunsg** [comment]
Fair enough. :)

I'll open a new one.

**Comment by pradyunsg** [comment]
Oh, I just realized that I never posted my current workaround here:

```
@media (min-width: 1200px) {
  /* Center the content on large screens */
  .navbar, .flex-content {
    padding-left: calc((100% - 1200px) / 2);
    padding-right: calc((100% - 1200px) / 2);
  }
}
```

It isn't perfect but it's good enough.
