### ISSUE TITLE
Add indication in Web UI of the deployed version (git hash?)

### ISSUE THREAD

**Issue by pradyunsg** [octobox/octobox#795]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

---

Just a thought, looking at https://github.com/octobox/octobox/pull/775#issuecomment-413515661

How about showing somewhere in the UI what version/point in history the currently deployed Octobox instance is on; perhaps even showing that there is an update on master that's coming? octobox.io can then disable it at the instance level and self-deployed users can see that there's an update available.

**Comment by andrew** [comment]
That feature should already be implemented: https://github.com/octobox/octobox/issues/503

It shows up in the settings page: 

![screen shot 2018-08-16 at 12 57 14](https://user-images.githubusercontent.com/1060/44207135-f0da5c80-a153-11e8-84db-60274d15a8ba.png)

I also opened a related issue about changelogs yesterday: https://github.com/octobox/octobox/issues/786

**Comment by pradyunsg** [comment]
<img width="1669" alt="screen shot 2018-08-16 at 5 28 17 pm" src="https://user-images.githubusercontent.com/3275593/44207168-d74c0b80-a179-11e8-890f-47a08360400d.png">

Hmm...

**Comment by pradyunsg** [comment]
Indeed. I'll let this sit open for tracking the docs update. :)

**Comment by pradyunsg** [comment]
Additional thought: How about adding a "changes since" link; or some indication that Octobox master has moved forward?

Basically linking to https://github.com/octobox/octobox/compare/88721582d823c8c7e07d1d9ec3016a28a6857fea...master when your revision is https://github.com/octobox/octobox/compare/88721582d823c8c7e07d1d9ec3016a28a6857fea...master

**Comment by andrew** [comment]
@pradyunsg great idea: https://github.com/octobox/octobox/pull/805
