### ISSUE TITLE
Emoji reaction notifications

### ISSUE THREAD

**Issue by M-Zuber** [octobox/octobox#80]
Is there any way to get that information?

Now that everyone has been encouraged to 👍 the original issue and not make their own comment, it is actually harder to keep track of that without actually opening the issue/pr

**Comment by tarebyte** [comment]
@M-Zuber you can get the reaction data from an issue/pull request from the API https://developer.github.com/v3/reactions/

**Comment by M-Zuber** [comment]
I assume I would need to know ruby in order to attempt to integrate it into octobox though, correct?

**Comment by andrew** [comment]
partly dependent on https://github.com/andrew/octobox/issues/4

**Comment by whit537** [comment]
FTR this is the opposite of https://github.com/octobox/octobox/issues/188.

**Comment by M-Zuber** [comment]
I do definitely understand the need to make such notifications configurable, but some projects use it to decide what to work on next

**Comment by andrew** [comment]
I think this one is out of scope for the project atm
