### ISSUE TITLE
Additional visual distinction for unread notifications

### ISSUE THREAD

**Issue by pradyunsg** [octobox/octobox#800]
I've been experimenting lately with trying to make unread notifications more prominent, to aid spotting and getting them done with. I've found that coupling the current bold text, with a slight accented colour for the row, makes them easier to find.

Current:
<img width="787" alt="screen shot 2018-08-17 at 10 11 58 am" src="https://user-images.githubusercontent.com/3275593/44248098-4111f700-a206-11e8-8708-c8612d57edf9.png">

Prototype:
<img width="791" alt="screen shot 2018-08-17 at 10 12 09 am" src="https://user-images.githubusercontent.com/3275593/44248101-42dbba80-a206-11e8-841a-7a92a204c2a0.png">

The CSS I injected:

```css
.table-notifications .active {
    background-color: #FAFAFF;
}
```

**Comment by andrew** [comment]
🚢
