### ISSUE TITLE
Search History suggestions

### ISSUE THREAD

**Issue by pradyunsg** [octobox/octobox#803]
From #775.

> Keeping history of searches in the LocalStorage of the user and allow them to remove them (GitLab does something like this IIRC, even Gmail).

This would mean that common searches would be auto-suggested.

**Comment by prashuchaudhary** [comment]
@andrew I can take this up. And I was thinking we should user IndexedDB instead of LocalStorage.
What do you say ?

**Comment by andrew** [comment]
IndexedDB sounds fine to me :+1:

**Comment by prashuchaudhary** [comment]
@andrew I have started working on this. Just want to discuss few things like `Order of Search History
Suggestions` or `Count of suggestions should be shown ?`

Should be limit the number of suggestion that can be stored ??

**Comment by andrew** [comment]
@prashuchaudhary let's save/show a maximum of 10 now, and order by most recent, we can get more clever with frequency of searches later.

**Comment by prashuchaudhary** [comment]
@andrew  this is complete. please review the code. Also if you have got free some time, please check out the functionality once.

As discussed, I have limited saved Seaches to 10 items and ordered by recent.
