### ISSUE TITLE
Sorting options

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#813]
Pulled out from the [triage view thread](https://github.com/octobox/octobox/pull/752#issuecomment-413916688).

A number of people have mentioned wanting the ability to sort lists in ways other than `updated_at DESC`, accessible via a drop down and search prefix (`sort:last_read_at order:asc`).

List of potential sorting columns:

- created_at
- updated_at (ascending)
- last_read_at
- subject_title

Some more options once these features are complete:

- Comment count https://github.com/octobox/octobox/pull/709
- due date https://github.com/octobox/octobox/issues/812
- muted_at https://github.com/octobox/octobox/issues/811
- "last time I commented" @pradyunsg in https://github.com/octobox/octobox/pull/752#issuecomment-411306052 (semi-related to https://github.com/octobox/octobox/issues/739)

**Comment by pradyunsg** [comment]
minor point: `-` also looks nicer than `_` IMO. `muted-at` vs `muted_at`.

**Comment by paulleader** [comment]
@andrew I've started work on this one in https://github.com/octobox/octobox/pull/891 but just want to clarify the fields.

What does updated_at actually refer to in the context of a notification? Is that when the object the notification was triggered by (e.g. a comment) has been edited, or would that action create a new notification?

**Comment by andrew** [comment]
The current sort is `notifications.updated_at`, which is very similar to `subjects.updated_at` (if present), and tbh I’d have to have a play around with some real world data to see what it looks like. 

One thing that springs to mind is that sorts on the `notifications` table fields are the only ones that are guaranteed, as not every notification will have a subject, so most sorts on subjects fields may need a fallback or secondary sort on the notifications table as well

**Comment by andrew** [comment]
First chunk completed by @paulleader, we can open new issues to add more sort options as fields become available :shipit:
