### ISSUE TITLE
Incorrect state of issues

### ISSUE THREAD

**Issue by pradyunsg** [octobox/octobox#816]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**
The actual state vs the shown state of the issues are not in matching:

<img width="999" alt="screen shot 2018-08-20 at 10 41 55 am" src="https://user-images.githubusercontent.com/3275593/44321466-dfe85e80-a465-11e8-9e78-013dab42d76e.png">
<img width="1022" alt="screen shot 2018-08-20 at 10 44 05 am" src="https://user-images.githubusercontent.com/3275593/44321495-fe4e5a00-a465-11e8-8c08-15b828b5ba3d.png">

The issue in question is toml-lang/toml, 555 (not putting hash to avoid a cross-reference). You can see that issue was never actually closed throughout it's history. I'm not sure when this occurs but it has, hence the issue. :)

🎯 **Goal**
They should be matching.

**Comment by andrew** [comment]
![65a9cf9d-9b8e-4c30-beba-af8c4367d198](https://user-images.githubusercontent.com/1060/44322295-96d3e280-a444-11e8-9a8f-8473ed25ae67.png)

Weird, it’s showing as closed for me on GitHub

**Comment by pradyunsg** [comment]
Huh. Did I forget to refresh in a hurry?

**Comment by pradyunsg** [comment]
Let's assume this never happened. 😬

**Comment by andrew** [comment]
🤫
