### ISSUE TITLE
"r" to refresh keyboard shortcut no longer works

### ISSUE THREAD

**Issue by RX14** [octobox/octobox#829]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

Using "r" as a keyboard shortcut to refresh the list has always worked, but today it stopped working on octobox.io.

**Comment by rhuss** [comment]
Also pushing the reload button keeps the tooltip open and the spinner doesn't start (button remains static).

**Comment by andrew** [comment]
Sorry my fault, just pushed https://github.com/octobox/octobox/commit/c070aa61e9b3332fa775f004e78db4a9e7636c86 to fix it, will be deployed to octobox.io within a few mins

**Comment by pradyunsg** [comment]
Thanks for the super-fast fix @andrew! :)

**Comment by RX14** [comment]
Thanks, can confirm this fixed it!
