### ISSUE TITLE
More information regarding author

### ISSUE THREAD

**Issue by WilsonChiang** [octobox/octobox#83]
It would be nice if there was the option of showing the author of a PR/issue, and/or showing the person who last caused a notification to occur. If clutter is a concern maybe this could be a toggleable option.

If there's any interest for this I could work on adding this.

**Comment by andrew** [comment]
Yeah would be good, related to https://github.com/andrew/octobox/issues/4

**Comment by andrew** [comment]
First part of this has been merged in #411 and is available behind the `FETCH_SUBJECT` env var feature flag, docs here: https://github.com/octobox/octobox/blob/master/INSTALLATION.md#downloading-subjects

Still working on getting it available on https://octobox.io

**Comment by andrew** [comment]
Closing this as it's available if you run your own instance, waiting on https://github.com/octobox/octobox/issues/472 for it to be enabled on https://octobox.io
