### ISSUE TITLE
impossible  to delete it!!!!!

### ISSUE THREAD

**Issue by Banginpadr** [octobox/octobox#831]
i dont want this app no more but it doenst get uninstall. i got to settings applications revoke. then still the app will still oven the octobox.io site. i want to have my normal notifications again.

**Comment by andrew** [comment]
Hi @banginpadr, when you say “the app will still open the Octobox.io site”, which app are you talking about?

**Comment by Banginpadr** [comment]
@andrew this one, i had this pluggin on my profile to read my notifications but now even after i did it it wont go back to my normal github notification page

**Comment by Banginpadr** [comment]
@andrew problem solved. after you revoke the this app you even have to delete le firefox pluggin or it will still show you the octobox page

**Comment by andrew** [comment]
Ah, good to know, thanks for closing 👍
