### ISSUE TITLE
New favicons should have a transparent background

### ISSUE THREAD

**Issue by BPScott** [octobox/octobox#845]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [x] My instance

🐞 **Problem**

After the icon updates in #835 favicons now have a solid white background. A transparent background would look nicer in the tab bar.

<img width="363" alt="screenshot of browser tabs" src="https://user-images.githubusercontent.com/227292/44804872-8247c680-ab77-11e8-89b6-900fa18510d5.png">

You can see this in action on https://octobox.io/

🎯 **Goal**

Slightly prettier tab bars

💡 **Possible solutions**

Update the icons that were changed to have white background in #835 to have a transparent background.

Looking at the diff this seems to affect:

- public/android-icon-*.png
- public/apple-icon-*.png
- public/ms-icon-*.png
- public/favicon-*.png
- public/favicon.ico
- public/icon/icon.*.png

**Comment by andrew** [comment]
👍 I believe that @BenJam was working on this today
