### ISSUE TITLE
Filter by isPrivate links in sidebar both say "Private"

### ISSUE THREAD

**Issue by BPScott** [octobox/octobox#847]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**

In the Public/Private filter in the sidebar both options say "Private". Selecting the top one correctly filters to only show public repositories but the label text is wrong.

<img width="682" alt="screen shot 2018-08-29 at 12 57 23 pm" src="https://user-images.githubusercontent.com/227292/44812149-55051380-ab8b-11e8-9192-94f21c4e3aed.png">

🎯 **Goal**

Labels that reflect their function

💡 **Possible solutions**

I guess the logic around visibility is at fault: https://github.com/octobox/octobox/blob/3074820126df85bf9b14798d7527acbed9781caf/app/views/notifications/_sidebar.html.erb#L106-L117

I also note that other boolean filter options (e.g. `bot`, `unread`, `unlabelled`) use the values true/false and are not prefixed with an `is_`. While `is_private` sets the values `0` or `1`.

Renaming `is_private` to `private` and changing the set value to be 'false' or 'true' may help with consistency and this not chosing-the-right-text-correctly issue may be related that inconsistency.

e.g. the query string `?bot=true&is_private=1&reason=&unlabelled=true&unread=true` would become `?bot=true&private=true&reason=&unlabelled=true&unread=true`.

**Comment by andrew** [comment]
@BPScott out of interest, are you using mysql?

**Comment by BPScott** [comment]
I *think* we're using MySQL yes. I believe @jules2689 maintains our instance so they can confirm.

**Comment by jules2689** [comment]
Ignore issues in our octobox right now. We're having issues due to an upgrade.

**Comment by andrew** [comment]
Ok, give me a shout if you need any help with the upgrade

**Comment by jules2689** [comment]
Turns out we are being hit by https://github.com/rails/rails/issues/31445

Sometimes we get subject urls coming in as `https://github.com/shopify/foo/...` and others as `https://github.com/shopify/Foo/...`, I dont know why.

I'm using https://github.com/jules2689/rails/tree/5-2-stable to fix the bug for now, but now I'm dealing with the background job stuff. I'd love to work with you to get that in soon.

I also have some bugfixes I'll be pushing up from the bootstrap upgrade with notifications

**Comment by jules2689** [comment]
@andrew here is a full list of what is left for us to upgrade:

---

PRs upstream
---
- [ ] Background Jobs (https://github.com/octobox/octobox/pull/603)
- [x] Notification Issue (https://github.com/octobox/octobox/pull/855)

Rails Bug
---
- [ ] Fix Rails Bug
- [Using my branch](https://github.com/Shopify/octobox/commit/a4cb060ba363d7bca94c2f8e5b873ebc36710327)
- [To Fix](https://github.com/rails/rails/issues/31445)

To add to #855
---
- [ ] [Fix syncing](https://github.com/Shopify/octobox/commit/6f5164a1e237ec2375bbd12179ddd583c7491464)
- [ ] [Fix alerts](https://github.com/Shopify/octobox/commit/6f5164a1e237ec2375bbd12179ddd583c7491464)
- [ ] [Fix priority queue](https://github.com/Shopify/octobox/commit/09bc1be2c7da1c7eb292aa470b4b04c68b5b1f1d). I think this broke with a sidekiq upgrade

Other Commits
---
- [ ] [Timeout on sync](https://github.com/Shopify/octobox/commit/80e7ffa17d5f05b85c6340611b7d9ab6b36c706f)
- [ ] [Octobox Native Link](https://github.com/Shopify/octobox/commit/efd79dd426f8a27a29c06ad76fe26b29090ce47c)
