### ISSUE TITLE
Document how to enable periodic background polling

### ISSUE THREAD

**Issue by rhuss** [octobox/octobox#876]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [X] My instance

🐞 **Problem**

Currently it is not cleare what configuration is needed for a periodic background polling of notifications. According to #862 it looks like that the environment variable `OCTOBOX_BACKGROUND_JOBS_ENABLED` needs to be set (to any value, even `false` :) and you neeed to point sidekiq to an existing redis installation (however this works).

It would be super awesome if we could get a quick documentation update explaining the necessary steps. 

That way I also could add that support to the OpenShift template so that it is enabled by default on OpenShift.

🎯 **Goal**

Knowing how to enable background fetching of notifications.

💡 **Possible solutions**

Document it please ;)

**Comment by andrew** [comment]
Thinking aloud here before putting in into doc form as my brain is a little frazzled on a friday afternoon.

Things required for sidekiq to work:

- redis up and running
- redis url stored in an envirnoment variable called `REDIS_URL`
- a sidekiq worker running i.e. this command: `bundle exec sidekiq -C config/sidekiq.yml`

note. Using the provided [`docker-compose.yml`](https://github.com/octobox/octobox/blob/master/docker-compose.yml) file will configure redis and `REDIS_URL` for you, you just need to run sidekiq

Then you can enable periodic background polling of notifications in sidekiq with the [`OCTOBOX_SIDEKIQ_SCHEDULE_ENABLED`](https://github.com/octobox/octobox/blob/master/docs/INSTALLATION.md#option-2) env var set to `true`.

To enable background syncing of all notifications and subjects, assuming you have sidekiq up and running, either `OCTOBOX_SIDEKIQ_SCHEDULE_ENABLED` or `OCTOBOX_BACKGROUND_JOBS_ENABLED` should be set to `true`

**Comment by rhuss** [comment]
When using an OpenShift setup Redis and the Octobox containers are running both in a single pod so that Octobox can connect to Redis via localhost:6379. I set REDIS_URL=localhost:6379 and OCTOBOX_BACKGROUND_JOBS_ENABLED=true

So I guess I'm just missing the sidekiq part. I will try to add it as another sidecar container to the openshift part but can get tricky to get it running on OpenShift starter because of resource limits (an additional containers adds at least 100 MB afair).

**Comment by andrew** [comment]
@rhuss to reduce ram usage, you can reduce `RAILS_MAX_THREADS` from the default of 5 to something lower like 2.

**Comment by andrew** [comment]
You could potentially also use [foreman](https://github.com/ddollar/foreman) to run both the rails and sidekiq processes in the same container.

**Comment by rhuss** [comment]
@andrew thanks for the pointer and hint. 

I will try the separate container-based approach first as this has the nice effect that I could use the upstream octobox docker image directly and the openshift installation has an image change trigger so that it will pick up and redeploy on every image update on Docker Hub. Living at the bleeding edge ;-)

Otherwise, I would need to prep a custom image with foreman and sidekiq installed. But maybe that kind of Docker image would be generally a good idea as a variation of the current docker image (like a 'octobox/octobox-sidekiq' image in addition to 'octobox/octobox').

**Comment by andrew** [comment]
@rhuss I think we'll probably want the mainline octobox to use sidekiq by default soon as I suspect all of the maintainers will be running that configuration, the syncing performance alone is much better and it's pretty much a requirement for running the GitHub App version.

**Comment by rhuss** [comment]
Found my issue for now, the REDIS_URL required a mandatory "redis://" scheme (a hostname alone is not good enough)
