### ISSUE TITLE
Invert Favicon ?

### ISSUE THREAD

**Issue by rhuss** [octobox/octobox#885]
Are you experiencing this issue in octobox.io or your own instance?
 - [X] octobox.io
 - [X] My instance

🐞 **Problem**

Not really a problem, but the new logo doesn't really look nice when scaled down and used e.g. for bookmarks in a browser, especially when used on a light background:

![image](https://user-images.githubusercontent.com/99080/45167717-ffb7aa80-b1f9-11e8-8ca8-1b494134b524.png)

Tbh, i liked the old, more iconic logo better, but that's a matter of taste.

However, what's about the suggestion to use an inverse (black on white) favicon to complement the new logo ?

**Comment by BenJam** [comment]
^ like that?

**Comment by andrew** [comment]
Just merged and deployed #890, as usual with favicons, things may be cached for ages!

**Comment by rhuss** [comment]
Cool, thanks !
