### ISSUE TITLE
Octobox does not sync anymore

### ISSUE THREAD

**Issue by smola** [octobox/octobox#887]
Octobox notifications are not being sync anymore. This is happening to multiple users in the @src-d organization. Last successful sync was 16h ago.

Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io (version https://github.com/octobox/octobox/commit/ffd11b47aad3fad2b085fc77ca0366677e5e1677)

🐞 **Problem**
N/A

🎯 **Goal**
N/A

💡 **Possible solutions**
N/A

📋  **Steps to solve the problem**
N/A

**Comment by andrew** [comment]
@smola I'm investigating this at the moment

**Comment by andrew** [comment]
Looks like this happened around the time that I upgraded the redis addon on heroku, no code changes were deployed 16 hours ago.

**Comment by andrew** [comment]
@smola I think I've squashed this, can you try syncing again?

When I upgraded the redis addon, the unique jobs keys were persisted which stopped allowing any new sync jobs to be created, emptying the unique jobs set solved it.

In future need to be much more careful relying on the heroku redis addon upgrade experience!

**Comment by smola** [comment]
@andrew Thanks, it works n ow.

**Comment by gep13** [comment]
Yip, all working here for me as well.  Thanks for fixing this @andrew :+1:
