### ISSUE TITLE
Octobox errors and won't sync

### ISSUE THREAD

**Issue by jhosman** [octobox/octobox#889]
Hey there 👋 Octobox is behaving oddly for me this morning - It synced once when I first opened it, but then started showing an error page when I tried to mark a bunch of items as read. (Sorry, I forgot to screenshot the error page and it's not happening anymore.) Now sync has stopped working completely. The spinner keeps spinning, but it hasn't updated since 32 minutes ago. Edit: Actually, it's said "Last sync: 32 minutes ago" for a while - Looks like the UI isn't updating at all.

I tried a different browser and a private browser window, and also tried completely signing out of Octobox, revoking the app's access in my GitHub account, and signing in / granting access again. No luck. Any ideas?

_Possibly related to #887._

Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by andrew** [comment]
Investigating this now

**Comment by jhosman** [comment]
Oh strange - It's for my @jhosman account.

**Comment by andrew** [comment]
@jhosman I can't see your account in the logs at all, are you sure this is happening on https://octobox.io and not an internal GitHub install? Or can you try logging in again?

**Comment by jhosman** [comment]
Doh! This _is_ an internal GitHub install 🤦‍♀️ Sorry about that - could've sworn I set it up from https://octobox.io. That's what I get for opening issues before coffee 😞

**Comment by andrew** [comment]
No worries, I'm sure @tarebyte can help you out, might be related to recent changes in the syncing, not sure how recent the version you're running is

**Comment by jhosman** [comment]
Thanks! I think I fixed it 🤞 Had to delete my octobox account and recreate it. Things seem to be working now.
