### ISSUE TITLE
No refresh spinner anymore

### ISSUE THREAD

**Issue by rhuss** [octobox/octobox#913]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [X] My instance

🐞 **Problem**

With the latest update (I think already since some days), refreshing the notification list with either the top-level button or the central button on an empty list doesn't provide any feedback anymore that it's refreshing. Previously there was a spinner during refresh.

This resembles a bit https://github.com/octobox/octobox/issues/829#issuecomment-414927819 but the key shortcut 'r' still works.

It still just looks like

![image](https://user-images.githubusercontent.com/99080/45384617-cbcff100-b60e-11e8-9114-b8c91f2d4deb.png)

during refresh, without any animation.

**Comment by andrew** [comment]
@rhuss is this with or without background syncing enabled?

**Comment by rhuss** [comment]
I don't thinks so. I have these env variables set:

![image](https://user-images.githubusercontent.com/99080/45386300-53b7fa00-b613-11e8-8ddd-c79c91a760a9.png)

**Comment by andrew** [comment]
I managed to replicate this bug locally, so it's on my todo list to fix it
