### ISSUE TITLE
Mobile UI bugs/improvements

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#925]
There's a number of annoying little bugs when using Octobox on a phone/small screen, consider this issue a bit of a dumping ground for them for now.

**Comment by andrew** [comment]
- [ ] No momentum scrolling on settings page (iOS)

**Comment by andrew** [comment]
- [ ] Main page is longer than the viewport, creating weird scrolling behaviours: 

![png image](https://user-images.githubusercontent.com/1060/45494650-6d6b5580-b769-11e8-98e2-d0e666c58497.png)

**Comment by andrew** [comment]
- [ ] too many lines when menu and search are both expanded: 
![png image 5](https://user-images.githubusercontent.com/1060/45494732-9db2f400-b769-11e8-94fd-1f3d08e5c79b.png)

**Comment by BenJam** [comment]
> Sync button stays black (focus state) after sync has finished
tried setting this element to `.blur()` before calling the sync but that's not happy.

**Comment by andrew** [comment]
Moving #858 over here too, where labels are overflowing the updated at date on mobile:

![44876112-009b8a00-ac98-11e8-8ba7-ad8151577696](https://user-images.githubusercontent.com/1060/45952511-3154b200-bfff-11e8-9849-67460b3b376a.PNG)

**Comment by BenJam** [comment]
moving remainder to #1034
