### ISSUE TITLE
Dockerfile is development specific(?)

### ISSUE THREAD

**Issue by chrisarcand** [octobox/octobox#927]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**

I'm completely new to Docker, so bear with me a bit and I realize it might just be my own lack of experience here.

I'm attempting to deploy an Octobox instance via [docker-compose in production](https://docs.docker.com/compose/production/). This would require me making my own custom compose yaml (which we might want to mention in the docs), which I've done - but I've hit a snag in that the Dockerfile we have [does not install gems for the production environment.](https://github.com/octobox/octobox/blob/88a6d926bdc7201035d1cf69137e3e6e7ae3b26d/Dockerfile#L22) That means gems used only in production cause the Rails initialization process to fail (in my case, lograge is missing.)

Should Dockerfiles be tied to the specific environment as ours currently is, or should we be installing dependencies for all potential environments? I'm assuming the latter, but I don't really know what I'm doing and I know other people are using Docker in "production like environments" (I'm wondering if they are all running in dev, actually, though)

🎯 **Goal**

I should be able to run Octobox in an actual production environment using Docker (and, hopefully, Compose) more easily.

💡 **Possible solutions**

I think we might just need to tweak the Dockerfile and leave slightly better instructions in the docs.

**Comment by andrew** [comment]
@chrisarcand yeah we should definitely add back in the production gems, I seem to remember removing them to reduce the size of the docker image

**Comment by chrisarcand** [comment]
Cool; Yeah I'm toying with this a bit and will have something soonish. I think a revamped set of compose yamls (generalize docker-compose.yml, add in overrides to be use in the dev yaml to be used [over the top of the general one](https://docs.docker.com/compose/extends/#example-use-case), and changes to the Dockerfile(s). 👈 We can either generalize the normal Dockerfile for all envs or we can also do a separate Dockerfile for production images to keep the size down (no dev/test gems, etc).

**Comment by andrew** [comment]
You can tell that I’m not running it on Docker 😅

**Comment by chrisarcand** [comment]
I'm setting up a new instance finally so I figured hey why not :) 🔜

**Comment by rhuss** [comment]
I adapted the Dockerfile to include also production gems (i.e. removed that '--without production') but then run in another issue when running:

```
16:50:52 web.1    | bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
16:50:52 web.1    | ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`
16:50:52 web.1    |   /usr/local/bundle/gems/railties-5.2.1/lib/rails/application.rb:585:in `validate_secret_key_base'
16:50:52 web.1    |   /usr/local/bundle/gems/railties-5.2.1/lib/rails/application.rb:432:in `secret_key_base'
16:50:52 web.1    |   /usr/src/app/lib/octobox/configurator.rb:8:in `attr_encyrption_key'
```

Not sure what's required here (remember, I'm a ruby and rails noob ;-)

**Comment by andrew** [comment]
@rhuss you need to set `ENV['SECRET_KEY_BASE']`, which gets loaded here: https://github.com/octobox/octobox/blob/master/config/secrets.yml#L36
