### ISSUE TITLE
Same notification appears multiple times in the list

### ISSUE THREAD

**Issue by smola** [octobox/octobox#928]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io

🐞 **Problem**
There is one notification from a private repository that appears repeated 6 times in my list:
![2018-09-14-110326_617x511_scrot](https://user-images.githubusercontent.com/23248/45540886-d99f9500-b80d-11e8-89cf-6cd48d6ee051.png)

If you need more details, I can provide the exact repository and issue number in private (e.g. on gitter).

**Comment by andrew** [comment]
@smola investigating this for you now

**Comment by andrew** [comment]
@smola just pinging you in gitter

**Comment by andrew** [comment]
This was caused by multiple subjects with the same `url` existing in the database, pr to add validation over here: https://github.com/octobox/octobox/pull/929
