### ISSUE TITLE
Issues showing up with PR icon

### ISSUE THREAD

**Issue by Tyriar** [octobox/octobox#932]
Starting this morning (was fine last night), many issues are being shown as PRs:

<img width="195" alt="screen shot 2018-09-14 at 7 42 26 am" src="https://user-images.githubusercontent.com/2193314/45557167-d8f90580-b7f1-11e8-9c94-ccd1d4049fc3.png">
<img width="583" alt="screen shot 2018-09-14 at 7 43 26 am" src="https://user-images.githubusercontent.com/2193314/45557185-e1e9d700-b7f1-11e8-8038-7b1f94701a49.png">

Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

I suspect it's a bug introduced in a recent commit (not sure how often deployments are).

**Comment by andrew** [comment]
This looks to be a problem with data coming from GitHub: https://twitter.com/teabass/status/1040589741845045248

**Comment by andrew** [comment]
This data is showing up in https://api.github.com/notifications?all=1 for me

```json
{
    "id": "379818496",
    "unread": false,
    "reason": "subscribed",
    "updated_at": "2018-09-14T11:03:50Z",
    "last_read_at": "2018-09-14T13:05:16Z",
    "subject": {
      "title": "Same notification appears multiple times in the list",
      "url": "https://api.github.com/repos/octobox/octobox/pulls/928",
      "latest_comment_url": "https://api.github.com/repos/octobox/octobox/pulls/928",
      "type": "PullRequest"
    }
}
```

but #928 is an issue not a pull request: https://github.com/octobox/octobox/issues/928 

I've contacted github support but not heard anything back cc @tarebyte

**Comment by Tyriar** [comment]
Thanks for the quick follow up @andrew 😃

**Comment by andrew** [comment]
@Tyriar my octobox account has fixed itself up now, hopefully yours will too after the next sync

**Comment by Tyriar** [comment]
@andrew looks good 👍
