### ISSUE TITLE
Remove filter bar in favour of the search bar

### ISSUE THREAD

**Issue by pradyunsg** [octobox/octobox#952]
Currently, clicking on the side bar results in the filters being added to the current search.

This shows up in the search bar as well as in the "filter" bar. IMO it seems feasible that we would be able to get rid of the filter bar.

**Comment by andrew** [comment]
cc @paulleader, we were talking about this last week and I believe he's going to do some refactoring to make this happen 👍

**Comment by b3u** [comment]
@paulleader Triaging. Was this solved in #1015?

**Comment by andrew** [comment]
@b3u I don't believe that it's been completely solved as there's still some duplication between the search box and the filter bar, although they now at least show the same thing.
