### ISSUE TITLE
Migrations can cause deadlocks in deploys

### ISSUE THREAD

**Issue by jules2689** [octobox/octobox#958]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**

Migrations to various tables are troublesome in larger instances. A recent addition of an [index to the notification table](https://github.com/octobox/octobox/pull/902) has caused our deploys to timeout as the migration takes too long. We are now in a state where we are locked and need to wait for our migrations to finish in the background. This are our stats:

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/3074765/45639082-09080900-ba7d-11e8-85c4-cd52b6f87b73.png">

💡 **Possible solutions**
 - Let's try to limit changes to the notifications table
- Let's consider adding something to handle larger changes, like the [LHM gem](https://github.com/soundcloud/lhm), but for both postgres and mysql

**Comment by andrew** [comment]
For postgres we can create migration concurrently: 
https://robots.thoughtbot.com/how-to-create-postgres-indexes-concurrently-in
