### ISSUE TITLE
Inverse matching in search

### ISSUE THREAD

**Issue by FedericoCeratto** [octobox/octobox#961]
Hi and thank you for developing octobox.

It would be very handy to be able to filter out / exclude search items e.g.:

```
repo:-octobox/octobox   Exclude notifications from the octobox/octobox repository.
owner:-microsoft        Exclude notifications from repos in the microsoft organisation.
type:-pull_request      Show notifications of all types except pull requests
```

Thanks!

**Comment by andrew** [comment]
@FedericoCeratto thanks for the excellent feature request!

**Comment by andrew** [comment]
All of the potential prefixes that could support an exclude option:

- repo
- owner
- type
- reason
- label
- state
- author
- assignee

**Comment by andrew** [comment]
Pondering this more, one change I'd make to the original issue would be to match [GitHub's inverse syntax](https://help.github.com/articles/searching-issues-and-pull-requests/#search-by-label), by putting the `-` at the start of the prefix, for example:

```
-repo:octobox/octobox   Exclude notifications from the octobox/octobox repository.
-owner:microsoft        Exclude notifications from repos in the microsoft organisation.
-type:pull_request      Show notifications of all types except pull requests
```

**Comment by andrew** [comment]
Pull request over here: https://github.com/octobox/octobox/pull/982

**Comment by andrew** [comment]
Deploying this to https://octobox.io now :shipit:
