### ISSUE TITLE
Refactor and unify search and filtering options into  single concept

### ISSUE THREAD

**Issue by paulleader** [octobox/octobox#963]
🐞 **Problem**
At the moment, `NotificationsController` deals with raw params, pulling out search and filtering options as needed, and treating the search string (the `q` parameter) as a completely separate concern. Options provided as url parameters are not reflected in the search string. This is preventing us from:

- Converting url options to search string options (e.g. instead of `?reason=author` have the search string `reason:author`)
- Removing the filter bar in favour of the search bar (#952)

🎯 **Goal**
This refactoring aims to combine all search and filtering option handling into a single concept, as a precursor to enabling the above changes.

📋  **Steps (probably one PR per step)**
- [ ] Replace direct access to the various search and filter params with a delegator that wraps the `params` object (`SearchOptions`).
- [ ] Replace `[]` based access to these parameters with methods for each parameter.
- [ ] Add parsing of the query string (`q`) to `SearchOptions`, and expose all the available options as accessors by delegating to `SearchParser`. Unifying access to options that can be specified through either url params or query string options with the string version taking precedence.
- [ ] Update the `Search` class to take a `SearchOptions` object rather than the raw query string.
- [ ] Move search and scoping logic from the `NotificationsController` into the `Search` class, reducing the complexity of the controller.

**Comment by paulleader** [comment]
@andrew Would you mind assigning this to me please :)

**Comment by andrew** [comment]
Excellent write up @paulleader, excited to see this happen and unify the search query with the url query params 🎉
