### ISSUE TITLE
Octobox won't sync

### ISSUE THREAD

**Issue by shubheksha** [octobox/octobox#965]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**

Despite forcing sync, none of my notifications from the past 5 days have shown up. The last notification is from 13th Sep. It was working fine before that.

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by andrew** [comment]
I’ll investigate this for you once I get back from my dog walk, thanks for reporting

**Comment by andrew** [comment]
@shubheksha do you have an example issue/pr that should be showing up in your inbox but isn't?

**Comment by shubheksha** [comment]
Yes, these:
https://github.com/kubernetes/kubectl/issues/80
https://github.com/kubernetes/kubernetes/pull/68774
https://github.com/kubernetes/website/pull/10145

**Comment by andrew** [comment]
That's really weird, from the database it looks like they should be showing up, can you email me a screenshot of what you're seeing on https://octobox.io to andrew@octobox.io (or post it here if you don't mind sharing the contents of your octobox inbox publicly)

**Comment by shubheksha** [comment]
Funnily enough, it synced right after I opened this issue?!

**Comment by shubheksha** [comment]
@andrew, sure! Sorry for the trouble and thanks for Octobox, it has made my life easier :heart: :100:

**Comment by andrew** [comment]
@shubheksha excellent, you're going to love the new features coming online in a couple weeks! 😉
