### ISSUE TITLE
Sync and allow filtering/searching by Milestone

### ISSUE THREAD

**Issue by andrew** [octobox/octobox#975]
Similar to labels, it would be nice to be able to filter and search by Milestone, for example: `milestone:Launch`

Subjects (only issues and pull requests) can belong to a single milestone and a milestone belongs to a repository.

API docs here: https://developer.github.com/v3/issues/milestones/

The minimum we'd need to keep in sync for the milestone record is it's `title` but other details like `number`, `state`, `description` and `due_on` would be nice to have too.

When configured as a GitHub App, we can also receive webhooks for milestone change events, details here: https://developer.github.com/v3/activity/events/types/#milestoneevent

**Comment by 0sc** [comment]
I'd love to try my hands at this. Is it still up for grabs?

**Comment by andrew** [comment]
@0sc yep, go for it 👍

**Comment by 0sc** [comment]
Hi @andrew, I got started on this and was modelling the milestones like the labels. But labels currently done follow this relationship:
> Subjects (only issues and pull requests) can belong to a single milestone and a milestone belongs to a repository.
Should I stick to the current way they are associated?

**Comment by andrew** [comment]
@0sc sorry for the delay, the way labels are set up right now aren't quite correct, there should only be one milestone per repository that subjects can belong to.

**Comment by boegel** [comment]
I'm very interested in having support for this, milestones are something I rely on quite heavily for the EasyBuild project.
