### ISSUE TITLE
Dark Theme and Light Theme have different fonts

### ISSUE THREAD

**Issue by Fryguy** [octobox/octobox#981]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [x] My instance

🐞 **Problem**
Dark Theme and Light Theme have different fonts

All seems different but the "6" in the Inbox tag is really recognizable.

![octobox 586 2018-09-20 14-49-17](https://user-images.githubusercontent.com/52120/45840404-de1fee00-bce4-11e8-8120-38056486cc0c.png)

🎯 **Goal**
Same font

**Comment by andrew** [comment]
Yep, definitely not right, header also has more padding, PR opened to fix here: https://github.com/octobox/octobox/pull/983
