### ISSUE TITLE
Review requested category

### ISSUE THREAD

**Issue by Kubuxu** [octobox/octobox#99]
Github introduced review requests unfortunately the only way to track them are notifications.
Is it possible to have notification category of 'review requested'?

**Comment by andrew** [comment]
As far as I can see there's nothing in the notifications API that says its a review request but there are a couple beta apis for finding reviews and request details:

- https://developer.github.com/changes/2016-12-14-reviews-api/
- https://developer.github.com/changes/2016-12-16-review-requests-api/

Related to #4

**Comment by watadarkstar** [comment]
@andrew Is there a PR that uses the beta apis, I can look at? Thinking of maybe working on this.

**Comment by andrew** [comment]
@watadarkstar there isn't one, feel free to take a stab at it

**Comment by watadarkstar** [comment]
@andrew Okay Andrew maybe this weekend I will give it a try. Haven't done ruby / rails in a long time.

**Comment by chaserx** [comment]
`Review Requested` exists as a category. Probably can close this one. Thoughts @andrew @Kubuxu 

![screen shot 2018-05-28 at 10 18 56 am](https://user-images.githubusercontent.com/7292/40618831-b9f40d56-6260-11e8-987d-589b947e9f29.png)

**Comment by andrew** [comment]
Thank I think this is done, good catch @chaserx!
