### ISSUE TITLE
Username in notification when filtered by repository sometimes messed up

### ISSUE THREAD

**Issue by rhuss** [octobox/octobox#990]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [X] My instance

🐞 **Problem**

This is the first time I encountered the issue described by the screenshot, I don't see it anywhere else:

![image](https://user-images.githubusercontent.com/99080/45875922-695abb80-bd99-11e8-99cc-3cfdd07b485b.png)

Anything I can do to check in the DB (SQL query) ?

**Comment by rhuss** [comment]
Originally appeared in #988

**Comment by andrew** [comment]
Looks like the `author` field on that subject is nil, so we shouldn't try to render the author at all if that's the case.

This line: https://github.com/octobox/octobox/blob/9f18511358318dabd272aadac817d4c62e0a0683/app/views/notifications/_notification.html.erb#L47 should be changed to:

```
<% if notification.subject && notification.subject.author %>
```
