### ISSUE TITLE
Allow configuration of the shown columns

### ISSUE THREAD

**Issue by rhuss** [octobox/octobox#991]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [X] My instance

🐞 **Problem**

I would like to suggest a feature to allow the customization of the columns shown in various views (top level and repository specific). This customization could happen either per user or site wide.

🎯 **Goal**

In order to support users with limited screen real estate, it would be awesome to switch off some columns on demand (like the author name or the date in the overall view) in order to spend more space for the notification itself, which can be quite lengthy with descriptions and all labels attached, leading often to wrapped rows.

E.g.

![image](https://user-images.githubusercontent.com/99080/45876151-1e8d7380-bd9a-11e8-9f19-99bf40efc302.png)

💡 **Possible solutions**

An ideal solution would be probably to allows this in the user settings (as this is a user-specific UX preference), but probably more advanced than merely one or two global environments variables, which hold the column names to show as a comma-separated list.

**Comment by rhuss** [comment]
Orignally appeared in #988

**Comment by andrew** [comment]
I'd prefer to fix the responsive aspects of the notifications table rather than add extra configuration options to avoid the bug at this point.
